"""Type declarations for the dcex Rust extension."""

from typing import Any

class ProductTable:
    """Indexed canonical and exchange-specific product metadata."""

    def __init__(self, rows: list[dict[str, str]]) -> None: ...
    def rows(self) -> list[dict[str, str]]: ...
    def get(
        self,
        key: str,
        product_symbol: str | None = None,
        exchange: str | None = None,
        product_type: str | None = None,
        exchange_type: str | None = None,
        exchange_symbol: str | None = None,
    ) -> str: ...
    def get_exchange_symbol(self, exchange: str, product_symbol: str) -> str: ...
    def get_product_symbol(
        self,
        exchange: str,
        exchange_symbol: str,
        product_type: str | None = None,
        exchange_type: str | None = None,
    ) -> str: ...
    def get_product_type(
        self,
        exchange: str,
        product_symbol: str | None = None,
        exchange_symbol: str | None = None,
    ) -> str: ...
    def get_exchange_type(
        self,
        exchange: str,
        product_symbol: str | None = None,
        exchange_symbol: str | None = None,
    ) -> str: ...
    def get_base_currency(self, exchange: str, product_symbol: str) -> str: ...
    def get_quote_currency(self, exchange: str, product_symbol: str) -> str: ...
    def get_trading_details(self, exchange: str, product_symbol: str) -> dict[str, str]: ...
    def get_exchange_symbols(
        self,
        exchange: str,
        product_type: str | None = None,
        exchange_type: str | None = None,
    ) -> list[str]: ...
    def get_product_symbols(
        self,
        exchange: str,
        product_type: str | None = None,
        exchange_type: str | None = None,
    ) -> list[str]: ...

def fetch_product_table(
    exchange_name: str | None = None, timeout: float = 10.0
) -> list[dict[str, str]]: ...
async def fetch_product_table_async(
    exchange_name: str | None = None,
    timeout: float = 10.0,  # noqa: ASYNC109
) -> list[dict[str, str]]: ...
def exchange_names() -> list[str]: ...
def order_side_parse(value: str) -> str: ...
def order_side_to_exchange(side: str, exchange: str) -> str: ...
def order_side_is_buy(side: str) -> bool: ...
def generate_timestamp_ms() -> int: ...
def generate_timestamp_iso() -> str: ...
def get_decimal_places(value: float) -> int: ...
def reverse_decimal_places(decimal_places: int) -> float: ...
def bybit_convert_timeframe(timeframe: str) -> str: ...
def bitmart_convert_timeframe(timeframe: str) -> int: ...
def kucoin_convert_timeframe(timeframe: str) -> str: ...
def address_to_bytes(address: str) -> bytes: ...
def sanitize_url(url: str) -> str: ...
def sanitize_message(message: str) -> str: ...
def sanitize_request(request: str) -> str: ...
def __getattr__(name: str) -> Any: ...  # noqa: ANN401
