"""Type declarations for the dcex Rust extension."""

from typing import Any

NativeHeaders = dict[str, str]
NativeParams = list[tuple[str, str]]
NativeResponse = tuple[int, NativeHeaders, bytes]
NativeJsonResponse = tuple[int, NativeHeaders, Any]
LighterSignedTransaction = tuple[int, str, str, str | None]

class ProductColumn:
    """Column view returned by ProductTable string indexing."""

    def to_list(self) -> list[str]: ...

class ProductTable:
    """Indexed canonical and exchange-specific product metadata."""

    def __init__(self, rows: list[dict[str, str]]) -> None: ...
    @property
    def height(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: int | str) -> dict[str, str] | ProductColumn: ...
    def rows(self) -> list[dict[str, str]]: ...
    def to_dicts(self) -> list[dict[str, str]]: ...
    def write_csv(self, path: str | object) -> None: ...
    def get(
        self,
        key: str,
        product_symbol: str | None = None,
        exchange: str | None = None,
        product_type: str | None = None,
        exchange_type: str | None = None,
        exchange_symbol: str | None = None,
    ) -> str: ...
    def get_exchange_symbol(self, exchange: str, product_symbol: str) -> str: ...
    def get_product_symbol(
        self,
        exchange: str,
        exchange_symbol: str,
        product_type: str | None = None,
        exchange_type: str | None = None,
    ) -> str: ...
    def get_product_type(
        self,
        exchange: str,
        product_symbol: str | None = None,
        exchange_symbol: str | None = None,
    ) -> str: ...
    def get_exchange_type(
        self,
        exchange: str,
        product_symbol: str | None = None,
        exchange_symbol: str | None = None,
    ) -> str: ...
    def get_base_currency(self, exchange: str, product_symbol: str) -> str: ...
    def get_quote_currency(self, exchange: str, product_symbol: str) -> str: ...
    def get_trading_details(self, exchange: str, product_symbol: str) -> dict[str, str]: ...
    def get_exchange_symbols(
        self,
        exchange: str,
        product_type: str | None = None,
        exchange_type: str | None = None,
    ) -> list[str]: ...
    def get_product_symbols(
        self,
        exchange: str,
        product_type: str | None = None,
        exchange_type: str | None = None,
    ) -> list[str]: ...

class HttpClient:
    """Low-level native HTTP client."""

    def __init__(self, timeout: float = 10.0) -> None: ...
    def request(
        self,
        method: str,
        base_url: str,
        path: str,
        query: NativeParams | None = None,
        headers: NativeHeaders | None = None,
        body: bytes | None = None,
    ) -> NativeResponse: ...
    def request_json(
        self,
        method: str,
        base_url: str,
        path: str,
        query: NativeParams | None = None,
        headers: NativeHeaders | None = None,
        body: bytes | None = None,
    ) -> NativeJsonResponse: ...
    async def request_async(
        self,
        method: str,
        base_url: str,
        path: str,
        query: NativeParams | None = None,
        headers: NativeHeaders | None = None,
        body: bytes | None = None,
    ) -> NativeResponse: ...
    async def request_json_async(
        self,
        method: str,
        base_url: str,
        path: str,
        query: NativeParams | None = None,
        headers: NativeHeaders | None = None,
        body: bytes | None = None,
    ) -> NativeJsonResponse: ...

class _NativeExchangeClient:
    """Common methods exposed by exchange-specific native clients."""

    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def set_product_table(self, table: ProductTable) -> None: ...
    def public_request_json(
        self, method_name: str, params: NativeParams | None = None
    ) -> NativeJsonResponse: ...
    async def public_request_json_async(
        self, method_name: str, params: NativeParams | None = None
    ) -> NativeJsonResponse: ...
    def private_request_json(
        self, method_name: str, params: NativeParams | None = None
    ) -> NativeJsonResponse: ...
    async def private_request_json_async(
        self, method_name: str, params: NativeParams | None = None
    ) -> NativeJsonResponse: ...
    def request_raw_json(self, *args: object, **kwargs: object) -> NativeJsonResponse: ...
    async def request_raw_json_async(
        self, *args: object, **kwargs: object
    ) -> NativeJsonResponse: ...

class AsterHttpClient(_NativeExchangeClient):
    def request_raw_auto_json(self, *args: object, **kwargs: object) -> NativeJsonResponse: ...
    async def request_raw_auto_json_async(
        self, *args: object, **kwargs: object
    ) -> NativeJsonResponse: ...

class AsterPublicWebSocketClient:
    def __init__(
        self,
        market: str = "futures",
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    def set_product_table(self, table: ProductTable) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def subscribe(self, streams: list[str]) -> int: ...
    async def unsubscribe(self, streams: list[str]) -> int: ...
    async def list_subscriptions(self) -> int: ...
    async def subscribe_trades(self, product_symbol: str) -> int: ...
    async def subscribe_agg_trades(self, product_symbol: str) -> int: ...
    async def subscribe_orderbook(self, product_symbol: str) -> int: ...
    async def subscribe_book_ticker(self, product_symbol: str) -> int: ...
    async def subscribe_ticker(self, product_symbol: str) -> int: ...
    async def subscribe_klines(self, product_symbol: str, interval: str) -> int: ...
    async def subscribe_mark_price(self, product_symbol: str, fast: bool = False) -> int: ...
    async def recv(self) -> bytes: ...

class AsterPrivateWebSocketClient:
    def __init__(
        self,
        signer_address: str,
        private_key: str,
        user_address: str | None = None,
        market: str = "futures",
        timeout: float = 10.0,
        spot_http_base_url: str | None = None,
        futures_http_base_url: str | None = None,
        ws_base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> str: ...
    async def connect_with_listen_key(self, listen_key: str) -> None: ...
    async def keep_alive(self) -> None: ...
    async def close_listen_key(self) -> None: ...
    async def close(self) -> None: ...
    def listen_key(self) -> str | None: ...
    async def recv(self) -> bytes: ...

class BackpackHttpClient(_NativeExchangeClient): ...

class BackpackPublicWebSocketClient:
    def __init__(self, timeout: float = 10.0, base_url: str | None = None) -> None: ...
    def set_product_table(self, table: ProductTable) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, streams: list[str]) -> None: ...
    async def unsubscribe(self, streams: list[str]) -> None: ...
    async def subscribe_book_ticker(self, product_symbol: str) -> None: ...
    async def subscribe_depth(self, product_symbol: str, speed: str | None = None) -> None: ...
    async def subscribe_orderbook(self, product_symbol: str, speed: str | None = None) -> None: ...
    async def subscribe_klines(self, product_symbol: str, interval: str) -> None: ...
    async def subscribe_liquidation(self) -> None: ...
    async def subscribe_mark_price(self, product_symbol: str) -> None: ...
    async def subscribe_ticker(self, product_symbol: str) -> None: ...
    async def subscribe_open_interest(self, product_symbol: str) -> None: ...
    async def subscribe_trades(self, product_symbol: str) -> None: ...
    async def recv(self) -> bytes: ...

class BackpackPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        window: int = 5000,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    def set_product_table(self, table: ProductTable) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, streams: list[str]) -> None: ...
    async def unsubscribe(self, streams: list[str]) -> None: ...
    async def subscribe_orders(self, product_symbol: str | None = None) -> None: ...
    async def subscribe_positions(self, product_symbol: str | None = None) -> None: ...
    async def subscribe_rfq(self, product_symbol: str | None = None) -> None: ...
    async def recv(self) -> bytes: ...

class BinanceHttpClient(_NativeExchangeClient):
    def request(self, *args: object, **kwargs: object) -> NativeResponse: ...
    async def request_async(self, *args: object, **kwargs: object) -> NativeResponse: ...
    def request_raw_auto_json(self, *args: object, **kwargs: object) -> NativeJsonResponse: ...
    async def request_raw_auto_json_async(
        self, *args: object, **kwargs: object
    ) -> NativeJsonResponse: ...

class BinancePublicWebSocketClient:
    def __init__(self, timeout: float = 10.0, base_url: str | None = None) -> None: ...
    def set_product_table(self, table: ProductTable) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def subscribe(self, streams: list[str]) -> int: ...
    async def unsubscribe(self, streams: list[str]) -> int: ...
    async def subscribe_trades(self, product_symbol: str) -> int: ...
    async def subscribe_agg_trades(self, product_symbol: str) -> int: ...
    async def subscribe_orderbook(self, product_symbol: str) -> int: ...
    async def subscribe_ticker(self, product_symbol: str) -> int: ...
    async def subscribe_klines(self, product_symbol: str, interval: str) -> int: ...
    async def recv(self) -> bytes: ...

class BinancePrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        timeout: float = 10.0,
        spot_http_base_url: str | None = None,
        futures_http_base_url: str | None = None,
        ws_base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> str: ...
    async def keep_alive(self) -> None: ...
    async def close_listen_key(self) -> None: ...
    async def close(self) -> None: ...
    def listen_key(self) -> str | None: ...
    async def recv(self) -> bytes: ...

class BingxHttpClient(_NativeExchangeClient): ...

class BingxPublicWebSocketClient:
    def __init__(self, timeout: float = 10.0, base_url: str | None = None) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, data_type: str) -> str: ...
    async def unsubscribe(self, data_type: str) -> str: ...
    async def subscribe_ticker(self, product_symbol: str) -> str: ...
    async def subscribe_trades(self, product_symbol: str) -> str: ...
    async def subscribe_orderbook(
        self, product_symbol: str, depth: int = 5, speed: str = "500ms"
    ) -> str: ...
    async def subscribe_klines(self, product_symbol: str, interval: str) -> str: ...
    async def recv(self) -> bytes: ...

class BingxPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        timeout: float = 10.0,
        http_base_url: str | None = None,
        ws_base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> str: ...
    async def connect_with_listen_key(self, listen_key: str) -> None: ...
    async def keep_alive(self) -> str: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, data_type: str) -> str: ...
    async def unsubscribe(self, data_type: str) -> str: ...
    async def subscribe_orders(self) -> str: ...
    def listen_key(self) -> str | None: ...
    async def recv(self) -> bytes: ...

class BitgetHttpClient(_NativeExchangeClient): ...

class BitgetPublicWebSocketClient:
    def __init__(
        self,
        inst_type: str,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    def set_product_table(self, table: ProductTable) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe_channel(self, channel: str, product_symbol: str) -> None: ...
    async def unsubscribe_channel(self, channel: str, product_symbol: str) -> None: ...
    async def subscribe_ticker(self, product_symbol: str) -> None: ...
    async def subscribe_trades(self, product_symbol: str) -> None: ...
    async def subscribe_orderbook(self, product_symbol: str, depth: int = 5) -> None: ...
    async def subscribe_klines(self, product_symbol: str, interval: str) -> None: ...
    async def recv(self) -> bytes: ...

class BitgetPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        passphrase: str,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> None: ...
    async def login(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe_channel(
        self,
        inst_type: str,
        channel: str,
        inst_id: str | None = None,
        coin: str | None = None,
    ) -> None: ...
    async def unsubscribe_channel(
        self,
        inst_type: str,
        channel: str,
        inst_id: str | None = None,
        coin: str | None = None,
    ) -> None: ...
    async def subscribe_orders(
        self, inst_type: str | None = None, inst_id: str | None = None
    ) -> None: ...
    async def subscribe_fills(
        self, inst_type: str | None = None, inst_id: str | None = None
    ) -> None: ...
    async def subscribe_positions(
        self, inst_type: str | None = None, inst_id: str | None = None
    ) -> None: ...
    async def subscribe_account(
        self, inst_type: str | None = None, coin: str | None = None
    ) -> None: ...
    async def subscribe_equity(self, inst_type: str | None = None) -> None: ...
    def is_logged_in(self) -> bool: ...
    async def recv(self) -> bytes: ...

class BitmexHttpClient(_NativeExchangeClient): ...

class BitmexPublicWebSocketClient:
    def __init__(self, timeout: float = 10.0, base_url: str | None = None) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, args: list[str]) -> None: ...
    async def unsubscribe(self, args: list[str]) -> None: ...
    async def subscribe_table(self, table: str, product_symbol: str | None = None) -> None: ...
    async def unsubscribe_table(self, table: str, product_symbol: str | None = None) -> None: ...
    async def subscribe_instrument(self, product_symbol: str) -> None: ...
    async def subscribe_trades(self, product_symbol: str) -> None: ...
    async def subscribe_quotes(self, product_symbol: str) -> None: ...
    async def subscribe_orderbook(self, product_symbol: str, depth: int = 10) -> None: ...
    async def subscribe_klines(self, product_symbol: str, bin_size: str) -> None: ...
    async def recv(self) -> bytes: ...

class BitmexPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> None: ...
    async def login(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, args: list[str]) -> None: ...
    async def unsubscribe(self, args: list[str]) -> None: ...
    async def subscribe_orders(self, product_symbol: str | None = None) -> None: ...
    async def subscribe_executions(self, product_symbol: str | None = None) -> None: ...
    async def subscribe_positions(self, product_symbol: str | None = None) -> None: ...
    async def subscribe_margin(self) -> None: ...
    async def subscribe_wallet(self) -> None: ...
    def is_authenticated(self) -> bool: ...
    async def recv(self) -> bytes: ...

class BybitHttpClient(_NativeExchangeClient): ...

class BybitPublicWebSocketClient:
    def __init__(
        self,
        category: str,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    def set_product_table(self, table: ProductTable) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def subscribe(self, topics: list[str]) -> str: ...
    async def unsubscribe(self, topics: list[str]) -> str: ...
    async def ping(self) -> str: ...
    async def subscribe_trades(self, product_symbol: str) -> str: ...
    async def subscribe_ticker(self, product_symbol: str) -> str: ...
    async def subscribe_orderbook(self, product_symbol: str, depth: int = 1) -> str: ...
    async def subscribe_klines(self, product_symbol: str, interval: str) -> str: ...
    async def recv(self) -> bytes: ...

class BybitPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> None: ...
    async def auth(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> str: ...
    async def subscribe(self, topics: list[str]) -> str: ...
    async def unsubscribe(self, topics: list[str]) -> str: ...
    async def subscribe_orders(self) -> str: ...
    async def subscribe_executions(self) -> str: ...
    async def subscribe_positions(self) -> str: ...
    async def subscribe_wallet(self) -> str: ...
    def is_authenticated(self) -> bool: ...
    async def recv(self) -> bytes: ...

class ExtendedHttpClient(_NativeExchangeClient):
    def __init__(
        self,
        api_key: str | None = None,
        stark_private_key: str | None = None,
        stark_public_key: str | None = None,
        vault_number: int | None = None,
        client_id: str | None = None,
        timeout: float = 10.0,
        base_url: str | None = None,
        user_agent: str = "dcex-rust/0.1",
    ) -> None: ...

class ExtendedPublicWebSocketClient:
    def __init__(self, timeout: float = 10.0, base_url: str | None = None) -> None: ...
    def is_connected(self) -> bool: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe_orderbook(
        self,
        market: str | None = None,
        depth: int | None = None,
    ) -> None: ...
    async def subscribe_trades(self, market: str | None = None) -> None: ...
    async def subscribe_funding(self, market: str | None = None) -> None: ...
    async def subscribe_candles(
        self,
        market: str,
        candle_type: str,
        interval: str,
    ) -> None: ...
    async def subscribe_mark_price(self, market: str | None = None) -> None: ...
    async def subscribe_index_price(self, market: str | None = None) -> None: ...
    async def recv(self) -> bytes: ...

class ExtendedPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    def is_connected(self) -> bool: ...
    async def connect(self) -> None: ...
    async def subscribe_account(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def recv(self) -> bytes: ...

class HyperliquidHttpClient(_NativeExchangeClient): ...

class HyperliquidPublicWebSocketClient:
    def __init__(
        self,
        testnet: bool = False,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def subscribe(self, subscription_json: bytes) -> None: ...
    async def unsubscribe(self, subscription_json: bytes) -> None: ...
    async def subscribe_all_mids(self, dex: str | None = None) -> None: ...
    async def subscribe_trades(self, product_symbol: str) -> None: ...
    async def subscribe_orderbook(self, product_symbol: str) -> None: ...
    async def subscribe_l2_book(
        self,
        product_symbol: str,
        n_sig_figs: int | None = None,
        mantissa: int | None = None,
    ) -> None: ...
    async def subscribe_bbo(self, product_symbol: str) -> None: ...
    async def subscribe_klines(self, product_symbol: str, interval: str) -> None: ...
    async def subscribe_active_asset_ctx(self, product_symbol: str) -> None: ...
    async def recv(self) -> bytes: ...

class HyperliquidPrivateWebSocketClient:
    def __init__(
        self,
        user: str,
        testnet: bool = False,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    def user(self) -> str: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def subscribe(self, subscription_json: bytes) -> None: ...
    async def unsubscribe(self, subscription_json: bytes) -> None: ...
    async def subscribe_user_subscription(
        self, subscription_type: str, dex: str | None = None
    ) -> None: ...
    async def unsubscribe_user_subscription(
        self, subscription_type: str, dex: str | None = None
    ) -> None: ...
    async def subscribe_notifications(self) -> None: ...
    async def subscribe_web_data3(self) -> None: ...
    async def subscribe_clearinghouse_state(self, dex: str | None = None) -> None: ...
    async def subscribe_open_orders(self, dex: str | None = None) -> None: ...
    async def subscribe_order_updates(self) -> None: ...
    async def subscribe_user_events(self) -> None: ...
    async def subscribe_user_fills(self, aggregate_by_time: bool | None = None) -> None: ...
    async def subscribe_user_fundings(self) -> None: ...
    async def subscribe_user_non_funding_ledger_updates(self) -> None: ...
    async def subscribe_twap_states(self, dex: str | None = None) -> None: ...
    async def subscribe_user_twap_slice_fills(self) -> None: ...
    async def subscribe_user_twap_history(self) -> None: ...
    async def subscribe_active_asset_data(self, product_symbol: str) -> None: ...
    async def recv(self) -> bytes: ...

class KrakenHttpClient(_NativeExchangeClient): ...

class KrakenPublicWebSocketClient:
    def __init__(self, timeout: float = 10.0, base_url: str | None = None) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> int: ...
    async def subscribe_channel(self, channel: str, product_symbols: list[str]) -> int: ...
    async def unsubscribe_channel(self, channel: str, product_symbols: list[str]) -> int: ...
    async def subscribe_ticker(self, product_symbol: str) -> int: ...
    async def subscribe_trades(self, product_symbol: str) -> int: ...
    async def subscribe_orderbook(self, product_symbol: str, depth: int = 10) -> int: ...
    async def subscribe_klines(self, product_symbol: str, interval: int = 1) -> int: ...
    async def recv(self) -> bytes: ...

class KrakenPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        timeout: float = 10.0,
        spot_http_base_url: str | None = None,
        ws_base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> str: ...
    async def fetch_token(self) -> str: ...
    async def close(self) -> None: ...
    async def ping(self) -> int: ...
    async def subscribe_balances(self) -> int: ...
    async def unsubscribe_balances(self) -> int: ...
    async def subscribe_executions(
        self, snap_orders: bool = True, snap_trades: bool = False
    ) -> int: ...
    async def unsubscribe_executions(self) -> int: ...
    def token(self) -> str | None: ...
    async def recv(self) -> bytes: ...

class KucoinHttpClient(_NativeExchangeClient): ...

class KucoinPublicWebSocketClient:
    def __init__(
        self,
        timeout: float = 10.0,
        spot_http_base_url: str | None = None,
        futures_http_base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> str: ...
    async def subscribe(self, topic: str) -> str: ...
    async def unsubscribe(self, topic: str) -> str: ...
    async def subscribe_ticker(self, product_symbol: str) -> str: ...
    async def subscribe_trades(self, product_symbol: str) -> str: ...
    async def subscribe_orderbook(self, product_symbol: str) -> str: ...
    async def subscribe_klines(self, product_symbol: str, interval: str) -> str: ...
    async def recv(self) -> bytes: ...

class KucoinPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        passphrase: str,
        timeout: float = 10.0,
        spot_http_base_url: str | None = None,
        futures_http_base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> str: ...
    async def subscribe(self, topic: str) -> str: ...
    async def unsubscribe(self, topic: str) -> str: ...
    async def subscribe_orders(self) -> str: ...
    async def subscribe_balances(self) -> str: ...
    async def recv(self) -> bytes: ...

class LighterHttpClient(_NativeExchangeClient):
    def sign_request(
        self, method_name: str, params: NativeParams | None = None
    ) -> LighterSignedTransaction: ...
    async def sign_request_async(
        self, method_name: str, params: NativeParams | None = None
    ) -> LighterSignedTransaction: ...
    def create_auth_token(
        self, deadline: int | None = None, api_key_index: int | None = None
    ) -> str: ...
    async def create_auth_token_async(
        self, deadline: int | None = None, api_key_index: int | None = None
    ) -> str: ...
    def check_client(self) -> str | None: ...
    async def check_client_async(self) -> str | None: ...

class LighterPublicWebSocketClient:
    def __init__(
        self,
        testnet: bool = False,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, channel: str) -> None: ...
    async def unsubscribe(self, channel: str) -> None: ...
    async def subscribe_orderbook(self, market_id: int) -> None: ...
    async def subscribe_ticker(self, market_id: int) -> None: ...
    async def subscribe_market_stats(self, market_id: int) -> None: ...
    async def subscribe_all_market_stats(self) -> None: ...
    async def subscribe_trades(self, market_id: int) -> None: ...
    async def subscribe_klines(self, market_id: int, resolution: str) -> None: ...
    async def subscribe_mark_price_klines(self, market_id: int, resolution: str) -> None: ...
    async def subscribe_spot_market_stats(self, market_id: int) -> None: ...
    async def subscribe_all_spot_market_stats(self) -> None: ...
    async def subscribe_height(self) -> None: ...
    async def recv(self) -> bytes: ...

class LighterPrivateWebSocketClient:
    def __init__(
        self,
        account_index: int,
        api_key_index: int,
        api_private_key: str,
        testnet: bool = False,
        timeout: float = 10.0,
        ws_base_url: str | None = None,
        http_base_url: str | None = None,
    ) -> None: ...
    def account_index(self) -> int: ...
    def create_auth_token(
        self, deadline: int | None = None, api_key_index: int | None = None
    ) -> str: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, channel: str, auth: str | None = None) -> None: ...
    async def unsubscribe(self, channel: str) -> None: ...
    async def subscribe_authenticated(self, channel: str) -> None: ...
    async def subscribe_account_all(self) -> None: ...
    async def subscribe_account_market(self, market_id: int) -> None: ...
    async def subscribe_user_stats(self) -> None: ...
    async def subscribe_account_tx(self) -> None: ...
    async def subscribe_account_all_orders(self) -> None: ...
    async def subscribe_pool_data(self) -> None: ...
    async def subscribe_pool_info(self) -> None: ...
    async def subscribe_notifications(self) -> None: ...
    async def subscribe_account_orders(self, market_id: int) -> None: ...
    async def subscribe_account_all_trades(self) -> None: ...
    async def subscribe_account_all_positions(self) -> None: ...
    async def subscribe_account_all_assets(self) -> None: ...
    async def subscribe_account_spot_avg_entry_prices(self) -> None: ...
    async def subscribe_rfq(self) -> None: ...
    async def recv(self) -> bytes: ...

class MexcHttpClient(_NativeExchangeClient): ...

class MexcPublicWebSocketClient:
    def __init__(self, timeout: float = 10.0, base_url: str | None = None) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, channels: list[str]) -> None: ...
    async def unsubscribe(self, channels: list[str]) -> None: ...
    async def subscribe_trades(self, product_symbol: str) -> None: ...
    async def subscribe_orderbook(self, product_symbol: str, speed: str | None = None) -> None: ...
    async def subscribe_partial_orderbook(self, product_symbol: str, levels: int = 5) -> None: ...
    async def subscribe_book_ticker(self, product_symbol: str) -> None: ...
    async def subscribe_klines(self, product_symbol: str, interval: str) -> None: ...
    async def recv(self) -> bytes: ...

class MexcPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str | None = None,
        timeout: float = 10.0,
        spot_http_base_url: str | None = None,
        ws_base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> str: ...
    async def keep_alive(self) -> str: ...
    async def close_listen_key(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, channels: list[str]) -> None: ...
    async def unsubscribe(self, channels: list[str]) -> None: ...
    async def subscribe_account(self) -> None: ...
    async def subscribe_deals(self) -> None: ...
    async def subscribe_orders(self) -> None: ...
    def listen_key(self) -> str | None: ...
    async def recv(self) -> bytes: ...

class OkxHttpClient(_NativeExchangeClient): ...

class OkxPublicWebSocketClient:
    def __init__(self, timeout: float = 10.0, base_url: str | None = None) -> None: ...
    def set_product_table(self, table: ProductTable) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def subscribe_channel(self, channel: str, product_symbol: str | None = None) -> None: ...
    async def unsubscribe_channel(
        self, channel: str, product_symbol: str | None = None
    ) -> None: ...
    async def subscribe_trades(self, product_symbol: str) -> None: ...
    async def subscribe_ticker(self, product_symbol: str) -> None: ...
    async def subscribe_orderbook(self, product_symbol: str) -> None: ...
    async def subscribe_orderbook5(self, product_symbol: str) -> None: ...
    async def subscribe_klines(self, product_symbol: str, interval: str) -> None: ...
    async def recv(self) -> bytes: ...

class OkxPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        passphrase: str,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> None: ...
    async def login(self) -> None: ...
    async def close(self) -> None: ...
    async def subscribe_channel(
        self,
        channel: str,
        inst_type: str | None = None,
        inst_id: str | None = None,
        ccy: str | None = None,
    ) -> None: ...
    async def unsubscribe_channel(
        self,
        channel: str,
        inst_type: str | None = None,
        inst_id: str | None = None,
        ccy: str | None = None,
    ) -> None: ...
    async def subscribe_orders(
        self, inst_type: str | None = None, inst_id: str | None = None
    ) -> None: ...
    async def subscribe_account(self, ccy: str | None = None) -> None: ...
    async def subscribe_positions(self, inst_type: str | None = None) -> None: ...
    def is_logged_in(self) -> bool: ...
    async def recv(self) -> bytes: ...

def fetch_product_table(
    exchange_name: str | None = None, timeout: float = 10.0
) -> ProductTable: ...
async def fetch_product_table_async(
    exchange_name: str | None = None,
    timeout: float = 10.0,  # noqa: ASYNC109
) -> ProductTable: ...
def lighter_poseidon_hash_bytes(values: list[int]) -> bytes: ...
def lighter_public_key_bytes(private_key: bytes) -> bytes: ...
def lighter_schnorr_sign(message_hash: bytes, private_key: bytes, nonce: bytes) -> bytes: ...
def lighter_sign_transaction(
    values: list[int],
    attributes: list[tuple[int, int]],
    payload_json: bytes,
    private_key: bytes,
    nonce: bytes,
) -> tuple[bytes, bytes]: ...
def lighter_auth_token(
    expiry: int,
    account_index: int,
    api_key_index: int,
    private_key: bytes,
    nonce: bytes,
) -> str: ...
def aster_sign_message(message: str, private_key: str) -> str: ...
def exchange_names() -> list[str]: ...
def order_side_parse(value: str) -> str: ...
def order_side_to_exchange(side: str, exchange: str) -> str: ...
def order_side_is_buy(side: str) -> bool: ...
def generate_timestamp_ms() -> int: ...
def generate_timestamp_iso() -> str: ...
def get_decimal_places(value: float) -> int: ...
def reverse_decimal_places(decimal_places: int) -> float: ...
def bybit_convert_timeframe(timeframe: str) -> str: ...
def kucoin_convert_timeframe(timeframe: str) -> str: ...
def address_to_bytes(address: str) -> bytes: ...
def sanitize_url(url: str) -> str: ...
def sanitize_message(message: str) -> str: ...
def sanitize_request(request: str) -> str: ...
def __getattr__(name: str) -> Any: ...  # noqa: ANN401
