"""Type declarations for the dcex Rust extension."""

from typing import Any

NativeHeaders = dict[str, str]
NativeParams = list[tuple[str, str]]
NativeResponse = tuple[int, NativeHeaders, bytes]
LighterSignedTransaction = tuple[int, str, str, str | None]

class ProductColumn:
    """Column view returned by ProductTable string indexing."""

    def to_list(self) -> list[str]: ...

class ProductTable:
    """Indexed canonical and exchange-specific product metadata."""

    def __init__(self, rows: list[dict[str, str]]) -> None: ...
    @property
    def height(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: int | str) -> dict[str, str] | ProductColumn: ...
    def rows(self) -> list[dict[str, str]]: ...
    def to_dicts(self) -> list[dict[str, str]]: ...
    def write_csv(self, path: str | object) -> None: ...
    def get(
        self,
        key: str,
        product_symbol: str | None = None,
        exchange: str | None = None,
        product_type: str | None = None,
        exchange_type: str | None = None,
        exchange_symbol: str | None = None,
    ) -> str: ...
    def get_exchange_symbol(self, exchange: str, product_symbol: str) -> str: ...
    def get_product_symbol(
        self,
        exchange: str,
        exchange_symbol: str,
        product_type: str | None = None,
        exchange_type: str | None = None,
    ) -> str: ...
    def get_product_type(
        self,
        exchange: str,
        product_symbol: str | None = None,
        exchange_symbol: str | None = None,
    ) -> str: ...
    def get_exchange_type(
        self,
        exchange: str,
        product_symbol: str | None = None,
        exchange_symbol: str | None = None,
    ) -> str: ...
    def get_base_currency(self, exchange: str, product_symbol: str) -> str: ...
    def get_quote_currency(self, exchange: str, product_symbol: str) -> str: ...
    def get_trading_details(self, exchange: str, product_symbol: str) -> dict[str, str]: ...
    def get_exchange_symbols(
        self,
        exchange: str,
        product_type: str | None = None,
        exchange_type: str | None = None,
    ) -> list[str]: ...
    def get_product_symbols(
        self,
        exchange: str,
        product_type: str | None = None,
        exchange_type: str | None = None,
    ) -> list[str]: ...

class HttpClient:
    """Low-level native HTTP client."""

    def __init__(self, timeout: float = 10.0) -> None: ...
    def request(
        self,
        method: str,
        base_url: str,
        path: str,
        query: NativeParams | None = None,
        headers: NativeHeaders | None = None,
        body: bytes | None = None,
    ) -> NativeResponse: ...
    async def request_async(
        self,
        method: str,
        base_url: str,
        path: str,
        query: NativeParams | None = None,
        headers: NativeHeaders | None = None,
        body: bytes | None = None,
    ) -> NativeResponse: ...

class _NativeExchangeClient:
    """Common methods exposed by exchange-specific native clients."""

    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def set_product_table(self, table: ProductTable) -> None: ...
    def public_request(
        self, method_name: str, params: NativeParams | None = None
    ) -> NativeResponse: ...
    async def public_request_async(
        self, method_name: str, params: NativeParams | None = None
    ) -> NativeResponse: ...
    def private_request(
        self, method_name: str, params: NativeParams | None = None
    ) -> NativeResponse: ...
    async def private_request_async(
        self, method_name: str, params: NativeParams | None = None
    ) -> NativeResponse: ...
    def request_raw(self, *args: object, **kwargs: object) -> NativeResponse: ...
    async def request_raw_async(self, *args: object, **kwargs: object) -> NativeResponse: ...

class AsterHttpClient(_NativeExchangeClient):
    def request_raw_auto(self, *args: object, **kwargs: object) -> NativeResponse: ...
    async def request_raw_auto_async(self, *args: object, **kwargs: object) -> NativeResponse: ...

class BackpackHttpClient(_NativeExchangeClient): ...

class BinanceHttpClient(_NativeExchangeClient):
    def request(self, *args: object, **kwargs: object) -> NativeResponse: ...
    async def request_async(self, *args: object, **kwargs: object) -> NativeResponse: ...
    def request_raw_auto(self, *args: object, **kwargs: object) -> NativeResponse: ...
    async def request_raw_auto_async(self, *args: object, **kwargs: object) -> NativeResponse: ...

class BinancePublicWebSocketClient:
    def __init__(self, timeout: float = 10.0, base_url: str | None = None) -> None: ...
    def set_product_table(self, table: ProductTable) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def subscribe(self, streams: list[str]) -> int: ...
    async def unsubscribe(self, streams: list[str]) -> int: ...
    async def subscribe_trades(self, product_symbol: str) -> int: ...
    async def subscribe_agg_trades(self, product_symbol: str) -> int: ...
    async def subscribe_orderbook(self, product_symbol: str) -> int: ...
    async def subscribe_ticker(self, product_symbol: str) -> int: ...
    async def subscribe_klines(self, product_symbol: str, interval: str) -> int: ...
    async def recv(self) -> bytes: ...

class BinancePrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        timeout: float = 10.0,
        spot_http_base_url: str | None = None,
        futures_http_base_url: str | None = None,
        ws_base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> str: ...
    async def keep_alive(self) -> None: ...
    async def close_listen_key(self) -> None: ...
    async def close(self) -> None: ...
    def listen_key(self) -> str | None: ...
    async def recv(self) -> bytes: ...

class BingxHttpClient(_NativeExchangeClient): ...
class BitgetHttpClient(_NativeExchangeClient): ...

class BitgetPublicWebSocketClient:
    def __init__(
        self,
        inst_type: str,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    def set_product_table(self, table: ProductTable) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe_channel(self, channel: str, product_symbol: str) -> None: ...
    async def unsubscribe_channel(self, channel: str, product_symbol: str) -> None: ...
    async def subscribe_ticker(self, product_symbol: str) -> None: ...
    async def subscribe_trades(self, product_symbol: str) -> None: ...
    async def subscribe_orderbook(self, product_symbol: str, depth: int = 5) -> None: ...
    async def subscribe_klines(self, product_symbol: str, interval: str) -> None: ...
    async def recv(self) -> bytes: ...

class BitgetPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        passphrase: str,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> None: ...
    async def login(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe_channel(
        self,
        inst_type: str,
        channel: str,
        inst_id: str | None = None,
        coin: str | None = None,
    ) -> None: ...
    async def unsubscribe_channel(
        self,
        inst_type: str,
        channel: str,
        inst_id: str | None = None,
        coin: str | None = None,
    ) -> None: ...
    async def subscribe_orders(
        self, inst_type: str | None = None, inst_id: str | None = None
    ) -> None: ...
    async def subscribe_fills(
        self, inst_type: str | None = None, inst_id: str | None = None
    ) -> None: ...
    async def subscribe_positions(
        self, inst_type: str | None = None, inst_id: str | None = None
    ) -> None: ...
    async def subscribe_account(
        self, inst_type: str | None = None, coin: str | None = None
    ) -> None: ...
    async def subscribe_equity(self, inst_type: str | None = None) -> None: ...
    def is_logged_in(self) -> bool: ...
    async def recv(self) -> bytes: ...

class BitmartHttpClient(_NativeExchangeClient):
    def request_raw_auto(self, *args: object, **kwargs: object) -> NativeResponse: ...
    async def request_raw_auto_async(self, *args: object, **kwargs: object) -> NativeResponse: ...

class BitmartPublicWebSocketClient:
    def __init__(self, timeout: float = 10.0, base_url: str | None = None) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, topics: list[str]) -> None: ...
    async def unsubscribe(self, topics: list[str]) -> None: ...
    async def request_depth_snapshot(self, product_symbol: str) -> None: ...
    async def subscribe_ticker(self, product_symbol: str) -> None: ...
    async def subscribe_book_ticker(self, product_symbol: str) -> None: ...
    async def subscribe_klines(self, product_symbol: str, interval: str) -> None: ...
    async def subscribe_orderbook(self, product_symbol: str, depth: int = 20) -> None: ...
    async def subscribe_depth_increase(self, product_symbol: str) -> None: ...
    async def subscribe_trades(self, product_symbol: str) -> None: ...
    async def recv(self) -> bytes: ...

class BitmartPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        memo: str,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> None: ...
    async def login(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, topics: list[str]) -> None: ...
    async def unsubscribe(self, topics: list[str]) -> None: ...
    async def subscribe_orders(self, product_symbol: str | None = None) -> None: ...
    async def subscribe_balance(self) -> None: ...
    def is_logged_in(self) -> bool: ...
    async def recv(self) -> bytes: ...

class BitmexHttpClient(_NativeExchangeClient): ...

class BitmexPublicWebSocketClient:
    def __init__(self, timeout: float = 10.0, base_url: str | None = None) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, args: list[str]) -> None: ...
    async def unsubscribe(self, args: list[str]) -> None: ...
    async def subscribe_table(self, table: str, product_symbol: str | None = None) -> None: ...
    async def unsubscribe_table(self, table: str, product_symbol: str | None = None) -> None: ...
    async def subscribe_instrument(self, product_symbol: str) -> None: ...
    async def subscribe_trades(self, product_symbol: str) -> None: ...
    async def subscribe_quotes(self, product_symbol: str) -> None: ...
    async def subscribe_orderbook(self, product_symbol: str, depth: int = 10) -> None: ...
    async def subscribe_klines(self, product_symbol: str, bin_size: str) -> None: ...
    async def recv(self) -> bytes: ...

class BitmexPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> None: ...
    async def login(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, args: list[str]) -> None: ...
    async def unsubscribe(self, args: list[str]) -> None: ...
    async def subscribe_orders(self, product_symbol: str) -> None: ...
    async def subscribe_executions(self, product_symbol: str) -> None: ...
    async def subscribe_positions(self, product_symbol: str) -> None: ...
    async def subscribe_margin(self) -> None: ...
    async def subscribe_wallet(self) -> None: ...
    def is_authenticated(self) -> bool: ...
    async def recv(self) -> bytes: ...

class BybitHttpClient(_NativeExchangeClient): ...

class BybitPublicWebSocketClient:
    def __init__(
        self,
        category: str,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    def set_product_table(self, table: ProductTable) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def subscribe(self, topics: list[str]) -> str: ...
    async def unsubscribe(self, topics: list[str]) -> str: ...
    async def ping(self) -> str: ...
    async def subscribe_trades(self, product_symbol: str) -> str: ...
    async def subscribe_ticker(self, product_symbol: str) -> str: ...
    async def subscribe_orderbook(self, product_symbol: str, depth: int = 1) -> str: ...
    async def subscribe_klines(self, product_symbol: str, interval: str) -> str: ...
    async def recv(self) -> bytes: ...

class BybitPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> None: ...
    async def auth(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> str: ...
    async def subscribe(self, topics: list[str]) -> str: ...
    async def unsubscribe(self, topics: list[str]) -> str: ...
    async def subscribe_orders(self) -> str: ...
    async def subscribe_executions(self) -> str: ...
    async def subscribe_positions(self) -> str: ...
    async def subscribe_wallet(self) -> str: ...
    def is_authenticated(self) -> bool: ...
    async def recv(self) -> bytes: ...

class GateioHttpClient(_NativeExchangeClient): ...

class GateioPublicWebSocketClient:
    def __init__(self, timeout: float = 10.0, base_url: str | None = None) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, channel: str, payload: list[str]) -> None: ...
    async def unsubscribe(self, channel: str, payload: list[str]) -> None: ...
    async def subscribe_ticker(self, product_symbol: str) -> None: ...
    async def subscribe_trades(self, product_symbol: str) -> None: ...
    async def subscribe_candlesticks(self, product_symbol: str, interval: str) -> None: ...
    async def subscribe_book_ticker(self, product_symbol: str) -> None: ...
    async def subscribe_orderbook(self, product_symbol: str, speed: str = "100ms") -> None: ...
    async def recv(self) -> bytes: ...

class GateioPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, channel: str, payload: list[str]) -> None: ...
    async def unsubscribe(self, channel: str, payload: list[str]) -> None: ...
    async def subscribe_orders(self, product_symbols: list[str]) -> None: ...
    async def subscribe_user_trades(self, product_symbols: list[str]) -> None: ...
    async def subscribe_balances(self) -> None: ...
    async def recv(self) -> bytes: ...

class HyperliquidHttpClient(_NativeExchangeClient): ...
class KrakenHttpClient(_NativeExchangeClient): ...

class KrakenPublicWebSocketClient:
    def __init__(self, timeout: float = 10.0, base_url: str | None = None) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> int: ...
    async def subscribe_channel(self, channel: str, product_symbols: list[str]) -> int: ...
    async def unsubscribe_channel(self, channel: str, product_symbols: list[str]) -> int: ...
    async def subscribe_ticker(self, product_symbol: str) -> int: ...
    async def subscribe_trades(self, product_symbol: str) -> int: ...
    async def subscribe_orderbook(self, product_symbol: str, depth: int = 10) -> int: ...
    async def subscribe_klines(self, product_symbol: str, interval: int = 1) -> int: ...
    async def recv(self) -> bytes: ...

class KrakenPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        timeout: float = 10.0,
        spot_http_base_url: str | None = None,
        ws_base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> str: ...
    async def fetch_token(self) -> str: ...
    async def close(self) -> None: ...
    async def ping(self) -> int: ...
    async def subscribe_balances(self) -> int: ...
    async def unsubscribe_balances(self) -> int: ...
    async def subscribe_executions(
        self, snap_orders: bool = True, snap_trades: bool = False
    ) -> int: ...
    async def unsubscribe_executions(self) -> int: ...
    def token(self) -> str | None: ...
    async def recv(self) -> bytes: ...

class KucoinHttpClient(_NativeExchangeClient): ...

class LighterHttpClient(_NativeExchangeClient):
    def sign_request(
        self, method_name: str, params: NativeParams | None = None
    ) -> LighterSignedTransaction: ...
    async def sign_request_async(
        self, method_name: str, params: NativeParams | None = None
    ) -> LighterSignedTransaction: ...
    def create_auth_token(
        self, deadline: int | None = None, api_key_index: int | None = None
    ) -> str: ...
    async def create_auth_token_async(
        self, deadline: int | None = None, api_key_index: int | None = None
    ) -> str: ...
    def check_client(self) -> str | None: ...
    async def check_client_async(self) -> str | None: ...

class MexcHttpClient(_NativeExchangeClient): ...

class MexcPublicWebSocketClient:
    def __init__(self, timeout: float = 10.0, base_url: str | None = None) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, channels: list[str]) -> None: ...
    async def unsubscribe(self, channels: list[str]) -> None: ...
    async def subscribe_trades(self, product_symbol: str) -> None: ...
    async def subscribe_orderbook(self, product_symbol: str, speed: str | None = None) -> None: ...
    async def subscribe_partial_orderbook(self, product_symbol: str, levels: int = 5) -> None: ...
    async def subscribe_book_ticker(self, product_symbol: str) -> None: ...
    async def subscribe_klines(self, product_symbol: str, interval: str) -> None: ...
    async def recv(self) -> bytes: ...

class MexcPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        timeout: float = 10.0,
        spot_http_base_url: str | None = None,
        ws_base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> str: ...
    async def keep_alive(self) -> str: ...
    async def close_listen_key(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> None: ...
    async def subscribe(self, channels: list[str]) -> None: ...
    async def unsubscribe(self, channels: list[str]) -> None: ...
    async def subscribe_account(self) -> None: ...
    async def subscribe_deals(self) -> None: ...
    async def subscribe_orders(self) -> None: ...
    def listen_key(self) -> str | None: ...
    async def recv(self) -> bytes: ...

class OkxHttpClient(_NativeExchangeClient): ...

class OkxPublicWebSocketClient:
    def __init__(self, timeout: float = 10.0, base_url: str | None = None) -> None: ...
    def set_product_table(self, table: ProductTable) -> None: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def subscribe_channel(self, channel: str, product_symbol: str | None = None) -> None: ...
    async def unsubscribe_channel(
        self, channel: str, product_symbol: str | None = None
    ) -> None: ...
    async def subscribe_trades(self, product_symbol: str) -> None: ...
    async def subscribe_ticker(self, product_symbol: str) -> None: ...
    async def subscribe_orderbook(self, product_symbol: str) -> None: ...
    async def subscribe_orderbook5(self, product_symbol: str) -> None: ...
    async def subscribe_klines(self, product_symbol: str, interval: str) -> None: ...
    async def recv(self) -> bytes: ...

class OkxPrivateWebSocketClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        passphrase: str,
        timeout: float = 10.0,
        base_url: str | None = None,
    ) -> None: ...
    async def connect(self) -> None: ...
    async def login(self) -> None: ...
    async def close(self) -> None: ...
    async def subscribe_channel(
        self,
        channel: str,
        inst_type: str | None = None,
        inst_id: str | None = None,
        ccy: str | None = None,
    ) -> None: ...
    async def unsubscribe_channel(
        self,
        channel: str,
        inst_type: str | None = None,
        inst_id: str | None = None,
        ccy: str | None = None,
    ) -> None: ...
    async def subscribe_orders(
        self, inst_type: str | None = None, inst_id: str | None = None
    ) -> None: ...
    async def subscribe_account(self, ccy: str | None = None) -> None: ...
    async def subscribe_positions(self, inst_type: str | None = None) -> None: ...
    def is_logged_in(self) -> bool: ...
    async def recv(self) -> bytes: ...

def fetch_product_table(
    exchange_name: str | None = None, timeout: float = 10.0
) -> ProductTable: ...
async def fetch_product_table_async(
    exchange_name: str | None = None,
    timeout: float = 10.0,  # noqa: ASYNC109
) -> ProductTable: ...
def lighter_poseidon_hash_bytes(values: list[int]) -> bytes: ...
def lighter_public_key_bytes(private_key: bytes) -> bytes: ...
def lighter_schnorr_sign(message_hash: bytes, private_key: bytes, nonce: bytes) -> bytes: ...
def lighter_sign_transaction(
    values: list[int],
    attributes: list[tuple[int, int]],
    payload_json: bytes,
    private_key: bytes,
    nonce: bytes,
) -> tuple[bytes, bytes]: ...
def lighter_auth_token(
    expiry: int,
    account_index: int,
    api_key_index: int,
    private_key: bytes,
    nonce: bytes,
) -> str: ...
def aster_sign_message(message: str, private_key: str) -> str: ...
def exchange_names() -> list[str]: ...
def order_side_parse(value: str) -> str: ...
def order_side_to_exchange(side: str, exchange: str) -> str: ...
def order_side_is_buy(side: str) -> bool: ...
def generate_timestamp_ms() -> int: ...
def generate_timestamp_iso() -> str: ...
def get_decimal_places(value: float) -> int: ...
def reverse_decimal_places(decimal_places: int) -> float: ...
def bybit_convert_timeframe(timeframe: str) -> str: ...
def bitmart_convert_timeframe(timeframe: str) -> int: ...
def kucoin_convert_timeframe(timeframe: str) -> str: ...
def address_to_bytes(address: str) -> bytes: ...
def sanitize_url(url: str) -> str: ...
def sanitize_message(message: str) -> str: ...
def sanitize_request(request: str) -> str: ...
def __getattr__(name: str) -> Any: ...  # noqa: ANN401
