use super::BinanceClient;
crate::exchanges::impl_exchange_method_wrappers! {
    @extend; BinanceClient;
    public [
        alpha_aggregated_trades(symbol => "symbol"),
        alpha_full_depth(symbol => "symbol"),
        alpha_get_exchange_info(),
        alpha_klines(symbol => "symbol", interval => "interval"),
        alpha_ticker(symbol => "symbol"),
        alpha_token_list(),
        acquiring_algorithm(),
        acquiring_coinname(),
        prediction_get_market_detail(market_topic_id => "marketTopicId"),
        prediction_list_prediction_categories(),
        prediction_list_prediction_markets(),
        prediction_market_search(query => "query"),
        prediction_query_last_trade_price(market_id => "marketId"),
        prediction_query_order_book(vendor => "vendor", market_id => "marketId", token_id => "tokenId"),
    ];
    private [
        get_c2_c_trade_history(),
        fiat_deposit(currency => "currency", api_payment_method => "apiPaymentMethod", amount => "amount"),
        /// API withdrawals have no second confirmation; they execute on submit.
        fiat_withdraw(currency => "currency", api_payment_method => "apiPaymentMethod", amount => "amount", account_info => "accountInfo"),
        get_fiat_deposit_withdraw_history(transaction_type => "transactionType"),
        get_fiat_payments_history(transaction_type => "transactionType"),
        get_order_detail(order_no => "orderNo"),
        create_a_dual_token_gift_card(base_token => "baseToken", face_token => "faceToken", base_token_amount => "baseTokenAmount"),
        create_a_single_token_gift_card(token => "token", amount => "amount"),
        fetch_rsa_public_key(),
        fetch_token_limit(base_token => "baseToken"),
        redeem_a_binance_gift_card(code => "code"),
        verify_binance_gift_card_by_gift_card_number(reference_no => "referenceNo"),
        account_list(algo => "algo", user_name => "userName"),
        cancel_hashrate_resale_configuration(config_id => "configId", user_name => "userName"),
        earnings_list(algo => "algo", user_name => "userName"),
        extra_bonus_list(algo => "algo", user_name => "userName"),
        hashrate_resale_detail(config_id => "configId"),
        hashrate_resale_list(),
        hashrate_resale_request(user_name => "userName", algo => "algo", end_date => "endDate", start_date => "startDate", to_pool_user => "toPoolUser", hash_rate => "hashRate"),
        mining_account_earning(algo => "algo"),
        request_for_detail_miner_list(algo => "algo", user_name => "userName", worker_name => "workerName"),
        request_for_miner_list(algo => "algo", user_name => "userName"),
        statistic_list(algo => "algo", user_name => "userName"),
        get_pay_trade_history(),
        get_spot_rebate_history_records(),
        get_borrow_interest_rate(loan_coin => "loanCoin"),
        get_collateral_asset_data(),
        get_loanable_assets_data(),
        get_vip_loan_interest_rate_history(coin => "coin", recv_window => "recvWindow"),
        query_vip_loan_fixed_rate_market(loan_coin => "loanCoin"),
        vip_loan_borrow(loan_account_id => "loanAccountId", loan_coin => "loanCoin", loan_amount => "loanAmount", collateral_account_id => "collateralAccountId", collateral_coin => "collateralCoin", is_flexible_rate => "isFlexibleRate"),
        vip_loan_fixed_rate_borrow(supply_request => "supplyRequest", borrow_coin => "borrowCoin", loan_term => "loanTerm", borrow_uid => "borrowUid", collateral_coin => "collateralCoin", collateral_account_id => "collateralAccountId"),
        vip_loan_renew(order_id => "orderId", loan_term => "loanTerm"),
        vip_loan_repay(order_id => "orderId", amount => "amount"),
        check_vip_loan_collateral_account(),
        get_vip_loan_accrued_interest(),
        get_vip_loan_ongoing_orders(),
        get_vip_loan_repayment_history(),
        query_application_status(),
        prediction_create_otc_blocktrade(market_id => "marketId", token_id => "tokenId", side => "side", maker_amount => "makerAmount", taker_amount => "takerAmount", price_per_share => "pricePerShare", expiration => "expiration"),
        prediction_fulfil_otc_blocktrade(order_id => "orderId", secret_token => "secretToken"),
        prediction_get_otc_blocktrade_detail(order_id => "orderId"),
        prediction_get_otc_blocktrade_events(),
        prediction_get_otc_reserved_balances(assets => "assets"),
        prediction_list_otc_blocktrades(),
        prediction_preview_otc_blocktrade(secret_token => "secretToken"),
        prediction_remove_otc_blocktrades(order_ids => "orderIds"),
        prediction_get_position_by_token(wallet_address => "walletAddress", token_id => "tokenId"),
        prediction_query_pn_l(wallet_address => "walletAddress"),
        prediction_query_positions(wallet_address => "walletAddress"),
        prediction_query_positions_by_filter(),
        prediction_query_settled_position_history(wallet_address => "walletAddress"),
        prediction_batch_redeem(wallet_address => "walletAddress", wallet_id => "walletId", token_ids => "tokenIds"),
        prediction_get_redeem_status(wallet_address => "walletAddress", tx_hash => "txHash"),
        prediction_batch_cancel_orders(wallet_address => "walletAddress", wallet_id => "walletId"),
        prediction_get_quote(wallet_address => "walletAddress", token_id => "tokenId", side => "side", amount_in => "amountIn", order_type => "orderType", slippage_bps => "slippageBps"),
        prediction_place_order(wallet_address => "walletAddress", wallet_id => "walletId", quote_id => "quoteId", time_in_force => "timeInForce", account_type => "accountType", order_type => "orderType", slippage_bps => "slippageBps"),
        prediction_query_active_orders(wallet_address => "walletAddress"),
        prediction_query_order_history(wallet_address => "walletAddress"),
        prediction_apply_mm_deposit(from_token => "fromToken", from_token_amount => "fromTokenAmount", to_token => "toToken", account_type => "accountType"),
        /// API withdrawals have no second confirmation; they execute on submit.
        prediction_apply_mm_withdraw(coin => "coin", network => "network", amount => "amount"),
        prediction_create_inbound_transfer(wallet_id => "walletId", wallet_address => "walletAddress", from_token_amount => "fromTokenAmount", account_type => "accountType"),
        prediction_create_outbound_transfer(wallet_id => "walletId", wallet_address => "walletAddress", from_token_amount => "fromTokenAmount", account_type => "accountType", source_biz => "sourceBiz"),
        prediction_query_transfer_list(wallet_address => "walletAddress", start_date => "startDate", end_date => "endDate"),
        prediction_query_transfer_status(transfer_id => "transferId"),
        prediction_get_portfolio(wallet_address => "walletAddress"),
        prediction_get_quota_status(),
        prediction_list_prediction_wallets(),
        prediction_query_payment_option_balances(),
    ];
}
