use crate::exchanges::binance::BinanceClient;
crate::exchanges::impl_exchange_method_wrappers! { @extend; BinanceClient; public []; private [
accept_options_block_order(block_order_matching_key => "blockOrderMatchingKey"),
get_options_account_block_trades(),
cancel_options_block_order(block_order_matching_key => "blockOrderMatchingKey"),
extend_options_block_order(block_order_matching_key => "blockOrderMatchingKey"),
create_options_block_order(liquidity => "liquidity",legs => "legs"),
get_options_block_order_details(block_order_matching_key => "blockOrderMatchingKey"),
get_options_block_orders(),
/// API withdrawals and external transfers have no second confirmation; they execute on submit.
withdraw_managed_sub_account(from_email => "fromEmail",asset => "asset",amount => "amount"),
disable_fast_withdraw_switch(),
enable_fast_withdraw_switch(),
/// API withdrawals and external transfers have no second confirmation; they execute on submit.
create_withdrawal(coin => "coin",address => "address",amount => "amount"),
/// API withdrawals and external transfers have no second confirmation; they execute on submit.
create_broker_withdrawal(address => "address",coin => "coin",amount => "amount",withdraw_order_id => "withdrawOrderId",questionnaire => "questionnaire",originator_pii => "originatorPii"),
submit_broker_deposit_questionnaire(sub_account_id => "subAccountId",deposit_id => "depositId",questionnaire => "questionnaire",beneficiary_pii => "beneficiaryPii"),
/// API withdrawals and external transfers have no second confirmation; they execute on submit.
create_travel_rule_withdrawal(coin => "coin",address => "address",amount => "amount",questionnaire => "questionnaire"),
]; }

mod schema_methods {
    use crate::exchanges::binance::client::BinanceClient;
    crate::exchanges::impl_exchange_method_wrappers! { @extend; BinanceClient; public [
    get_coin_futures_aggregate_trades(symbol => "symbol"),
    get_coin_futures_continuous_klines(pair => "pair",contract_type => "contractType",interval => "interval"),
    get_coin_futures_funding_info(),
    get_coin_futures_index_price_klines(pair => "pair",interval => "interval"),
    get_coin_futures_mark_price_klines(symbol => "symbol",interval => "interval"),
    get_coin_futures_open_interest(symbol => "symbol"),
    get_coin_futures_premium_index_klines(symbol => "symbol",interval => "interval"),
    get_coin_futures_book_ticker(),
    get_coin_futures_24h_ticker(),
    get_futures_aggregate_trades(product_symbol => "product_symbol"),
    get_futures_continuous_klines(pair => "pair",contract_type => "contractType",interval => "interval"),
    get_futures_funding_info(),
    get_futures_index_price_klines(pair => "pair",interval => "interval"),
    get_futures_mark_price_klines(product_symbol => "product_symbol",interval => "interval"),
    get_futures_premium_index_klines(product_symbol => "product_symbol",interval => "interval"),
    get_futures_recent_trades(product_symbol => "product_symbol"),
    get_futures_price_ticker_v1(),
    get_futures_price_ticker(),
    get_futures_24h_ticker(),
    get_margin_delist_schedule(),
    get_spot_aggregate_trades(product_symbol => "product_symbol"),
    get_spot_average_price(product_symbol => "product_symbol"),
    get_spot_24h_ticker(),
    get_spot_book_ticker(),
    get_spot_delist_schedule(),
    get_system_status(),
    ]; private [
    place_spot_sor_order(symbol => "symbol", side => "side", order_type => "type", quantity => "quantity"),
    test_spot_sor_order(symbol => "symbol", side => "side", order_type => "type", quantity => "quantity"),
    sign_futures_tradfi_perps_contract(),
    liquidate_margin_account(kind_type => "type"),

    place_margin_oco(product_symbol => "product_symbol",side => "side",quantity => "quantity",price => "price",stop_price => "stopPrice"),
    place_margin_oto(product_symbol => "product_symbol",working_type => "workingType",working_side => "workingSide",working_price => "workingPrice",working_quantity => "workingQuantity",working_iceberg_qty => "workingIcebergQty",pending_type => "pendingType",pending_side => "pendingSide",pending_quantity => "pendingQuantity"),
    place_margin_otoco(product_symbol => "product_symbol",working_type => "workingType",working_side => "workingSide",working_price => "workingPrice",working_quantity => "workingQuantity",pending_side => "pendingSide",pending_quantity => "pendingQuantity",pending_above_type => "pendingAboveType"),
    place_spot_opo(product_symbol => "product_symbol",working_type => "workingType",working_side => "workingSide",working_price => "workingPrice",working_quantity => "workingQuantity",pending_type => "pendingType",pending_side => "pendingSide"),
    place_spot_opoco(product_symbol => "product_symbol",working_type => "workingType",working_side => "workingSide",working_price => "workingPrice",working_quantity => "workingQuantity",pending_side => "pendingSide",pending_above_type => "pendingAboveType"),
    get_coin_futures_income_history(),
    get_coin_futures_commission_rate(symbol => "symbol"),
    adjust_coin_futures_position_margin(symbol => "symbol",amount => "amount",kind_type => "type"),
    get_coin_futures_adl_quantiles(),
    get_coin_futures_force_orders(),
    get_pm_coin_income_history(),
    get_pm_margin_interest_history(),
    get_pm_futures_income_history(),
    get_pm_coin_commission_rate(symbol => "symbol"),
    get_pm_futures_commission_rate(product_symbol => "product_symbol"),
    get_pm_margin_loan_records(asset => "asset"),
    get_pm_margin_transferable_amount(asset => "asset"),
    get_pm_margin_repayment_records(asset => "asset"),
    get_pm_order_rate_limits(),
    get_futures_account_config(),
    get_futures_trading_status(),
    get_futures_multi_assets_mode(),
    get_futures_order_rate_limits(),
    get_futures_symbol_config(),
    set_futures_multi_assets_mode(multi_assets_margin => "multiAssetsMargin"),
    adjust_futures_position_margin(product_symbol => "product_symbol",amount => "amount",kind_type => "type"),
    get_futures_adl_quantiles(),
    get_futures_force_orders(),
    get_margin_risk_coefficients(),
    get_margin_capital_flow(),
    get_margin_liquidation_records(),
    cancel_margin_order_list(product_symbol => "product_symbol"),
    get_margin_order_rate_limits(),
    get_margin_all_order_lists(),
    get_margin_order_list(),
    get_margin_open_order_lists(),
    close_margin_listen_key(),
    keep_alive_margin_listen_key(listen_key => "listenKey"),
    create_margin_listen_key(),
    get_account_trading_status(),
    get_account_status(),
    get_api_key_permissions(),
    get_spot_trade_fees(),
    get_user_assets(),
    get_coin_network_config(),
    get_deposit_address(coin => "coin"),
    get_deposit_history(),
    ]; }

    crate::exchanges::impl_exchange_method_wrappers! { @extend; BinanceClient; public [
    coin_futures_old_trades_lookup(symbol => "symbol"),
    query_coin_futures_index_price_constituents(symbol => "symbol"),
    coin_futures_taker_buy_sell_volume(pair => "pair",contract_type => "contractType",period => "period"),
    coin_futures_test_connectivity(),
    pm_test_connectivity(),
    futures_list_all_convert_pairs(),
    futures_adl_risk(),
    futures_asset_index(),
    futures_composite_index_symbol_information(),
    futures_old_trades_lookup(symbol => "symbol"),
    futures_quarterly_contract_settlement_price(pair => "pair"),
    query_futures_index_price_constituents(symbol => "symbol"),
    query_futures_insurance_fund_balance_snapshot(),
    futures_rpi_order_book(symbol => "symbol"),
    futures_test_connectivity(),
    futures_trading_schedule(),
    margin_cross_margin_collateral_ratio(),
    get_margin_limit_price_pairs(),
    get_margin_list_schedule(),
    get_margin_margin_asset_risk_based_liquidation_ratio(),
    get_margin_margin_restricted_assets(),
    query_margin_liability_coin_leverage_bracket_in_cross_margin_pro_mode(),
    spot_execution_rules(),
    spot_ping(),
    spot_historical_block_trades(symbol => "symbol",from_id => "fromId"),
    spot_historical_trades(symbol => "symbol"),
    spot_reference_price(symbol => "symbol"),
    spot_reference_price_calculation(symbol => "symbol"),
    spot_ticker(),
    spot_ticker_trading_day(),
    spot_ui_klines(symbol => "symbol",interval => "interval"),
    get_wallet_open_symbol_list(),
    get_wallet_spot_asset_tags(),
    ]; private [
    get_coin_futures_download_id_for_futures_order_history(start_time => "startTime",end_time => "endTime"),
    get_coin_futures_download_id_for_futures_trade_history(start_time => "startTime",end_time => "endTime"),
    get_coin_futures_download_id_for_futures_transaction_history(start_time => "startTime",end_time => "endTime"),
    get_coin_futures_futures_order_history_download_link_by_id(download_id => "downloadId"),
    get_coin_futures_futures_trade_download_link_by_id(download_id => "downloadId"),
    get_coin_futures_futures_transaction_history_download_link_by_id(download_id => "downloadId"),
    get_coin_futures_order_modify_history(symbol => "symbol"),
    get_coin_futures_position_margin_change_history(symbol => "symbol"),
    query_coin_futures_current_open_order(symbol => "symbol"),
    pm_bnb_transfer(amount => "amount",transfer_side => "transferSide"),
    change_pm_auto_repay_futures_status(auto_repay => "autoRepay"),
    pm_fund_auto_collection(),
    pm_fund_collection_by_asset(asset => "asset"),
    get_pm_auto_repay_futures_status(),
    get_pm_download_id_for_um_futures_order_history(start_time => "startTime",end_time => "endTime"),
    get_pm_download_id_for_um_futures_trade_history(start_time => "startTime",end_time => "endTime"),
    get_pm_download_id_for_um_futures_transaction_history(start_time => "startTime",end_time => "endTime"),
    get_pm_um_account_detail_v2(),
    get_pm_um_futures_order_download_link_by_id(download_id => "downloadId"),
    get_pm_um_futures_trade_download_link_by_id(download_id => "downloadId"),
    get_pm_um_futures_transaction_download_link_by_id(download_id => "downloadId"),
    query_pm_portfolio_margin_negative_balance_interest_history(),
    query_pm_user_negative_balance_auto_exchange_record(start_time => "startTime",end_time => "endTime"),
    repay_pm_futures_negative_balance(),
    pm_futures_tradfi_perps_contract(),
    get_pm_um_futures_bnb_burn_status(),
    query_pm_current_cm_open_order(symbol => "symbol"),
    query_pm_current_um_open_order(symbol => "symbol"),
    toggle_pm_bnb_burn_on_um_futures_trade(fee_burn => "feeBurn"),
    get_futures_bnb_burn_status(),
    get_futures_download_id_for_futures_order_history(start_time => "startTime",end_time => "endTime"),
    get_futures_download_id_for_futures_trade_history(start_time => "startTime",end_time => "endTime"),
    get_futures_download_id_for_futures_transaction_history(start_time => "startTime",end_time => "endTime"),
    get_futures_futures_order_history_download_link_by_id(download_id => "downloadId"),
    get_futures_futures_trade_download_link_by_id(download_id => "downloadId"),
    get_futures_futures_transaction_history_download_link_by_id(download_id => "downloadId"),
    toggle_futures_bnb_burn_on_futures_trade(fee_burn => "feeBurn"),
    futures_accept_the_offered_quote(quote_id => "quoteId"),
    futures_order_status(),
    futures_send_quote_request(from_asset => "fromAsset",to_asset => "toAsset"),
    futures_classic_portfolio_margin_account_information(asset => "asset"),
    get_futures_order_modify_history(symbol => "symbol"),
    get_futures_position_margin_change_history(symbol => "symbol"),
    adjust_margin_cross_margin_max_leverage(max_leverage => "maxLeverage"),
    get_margin_bnb_burn_status(),
    query_margin_cross_margin_fee_data(),
    query_margin_enabled_isolated_margin_account_limit(),
    query_margin_isolated_margin_fee_data(),
    get_margin_future_hourly_interest_rate(assets => "assets",is_isolated => "isIsolated"),
    query_margin_margin_interest_rate_history(asset => "asset"),
    query_margin_isolated_margin_tier_data(symbol => "symbol"),
    query_margin_margin_available_inventory(kind_type => "type"),
    create_margin_special_key(api_name => "apiName"),
    delete_margin_special_key(),
    edit_margin_ip_for_special_key(ip => "ip"),
    margin_exit_special_key_mode(),
    get_margin_small_liability_exchange_coin_list(),
    get_margin_small_liability_exchange_history(current => "current",size => "size"),
    margin_liquidation_loan_repay(asset => "asset",amount => "amount"),
    query_margin_liquidation_loan(),
    query_margin_liquidation_loan_repay_history(),
    query_margin_prevented_matches(symbol => "symbol"),
    query_margin_special_key(),
    query_margin_special_key_list(),
    margin_small_liability_exchange(asset_names => "assetNames"),
    get_margin_cross_margin_transfer_history(),
    spot_my_filters(symbol => "symbol"),
    spot_order_amendments(symbol => "symbol",order_id => "orderId"),
    wallet_account_info(),
    wallet_daily_account_snapshot(kind_type => "type"),
    wallet_asset_detail(),
    wallet_asset_dividend_record(),
    wallet_dust_convert(asset => "asset"),
    wallet_dust_convertible_assets(target_asset => "targetAsset"),
    wallet_dust_transfer(asset => "asset"),
    wallet_dustlog(),
    get_wallet_assets_that_can_be_converted_into_bnb(),
    toggle_wallet_bnb_burn_on_spot_trade_and_margin_interest(),
    wallet_fetch_deposit_address_list_with_network(coin => "coin"),
    wallet_one_click_arrival_deposit_apply(),
    ]; }

    crate::exchanges::impl_exchange_method_wrappers! { @extend; BinanceClient; public [
    pm_pro_portfolio_margin_collateral_rate(),
    query_pm_pro_portfolio_margin_asset_index_price(),
    ]; private [
    algo_cancel_algo_order_future_algo(),
    query_algo_current_algo_open_orders_future_algo(),
    query_algo_historical_algo_orders_future_algo(),
    query_algo_sub_orders_future_algo(algo_id => "algoId"),
    algo_time_weighted_average_price_future_algo(symbol => "symbol",side => "side",quantity => "quantity",duration => "duration"),
    algo_volume_participation_future_algo(symbol => "symbol",side => "side",quantity => "quantity",urgency => "urgency"),
    algo_cancel_algo_order_spot_algo(),
    query_algo_current_algo_open_orders_spot_algo(),
    query_algo_historical_algo_orders_spot_algo(),
    query_algo_sub_orders_spot_algo(algo_id => "algoId"),
    algo_time_weighted_average_price_spot_algo(symbol => "symbol",side => "side",quantity => "quantity",duration => "duration"),
    pm_pro_bnb_transfer(amount => "amount",transfer_side => "transferSide"),
    change_pm_pro_auto_repay_futures_status(auto_repay => "autoRepay"),
    delete_pm_pro_margin_call_level(),
    pm_pro_fund_auto_collection(),
    pm_pro_fund_collection_by_asset(asset => "asset"),
    get_pm_pro_auto_repay_futures_status(),
    get_pm_pro_delta_mode_status(),
    get_pm_pro_margin_call_level(),
    get_pm_pro_portfolio_margin_pro_account_balance(),
    get_pm_pro_portfolio_margin_pro_account_info(),
    get_pm_pro_portfolio_margin_pro_span_account_info(),
    pm_pro_portfolio_margin_pro_bankruptcy_loan_repay(),
    query_pm_pro_portfolio_margin_pro_bankruptcy_loan_amount(),
    query_pm_pro_portfolio_margin_pro_bankruptcy_loan_repay_history(),
    query_pm_pro_portfolio_margin_pro_negative_balance_interest_history(),
    repay_pm_pro_futures_negative_balance(),
    set_pm_pro_margin_call_level(margin_call_level => "marginCallLevel"),
    pm_pro_switch_delta_mode(delta_enabled => "deltaEnabled"),
    get_pm_pro_portfolio_margin_asset_leverage(),
    pm_pro_portfolio_margin_pro_tiered_collateral_rate(),
    ]; }

    crate::exchanges::impl_exchange_method_wrappers! { @extend; BinanceClient; public [
    ]; private [
    get_dual_investment_product_list(option_type => "optionType",exercised_coin => "exercisedCoin",invest_coin => "investCoin"),
    tradfi_options_contract(),
    get_cloud_mining_payment_and_refund_history(start_time => "startTime",end_time => "endTime"),
    query_user_delegation_history(email => "email",start_time => "startTime",end_time => "endTime"),
    fetch_withdraw_address_list(),
    fetch_withdraw_quota(),
    get_withdrawal_history(),
    check_questionnaire_requirements(),
    get_travel_rule_deposit_history(),
    get_travel_rule_deposit_history_v2(),
    fetch_address_verification_list(),
    get_country_list(),
    get_region_list(country_code => "countryCode"),
    submit_deposit_questionnaire_travel_rule(tran_id => "tranId",questionnaire => "questionnaire"),
    submit_deposit_questionnaire_v2(deposit_id => "depositId",questionnaire => "questionnaire"),
    vasp_list(),
    get_travel_rule_withdrawal_history(),
    get_travel_rule_withdrawal_history_v2(),
    get_futures_lead_trader_status(),
    get_futures_lead_trading_symbol_whitelist(),
    change_auto_compound_status(position_id => "positionId",auto_compound_plan => "autoCompoundPlan"),
    check_dual_investment_accounts(),
    get_dual_investment_positions(),
    subscribe_dual_investment_products(id => "id",order_id => "orderId",deposit_amount => "depositAmount",auto_compound_plan => "autoCompoundPlan"),
    get_bfusd_account(),
    get_bfusd_quota_details(),
    get_bfusd_rate_history(),
    get_bfusd_redemption_history(),
    get_bfusd_rewards_history(),
    get_bfusd_subscription_history(),
    redeem_bfusd(amount => "amount",type_ => "type"),
    subscribe_bfusd(asset => "asset",amount => "amount"),
    get_collateral_record(),
    get_flexible_personal_left_quota(product_id => "productId"),
    get_flexible_subscription_preview(product_id => "productId",amount => "amount"),
    get_locked_personal_left_quota(project_id => "projectId"),
    get_locked_subscription_preview(project_id => "projectId",amount => "amount"),
    get_flexible_rate_history(product_id => "productId"),
    set_flexible_auto_subscribe(product_id => "productId",auto_subscribe => "autoSubscribe"),
    set_locked_auto_subscribe(position_id => "positionId",auto_subscribe => "autoSubscribe"),
    set_locked_product_redeem_option(position_id => "positionId",redeem_to => "redeemTo"),
    get_rwusd_account(),
    get_rwusd_quota_details(),
    get_rwusd_rate_history(),
    get_rwusd_redemption_history(),
    get_rwusd_rewards_history(),
    get_rwusd_subscription_history(),
    redeem_rwusd(amount => "amount",type_ => "type"),
    subscribe_rwusd(asset => "asset",amount => "amount"),
    get_yield_arena_activities(),
    create_a_virtual_sub_account(sub_account_string => "subAccountString"),
    enable_futures_for_sub_account(email => "email"),
    enable_options_for_sub_account(email => "email"),
    add_ip_restriction_for_sub_account_api_key(email => "email",sub_account_api_key => "subAccountApiKey",status => "status"),
    create_sub_account_api_key(email => "email",api_name => "apiName",status => "status"),
    delete_ip_list_for_a_sub_account_api_key(email => "email",sub_account_api_key => "subAccountApiKey",ip_address => "ipAddress"),
    delete_sub_account_api_key(email => "email",sub_account_api_key => "subAccountApiKey"),
    get_ip_restriction_for_a_sub_account_api_key(email => "email",sub_account_api_key => "subAccountApiKey"),
    modify_sub_account_api_key_permission(email => "email",sub_account_api_key => "subAccountApiKey"),
    query_sub_account_api_key(email => "email"),
    get_move_position_history_for_sub_account(symbol => "symbol",page => "page",rows => "rows"),
    get_sub_account_deposit_address(email => "email",coin => "coin"),
    get_sub_account_deposit_history(email => "email"),
    move_position_for_sub_account(from_user_email => "fromUserEmail",to_user_email => "toUserEmail",product_type => "productType",order_args => "orderArgs"),
    deposit_assets_into_the_managed_sub_account(to_email => "toEmail",asset => "asset",amount => "amount"),
    get_managed_sub_account_deposit_address(email => "email",coin => "coin"),
    query_managed_sub_account_asset_details(email => "email"),
    query_managed_sub_account_futures_asset_details(email => "email"),
    query_managed_sub_account_list(),
    query_managed_sub_account_margin_asset_details(email => "email"),
    query_managed_sub_account_snapshot(email => "email",type_ => "type"),
    query_managed_sub_account_transfer_log_master_account_investor(email => "email",start_time => "startTime",end_time => "endTime",page => "page",limit => "limit"),
    query_managed_sub_account_transfer_log_master_account_trading(email => "email",start_time => "startTime",end_time => "endTime",page => "page",limit => "limit"),
    query_managed_sub_account_transfer_log_sub_account_trading(start_time => "startTime",end_time => "endTime",page => "page",limit => "limit"),
    ]; }

    crate::exchanges::impl_exchange_method_wrappers! { @extend; BinanceClient; public [

    ]; private [
    get_transferable_earn_asset_balance_for_portfolio_margin(asset => "asset",transfer_type => "transferType"),
    transfer_ldusdt_rwusd_for_portfolio_margin(asset => "asset",transfer_type => "transferType",amount => "amount"),
    ]; }

    crate::exchanges::impl_exchange_method_wrappers! {@extend;BinanceClient;public [];private [enable_isolated_margin_account(symbol => "symbol")];}

    crate::exchanges::impl_exchange_method_wrappers! {@extend;BinanceClient;public [];private [disable_isolated_margin_account(symbol => "symbol")];}

    crate::exchanges::impl_exchange_method_wrappers! {
        @extend;
        BinanceClient;
        public [];
        private [
            get_options_cancel_countdown(),
            set_options_cancel_countdown(underlying => "underlying", countdown_time => "countdownTime"),
            send_options_cancel_heartbeat(underlyings => "underlyings"),
            get_options_mmp_config(underlying => "underlying"),
            reset_options_mmp(underlying => "underlying"),
            set_options_mmp_config(underlying => "underlying", window_time => "windowTimeInMilliseconds", frozen_time => "frozenTimeInMilliseconds", qty_limit => "qtyLimit", delta_limit => "deltaLimit"),
        ];
    }
}
