//! Endpoint metadata checked against official Bitget documentation.
use super::Endpoint;

pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#get-history-transactions
        "get_futures_trade_history" => Endpoint {
            path: "/api/v2/mix/market/fills-history",
            post: false,
            public: true,
            fields: &[
                "symbol",
                "productType",
                "limit",
                "idLessThan",
                "startTime",
                "endTime",
            ],
            required: &["symbol", "productType"],
            arrays: &[],
            limit: Some(1000),
            days: Some(7),
        },
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#get-historical-index-price-candlestick
        "get_futures_index_candle_history" => Endpoint {
            path: "/api/v2/mix/market/history-index-candles",
            post: false,
            public: true,
            fields: &[
                "symbol",
                "productType",
                "granularity",
                "startTime",
                "endTime",
                "limit",
            ],
            required: &["symbol", "productType", "granularity"],
            arrays: &[],
            limit: Some(200),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#get-historical-mark-price-candlestick
        "get_futures_mark_candle_history" => Endpoint {
            path: "/api/v2/mix/market/history-mark-candles",
            post: false,
            public: true,
            fields: &[
                "symbol",
                "productType",
                "granularity",
                "startTime",
                "endTime",
                "limit",
            ],
            required: &["symbol", "productType", "granularity"],
            arrays: &[],
            limit: Some(200),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#get-next-funding-time
        "get_futures_next_funding_time" => Endpoint {
            path: "/api/v2/mix/market/funding-time",
            post: false,
            public: true,
            fields: &["symbol", "productType"],
            required: &["symbol", "productType"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#get-contract-oi-limit
        "get_futures_open_interest_limit" => Endpoint {
            path: "/api/v2/mix/market/oi-limit",
            post: false,
            public: true,
            fields: &["productType", "symbol"],
            required: &["productType"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-position/classic-contract-position#get-position-tier
        "get_futures_position_tiers" => Endpoint {
            path: "/api/v2/mix/market/query-position-lever",
            post: false,
            public: true,
            fields: &["productType", "symbol"],
            required: &["productType", "symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#get-discount-rate
        "get_futures_discount_rates" => Endpoint {
            path: "/api/v2/mix/market/discount-rate",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#get-interest-exchange-rate
        "get_futures_interest_exchange_rates" => Endpoint {
            path: "/api/v2/mix/market/exchange-rate",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#get-interest-rate-history
        "get_futures_interest_rate_history" => Endpoint {
            path: "/api/v2/mix/market/union-interest-rate-history",
            post: false,
            public: true,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#vip-fee-rate
        "get_futures_vip_fee_rates" => Endpoint {
            path: "/api/v2/mix/market/vip-fee-rate",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-subaccount-assets
        "get_futures_sub_account_assets" => Endpoint {
            path: "/api/v2/mix/account/sub-account-assets",
            post: false,
            public: false,
            fields: &["productType"],
            required: &["productType"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#my-estimated-open-count
        "get_futures_estimated_open_count" => Endpoint {
            path: "/api/v2/mix/account/open-count",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "productType",
                "marginCoin",
                "openAmount",
                "openPrice",
                "leverage",
            ],
            required: &[
                "symbol",
                "productType",
                "marginCoin",
                "openAmount",
                "openPrice",
            ],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-liquidation-price
        "get_futures_liquidation_price" => Endpoint {
            path: "/api/v2/mix/account/liq-price",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "productType",
                "marginCoin",
                "posSide",
                "orderType",
                "openAmount",
                "openPrice",
            ],
            required: &[
                "symbol",
                "productType",
                "marginCoin",
                "posSide",
                "orderType",
                "openAmount",
            ],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-max-openable-quantity
        "get_futures_max_open_quantity" => Endpoint {
            path: "/api/v2/mix/account/max-open",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "productType",
                "marginCoin",
                "posSide",
                "orderType",
                "openPrice",
            ],
            required: &[
                "symbol",
                "productType",
                "marginCoin",
                "posSide",
                "orderType",
            ],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-usdt-m-futures-interest-history
        "get_futures_interest_history" => Endpoint {
            path: "/api/v2/mix/account/interest-history",
            post: false,
            public: false,
            fields: &[
                "productType",
                "startTime",
                "endTime",
                "coin",
                "idLessThan",
                "limit",
            ],
            required: &["productType", "startTime", "endTime"],
            arrays: &[],
            limit: Some(100),
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#change-the-product-line-leverage
        "set_futures_all_leverage" => Endpoint {
            path: "/api/v2/mix/account/set-all-leverage",
            post: true,
            public: false,
            fields: &["productType", "leverage"],
            required: &["productType", "leverage"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#set-isolated-position-auto-margin
        "set_futures_auto_margin" => Endpoint {
            path: "/api/v2/mix/account/set-auto-margin",
            post: true,
            public: false,
            fields: &["symbol", "autoMargin", "marginCoin", "holdSide"],
            required: &["symbol", "autoMargin", "marginCoin", "holdSide"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#set-usdt-m-futures-asset-mode
        "set_futures_asset_mode" => Endpoint {
            path: "/api/v2/mix/account/set-asset-mode",
            post: true,
            public: false,
            fields: &["productType", "assetMode"],
            required: &["productType", "assetMode"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#union-convert
        "convert_futures_union_asset" => Endpoint {
            path: "/api/v2/mix/account/union-convert",
            post: true,
            public: false,
            fields: &["coin", "amount"],
            required: &["coin", "amount"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-union-transfer-limits
        "get_futures_union_transfer_limits" => Endpoint {
            path: "/api/v2/mix/account/transfer-limits",
            post: false,
            public: false,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-union-config
        "get_futures_union_config" => Endpoint {
            path: "/api/v2/mix/account/union-config",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-isolated-symbols
        "get_futures_isolated_symbols" => Endpoint {
            path: "/api/v2/mix/account/isolated-symbols",
            post: false,
            public: false,
            fields: &["productType"],
            required: &["productType"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-position/classic-contract-position#get-historical-position
        "get_futures_position_history" => Endpoint {
            path: "/api/v2/mix/position/history-position",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "productType",
                "idLessThan",
                "startTime",
                "endTime",
                "limit",
            ],
            required: &[],
            arrays: &[],
            limit: Some(100),
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-position/classic-contract-position#get-position-adl-rank
        "get_futures_adl_rank" => Endpoint {
            path: "/api/v2/mix/position/adlRank",
            post: false,
            public: false,
            fields: &["productType"],
            required: &["productType"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-trade/classic-contract-trade#reversal
        "reverse_futures_position" => Endpoint {
            path: "/api/v2/mix/order/click-backhand",
            post: true,
            public: false,
            fields: &[
                "symbol",
                "marginCoin",
                "productType",
                "side",
                "size",
                "tradeSide",
                "clientOid",
            ],
            required: &["symbol", "marginCoin", "productType", "side"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-trade/classic-contract-trade#get-historical-transaction-details
        "get_futures_fill_history" => Endpoint {
            path: "/api/v2/mix/order/fill-history",
            post: false,
            public: false,
            fields: &[
                "productType",
                "orderId",
                "symbol",
                "startTime",
                "endTime",
                "idLessThan",
                "limit",
            ],
            required: &["productType"],
            arrays: &[],
            limit: Some(100),
            days: Some(7),
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#get-mainsub-transfer-record
        "get_spot_sub_account_transfer_records" => Endpoint {
            path: "/api/v2/spot/account/sub-main-trans-record",
            post: false,
            public: false,
            fields: &[
                "coin",
                "role",
                "subUid",
                "startTime",
                "endTime",
                "clientOid",
                "limit",
                "idLessThan",
            ],
            required: &[],
            arrays: &[],
            limit: Some(100),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#get-sub-accounts-assets
        "get_spot_sub_account_assets" => Endpoint {
            path: "/api/v2/spot/account/subaccount-assets",
            post: false,
            public: false,
            fields: &["idLessThan", "limit"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#sub-transfer
        "transfer_spot_sub_account" => Endpoint {
            path: "/api/v2/spot/wallet/subaccount-transfer",
            post: true,
            public: false,
            fields: &[
                "fromType",
                "toType",
                "amount",
                "coin",
                "fromUserId",
                "toUserId",
                "symbol",
                "clientOid",
            ],
            required: &[
                "fromType",
                "toType",
                "amount",
                "coin",
                "fromUserId",
                "toUserId",
            ],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#get-cross-account-assets
        "get_cross_margin_assets" => Endpoint {
            path: "/api/v2/margin/crossed/account/assets",
            post: false,
            public: false,
            fields: &["coin"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#cross-borrow
        "borrow_cross_margin_asset" => Endpoint {
            path: "/api/v2/margin/crossed/account/borrow",
            post: true,
            public: false,
            fields: &["coin", "borrowAmount", "clientOid"],
            required: &["coin", "borrowAmount"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#cross-repay
        "repay_cross_margin_asset" => Endpoint {
            path: "/api/v2/margin/crossed/account/repay",
            post: true,
            public: false,
            fields: &["coin", "repayAmount"],
            required: &["coin", "repayAmount"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#get-cross-risk-rate
        "get_cross_margin_risk_rate" => Endpoint {
            path: "/api/v2/margin/crossed/account/risk-rate",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#get-cross-max-borrowable
        "get_cross_margin_max_borrowable" => Endpoint {
            path: "/api/v2/margin/crossed/account/max-borrowable-amount",
            post: false,
            public: false,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#get-cross-max-transferable
        "get_cross_margin_max_transferable" => Endpoint {
            path: "/api/v2/margin/crossed/account/max-transfer-out-amount",
            post: false,
            public: false,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#cross-flash-repay
        "flash_repay_cross_margin_assets" => Endpoint {
            path: "/api/v2/margin/crossed/account/flash-repay",
            post: true,
            public: false,
            fields: &["coin"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#get-cross-flash-repay-result
        "get_cross_margin_flash_repay_result" => Endpoint {
            path: "/api/v2/margin/crossed/account/query-flash-repay-status",
            post: true,
            public: false,
            fields: &["idList"],
            required: &["idList"],
            arrays: &["idList"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#get-cross-interest-rate-and-max-borrowable
        "get_cross_margin_interest_rate_limits" => Endpoint {
            path: "/api/v2/margin/crossed/interest-rate-and-limit",
            post: false,
            public: false,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#get-cross-tier-configuration
        "get_cross_margin_tiers" => Endpoint {
            path: "/api/v2/margin/crossed/tier-data",
            post: false,
            public: false,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-record/classic-margin-cross-record#get-cross-borrow-history
        "get_cross_margin_borrow_history" => Endpoint {
            path: "/api/v2/margin/crossed/borrow-history",
            post: false,
            public: false,
            fields: &[
                "startTime",
                "loanId",
                "coin",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-record/classic-margin-cross-record#get-cross-repay-history
        "get_cross_margin_repay_history" => Endpoint {
            path: "/api/v2/margin/crossed/repay-history",
            post: false,
            public: false,
            fields: &[
                "startTime",
                "repayId",
                "coin",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-record/classic-margin-cross-record#get-cross-interest-history
        "get_cross_margin_interest_history" => Endpoint {
            path: "/api/v2/margin/crossed/interest-history",
            post: false,
            public: false,
            fields: &["startTime", "coin", "endTime", "limit", "idLessThan"],
            required: &["startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-record/classic-margin-cross-record#get-cross-liquidation-history
        "get_cross_margin_liquidation_history" => Endpoint {
            path: "/api/v2/margin/crossed/liquidation-history",
            post: false,
            public: false,
            fields: &["startTime", "endTime", "limit", "idLessThan"],
            required: &["startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-record/classic-margin-cross-record#get-cross-financial-history
        "get_cross_margin_financial_records" => Endpoint {
            path: "/api/v2/margin/crossed/financial-records",
            post: false,
            public: false,
            fields: &[
                "startTime",
                "marginType",
                "coin",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-trade/classic-margin-cross-trade#cross-place-order
        "place_cross_margin_order" => Endpoint {
            path: "/api/v2/margin/crossed/place-order",
            post: true,
            public: false,
            fields: &[
                "symbol",
                "orderType",
                "loanType",
                "force",
                "side",
                "price",
                "baseSize",
                "quoteSize",
                "clientOid",
                "stpMode",
            ],
            required: &["symbol", "orderType", "loanType", "force", "side"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-trade/classic-margin-cross-trade#cross-cancel-order
        "cancel_cross_margin_order" => Endpoint {
            path: "/api/v2/margin/crossed/cancel-order",
            post: true,
            public: false,
            fields: &["symbol", "orderId", "clientOid"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-trade/classic-margin-cross-trade#get-cross-current-orders
        "get_cross_margin_open_orders" => Endpoint {
            path: "/api/v2/margin/crossed/open-orders",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "orderId",
                "clientOid",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-trade/classic-margin-cross-trade#get-cross-history-orders
        "get_cross_margin_order_history" => Endpoint {
            path: "/api/v2/margin/crossed/history-orders",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "orderId",
                "enterPointSource",
                "clientOid",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-trade/classic-margin-cross-trade#get-cross-order-fills
        "get_cross_margin_fills" => Endpoint {
            path: "/api/v2/margin/crossed/fills",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "orderId",
                "idLessThan",
                "endTime",
                "limit",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#get-isolated-account-asset
        "get_isolated_margin_assets" => Endpoint {
            path: "/api/v2/margin/isolated/account/assets",
            post: false,
            public: false,
            fields: &["symbol"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#isolated-borrow
        "borrow_isolated_margin_asset" => Endpoint {
            path: "/api/v2/margin/isolated/account/borrow",
            post: true,
            public: false,
            fields: &["symbol", "coin", "borrowAmount", "clientOid"],
            required: &["symbol", "coin", "borrowAmount"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#isolated-repay
        "repay_isolated_margin_asset" => Endpoint {
            path: "/api/v2/margin/isolated/account/repay",
            post: true,
            public: false,
            fields: &["repayAmount", "coin", "symbol", "clientOid"],
            required: &["repayAmount", "coin", "symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#get-isolated-risk-rate
        "get_isolated_margin_risk_rate" => Endpoint {
            path: "/api/v2/margin/isolated/account/risk-rate",
            post: false,
            public: false,
            fields: &["symbol", "pageNum", "pageSize"],
            required: &[],
            arrays: &[],
            limit: Some(500),
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#get-isolated-max-borrowable
        "get_isolated_margin_max_borrowable" => Endpoint {
            path: "/api/v2/margin/isolated/account/max-borrowable-amount",
            post: false,
            public: false,
            fields: &["symbol"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#get-isolated-max-transferable
        "get_isolated_margin_max_transferable" => Endpoint {
            path: "/api/v2/margin/isolated/account/max-transfer-out-amount",
            post: false,
            public: false,
            fields: &["symbol"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#isolated-flash-repay
        "flash_repay_isolated_margin_assets" => Endpoint {
            path: "/api/v2/margin/isolated/account/flash-repay",
            post: true,
            public: false,
            fields: &["symbolList"],
            required: &[],
            arrays: &["symbolList"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#query-isolated-flash-repayment-result
        "get_isolated_margin_flash_repay_result" => Endpoint {
            path: "/api/v2/margin/isolated/account/query-flash-repay-status",
            post: true,
            public: false,
            fields: &["idList"],
            required: &["idList"],
            arrays: &["idList"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#get-isolated-interest-rate-and-max-borrowable
        "get_isolated_margin_interest_rate_limits" => Endpoint {
            path: "/api/v2/margin/isolated/interest-rate-and-limit",
            post: false,
            public: false,
            fields: &["symbol"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#get-isolated-tier-configuration
        "get_isolated_margin_tiers" => Endpoint {
            path: "/api/v2/margin/isolated/tier-data",
            post: false,
            public: false,
            fields: &["symbol"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-record/classic-margin-isolated-record#get-isolated-borrow-history
        "get_isolated_margin_borrow_history" => Endpoint {
            path: "/api/v2/margin/isolated/borrow-history",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "loanId",
                "coin",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-record/classic-margin-isolated-record#get-isolated-repayment-history
        "get_isolated_margin_repay_history" => Endpoint {
            path: "/api/v2/margin/isolated/repay-history",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "repayId",
                "coin",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-record/classic-margin-isolated-record#get-isolated-interest-history
        "get_isolated_margin_interest_history" => Endpoint {
            path: "/api/v2/margin/isolated/interest-history",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "coin",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-record/classic-margin-isolated-record#get-isolated-liquidation-history
        "get_isolated_margin_liquidation_history" => Endpoint {
            path: "/api/v2/margin/isolated/liquidation-history",
            post: false,
            public: false,
            fields: &["symbol", "startTime", "endTime", "limit", "idLessThan"],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-record/classic-margin-isolated-record#get-isolated-financial-history
        "get_isolated_margin_financial_records" => Endpoint {
            path: "/api/v2/margin/isolated/financial-records",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "marginType",
                "coin",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-trade/classic-margin-isolated-trade#isolated-place-order
        "place_isolated_margin_order" => Endpoint {
            path: "/api/v2/margin/isolated/place-order",
            post: true,
            public: false,
            fields: &[
                "symbol",
                "orderType",
                "loanType",
                "force",
                "side",
                "price",
                "baseSize",
                "quoteSize",
                "clientOid",
                "stpMode",
            ],
            required: &["symbol", "orderType", "loanType", "force", "side"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-trade/classic-margin-isolated-trade#isolated-cancel-order
        "cancel_isolated_margin_order" => Endpoint {
            path: "/api/v2/margin/isolated/cancel-order",
            post: true,
            public: false,
            fields: &["symbol", "orderId", "clientOid"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-trade/classic-margin-isolated-trade#get-isolated-current-orders
        "get_isolated_margin_open_orders" => Endpoint {
            path: "/api/v2/margin/isolated/open-orders",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "orderId",
                "clientOid",
                "endTime",
                "limit",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-trade/classic-margin-isolated-trade#get-isolated-orders-history
        "get_isolated_margin_order_history" => Endpoint {
            path: "/api/v2/margin/isolated/history-orders",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "orderId",
                "enterPointSource",
                "clientOid",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-trade/classic-margin-isolated-trade#get-isolated-order-fills
        "get_isolated_margin_fills" => Endpoint {
            path: "/api/v2/margin/isolated/fills",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "orderId",
                "idLessThan",
                "endTime",
                "limit",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/market/derivatives#get-funding-rate-history
        "get_uta_funding_rate_history" => Endpoint {
            path: "/api/v3/market/history-fund-rate",
            post: false,
            public: true,
            fields: &["category", "symbol", "cursor", "limit"],
            required: &["category", "symbol"],
            arrays: &[],
            limit: Some(100),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/market/derivatives#get-index-price-components
        "get_uta_index_components" => Endpoint {
            path: "/api/v3/market/index-components",
            post: false,
            public: true,
            fields: &["symbol"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Margin-Loans
        "get_uta_margin_loan_rates" => Endpoint {
            path: "/api/v3/market/margin-loans",
            post: false,
            public: true,
            fields: &["coin", "level"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Position-Tier-Data
        "get_uta_position_tiers" => Endpoint {
            path: "/api/v3/market/position-tier",
            post: false,
            public: true,
            fields: &["category", "symbol", "coin"],
            required: &["category"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Contracts-Oi
        "get_uta_open_interest_limit" => Endpoint {
            path: "/api/v3/market/oi-limit",
            post: false,
            public: true,
            fields: &["symbol", "category"],
            required: &["category"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Discount-Rate
        "get_uta_discount_rates" => Endpoint {
            path: "/api/v3/market/discount-rate",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/market-data#get-rpi-order-book
        "get_uta_rpi_orderbook" => Endpoint {
            path: "/api/v3/market/rpi-orderbook",
            post: false,
            public: true,
            fields: &["category", "symbol", "limit"],
            required: &["category", "symbol"],
            arrays: &[],
            limit: Some(1000),
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/market-data#get-rpi-symbols
        "get_uta_rpi_symbols" => Endpoint {
            path: "/api/v3/market/rpi-symbols",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/assets-balance#get-account-funding-assets
        "get_uta_funding_assets" => Endpoint {
            path: "/api/v3/account/funding-assets",
            post: false,
            public: false,
            fields: &["coin"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/assets-balance#get-funding-financial-records
        "get_uta_funding_records" => Endpoint {
            path: "/api/v3/account/funding-financial-records",
            post: false,
            public: false,
            fields: &["coin", "type", "startTime", "endTime", "limit", "cursor"],
            required: &[],
            arrays: &[],
            limit: Some(100),
            days: Some(30),
        },
        // https://www.bitget.com/docs/catalog/account/assets-balance#get-account-fee-rate
        "get_uta_fee_rate" => Endpoint {
            path: "/api/v3/account/fee-rate",
            post: false,
            public: false,
            fields: &["symbol", "category"],
            required: &["symbol", "category"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/assets-balance#get-max-transferable
        "get_uta_max_transferable" => Endpoint {
            path: "/api/v3/account/max-transferable",
            post: false,
            public: false,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/assets-balance#set-collateral-type
        "set_uta_collateral_type" => Endpoint {
            path: "/api/v3/account/set-collateral-type",
            post: true,
            public: false,
            fields: &["collateralType", "collateralCoins", "allowCashplus"],
            required: &["collateralType"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/account-settings#get-account-setting
        "get_uta_settings" => Endpoint {
            path: "/api/v3/account/settings",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/account-settings#get-delta-info
        "get_uta_delta_info" => Endpoint {
            path: "/api/v3/account/delta-info",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-Repayable-Coins
        "get_uta_repayable_coins" => Endpoint {
            path: "/api/v3/account/repayable-coins",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-Payment-Coins
        "get_uta_payment_coins" => Endpoint {
            path: "/api/v3/account/payment-coins",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Borrow
        "borrow_uta_asset" => Endpoint {
            path: "/api/v3/account/borrow",
            post: true,
            public: false,
            fields: &["coin", "amount", "clientOid"],
            required: &["coin", "amount"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-Max-Borrowable
        "get_uta_max_borrowable" => Endpoint {
            path: "/api/v3/account/max-borrowable",
            post: false,
            public: false,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-OI-Limit
        "get_uta_account_open_interest_limit" => Endpoint {
            path: "/api/v3/account/open-interest-limit",
            post: false,
            public: false,
            fields: &["symbol", "category"],
            required: &["symbol", "category"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/transfer/Get-Transfer-Coins
        "get_uta_transferable_coins" => Endpoint {
            path: "/api/v3/account/transferable-coins",
            post: false,
            public: false,
            fields: &["fromType", "toType"],
            required: &["fromType", "toType"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/position-management#get-max-open-available
        "get_uta_max_open_available" => Endpoint {
            path: "/api/v3/account/max-open-available",
            post: true,
            public: false,
            fields: &[
                "category",
                "symbol",
                "orderType",
                "side",
                "price",
                "size",
                "autoBorrow",
            ],
            required: &["category", "symbol", "orderType", "side"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/position-management#get-move-position-history
        "get_uta_position_transfer_history" => Endpoint {
            path: "/api/v3/account/move-position-history",
            post: false,
            public: false,
            fields: &[
                "category",
                "symbol",
                "startTime",
                "endTime",
                "cursor",
                "limit",
            ],
            required: &["category"],
            arrays: &[],
            limit: Some(100),
            days: Some(90),
        },
        // https://www.bitget.com/legacy-docs/uta/account/Set-Repay-Mode
        "set_uta_repay_mode" => Endpoint {
            path: "/api/v3/account/set-repay-mode",
            post: true,
            public: false,
            fields: &["repayMode"],
            required: &["repayMode"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-Eligible-Discount-Rate
        "get_uta_eligible_discount_rates" => Endpoint {
            path: "/api/v3/account/eligible-discount-rate",
            post: false,
            public: false,
            fields: &["coin"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-Eligible-Loan-Info
        "get_uta_eligible_loan_info" => Endpoint {
            path: "/api/v3/account/eligible-loan-info",
            post: false,
            public: false,
            fields: &["coin"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-Eligible-Margin-Tier
        "get_uta_eligible_margin_tiers" => Endpoint {
            path: "/api/v3/account/eligible-margin-tier",
            post: false,
            public: false,
            fields: &["coin"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-Eligible-Symbols
        "get_uta_eligible_symbols" => Endpoint {
            path: "/api/v3/account/eligible-symbols",
            post: false,
            public: false,
            fields: &["symbol"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-Convert-Records
        "get_uta_convert_records" => Endpoint {
            path: "/api/v3/account/convert-records",
            post: false,
            public: false,
            fields: &[
                "fromCoin",
                "toCoin",
                "startTime",
                "endTime",
                "limit",
                "cursor",
            ],
            required: &[],
            arrays: &[],
            limit: Some(100),
            days: Some(30),
        },
        // https://www.bitget.com/docs/catalog/account/account-settings#adjust-account-mode
        "set_uta_account_mode" => Endpoint {
            path: "/api/v3/account/adjust-account-mode",
            post: true,
            public: false,
            fields: &["mode", "deltaSwitch", "targetUid"],
            required: &["mode"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/position-management#get-position-adl-rank
        "get_uta_adl_rank" => Endpoint {
            path: "/api/v3/position/adlRank",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/transfer/
        "transfer_uta_account" => Endpoint {
            path: "/api/v3/account/transfer",
            post: true,
            public: false,
            fields: &[
                "fromType",
                "toType",
                "amount",
                "coin",
                "symbol",
                "allowBorrow",
                "clientOid",
            ],
            required: &["fromType", "toType", "amount", "coin"],
            arrays: &[],
            limit: Some(100),
            days: Some(90),
        },
        // https://www.bitget.com/legacy-docs/uta/account/transfer/Sub-Master-Transfer
        "transfer_uta_sub_to_master" => Endpoint {
            path: "/api/v3/account/sub-master-transfer",
            post: true,
            public: false,
            fields: &["fromType", "toType", "amount", "coin", "clientOid"],
            required: &["fromType", "toType", "amount", "coin"],
            arrays: &[],
            limit: Some(100),
            days: Some(90),
        },
        // https://www.bitget.com/legacy-docs/uta/account/transfer/SubAccount-Transfer
        "transfer_uta_sub_account" => Endpoint {
            path: "/api/v3/account/sub-transfer",
            post: true,
            public: false,
            fields: &[
                "fromType",
                "toType",
                "amount",
                "coin",
                "fromUserId",
                "toUserId",
                "clientOid",
                "allowBorrow",
            ],
            required: &[
                "fromType",
                "toType",
                "amount",
                "coin",
                "fromUserId",
                "toUserId",
                "clientOid",
            ],
            arrays: &[],
            limit: Some(100),
            days: Some(90),
        },
        // https://www.bitget.com/legacy-docs/uta/account/transfer/SubAccount-Transfer-Get
        "get_uta_sub_account_transfer_records" => Endpoint {
            path: "/api/v3/account/sub-transfer-record",
            post: false,
            public: false,
            fields: &[
                "subUid",
                "role",
                "coin",
                "startTime",
                "endTime",
                "clientOid",
                "limit",
                "cursor",
            ],
            required: &[],
            arrays: &[],
            limit: Some(100),
            days: Some(90),
        },
        // https://www.bitget.com/legacy-docs/uta/account/sub-account/SubAccount-Get
        "get_uta_sub_accounts" => Endpoint {
            path: "/api/v3/user/sub-list",
            post: false,
            public: false,
            fields: &["limit", "cursor"],
            required: &[],
            arrays: &[],
            limit: Some(100),
            days: Some(90),
        },
        // https://www.bitget.com/legacy-docs/uta/account/sub-account/Get-SubAccount-Unified-Assets
        "get_uta_sub_account_assets" => Endpoint {
            path: "/api/v3/account/sub-unified-assets",
            post: false,
            public: false,
            fields: &["subUid", "cursor", "limit"],
            required: &[],
            arrays: &[],
            limit: Some(50),
            days: Some(90),
        },
        // https://www.bitget.com/legacy-docs/uta/strategy/Get-Strategy-Sub-Orders
        "get_uta_strategy_sub_orders" => Endpoint {
            path: "/api/v3/trade/strategy-sub-orders",
            post: false,
            public: false,
            fields: &["orderId", "limit", "cursor"],
            required: &["orderId"],
            arrays: &[],
            limit: Some(100),
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/deposit/Get-Deposit-Records
        "get_uta_deposit_records" => Endpoint {
            path: "/api/v3/account/deposit-records",
            post: false,
            public: false,
            fields: &["coin", "orderId", "startTime", "endTime", "limit", "cursor"],
            required: &["startTime", "endTime"],
            arrays: &[],
            limit: Some(100),
            days: None,
        },
        // https://www.bitget.com/legacy-docs/classic/common/public/Get-Server-Time
        "get_server_time" => Endpoint {
            path: "/api/v2/public/time",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: Some(100),
            days: None,
        },
        // https://www.bitget.com/legacy-docs/classic/common/public/Get-All-Trade-Rate
        "get_all_trade_rates" => Endpoint {
            path: "/api/v2/common/all-trade-rate",
            post: false,
            public: false,
            fields: &["businessType"],
            required: &["businessType"],
            arrays: &[],
            limit: Some(100),
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/account-settings#switch-deduct
        "set_uta_fee_deduction" => Endpoint {
            path: "/api/v3/account/switch-deduct",
            post: true,
            public: false,
            fields: &["deduct"],
            required: &["deduct"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/account-settings#get-deduct-info
        "get_uta_fee_deduction" => Endpoint {
            path: "/api/v3/account/deduct-info",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/account-settings#switch-account
        "upgrade_to_uta" => Endpoint {
            path: "/api/v3/account/switch",
            post: true,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/account-settings#get-switch-status
        "get_uta_upgrade_status" => Endpoint {
            path: "/api/v3/account/switch-status",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-switch-union-usdt
        "get_futures_margin_mode_switch_quota" => Endpoint {
            path: "/api/v2/mix/account/switch-union-usdt",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-trade/classic-margin-cross-trade#get-cross-liquidation-orders
        "get_cross_margin_liquidation_orders" => Endpoint {
            path: "/api/v2/margin/crossed/liquidation-order",
            post: false,
            public: false,
            fields: &[
                "type",
                "symbol",
                "fromCoin",
                "toCoin",
                "startTime",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &[],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-trade/classic-margin-isolated-trade#get-isolated-liquidation-orders
        "get_isolated_margin_liquidation_orders" => Endpoint {
            path: "/api/v2/margin/isolated/liquidation-order",
            post: false,
            public: false,
            fields: &[
                "type",
                "symbol",
                "fromCoin",
                "toCoin",
                "startTime",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &[],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#get-upgrade-status
        "get_classic_account_upgrade_status" => Endpoint {
            path: "/api/v2/spot/account/upgrade-status",
            post: false,
            public: false,
            fields: &["subUid"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#upgrade-account
        "upgrade_classic_account" => Endpoint {
            path: "/api/v2/spot/account/upgrade",
            post: true,
            public: false,
            fields: &["subUid"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#get-bgb-deduct-info
        "get_spot_fee_deduction" => Endpoint {
            path: "/api/v2/spot/account/deduct-info",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#switch-bgb-deduct
        "set_spot_fee_deduction" => Endpoint {
            path: "/api/v2/spot/account/switch-deduct",
            post: true,
            public: false,
            fields: &["deduct"],
            required: &["deduct"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#modify-deposit-account
        "set_spot_deposit_account" => Endpoint {
            path: "/api/v2/spot/wallet/modify-deposit-account",
            post: true,
            public: false,
            fields: &["accountType", "coin"],
            required: &["accountType", "coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#get-deposit-address
        "get_deposit_address" => Endpoint {
            path: "/api/v2/spot/wallet/deposit-address",
            post: false,
            public: false,
            fields: &["coin", "chain", "size"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#get-subaccount-deposit-address
        "get_sub_account_deposit_address" => Endpoint {
            path: "/api/v2/spot/wallet/subaccount-deposit-address",
            post: false,
            public: false,
            fields: &["subUid", "coin", "chain", "size"],
            required: &["subUid", "coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#get-subaccount-deposit-records
        "get_sub_account_deposit_records" => Endpoint {
            path: "/api/v2/spot/wallet/subaccount-deposit-records",
            post: false,
            public: false,
            fields: &[
                "subUid",
                "coin",
                "startTime",
                "endTime",
                "idLessThan",
                "limit",
            ],
            required: &["subUid"],
            arrays: &[],
            limit: Some(100),
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Deposit-Account
        "set_uta_deposit_account" => Endpoint {
            path: "/api/v3/account/deposit-account",
            post: true,
            public: false,
            fields: &["coin", "accountType"],
            required: &["coin", "accountType"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/sub-account/SubAccount-Create
        "create_uta_sub_account" => Endpoint {
            path: "/api/v3/user/create-sub",
            post: true,
            public: false,
            fields: &["username", "accountMode", "note"],
            required: &["username"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Cash-Dividend-Records
        "get_uta_cash_dividend_records" => Endpoint {
            path: "/api/v3/market/cash-dividend-records",
            post: false,
            public: true,
            fields: &["symbol", "type", "cursor", "limit"],
            required: &["symbol", "type"],
            arrays: &[],
            limit: Some(100),
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Risk-Reserve
        "get_uta_risk_reserve" => Endpoint {
            path: "/api/v3/market/risk-reserve",
            post: false,
            public: true,
            fields: &["category", "symbol", "marginCoin"],
            required: &["category", "symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Risk-Reserve-All
        "get_uta_all_risk_reserves" => Endpoint {
            path: "/api/v3/market/risk-reserve-all",
            post: false,
            public: true,
            fields: &["category"],
            required: &["category"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Risk-Reserve-Hour
        "get_uta_hourly_risk_reserve" => Endpoint {
            path: "/api/v3/market/risk-reserve-hour",
            post: false,
            public: true,
            fields: &["category", "symbol", "marginCoin"],
            required: &["category", "symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Split-Records
        "get_uta_split_records" => Endpoint {
            path: "/api/v3/market/split-records",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/trading-data/Get-Futures-Account-Long-Short
        "get_uta_futures_long_short_ratio" => Endpoint {
            path: "/api/v3/market/futures-account-long-short",
            post: false,
            public: true,
            fields: &["symbol", "period"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/trading-data/Get-Spot-Whale-Net-Flow
        "get_uta_spot_whale_flow" => Endpoint {
            path: "/api/v3/market/spot-whale-flow",
            post: false,
            public: true,
            fields: &["symbol"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/deposit-withdrawal#get-deposit-address
        "get_uta_deposit_address" => Endpoint {
            path: "/api/v3/account/deposit-address",
            post: false,
            public: false,
            fields: &["coin", "chain", "size"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/deposit-withdrawal#get-sub-deposit-address
        "get_uta_sub_deposit_address" => Endpoint {
            path: "/api/v3/account/sub-deposit-address",
            post: false,
            public: false,
            fields: &["subUid", "coin", "chain", "size"],
            required: &["subUid", "coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/deposit-withdrawal#get-sub-deposit-records
        "get_uta_sub_deposit_records" => Endpoint {
            path: "/api/v3/account/sub-deposit-records",
            post: false,
            public: false,
            fields: &["subUid", "startTime", "endTime", "coin", "limit", "cursor"],
            required: &["subUid", "startTime", "endTime"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/rate-limit-quota#get-ratelimit-quota
        "get_uta_rate_limit_quota" => Endpoint {
            path: "/api/v3/user/rate-limit-quota",
            post: false,
            public: false,
            fields: &["category", "uid", "cursor", "limit"],
            required: &["category"],
            arrays: &[],
            limit: Some(100),
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/rate-limit-quota#set-ratelimit-quota
        "uta_set_rate_limit_quota" => Endpoint {
            path: "/api/v3/user/set-rate-limit-quota",
            post: true,
            public: false,
            fields: &["category", "uids", "quota"],
            required: &["category", "uids", "quota"],
            arrays: &["uids"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/small-assets#get-small-assets-history
        "get_uta_small_assets_history" => Endpoint {
            path: "/api/v3/convert/small-assets-history",
            post: false,
            public: false,
            fields: &["orderId", "startTime", "endTime", "limit", "cursor"],
            required: &[],
            arrays: &[],
            limit: Some(100),
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/small-assets#get-small-assets
        "get_uta_small_assets" => Endpoint {
            path: "/api/v3/convert/small-assets",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/small-assets#small-assets-trade
        "uta_small_assets_trade" => Endpoint {
            path: "/api/v3/convert/small-assets-trade",
            post: true,
            public: false,
            fields: &["fromCoinList"],
            required: &["fromCoinList"],
            arrays: &["fromCoinList"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/sub-accounts#delete-sub-account
        "uta_delete_sub" => Endpoint {
            path: "/api/v3/user/delete-sub",
            post: true,
            public: false,
            fields: &["subUid"],
            required: &["subUid"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/sub-accounts#freeze-or-unfreeze-sub-account
        "uta_freeze_sub" => Endpoint {
            path: "/api/v3/user/freeze-sub",
            post: true,
            public: false,
            fields: &["subUid", "operation"],
            required: &["subUid", "operation"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/sub-accounts#create-sub-account-api-key
        "uta_create_sub_api" => Endpoint {
            path: "/api/v3/user/create-sub-api",
            post: true,
            public: false,
            fields: &["subUid", "note", "type", "passphrase", "permissions", "ips"],
            required: &["subUid", "note", "type", "passphrase", "permissions", "ips"],
            arrays: &["permissions", "ips"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/sub-accounts#modify-sub-account-api-key
        "uta_update_sub_api" => Endpoint {
            path: "/api/v3/user/update-sub-api",
            post: true,
            public: false,
            fields: &["apiKey", "passphrase", "type", "permissions", "ips"],
            required: &["apiKey", "passphrase"],
            arrays: &["permissions", "ips"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/sub-accounts#delete-sub-account-api-key
        "uta_delete_sub_api" => Endpoint {
            path: "/api/v3/user/delete-sub-api",
            post: true,
            public: false,
            fields: &["apiKey"],
            required: &["apiKey"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/sub-accounts#get-sub-account-api-keys
        "get_uta_sub_api_list" => Endpoint {
            path: "/api/v3/user/sub-api-list",
            post: false,
            public: false,
            fields: &["subUid", "limit", "cursor"],
            required: &["subUid"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-common-vsubaccount/classic-common-vsubaccount#create-virtual-subaccount
        "classic_create_virtual_subaccount" => Endpoint {
            path: "/api/v2/user/create-virtual-subaccount",
            post: true,
            public: false,
            fields: &["subAccountList"],
            required: &["subAccountList"],
            arrays: &["subAccountList"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-common-vsubaccount/classic-common-vsubaccount#create-virtual-subaccount-apikey
        "classic_create_virtual_subaccount_apikey" => Endpoint {
            path: "/api/v2/user/create-virtual-subaccount-apikey",
            post: true,
            public: false,
            fields: &["subAccountUid", "passphrase", "label", "permList", "ipList"],
            required: &["subAccountUid", "passphrase", "label", "permList"],
            arrays: &["permList", "ipList"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-common-vsubaccount/classic-common-vsubaccount#modify-virtual-subaccount
        "classic_modify_virtual_subaccount" => Endpoint {
            path: "/api/v2/user/modify-virtual-subaccount",
            post: true,
            public: false,
            fields: &["subAccountUid", "permList", "status"],
            required: &["subAccountUid", "permList", "status"],
            arrays: &["permList"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-common-vsubaccount/classic-common-vsubaccount#modify-virtual-subaccount-apikey
        "classic_modify_virtual_subaccount_apikey" => Endpoint {
            path: "/api/v2/user/modify-virtual-subaccount-apikey",
            post: true,
            public: false,
            fields: &[
                "subAccountUid",
                "passphrase",
                "label",
                "subAccountApiKey",
                "ipList",
                "permList",
            ],
            required: &["subAccountUid", "passphrase", "label", "subAccountApiKey"],
            arrays: &["ipList", "permList"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-common-vsubaccount/classic-common-vsubaccount#get-virtual-subaccounts
        "get_classic_virtual_subaccount_list" => Endpoint {
            path: "/api/v2/user/virtual-subaccount-list",
            post: false,
            public: false,
            fields: &["limit", "idLessThan", "status"],
            required: &[],
            arrays: &[],
            limit: Some(500),
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-common-vsubaccount/classic-common-vsubaccount#get-subaccount-apikey-list
        "get_classic_virtual_subaccount_apikey_list" => Endpoint {
            path: "/api/v2/user/virtual-subaccount-apikey-list",
            post: false,
            public: false,
            fields: &["subAccountUid"],
            required: &["subAccountUid"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-common/classic-margin-common#get-the-leverage-interest-rate
        "get_classic_interest_rate_record" => Endpoint {
            path: "/api/v2/margin/interest-rate-record",
            post: false,
            public: true,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-common/classic-margin-common#get-support-currencies
        "get_classic_margin_currencies" => Endpoint {
            path: "/api/v2/margin/currencies",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-convert/classic-spot-convert#get-convert-coins
        "get_classic_convert_currencies" => Endpoint {
            path: "/api/v2/convert/currencies",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-convert/classic-spot-convert#get-quoted-price
        "get_classic_quoted_price" => Endpoint {
            path: "/api/v2/convert/quoted-price",
            post: false,
            public: false,
            fields: &["fromCoin", "toCoin", "fromCoinSize", "toCoinSize"],
            required: &["fromCoin", "toCoin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-convert/classic-spot-convert#convert
        "classic_trade" => Endpoint {
            path: "/api/v2/convert/trade",
            post: true,
            public: false,
            fields: &[
                "fromCoin",
                "fromCoinSize",
                "cnvtPrice",
                "toCoin",
                "toCoinSize",
                "traceId",
            ],
            required: &[
                "fromCoin",
                "fromCoinSize",
                "cnvtPrice",
                "toCoin",
                "toCoinSize",
                "traceId",
            ],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-convert/classic-spot-convert#get-convert-history
        "get_classic_convert_record" => Endpoint {
            path: "/api/v2/convert/convert-record",
            post: false,
            public: false,
            fields: &["startTime", "endTime", "limit", "idLessThan"],
            required: &["startTime", "endTime"],
            arrays: &[],
            limit: Some(100),
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-market/classic-spot-market#get-merge-depth
        "get_classic_merge_depth" => Endpoint {
            path: "/api/v2/spot/market/merge-depth",
            post: false,
            public: true,
            fields: &["symbol", "precision", "limit"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-market/classic-spot-market#get-call-auction-information
        "get_classic_auction" => Endpoint {
            path: "/api/v2/spot/market/auction",
            post: false,
            public: true,
            fields: &["symbol"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-market/classic-spot-market#get-vip-fee-rate
        "get_classic_vip_fee_rate" => Endpoint {
            path: "/api/v2/spot/market/vip-fee-rate",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/public-config#get-proof-of-reserves
        "get_uta_proof_of_reserves" => Endpoint {
            path: "/api/v3/market/proof-of-reserves",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/public-config#get-market-maker-score-weight
        "get_uta_score_weights" => Endpoint {
            path: "/api/v3/market/score-weights",
            post: false,
            public: true,
            fields: &["category"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/public-config#get-institution-fee-group
        "get_uta_fee_group" => Endpoint {
            path: "/api/v3/market/fee-group",
            post: false,
            public: true,
            fields: &["category", "group"],
            required: &["category"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/trading-stats#get-spot-fund-flow-data
        "get_uta_spot_fund_flow" => Endpoint {
            path: "/api/v3/market/spot-fund-flow",
            post: false,
            public: true,
            fields: &["symbol", "period"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/trading-stats#get-spot-24h-net-capital-inflow-data
        "get_uta_spot_net_flow" => Endpoint {
            path: "/api/v3/market/spot-net-flow",
            post: false,
            public: true,
            fields: &["symbol"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/trading-stats#get-margin-long-short-ratio-data
        "get_uta_margin_long_short" => Endpoint {
            path: "/api/v3/market/margin-long-short",
            post: false,
            public: true,
            fields: &["symbol", "period", "coin"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/trading-stats#get-margin-loan-growth-rate-data
        "get_uta_margin_loan_growth" => Endpoint {
            path: "/api/v3/market/margin-loan-growth",
            post: false,
            public: true,
            fields: &["symbol", "period", "coin"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/trading-stats#get-isolated-margin-borrowing-ratio-data
        "get_uta_margin_isolated_borrow" => Endpoint {
            path: "/api/v3/market/margin-isolated-borrow",
            post: false,
            public: true,
            fields: &["symbol", "period"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/trading-stats#get-futures-active-buy-sell-volume-data
        "get_uta_futures_active_buy_sell" => Endpoint {
            path: "/api/v3/market/futures-active-buy-sell",
            post: false,
            public: true,
            fields: &["symbol", "period"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/trading-stats#get-futures-long-short-ratio-data
        "get_uta_futures_long_short" => Endpoint {
            path: "/api/v3/market/futures-long-short",
            post: false,
            public: true,
            fields: &["symbol", "period"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/trading-stats#get-futures-active-long-short-position-data
        "get_uta_futures_position_long_short" => Endpoint {
            path: "/api/v3/market/futures-position-long-short",
            post: false,
            public: true,
            fields: &["symbol", "period"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        "batch_create_classic_sub_accounts" => Endpoint {
            path: "/api/v2/user/batch-create-subaccount-and-apikey",
            post: true,
            public: false,
            fields: &["accounts"],
            required: &["accounts"],
            arrays: &[],
            limit: None,
            days: None,
        },
        "move_uta_positions" => Endpoint {
            path: "/api/v3/account/move-positions",
            post: true,
            public: false,
            fields: &["fromUid", "toUid", "category", "positionList"],
            required: &["fromUid", "toUid", "category", "positionList"],
            arrays: &[],
            limit: None,
            days: None,
        },
        _ => return None,
    })
}
