use super::client::BitgetClient;

crate::exchanges::impl_exchange_method_wrappers! {
    BitgetClient;
    public [
        get_classic_interest_rate_record(coin => "coin"),
        get_classic_margin_currencies(),
        get_classic_convert_currencies(),
        get_classic_merge_depth(product_symbol => "product_symbol"),
        get_classic_auction(product_symbol => "product_symbol"),
        get_classic_vip_fee_rate(),
        get_uta_proof_of_reserves(),
        get_uta_score_weights(),
        get_uta_fee_group(category => "category"),
        get_uta_spot_fund_flow(product_symbol => "product_symbol"),
        get_uta_spot_net_flow(product_symbol => "product_symbol"),
        get_uta_margin_long_short(product_symbol => "product_symbol"),
        get_uta_margin_loan_growth(product_symbol => "product_symbol"),
        get_uta_margin_isolated_borrow(product_symbol => "product_symbol"),
        get_uta_futures_active_buy_sell(product_symbol => "product_symbol"),
        get_uta_futures_long_short(product_symbol => "product_symbol"),
        get_uta_futures_position_long_short(product_symbol => "product_symbol"),
        get_uta_cash_dividend_records(product_symbol => "product_symbol", type_ => "type"),
        get_uta_risk_reserve(category => "category", product_symbol => "product_symbol"),
        get_uta_all_risk_reserves(category => "category"),
        get_uta_hourly_risk_reserve(category => "category", product_symbol => "product_symbol"),
        get_uta_split_records(),
        get_uta_futures_long_short_ratio(product_symbol => "product_symbol"),
        get_uta_spot_whale_flow(product_symbol => "product_symbol"),
        get_server_time(),

        get_futures_trade_history(product_symbol => "product_symbol", product_type => "productType"),
        get_futures_index_candle_history(product_symbol => "product_symbol", product_type => "productType", granularity => "granularity"),
        get_futures_mark_candle_history(product_symbol => "product_symbol", product_type => "productType", granularity => "granularity"),
        get_futures_next_funding_time(product_symbol => "product_symbol", product_type => "productType"),
        get_futures_open_interest_limit(product_type => "productType"),
        get_futures_position_tiers(product_type => "productType", product_symbol => "product_symbol"),
        get_futures_discount_rates(),
        get_futures_interest_exchange_rates(),
        get_futures_interest_rate_history(coin => "coin"),
        get_futures_vip_fee_rates(),
        get_uta_funding_rate_history(category => "category", product_symbol => "product_symbol"),
        get_uta_index_components(product_symbol => "product_symbol"),
        get_uta_margin_loan_rates(coin => "coin"),
        get_uta_position_tiers(category => "category"),
        get_uta_open_interest_limit(category => "category"),
        get_uta_discount_rates(),
        get_uta_rpi_orderbook(category => "category", product_symbol => "product_symbol"),
        get_uta_rpi_symbols(),
        get_futures_symbol_price(product_symbol => "product_symbol", product_type => "productType"),
        get_uta_open_interest(category => "category"),
        get_uta_current_funding_rate(),

        get_futures_contracts(),
        get_futures_current_funding_rate(),
        get_futures_history_funding_rate(product_symbol => "product_symbol"),
        get_futures_history_kline(product_symbol => "product_symbol", granularity => "granularity"),
        get_futures_kline(product_symbol => "product_symbol", granularity => "granularity"),
        get_futures_open_interest(product_symbol => "product_symbol"),
        get_uta_liquidations(product_symbol => "product_symbol"),
        get_uta_instruments(category => "category"),
        get_uta_tickers(category => "category"),
        get_uta_orderbook(category => "category", product_symbol => "product_symbol"),
        get_uta_public_fills(category => "category", product_symbol => "product_symbol"),
        get_uta_kline(category => "category", product_symbol => "product_symbol", interval => "interval"),
        get_uta_history_kline(category => "category", product_symbol => "product_symbol", interval => "interval"),
        get_reality_stock_info(),
        get_reality_market_states(),
        get_reality_market_calendar(),
        get_futures_orderbook(product_symbol => "product_symbol"),
        get_futures_recent_trades(product_symbol => "product_symbol"),
        get_futures_ticker(product_symbol => "product_symbol"),
        get_futures_tickers(),
        get_spot_coins(),
        get_spot_history_kline(product_symbol => "product_symbol", granularity => "granularity"),
        get_spot_kline(product_symbol => "product_symbol", granularity => "granularity"),
        get_spot_market_trades(product_symbol => "product_symbol"),
        get_spot_orderbook(product_symbol => "product_symbol"),
        get_spot_recent_trades(product_symbol => "product_symbol"),
        get_spot_symbols(),
        get_spot_tickers(),
    ];
    private [
        get_uta_deposit_address(coin => "coin"),
        get_uta_sub_deposit_address(sub_uid => "subUid", coin => "coin"),
        get_uta_sub_deposit_records(sub_uid => "subUid", start_time => "startTime", end_time => "endTime"),
        get_uta_rate_limit_quota(category => "category"),
        uta_set_rate_limit_quota(category => "category", uids => "uids", quota => "quota"),
        get_uta_small_assets_history(),
        get_uta_small_assets(),
        uta_small_assets_trade(from_coin_list => "fromCoinList"),
        convert_uta_small_assets(from_coin_list => "fromCoinList"),
        uta_delete_sub(sub_uid => "subUid"),
        delete_uta_subaccount(sub_uid => "subUid"),
        uta_freeze_sub(sub_uid => "subUid", operation => "operation"),
        uta_create_sub_api(sub_uid => "subUid", note => "note", type_ => "type", passphrase => "passphrase", permissions => "permissions", ips => "ips"),
        uta_update_sub_api(api_key => "apiKey", passphrase => "passphrase"),
        uta_delete_sub_api(api_key => "apiKey"),
        get_uta_sub_api_list(sub_uid => "subUid"),
        classic_create_virtual_subaccount(sub_account_list => "subAccountList"),
        classic_create_virtual_subaccount_apikey(sub_account_uid => "subAccountUid", passphrase => "passphrase", label => "label", perm_list => "permList"),
        classic_modify_virtual_subaccount(sub_account_uid => "subAccountUid", perm_list => "permList", status => "status"),
        classic_modify_virtual_subaccount_apikey(sub_account_uid => "subAccountUid", passphrase => "passphrase", label => "label", sub_account_api_key => "subAccountApiKey"),
        get_classic_virtual_subaccount_list(),
        get_classic_virtual_subaccount_apikey_list(sub_account_uid => "subAccountUid"),
        get_classic_quoted_price(from_coin => "fromCoin", to_coin => "toCoin"),
        classic_trade(from_coin => "fromCoin", from_coin_size => "fromCoinSize", cnvt_price => "cnvtPrice", to_coin => "toCoin", to_coin_size => "toCoinSize", trace_id => "traceId"),
        convert_classic_asset(from_coin => "fromCoin", from_coin_size => "fromCoinSize", cnvt_price => "cnvtPrice", to_coin => "toCoin", to_coin_size => "toCoinSize", trace_id => "traceId"),
        get_classic_convert_record(start_time => "startTime", end_time => "endTime"),
        set_uta_fee_deduction(deduct => "deduct"),
        get_uta_fee_deduction(),
        upgrade_to_uta(),
        get_uta_upgrade_status(),
        get_futures_margin_mode_switch_quota(),
        get_cross_margin_liquidation_orders(),
        get_isolated_margin_liquidation_orders(),
        get_classic_account_upgrade_status(),
        upgrade_classic_account(),
        get_spot_fee_deduction(),
        set_spot_fee_deduction(deduct => "deduct"),
        set_spot_deposit_account(account_type => "accountType", coin => "coin"),
        get_deposit_address(coin => "coin"),
        get_sub_account_deposit_address(sub_uid => "subUid", coin => "coin"),
        get_sub_account_deposit_records(sub_uid => "subUid"),
        set_uta_deposit_account(coin => "coin", account_type => "accountType"),
        create_uta_sub_account(username => "username"),
        get_uta_strategy_sub_orders(order_id => "orderId"),
        get_uta_deposit_records(start_time => "startTime", end_time => "endTime"),
        get_all_trade_rates(business_type => "businessType"),
        transfer_uta_account(from_type => "fromType", to_type => "toType", amount => "amount", coin => "coin"),
        transfer_uta_sub_to_master(from_type => "fromType", to_type => "toType", amount => "amount", coin => "coin"),
        transfer_uta_sub_account(from_type => "fromType", to_type => "toType", amount => "amount", coin => "coin", from_user_id => "fromUserId", to_user_id => "toUserId", client_oid => "clientOid"),
        get_uta_sub_account_transfer_records(),
        get_uta_sub_accounts(),
        get_uta_sub_account_assets(),
        place_cross_margin_batch_orders(product_symbol => "product_symbol", orders => "orderList"),
        place_isolated_margin_batch_orders(product_symbol => "product_symbol", orders => "orderList"),
        cancel_cross_margin_batch_orders(product_symbol => "product_symbol", orders => "orderIdList"),
        cancel_isolated_margin_batch_orders(product_symbol => "product_symbol", orders => "orderIdList"),
        batch_cancel_replace_spot_orders(orders => "orderList"),
        modify_uta_batch_orders(orders => "orders"),
        get_futures_sub_account_assets(product_type => "productType"),
        get_futures_estimated_open_count(product_symbol => "product_symbol", product_type => "productType", margin_coin => "marginCoin", open_amount => "openAmount", open_price => "openPrice"),
        get_futures_liquidation_price(product_symbol => "product_symbol", product_type => "productType", margin_coin => "marginCoin", pos_side => "posSide", order_type => "orderType", open_amount => "openAmount"),
        get_futures_max_open_quantity(product_symbol => "product_symbol", product_type => "productType", margin_coin => "marginCoin", pos_side => "posSide", order_type => "orderType"),
        get_futures_interest_history(product_type => "productType", start_time => "startTime", end_time => "endTime"),
        set_futures_all_leverage(product_type => "productType", leverage => "leverage"),
        set_futures_auto_margin(product_symbol => "product_symbol", auto_margin => "autoMargin", margin_coin => "marginCoin", hold_side => "holdSide"),
        set_futures_asset_mode(product_type => "productType", asset_mode => "assetMode"),
        convert_futures_union_asset(coin => "coin", amount => "amount"),
        get_futures_union_transfer_limits(coin => "coin"),
        get_futures_union_config(),
        get_futures_isolated_symbols(product_type => "productType"),
        get_futures_position_history(),
        get_futures_adl_rank(product_type => "productType"),
        reverse_futures_position(product_symbol => "product_symbol", margin_coin => "marginCoin", product_type => "productType", side => "side"),
        get_futures_fill_history(product_type => "productType"),
        get_spot_sub_account_transfer_records(),
        get_spot_sub_account_assets(),
        transfer_spot_sub_account(from_type => "fromType", to_type => "toType", amount => "amount", coin => "coin", from_user_id => "fromUserId", to_user_id => "toUserId"),
        get_cross_margin_assets(),
        borrow_cross_margin_asset(coin => "coin", borrow_amount => "borrowAmount"),
        repay_cross_margin_asset(coin => "coin", repay_amount => "repayAmount"),
        get_cross_margin_risk_rate(),
        get_cross_margin_max_borrowable(coin => "coin"),
        get_cross_margin_max_transferable(coin => "coin"),
        flash_repay_cross_margin_assets(),
        get_cross_margin_flash_repay_result(id_list => "idList"),
        get_cross_margin_interest_rate_limits(coin => "coin"),
        get_cross_margin_tiers(coin => "coin"),
        get_cross_margin_borrow_history(start_time => "startTime"),
        get_cross_margin_repay_history(start_time => "startTime"),
        get_cross_margin_interest_history(start_time => "startTime"),
        get_cross_margin_liquidation_history(start_time => "startTime"),
        get_cross_margin_financial_records(start_time => "startTime"),
        place_cross_margin_order(product_symbol => "product_symbol", order_type => "orderType", loan_type => "loanType", force => "force", side => "side"),
        cancel_cross_margin_order(product_symbol => "product_symbol"),
        get_cross_margin_open_orders(product_symbol => "product_symbol", start_time => "startTime"),
        get_cross_margin_order_history(product_symbol => "product_symbol", start_time => "startTime"),
        get_cross_margin_fills(product_symbol => "product_symbol", start_time => "startTime"),
        get_isolated_margin_assets(),
        borrow_isolated_margin_asset(product_symbol => "product_symbol", coin => "coin", borrow_amount => "borrowAmount"),
        repay_isolated_margin_asset(repay_amount => "repayAmount", coin => "coin", product_symbol => "product_symbol"),
        get_isolated_margin_risk_rate(),
        get_isolated_margin_max_borrowable(product_symbol => "product_symbol"),
        get_isolated_margin_max_transferable(product_symbol => "product_symbol"),
        flash_repay_isolated_margin_assets(),
        get_isolated_margin_flash_repay_result(id_list => "idList"),
        get_isolated_margin_interest_rate_limits(product_symbol => "product_symbol"),
        get_isolated_margin_tiers(product_symbol => "product_symbol"),
        get_isolated_margin_borrow_history(product_symbol => "product_symbol", start_time => "startTime"),
        get_isolated_margin_repay_history(product_symbol => "product_symbol", start_time => "startTime"),
        get_isolated_margin_interest_history(product_symbol => "product_symbol", start_time => "startTime"),
        get_isolated_margin_liquidation_history(product_symbol => "product_symbol", start_time => "startTime"),
        get_isolated_margin_financial_records(product_symbol => "product_symbol", start_time => "startTime"),
        place_isolated_margin_order(product_symbol => "product_symbol", order_type => "orderType", loan_type => "loanType", force => "force", side => "side"),
        cancel_isolated_margin_order(product_symbol => "product_symbol"),
        get_isolated_margin_open_orders(product_symbol => "product_symbol", start_time => "startTime"),
        get_isolated_margin_order_history(product_symbol => "product_symbol", start_time => "startTime"),
        get_isolated_margin_fills(product_symbol => "product_symbol", start_time => "startTime"),
        get_uta_funding_assets(),
        get_uta_funding_records(),
        get_uta_fee_rate(product_symbol => "product_symbol", category => "category"),
        get_uta_max_transferable(coin => "coin"),
        set_uta_collateral_type(collateral_type => "collateralType"),
        get_uta_settings(),
        get_uta_delta_info(),
        get_uta_repayable_coins(),
        get_uta_payment_coins(),
        borrow_uta_asset(coin => "coin", amount => "amount"),
        get_uta_max_borrowable(coin => "coin"),
        get_uta_account_open_interest_limit(product_symbol => "product_symbol", category => "category"),
        get_uta_transferable_coins(from_type => "fromType", to_type => "toType"),
        get_uta_max_open_available(category => "category", product_symbol => "product_symbol", order_type => "orderType", side => "side"),
        get_uta_position_transfer_history(category => "category"),
        set_uta_repay_mode(repay_mode => "repayMode"),
        get_uta_eligible_discount_rates(),
        get_uta_eligible_loan_info(),
        get_uta_eligible_margin_tiers(),
        get_uta_eligible_symbols(),
        get_uta_convert_records(),
        set_uta_account_mode(mode => "mode"),
        get_uta_adl_rank(),
        modify_futures_tpsl_order(margin_coin => "marginCoin", product_type => "productType", product_symbol => "product_symbol", trigger_price => "triggerPrice", size => "size"),
        place_futures_plan_order(plan_type => "planType", product_symbol => "product_symbol", product_type => "productType", margin_mode => "marginMode", margin_coin => "marginCoin", size => "size", trigger_price => "triggerPrice", trigger_type => "triggerType", side => "side", order_type => "orderType"),
        place_futures_position_tpsl(margin_coin => "marginCoin", product_type => "productType", product_symbol => "product_symbol", hold_side => "holdSide"),
        place_futures_tpsl_order(margin_coin => "marginCoin", product_type => "productType", product_symbol => "product_symbol", plan_type => "planType", trigger_price => "triggerPrice", hold_side => "holdSide"),
        get_futures_plan_sub_order(plan_type => "planType", plan_order_id => "planOrderId", product_type => "productType"),
        modify_futures_plan_order(product_type => "productType"),
        cancel_futures_plan_orders(product_type => "productType"),
        get_pending_futures_plan_orders(plan_type => "planType", product_type => "productType"),
        get_futures_plan_order_history(plan_type => "planType", product_type => "productType"),
        place_spot_plan_order(product_symbol => "product_symbol", side => "side", trigger_price => "triggerPrice", order_type => "orderType", size => "size", trigger_type => "triggerType"),
        modify_spot_plan_order(trigger_price => "triggerPrice", order_type => "orderType", size => "size"),
        cancel_spot_plan_order(),
        cancel_spot_plan_orders(),
        get_pending_spot_plan_orders(),
        get_spot_plan_order_history(),
        get_spot_plan_sub_order(plan_order_id => "planOrderId"),
        modify_futures_order(product_symbol => "product_symbol", product_type => "productType", new_client_oid => "newClientOid"),
        close_futures_positions(product_type => "productType"),
        cancel_all_futures_orders(product_type => "productType"),
        cancel_spot_orders_by_symbol(product_symbol => "product_symbol"),
        cancel_replace_spot_order(product_symbol => "product_symbol", price => "price", size => "size"),
        adjust_futures_position_margin(product_symbol => "product_symbol", product_type => "productType", margin_coin => "marginCoin", hold_side => "holdSide", amount => "amount"),
        modify_uta_order(product_symbol => "product_symbol", category => "category"),
        cancel_uta_orders_by_symbol(category => "category"),
        set_uta_cancel_countdown(countdown => "countdown"),
        close_uta_positions(category => "category"),
        get_uta_position_history(category => "category"),
        adjust_uta_position_margin(category => "category", product_symbol => "product_symbol", pos_side => "posSide", operation => "operation", amount => "amount"),
        get_uta_financial_records(category => "category"),

        get_futures_fee_rates(product_symbol => "product_symbol"),
        get_spot_fee_rates(product_symbol => "product_symbol"),
        cancel_futures_batch_orders(product_symbol => "product_symbol"),
        cancel_futures_order(product_symbol => "product_symbol"),
        cancel_spot_batch_orders(order_list => "orderList"),
        cancel_spot_order(product_symbol => "product_symbol"),
        cancel_uta_batch_orders(order_list => "orderList"),
        cancel_uta_order(),
        get_all_account_balance(),
        get_deposit_records(),
        get_funding_assets(),
        get_futures_account(product_symbol => "product_symbol"),
        get_futures_account_bills(),
        get_futures_accounts(),
        get_futures_fills(),
        get_futures_history_orders(),
        get_futures_open_orders(),
        get_futures_order(product_symbol => "product_symbol"),
        get_futures_position(product_symbol => "product_symbol"),
        get_futures_positions(),
        get_spot_account_assets(),
        get_spot_account_bills(),
        get_spot_account_info(),
        get_spot_fills(),
        get_spot_history_orders(),
        get_spot_open_orders(),
        get_spot_order(),
        get_transfer_records(coin => "coin"),
        get_transferable_coins(from_type => "fromType", to_type => "toType"),
        get_uta_account_assets(),
        get_reality_orderbook(product_symbol => "product_symbol"),
        get_reality_fills(product_symbol => "product_symbol"),
        get_uta_account_info(),
        get_uta_all_fee_rates(category => "category"),
        get_uta_loan_data(),
        get_crypto_loan_coins(),
        get_crypto_loan_interest(loan_coin => "loanCoin", pledge_coin => "pledgeCoin", daily => "daily", pledge_amount => "pledgeAmount"),
        borrow_crypto_loan(loan_coin => "loanCoin", pledge_coin => "pledgeCoin", daily => "daily"),
        get_crypto_loan_ongoing(),
        get_crypto_loan_borrow_history(start_time => "startTime", end_time => "endTime"),
        repay_crypto_loan(order_id => "orderId", repay_all => "repayAll"),
        get_crypto_loan_repay_history(start_time => "startTime", end_time => "endTime"),
        revise_crypto_loan_pledge(order_id => "orderId", amount => "amount", pledge_coin => "pledgeCoin", revise_type => "reviseType"),
        get_crypto_loan_pledge_history(start_time => "startTime", end_time => "endTime"),
        get_crypto_loan_liquidations(start_time => "startTime", end_time => "endTime"),
        get_crypto_loan_debts(),
        get_earn_account_assets(),
        get_savings_account(),
        get_savings_products(),
        get_savings_assets(period_type => "periodType"),
        get_savings_records(period_type => "periodType"),
        get_savings_subscription_info(product_id => "productId", period_type => "periodType"),
        subscribe_savings(product_id => "productId", period_type => "periodType", amount => "amount"),
        get_savings_subscription_result(order_id => "orderId", period_type => "periodType"),
        redeem_savings(product_id => "productId", period_type => "periodType", amount => "amount"),
        get_savings_redemption_result(order_id => "orderId", period_type => "periodType"),
        get_elite_earn_products(),
        get_elite_earn_subscription_info(product_id => "productId"),
        subscribe_elite_earn(product_sub_id => "productSubId", amount => "amount"),
        get_elite_earn_subscription_result(order_id => "orderId"),
        get_elite_earn_redemption_info(product_id => "productId"),
        redeem_elite_earn(product_id => "productId", product_sub_id => "productSubId", redeem_type => "redeemType", amount => "amount", receive_account => "receiveAccount"),
        get_elite_earn_assets(),
        get_elite_earn_records(record_type => "type"),
        repay_uta_liability(repayable_coin_list => "repayableCoinList", payment_coin_list => "paymentCoinList"),
        get_uta_collateral_type(),
        get_uta_custom_collateral_coins(),
        get_uta_pre_set_leverage(category => "category", margin_mode => "marginMode"),
        get_uta_fills(),
        get_uta_history_orders(category => "category"),
        get_uta_open_orders(),
        get_uta_order(),
        get_uta_positions(category => "category"),
        place_uta_strategy_order(category => "category", product_symbol => "product_symbol"),
        modify_uta_strategy_order(qty => "qty"),
        cancel_uta_strategy_order(),
        get_uta_unfilled_strategy_orders(category => "category"),
        get_uta_history_strategy_orders(category => "category"),
        place_futures_batch_orders(order_list => "orderList"),
        place_futures_limit_buy_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_futures_limit_order(product_symbol => "product_symbol", side => "side", size => "size", price => "price"),
        place_futures_limit_sell_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_futures_market_buy_order(product_symbol => "product_symbol", size => "size"),
        place_futures_market_order(product_symbol => "product_symbol", side => "side", size => "size"),
        place_futures_market_sell_order(product_symbol => "product_symbol", size => "size"),
        place_futures_order(product_symbol => "product_symbol", side => "side", order_type => "orderType", size => "size"),
        place_futures_post_only_limit_buy_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_futures_post_only_limit_order(product_symbol => "product_symbol", side => "side", size => "size", price => "price"),
        place_futures_post_only_limit_sell_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_spot_batch_orders(order_list => "orderList"),
        place_spot_limit_buy_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_spot_limit_order(product_symbol => "product_symbol", side => "side", size => "size", price => "price"),
        place_spot_limit_sell_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_spot_market_buy_order(product_symbol => "product_symbol", size => "size"),
        place_spot_market_order(product_symbol => "product_symbol", side => "side", size => "size"),
        place_spot_market_sell_order(product_symbol => "product_symbol", size => "size"),
        place_spot_order(product_symbol => "product_symbol", side => "side", order_type => "orderType", size => "size"),
        place_spot_post_only_limit_buy_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_spot_post_only_limit_order(product_symbol => "product_symbol", side => "side", size => "size", price => "price"),
        place_spot_post_only_limit_sell_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_uta_batch_orders(order_list => "orderList"),
        place_uta_order(category => "category", product_symbol => "product_symbol", side => "side", order_type => "orderType", qty => "qty"),
        place_reality_order(product_symbol => "product_symbol", side => "side", order_type => "orderType", qty => "qty"),
        cancel_reality_order(product_symbol => "product_symbol"),
        set_futures_leverage(product_symbol => "product_symbol", leverage => "leverage"),
        set_futures_margin_mode(product_symbol => "product_symbol", margin_mode => "marginMode"),
        set_futures_position_mode(pos_mode => "posMode"),
        set_uta_hold_mode(hold_mode => "holdMode"),
        set_uta_leverage(category => "category", leverage => "leverage"),
        transfer(coin => "coin", amount => "amount", from_type => "fromType", to_type => "toType"),
    ];
}

crate::exchanges::impl_exchange_method_wrappers! { @extend; BitgetClient; public []; private [batch_create_classic_sub_accounts(accounts => "accounts"), move_uta_positions(from_uid => "fromUid", to_uid => "toUid", category => "category", position_list => "positionList")]; }

crate::exchanges::impl_exchange_method_wrappers! { @extend; BitgetClient; public [
get_classic_earn_loan_public_coin_infos(),
get_classic_earn_loan_public_hour_interest(loan_coin => "loanCoin",pledge_coin => "pledgeCoin",daily => "daily",pledge_amount => "pledgeAmount"),
]; private [
get_uta_account_max_withdrawal(coin => "coin"),
get_classic_account_bot_assets(),
get_classic_spot_wallet_withdrawal_records(start_time => "startTime",end_time => "endTime"),
get_uta_account_withdrawal_records(start_time => "startTime",end_time => "endTime"),
get_uta_account_withdraw_address(),
get_classic_earn_elite_product(),
classic_earn_elite_subscribe(product_sub_id => "productSubId",amount => "amount"),
subscribe_classic_elite(product_sub_id => "productSubId",amount => "amount"),
get_classic_earn_elite_subscribe_result(order_id => "orderId"),
get_classic_earn_elite_subscribe_info(product_id => "productId"),
classic_earn_elite_redeem(product_id => "productId",product_sub_id => "productSubId",redeem_type => "redeemType",amount => "amount",receive_account => "receiveAccount"),
redeem_classic_elite(product_id => "productId",product_sub_id => "productSubId",redeem_type => "redeemType",amount => "amount",receive_account => "receiveAccount"),
get_classic_earn_elite_redeem_info(product_id => "productId"),
get_classic_earn_elite_assets(),
get_classic_earn_elite_records(type_ => "type"),
classic_earn_loan_borrow(loan_coin => "loanCoin",pledge_coin => "pledgeCoin",daily => "daily"),
borrow_classic_earn_loan(loan_coin => "loanCoin",pledge_coin => "pledgeCoin",daily => "daily"),
get_classic_earn_loan_ongoing_orders(),
classic_earn_loan_repay(order_id => "orderId",repay_all => "repayAll"),
repay_classic_earn_loan(order_id => "orderId",repay_all => "repayAll"),
get_classic_earn_loan_repay_history(start_time => "startTime",end_time => "endTime"),
classic_earn_loan_revise_pledge(order_id => "orderId",amount => "amount",pledge_coin => "pledgeCoin",revise_type => "reviseType"),
get_classic_earn_loan_revise_history(start_time => "startTime",end_time => "endTime"),
get_classic_earn_loan_borrow_history(start_time => "startTime",end_time => "endTime"),
get_classic_earn_loan_debts(),
get_classic_earn_loan_reduces(start_time => "startTime",end_time => "endTime"),
uta_trade_grid_add_investment(category => "category",bot_id => "botId",coin => "coin",size => "size",funds_source => "fundsSource"),
get_uta_trade_grid_bot_detail(bot_id => "botId"),
uta_trade_grid_close_bot(bot_id => "botId"),
uta_trade_grid_create_bot(category => "category",symbol => "symbol",max_price => "maxPrice",min_price => "minPrice",grid_num => "gridNum",grid_order_mode => "gridOrderMode",investment_amount => "investmentAmount",funds_source => "fundsSource",slippage => "slippage",auto_transfer_profits => "autoTransferProfits"),
uta_trade_grid_create_neutral_bot(category => "category",symbol => "symbol",max_price => "maxPrice",min_price => "minPrice",grid_num => "gridNum",grid_order_mode => "gridOrderMode",funds_source => "fundsSource"),
get_uta_trade_grid_list_details(category => "category",bot_id => "botId"),
uta_trade_grid_modify_bot(bot_id => "botId"),
uta_trade_grid_modify_grid_interval(category => "category",bot_id => "botId",max_price => "maxPrice",min_price => "minPrice",grid_num => "gridNum"),
uta_trade_grid_modify_neutral_bot(bot_id => "botId",category => "category"),
uta_trade_grid_modify_neutral_grid_interval(category => "category",bot_id => "botId",max_price => "maxPrice",min_price => "minPrice",grid_num => "gridNum"),
get_uta_trade_grid_neutral_bot_detail(bot_id => "botId"),
get_uta_trade_grid_neutral_list_details(category => "category",bot_id => "botId"),
uta_trade_grid_validate_neutral(category => "category",symbol => "symbol",max_price => "maxPrice",min_price => "minPrice",grid_num => "gridNum",grid_order_mode => "gridOrderMode"),
uta_trade_grid_validate(category => "category",symbol => "symbol",max_price => "maxPrice",min_price => "minPrice",grid_num => "gridNum",grid_order_mode => "gridOrderMode",investment_amount => "investmentAmount",auto_transfer_profits => "autoTransferProfits"),
]; }

crate::exchanges::impl_exchange_method_wrappers! { @extend; BitgetClient; public [
get_reality_company_overview(code => "code"),
get_reality_valuation_indicators(code => "code"),
get_reality_earnings_forecast(code => "code"),
get_reality_suspension_resumption_info(code => "code"),
get_reality_dividends(code => "code"),
get_reality_share_capital_change(code => "code"),
get_reality_inner_trades(code => "code"),
get_reality_executive_shareholdings(code => "code"),
get_reality_sharehold_detail(code => "code"),
]; private [

]; }

mod business_methods {
    use crate::exchanges::bitget::client::BitgetClient;

    crate::exchanges::impl_exchange_method_wrappers! {
        @extend; BitgetClient; public []; private [
            /// API withdrawals and external transfers have no second confirmation; they execute on submit.
            create_spot_withdrawal(coin => "coin", transfer_type => "transferType", address => "address", size => "size"),
            cancel_spot_withdrawal(order_id => "orderId"),
            create_uta_agent_sub_account(username => "username", passphrase => "passphrase"),
            create_classic_agent_sub_account(username => "username", passphrase => "passphrase"),
            /// API withdrawals and external transfers have no second confirmation; they execute on submit.
            create_uta_withdrawal(coin => "coin", transfer_type => "transferType", address => "address", size => "size"),
            cancel_uta_withdrawal(),
        ];
    }
}
