use super::client::BitgetClient;

crate::exchanges::impl_exchange_method_wrappers! {
    BitgetClient;
    public [
        get_futures_contracts(),
        get_futures_current_funding_rate(),
        get_futures_history_funding_rate(product_symbol => "product_symbol"),
        get_futures_history_kline(product_symbol => "product_symbol", granularity => "granularity"),
        get_futures_kline(product_symbol => "product_symbol", granularity => "granularity"),
        get_futures_open_interest(product_symbol => "product_symbol"),
        get_uta_liquidations(product_symbol => "product_symbol"),
        get_uta_instruments(category => "category"),
        get_uta_tickers(category => "category"),
        get_uta_orderbook(category => "category", product_symbol => "product_symbol"),
        get_uta_public_fills(category => "category", product_symbol => "product_symbol"),
        get_uta_kline(category => "category", product_symbol => "product_symbol", interval => "interval"),
        get_uta_history_kline(category => "category", product_symbol => "product_symbol", interval => "interval"),
        get_reality_stock_info(),
        get_reality_market_states(),
        get_reality_market_calendar(),
        get_futures_orderbook(product_symbol => "product_symbol"),
        get_futures_recent_trades(product_symbol => "product_symbol"),
        get_futures_ticker(product_symbol => "product_symbol"),
        get_futures_tickers(),
        get_spot_coins(),
        get_spot_history_kline(product_symbol => "product_symbol", granularity => "granularity"),
        get_spot_kline(product_symbol => "product_symbol", granularity => "granularity"),
        get_spot_market_trades(product_symbol => "product_symbol"),
        get_spot_orderbook(product_symbol => "product_symbol"),
        get_spot_recent_trades(product_symbol => "product_symbol"),
        get_spot_symbols(),
        get_spot_tickers(),
    ];
    private [
        get_futures_fee_rates(product_symbol => "product_symbol"),
        get_spot_fee_rates(product_symbol => "product_symbol"),
        cancel_futures_batch_orders(product_symbol => "product_symbol"),
        cancel_futures_order(product_symbol => "product_symbol"),
        cancel_spot_batch_orders(order_list => "orderList"),
        cancel_spot_order(product_symbol => "product_symbol"),
        cancel_uta_batch_orders(order_list => "orderList"),
        cancel_uta_order(),
        get_all_account_balance(),
        get_deposit_records(),
        get_funding_assets(),
        get_futures_account(product_symbol => "product_symbol"),
        get_futures_account_bills(),
        get_futures_accounts(),
        get_futures_fills(),
        get_futures_history_orders(),
        get_futures_open_orders(),
        get_futures_order(product_symbol => "product_symbol"),
        get_futures_position(product_symbol => "product_symbol"),
        get_futures_positions(),
        get_spot_account_assets(),
        get_spot_account_bills(),
        get_spot_account_info(),
        get_spot_fills(),
        get_spot_history_orders(),
        get_spot_open_orders(),
        get_spot_order(),
        get_transfer_records(coin => "coin"),
        get_transferable_coins(from_type => "fromType", to_type => "toType"),
        get_uta_account_assets(),
        get_uta_account_info(),
        get_uta_all_fee_rates(category => "category"),
        get_uta_loan_data(),
        get_crypto_loan_coins(),
        get_crypto_loan_interest(loan_coin => "loanCoin", pledge_coin => "pledgeCoin", daily => "daily", pledge_amount => "pledgeAmount"),
        borrow_crypto_loan(loan_coin => "loanCoin", pledge_coin => "pledgeCoin", daily => "daily"),
        get_crypto_loan_ongoing(),
        get_crypto_loan_borrow_history(start_time => "startTime", end_time => "endTime"),
        repay_crypto_loan(order_id => "orderId", repay_all => "repayAll"),
        get_crypto_loan_repay_history(start_time => "startTime", end_time => "endTime"),
        revise_crypto_loan_pledge(order_id => "orderId", amount => "amount", pledge_coin => "pledgeCoin", revise_type => "reviseType"),
        get_crypto_loan_pledge_history(start_time => "startTime", end_time => "endTime"),
        get_crypto_loan_liquidations(start_time => "startTime", end_time => "endTime"),
        get_crypto_loan_debts(),
        get_earn_account_assets(),
        get_savings_account(),
        get_savings_products(),
        get_savings_assets(period_type => "periodType"),
        get_savings_records(period_type => "periodType"),
        get_savings_subscription_info(product_id => "productId", period_type => "periodType"),
        subscribe_savings(product_id => "productId", period_type => "periodType", amount => "amount"),
        get_savings_subscription_result(order_id => "orderId", period_type => "periodType"),
        redeem_savings(product_id => "productId", period_type => "periodType", amount => "amount"),
        get_savings_redemption_result(order_id => "orderId", period_type => "periodType"),
        get_elite_earn_products(),
        get_elite_earn_subscription_info(product_id => "productId"),
        subscribe_elite_earn(product_sub_id => "productSubId", amount => "amount"),
        get_elite_earn_subscription_result(order_id => "orderId"),
        get_elite_earn_redemption_info(product_id => "productId"),
        redeem_elite_earn(product_id => "productId", product_sub_id => "productSubId", redeem_type => "redeemType", amount => "amount", receive_account => "receiveAccount"),
        get_elite_earn_assets(),
        get_elite_earn_records(record_type => "type"),
        repay_uta_liability(repayable_coin_list => "repayableCoinList", payment_coin_list => "paymentCoinList"),
        get_uta_collateral_type(),
        get_uta_custom_collateral_coins(),
        get_uta_pre_set_leverage(category => "category", margin_mode => "marginMode"),
        get_uta_fills(),
        get_uta_history_orders(category => "category"),
        get_uta_open_orders(),
        get_uta_order(),
        get_uta_positions(category => "category"),
        place_uta_strategy_order(category => "category", product_symbol => "product_symbol"),
        modify_uta_strategy_order(qty => "qty"),
        cancel_uta_strategy_order(),
        get_uta_unfilled_strategy_orders(category => "category"),
        get_uta_history_strategy_orders(category => "category"),
        place_futures_batch_orders(order_list => "orderList"),
        place_futures_limit_buy_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_futures_limit_order(product_symbol => "product_symbol", side => "side", size => "size", price => "price"),
        place_futures_limit_sell_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_futures_market_buy_order(product_symbol => "product_symbol", size => "size"),
        place_futures_market_order(product_symbol => "product_symbol", side => "side", size => "size"),
        place_futures_market_sell_order(product_symbol => "product_symbol", size => "size"),
        place_futures_order(product_symbol => "product_symbol", side => "side", order_type => "orderType", size => "size"),
        place_futures_post_only_limit_buy_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_futures_post_only_limit_order(product_symbol => "product_symbol", side => "side", size => "size", price => "price"),
        place_futures_post_only_limit_sell_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_spot_batch_orders(order_list => "orderList"),
        place_spot_limit_buy_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_spot_limit_order(product_symbol => "product_symbol", side => "side", size => "size", price => "price"),
        place_spot_limit_sell_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_spot_market_buy_order(product_symbol => "product_symbol", size => "size"),
        place_spot_market_order(product_symbol => "product_symbol", side => "side", size => "size"),
        place_spot_market_sell_order(product_symbol => "product_symbol", size => "size"),
        place_spot_order(product_symbol => "product_symbol", side => "side", order_type => "orderType", size => "size"),
        place_spot_post_only_limit_buy_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_spot_post_only_limit_order(product_symbol => "product_symbol", side => "side", size => "size", price => "price"),
        place_spot_post_only_limit_sell_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_uta_batch_orders(order_list => "orderList"),
        place_uta_order(category => "category", product_symbol => "product_symbol", side => "side", order_type => "orderType", qty => "qty"),
        place_reality_order(product_symbol => "product_symbol", side => "side", order_type => "orderType", qty => "qty"),
        cancel_reality_order(product_symbol => "product_symbol"),
        set_futures_leverage(product_symbol => "product_symbol", leverage => "leverage"),
        set_futures_margin_mode(product_symbol => "product_symbol", margin_mode => "marginMode"),
        set_futures_position_mode(pos_mode => "posMode"),
        set_uta_hold_mode(hold_mode => "holdMode"),
        set_uta_leverage(category => "category", leverage => "leverage"),
        transfer(coin => "coin", amount => "amount", from_type => "fromType", to_type => "toType"),
    ];
}
