//! Schemas checked against the official Kraken OpenAPI documentation.
use super::client::KrakenAuth;
use super::risk::{Endpoint, Field};
use crate::http::HttpMethod;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "get_spot_trades_info",
        path: "/0/private/QueryTrades",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["txid", "trades", "rebase_multiplier"],
        fields: &[
            Field {
                key: "txid",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "trades",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "rebase_multiplier",
                kind: "string",
                required: false,
                values: &["rebased", "base"],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_account_log_csv",
        path: "/api/history/v3/accountlogcsv",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &["conversion_details"],
        fields: &[Field {
            key: "conversion_details",
            kind: "boolean",
            required: false,
            values: &[],
            minimum: 0,
        }],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_account_log",
        path: "/api/history/v3/account-log",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[
            "since",
            "before",
            "from",
            "to",
            "sort",
            "info",
            "count",
            "conversion_details",
        ],
        fields: &[
            Field {
                key: "since",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "before",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "from",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 1,
            },
            Field {
                key: "to",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 1,
            },
            Field {
                key: "sort",
                kind: "string",
                required: false,
                values: &["asc", "desc"],
                minimum: 0,
            },
            Field {
                key: "info",
                kind: "array",
                required: false,
                values: &[
                    "deposit",
                    "withdrawal",
                    "futures partial liquidation",
                    "futures assignment",
                    "futures assignor",
                    "futures assignee",
                    "futures liquidation",
                    "futures_unwind",
                    "settlement",
                    "futures trade",
                    "admin transfer",
                    "transfer",
                    "subaccount transfer",
                    "fee credit",
                    "legacy",
                    "transfers fee",
                    "referral",
                    "funding rate change",
                    "revenue share",
                    "cross-exchange transfer",
                    "cross-exchange transfer failed",
                    "spot trade",
                    "spot fee credit",
                    "margin trade",
                    "margin position settlement",
                    "conversion credit",
                    "loan transfer",
                    "conversion",
                    "interest payment",
                    "interest payment credit",
                    "futures unwind bankrupt",
                    "futures unwind counterparty",
                    "kfee applied",
                    "covered liquidation",
                    "position transfer",
                    "portfolio auctioning",
                    "external custody delegation",
                    "external custody undelegation",
                    "external custody unbind",
                    "futures tax withheld",
                    "futures tax refund",
                    "tax conversion",
                    "options trade",
                    "hedging trade",
                    "rfq",
                    "funding rate payment - cash dividend",
                    "funding rate payment - spin off",
                    "funding rate payment - rights distribution",
                    "funding rate payment - cashflow",
                ],
                minimum: 0,
            },
            Field {
                key: "count",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 1,
            },
            Field {
                key: "conversion_details",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_execution_events",
        path: "/api/history/v3/executions",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[
            "since",
            "before",
            "sort",
            "continuation_token",
            "count",
            "tradeable",
            "product_symbol",
        ],
        fields: &[
            Field {
                key: "since",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "before",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "sort",
                kind: "string",
                required: false,
                values: &["asc", "desc"],
                minimum: 0,
            },
            Field {
                key: "continuation_token",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "count",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 1,
            },
            Field {
                key: "tradeable",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: Some("tradeable"),
    },
    Endpoint {
        name: "get_futures_order_events",
        path: "/api/history/v3/orders",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[
            "since",
            "before",
            "sort",
            "continuation_token",
            "count",
            "tradeable",
            "opened",
            "closed",
            "product_symbol",
        ],
        fields: &[
            Field {
                key: "since",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "before",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "sort",
                kind: "string",
                required: false,
                values: &["asc", "desc"],
                minimum: 0,
            },
            Field {
                key: "continuation_token",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "count",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 1,
            },
            Field {
                key: "tradeable",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "opened",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "closed",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: Some("tradeable"),
    },
    Endpoint {
        name: "get_futures_position_events",
        path: "/api/history/v3/positions",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[
            "since",
            "before",
            "sort",
            "continuation_token",
            "count",
            "opened",
            "closed",
            "increased",
            "decreased",
            "reversed",
            "no_change",
            "trades",
            "funding_realization",
            "settlement",
            "tradeable",
            "product_symbol",
        ],
        fields: &[
            Field {
                key: "since",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "before",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "sort",
                kind: "string",
                required: false,
                values: &["asc", "desc"],
                minimum: 0,
            },
            Field {
                key: "continuation_token",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "count",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 1,
            },
            Field {
                key: "opened",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "closed",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "increased",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "decreased",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "reversed",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "no_change",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "trades",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "funding_realization",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "settlement",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "tradeable",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: Some("tradeable"),
    },
    Endpoint {
        name: "get_futures_trigger_events",
        path: "/api/history/v3/triggers",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[
            "since",
            "before",
            "sort",
            "continuation_token",
            "count",
            "tradeable",
            "opened",
            "closed",
            "product_symbol",
        ],
        fields: &[
            Field {
                key: "since",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "before",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "sort",
                kind: "string",
                required: false,
                values: &["asc", "desc"],
                minimum: 0,
            },
            Field {
                key: "continuation_token",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "count",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 1,
            },
            Field {
                key: "tradeable",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "opened",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "closed",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: Some("tradeable"),
    },
    Endpoint {
        name: "get_spot_deposit_addresses",
        path: "/0/private/DepositAddresses",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["asset", "aclass", "method", "new", "amount"],
        fields: &[
            Field {
                key: "asset",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "aclass",
                kind: "string",
                required: false,
                values: &["currency", "tokenized_asset"],
                minimum: 0,
            },
            Field {
                key: "method",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "new",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "amount",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_spot_deposit_methods",
        path: "/0/private/DepositMethods",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["asset", "aclass", "rebase_multiplier"],
        fields: &[
            Field {
                key: "asset",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "aclass",
                kind: "string",
                required: false,
                values: &["currency", "tokenized_asset"],
                minimum: 0,
            },
            Field {
                key: "rebase_multiplier",
                kind: "string",
                required: false,
                values: &["rebased", "base"],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_instrument_status",
        path: "/derivatives/api/v3/instruments/{symbol}/status",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: true,
        allowed: &["symbol", "product_symbol"],
        fields: &[Field {
            key: "symbol",
            kind: "string",
            required: true,
            values: &[],
            minimum: 0,
        }],
        symbol_key: Some("symbol"),
    },
    Endpoint {
        name: "get_futures_instrument_statuses",
        path: "/derivatives/api/v3/instruments/status",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: true,
        allowed: &["contractType"],
        fields: &[Field {
            key: "contractType",
            kind: "array",
            required: false,
            values: &[
                "futures_inverse",
                "futures_vanilla",
                "flexible_futures",
                "options",
                "all",
            ],
            minimum: 0,
        }],
        symbol_key: None,
    },
    Endpoint {
        name: "transfer_spot_sub_account",
        path: "/0/private/AccountTransfer",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["asset", "asset_class", "amount", "from", "to"],
        fields: &[
            Field {
                key: "asset",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "asset_class",
                kind: "string",
                required: false,
                values: &["currency", "tokenized_asset"],
                minimum: 0,
            },
            Field {
                key: "amount",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "from",
                kind: "string",
                required: true,
                values: &[],
                minimum: 1,
            },
            Field {
                key: "to",
                kind: "string",
                required: true,
                values: &[],
                minimum: 1,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "transfer_futures_sub_account",
        path: "/derivatives/api/v3/transfer/subaccount",
        method: HttpMethod::Post,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[
            "fromUser",
            "toUser",
            "fromAccount",
            "toAccount",
            "unit",
            "amount",
        ],
        fields: &[
            Field {
                key: "fromUser",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "toUser",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "fromAccount",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "toAccount",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "unit",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "amount",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_spot_deposit_status",
        path: "/0/private/DepositStatus",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &[
            "asset",
            "aclass",
            "method",
            "start",
            "end",
            "cursor",
            "limit",
            "rebase_multiplier",
        ],
        fields: &[
            Field {
                key: "asset",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "aclass",
                kind: "string",
                required: false,
                values: &["currency", "tokenized_asset"],
                minimum: 0,
            },
            Field {
                key: "method",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "start",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "end",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "cursor",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "limit",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 1,
            },
            Field {
                key: "rebase_multiplier",
                kind: "string",
                required: false,
                values: &["rebased", "base"],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_spot_level3_orderbook",
        path: "/0/private/Level3",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["pair", "depth", "product_symbol"],
        fields: &[
            Field {
                key: "pair",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "depth",
                kind: "integer",
                required: false,
                values: &["0", "10", "25", "100", "250", "1000"],
                minimum: 0,
            },
        ],
        symbol_key: Some("pair"),
    },
    Endpoint {
        name: "get_spot_api_key_info",
        path: "/0/private/GetApiKeyInfo",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["otp"],
        fields: &[Field {
            key: "otp",
            kind: "string",
            required: false,
            values: &[],
            minimum: 0,
        }],
        symbol_key: None,
    },
    Endpoint {
        name: "get_spot_credit_lines",
        path: "/0/private/CreditLines",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["rebase_multiplier"],
        fields: &[Field {
            key: "rebase_multiplier",
            kind: "string",
            required: false,
            values: &["rebased", "base"],
            minimum: 0,
        }],
        symbol_key: None,
    },
    Endpoint {
        name: "get_spot_order_amends",
        path: "/0/private/OrderAmends",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["order_id", "rebase_multiplier"],
        fields: &[
            Field {
                key: "order_id",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "rebase_multiplier",
                kind: "string",
                required: false,
                values: &["rebased", "base"],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_spot_wallet_accounts",
        path: "/0/private/ListWalletAccounts",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &[],
        fields: &[],
        symbol_key: None,
    },
    Endpoint {
        name: "get_spot_ledger_entries",
        path: "/0/private/QueryLedgers",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["id", "trades", "rebase_multiplier"],
        fields: &[
            Field {
                key: "id",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "trades",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "rebase_multiplier",
                kind: "string",
                required: false,
                values: &["rebased", "base"],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_portfolio_margin_parameters",
        path: "/derivatives/api/v3/portfolio-margining/parameters",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[],
        fields: &[],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_unwind_queue",
        path: "/derivatives/api/v3/unwindqueue",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[],
        fields: &[],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_notifications",
        path: "/derivatives/api/v3/notifications",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[],
        fields: &[],
        symbol_key: None,
    },
    Endpoint {
        name: "get_spot_grouped_orderbook",
        path: "/0/public/GroupedBook",
        method: HttpMethod::Get,
        auth: KrakenAuth::Spot,
        public: true,
        allowed: &["pair", "depth", "grouping", "product_symbol"],
        fields: &[
            Field {
                key: "pair",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "depth",
                kind: "integer",
                required: false,
                values: &["10", "25", "100", "250", "1000"],
                minimum: 0,
            },
            Field {
                key: "grouping",
                kind: "integer",
                required: false,
                values: &["1", "5", "10", "25", "50", "100", "250", "500", "1000"],
                minimum: 0,
            },
        ],
        symbol_key: Some("pair"),
    },
    Endpoint {
        name: "get_spot_maintenance_schedule",
        path: "/0/public/MaintenanceSchedule",
        method: HttpMethod::Get,
        auth: KrakenAuth::Spot,
        public: true,
        allowed: &[],
        fields: &[],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_self_trade_strategy",
        path: "/derivatives/api/v3/self-trade-strategy",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[],
        fields: &[],
        symbol_key: None,
    },
    Endpoint {
        name: "set_futures_self_trade_strategy",
        path: "/derivatives/api/v3/self-trade-strategy",
        method: HttpMethod::Put,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &["strategy"],
        fields: &[Field {
            key: "strategy",
            kind: "string",
            required: true,
            values: &[
                "REJECT_TAKER",
                "CANCEL_MAKER_SELF",
                "CANCEL_MAKER_CHILD",
                "CANCEL_MAKER_ANY",
            ],
            minimum: 0,
        }],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_trading_instruments",
        path: "/derivatives/api/v3/trading/instruments",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &["contractType"],
        fields: &[Field {
            key: "contractType",
            kind: "array",
            required: false,
            values: &[
                "futures_inverse",
                "futures_vanilla",
                "flexible_futures",
                "options",
                "all",
            ],
            minimum: 0,
        }],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_subaccount_trading_status",
        path: "/derivatives/api/v3/subaccount/{subaccountUid}/trading-enabled",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &["subaccountUid"],
        fields: &[Field {
            key: "subaccountUid",
            kind: "string",
            required: true,
            values: &[],
            minimum: 0,
        }],
        symbol_key: None,
    },
    Endpoint {
        name: "set_futures_subaccount_trading_status",
        path: "/derivatives/api/v3/subaccount/{subaccountUid}/trading-enabled",
        method: HttpMethod::Put,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &["subaccountUid", "tradingEnabled"],
        fields: &[
            Field {
                key: "subaccountUid",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "tradingEnabled",
                kind: "boolean",
                required: true,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "delete_spot_export_report",
        path: "/0/private/RemoveExport",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["id", "type"],
        fields: &[
            Field {
                key: "id",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "type",
                kind: "string",
                required: true,
                values: &["cancel", "delete"],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_spot_export_status",
        path: "/0/private/ExportStatus",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["report"],
        fields: &[Field {
            key: "report",
            kind: "string",
            required: true,
            values: &["trades", "ledgers"],
            minimum: 0,
        }],
        symbol_key: None,
    },
    Endpoint {
        name: "request_spot_export_report",
        path: "/0/private/AddExport",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &[
            "report",
            "format",
            "description",
            "fields",
            "starttm",
            "endtm",
        ],
        fields: &[
            Field {
                key: "report",
                kind: "string",
                required: true,
                values: &["trades", "ledgers"],
                minimum: 0,
            },
            Field {
                key: "format",
                kind: "string",
                required: false,
                values: &["CSV", "TSV"],
                minimum: 0,
            },
            Field {
                key: "description",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "fields",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "starttm",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "endtm",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "simulate_futures_portfolio",
        path: "/derivatives/api/v3/portfolio-margining/simulate",
        method: HttpMethod::Post,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &["json"],
        fields: &[Field {
            key: "json",
            kind: "string",
            required: true,
            values: &[],
            minimum: 0,
        }],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_market_analytics",
        path: "/api/charts/v1/analytics/{symbol}/{analytics_type}",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: true,
        allowed: &["symbol", "analytics_type", "since", "interval", "to"],
        fields: &[
            Field {
                key: "symbol",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "analytics_type",
                kind: "string",
                required: true,
                values: &[
                    "open-interest",
                    "aggressor-differential",
                    "trade-volume",
                    "trade-count",
                    "liquidation-volume",
                    "rolling-volatility",
                    "long-short-ratio",
                    "long-short-info",
                    "cvd",
                    "top-traders",
                    "orderbook",
                    "spreads",
                    "liquidity",
                    "slippage",
                    "future-basis",
                    "funding",
                ],
                minimum: 0,
            },
            Field {
                key: "since",
                kind: "integer",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "interval",
                kind: "integer",
                required: true,
                values: &[
                    "60", "300", "900", "1800", "3600", "14400", "43200", "86400", "604800",
                ],
                minimum: 0,
            },
            Field {
                key: "to",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "check_futures_api_key",
        path: "/api/auth/v1/api-keys/v3/check",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[],
        fields: &[],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_ticker",
        path: "/derivatives/api/v3/tickers/{symbol}",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: true,
        allowed: &["symbol"],
        fields: &[Field {
            key: "symbol",
            kind: "string",
            required: true,
            values: &[],
            minimum: 0,
        }],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_pnl_preferences",
        path: "/derivatives/api/v3/pnlpreferences",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[],
        fields: &[],
        symbol_key: None,
    },
    Endpoint {
        name: "set_futures_pnl_preference",
        path: "/derivatives/api/v3/pnlpreferences",
        method: HttpMethod::Put,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &["symbol", "pnlPreference"],
        fields: &[
            Field {
                key: "symbol",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "pnlPreference",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "create_spot_subaccount",
        path: "/0/private/CreateSubaccount",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["username", "email"],
        fields: &[
            Field {
                key: "username",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "email",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_subaccounts",
        path: "/derivatives/api/v3/subaccounts",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[],
        fields: &[],
        symbol_key: None,
    },
    Endpoint {
        name: "get_spot_post_trade_data",
        path: "/0/public/PostTrade",
        method: HttpMethod::Get,
        auth: KrakenAuth::Spot,
        public: true,
        allowed: &["symbol", "from_ts", "to_ts", "count"],
        fields: &[
            Field {
                key: "symbol",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "from_ts",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "to_ts",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "count",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 1,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_spot_pre_trade_data",
        path: "/0/public/PreTrade",
        method: HttpMethod::Get,
        auth: KrakenAuth::Spot,
        public: true,
        allowed: &["symbol"],
        fields: &[Field {
            key: "symbol",
            kind: "string",
            required: true,
            values: &[],
            minimum: 0,
        }],
        symbol_key: None,
    },
];
