//! Every generated optional-parameter setter writes its value under the documented key,
//! and the list below matches the generated block in `mod.rs`.

use super::{ExchangeMethodFuture, ExchangeMethodRequest, ExchangeMethodRequestClient};

struct Offline;

impl ExchangeMethodRequestClient for Offline {
    fn input_exchange(&self) -> &'static str {
        "binance"
    }
    fn public_request_boxed<'a>(
        &'a self,
        _method_name: &'static str,
        _params: Vec<(String, String)>,
    ) -> ExchangeMethodFuture<'a> {
        unreachable!("setters never send")
    }
    fn private_request_boxed<'a>(
        &'a self,
        _method_name: &'static str,
        _params: Vec<(String, String)>,
    ) -> ExchangeMethodFuture<'a> {
        unreachable!("setters never send")
    }
}

macro_rules! setters {
    ($($name:ident => $key:literal),* $(,)?) => {
        vec![$((
            stringify!($name),
            $key,
            ExchangeMethodRequest::public(&Offline, "setter_check", Vec::new()).$name("1").params,
        )),*]
    };
}

#[test]
fn every_setter_writes_its_key() {
    let checked = setters![
        account => "account",
        account_index => "account_index",
        account_type => "accountType",
        aclass => "aclass",
        activate_price => "activatePrice",
        activation_price => "activationPrice",
        active_only => "active_only",
        after => "after",
        aggregate => "aggregate",
        aggregate_by_time => "aggregateByTime",
        algo_id => "algoId",
        algo_type => "algoType",
        allow_max_time_window => "allowMaxTimeWindow",
        amount => "amount",
        api_key => "apiKey",
        api_key_index => "api_key_index",
        ask_filter => "ask_filter",
        asset => "asset",
        asset_id => "asset_id",
        auth => "auth",
        authorization => "authorization",
        auto_borrow_repay => "autoBorrowRepay",
        auto_close_type => "autoCloseType",
        auto_cxl => "autoCxl",
        auto_lend => "autoLend",
        auto_lend_redeem => "autoLendRedeem",
        auto_repay => "auto_repay",
        ban_amend => "banAmend",
        bar => "bar",
        base_coin => "baseCoin",
        bbo => "bbo",
        before => "before",
        begin => "begin",
        between_timestamps => "between_timestamps",
        builder_address => "builder_address",
        business_type => "businessType",
        callback_rate => "callbackRate",
        cancel_after => "cancelAfter",
        cancel_client_order_id => "cancelClientOrderId",
        cancel_order_id => "cancelOrderId",
        cancel_restrictions => "cancelRestrictions",
        category => "category",
        ccy => "ccy",
        chain => "chain",
        cl_t_req_id => "clTReqId",
        cli_ord_id => "cliOrdId",
        cli_ord_ids => "cliOrdIds",
        client_algo_id => "clientAlgoId",
        client_id => "clientId",
        client_oid => "clientOid",
        client_order_id_list => "clientOrderIdList",
        client_strategy_id => "clientStrategyId",
        client_timestamp => "clientTimestamp",
        client_tran_id => "clientTranId",
        cloid => "cloid",
        close => "close",
        close_on_trigger => "closeOnTrigger",
        close_order => "closeOrder",
        close_position => "closePosition",
        closetime => "closetime",
        code => "code",
        coin => "coin",
        consolidate_taker => "consolidate_taker",
        consolidation => "consolidation",
        contract => "contract",
        contract_type => "contractType",
        count => "count",
        country => "country",
        ct_type => "ctType",
        currencies => "currencies",
        currency => "currency",
        current => "current",
        current_page => "currentPage",
        cursor => "cursor",
        cxl_on_fail => "cxlOnFail",
        deadline => "deadline",
        delta_limit => "deltaLimit",
        dep_id => "depId",
        depth => "depth",
        dex => "dex",
        docalcs => "docalcs",
        enabled => "enabled",
        end => "end",
        end_at => "endAt",
        end_timestamp => "end_timestamp",
        exclude_platform => "excludePlatform",
        expire_after => "expiresAfter",
        expires_after => "expiresAfter",
        expired => "expired",
        expiretm => "expiretm",
        external_oid => "externalOid",
        fee_info => "fee_info",
        fee_ten_bp => "fee_ten_bp",
        filter => "filter",
        force => "force",
        from_ => "from",
        from_account => "fromAccount",
        from_id => "fromId",
        from_symbol => "fromSymbol",
        from_time => "from_time",
        from_type => "fromType",
        from_user_id => "fromUserId",
        from_wd_id => "fromWdId",
        funds => "funds",
        good_till_date => "goodTillDate",
        grouping => "grouping",
        hidden => "hidden",
        hold_side => "holdSide",
        iceberg => "iceberg",
        id => "id",
        id_less_than => "idLessThan",
        ignore_transfers => "ignore_transfers",
        info => "info",
        inst_family => "instFamily",
        inst_type => "instType",
        integrator_account_index => "integrator_account_index",
        integrator_maker_fee => "integrator_maker_fee",
        integrator_taker_fee => "integrator_taker_fee",
        interval => "interval",
        is_leverage => "isLeverage",
        is_market => "isMarket",
        last_fill_time => "lastFillTime",
        last_time => "lastTime",
        leverage => "leverage",
        limit => "limit",
        limit_price => "limitPrice",
        loan_trans => "loanTrans",
        long_leverage => "longLeverage",
        margin_coin => "marginCoin",
        margin_mode => "marginMode",
        market => "market",
        market_id => "market_id",
        market_unit => "marketUnit",
        max_chase_offset => "maxChaseOffset",
        max_chase_offset_type => "maxChaseOffsetType",
        member_id => "memberId",
        mgn_ccy => "mgnCcy",
        mgn_mode => "mgnMode",
        mode => "mode",
        month => "month",
        need_btc_valuation => "needBtcValuation",
        network => "network",
        new_client_order_id => "newClientOrderId",
        new_order_resp_type => "newOrderRespType",
        new_px => "newPx",
        new_px_usd => "newPxUsd",
        new_px_vol => "newPxVol",
        new_sz => "newSz",
        nonce => "nonce",
        notional => "notional",
        offset => "offset",
        oflags => "oflags",
        ofs => "ofs",
        ord_id => "ordId",
        ord_type => "ordType",
        order => "order",
        order_expiry => "order_expiry",
        order_filter => "orderFilter",
        order_id_list => "orderIdList",
        order_ids => "orderIds",
        order_index => "order_index",
        order_iv => "orderIv",
        order_link_id => "orderLinkId",
        order_type => "order_type",
        orig_client_order_id => "origClientOrderId",
        orig_client_order_id_list => "origClientOrderIdList",
        page => "page",
        page_index => "pageIndex",
        page_no => "pageNo",
        pair => "pair",
        path => "path",
        peg_offset_value => "pegOffsetValue",
        peg_price_type => "pegPriceType",
        period => "period",
        pnl => "pnl",
        pos_side => "posSide",
        position_idx => "positionIdx",
        position_mode => "positionMode",
        position_side => "positionSide",
        position_type => "positionType",
        post_only => "postOnly",
        price => "price",
        price2 => "price2",
        price_limit => "priceLimit",
        price_match => "priceMatch",
        price_protect => "priceProtect",
        price_protection => "price_protection",
        price_rate => "priceRate",
        price_type => "priceType",
        process => "process",
        product_symbol => "product_symbol",
        product_symbols => "product_symbols",
        product_type => "productType",
        px => "px",
        px_usd => "pxUsd",
        px_vol => "pxVol",
        qty => "qty",
        qty_limit => "qtyLimit",
        quantity => "quantity",
        quote_asset => "quoteAsset",
        quote_order_qty => "quoteOrderQty",
        quote_quantity => "quoteQuantity",
        rebase_multiplier => "rebase_multiplier",
        recv_window => "recvWindow",
        remark => "remark",
        req_id => "reqId",
        reverse => "reverse",
        role => "role",
        self_trade_prevention => "selfTradePrevention",
        self_trade_prevention_mode => "selfTradePreventionMode",
        set_timestamp_to_end => "set_timestamp_to_end",
        settle_coin => "settleCoin",
        short_leverage => "shortLeverage",
        side => "side",
        since => "since",
        size => "size",
        skip_ask_order_id => "skip_ask_order_id",
        skip_bid_order_id => "skip_bid_order_id",
        skip_nonce => "skip_nonce",
        sl_limit_price => "slLimitPrice",
        sl_order_type => "slOrderType",
        sl_trigger_by => "slTriggerBy",
        sort_dir => "sort_dir",
        sort_direction => "sortDirection",
        source => "source",
        source_wallet => "sourceWallet",
        start => "start",
        start_at => "startAt",
        start_timestamp => "start_timestamp",
        starttm => "starttm",
        state => "state",
        states => "states",
        stats_end_timestamp => "stats_end_timestamp",
        stats_start_timestamp => "stats_start_timestamp",
        status => "status",
        stop => "stop",
        stop_guaranteed => "stopGuaranteed",
        stop_loss => "stopLoss",
        stop_loss_price => "stopLossPrice",
        stop_price => "stopPrice",
        stop_price_type => "stopPriceType",
        stp => "stp",
        strategy_id => "strategyId",
        sub_acct => "subAcct",
        sub_type => "subType",
        subaccount_id => "subaccountId",
        symbol => "symbol",
        symbol_status => "symbolStatus",
        symbols => "symbols",
        sz => "sz",
        tag => "tag",
        tags => "tags",
        take_profit => "takeProfit",
        take_profit_price => "takeProfitPrice",
        td_mode => "tdMode",
        tgt_ccy => "tgtCcy",
        tick_type => "tick_type",
        tier => "tier",
        tier_id => "tierId",
        tif => "tif",
        time => "time",
        timeinforce => "timeinforce",
        to => "to",
        to_account => "toAccount",
        to_account_index => "to_account_index",
        to_account_type => "toAccountType",
        to_symbol => "toSymbol",
        to_time => "to_time",
        to_user_id => "toUserId",
        tp_limit_price => "tpLimitPrice",
        tp_order_type => "tpOrderType",
        tp_trigger_by => "tpTriggerBy",
        tpsl => "tpsl",
        tpsl_mode => "tpslMode",
        tpsl_type => "tpslType",
        trade_side => "tradeSide",
        trade_type => "trade_type",
        trade_types => "tradeTypes",
        trades => "trades",
        tran_id => "tranId",
        trans_id => "transId",
        transfer_type => "transfer_type",
        trigger_by => "triggerBy",
        trigger_direction => "triggerDirection",
        trigger_px => "triggerPx",
        trigger_signal => "triggerSignal",
        tx_id => "txId",
        txid => "txid",
        uly => "uly",
        userref => "userref",
        validate => "validate",
        value => "value",
        value_limit => "valueLimit",
        vault_address => "vaultAddress",
        vip_level => "vipLevel",
        visible_size => "visibleSize",
        wd_id => "wdId",
        without_count => "without_count",
        working_type => "workingType",
    ];
    for (name, key, params) in &checked {
        assert_eq!(params, &vec![(key.to_string(), "1".to_string())], "{name}");
    }
    let source = include_str!("mod.rs");
    let block = &source[source.find("BEGIN GENERATED OPTIONAL").expect("start")
        ..source.find("END GENERATED OPTIONAL").expect("end")];
    let declared: Vec<&str> = block
        .split("pub fn ")
        .skip(1)
        .map(|chunk| &chunk[..chunk.find('(').expect("signature")])
        .collect();
    let listed: Vec<&str> = checked.iter().map(|(name, _, _)| *name).collect();
    assert_eq!(listed, declared, "setter list is stale");
}
