//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "get_futures_account_config",
        market: BinanceMarket::Futures,
        symbol_market: BinanceMarket::Futures,
        method: HttpMethod::Get,
        path: "/fapi/v1/accountConfig",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_futures_trading_status",
        market: BinanceMarket::Futures,
        symbol_market: BinanceMarket::Futures,
        method: HttpMethod::Get,
        path: "/fapi/v1/apiTradingStatus",
        public: false,
        api_key: false,
        allowed: &["symbol", "recvWindow", "product_symbol"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_futures_adl_quantiles",
        market: BinanceMarket::Futures,
        symbol_market: BinanceMarket::Futures,
        method: HttpMethod::Get,
        path: "/fapi/v1/adlQuantile",
        public: false,
        api_key: false,
        allowed: &["symbol", "recvWindow", "product_symbol"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_account_trading_status",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/account/apiTradingStatus",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_account_status",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/account/status",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_user_assets",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v3/asset/getUserAsset",
        public: false,
        api_key: false,
        allowed: &["asset", "needBtcValuation", "recvWindow"],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "needBtcValuation",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_network_config",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/capital/config/getall",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_futures_bnb_burn_status",
        market: BinanceMarket::Futures,
        symbol_market: BinanceMarket::Futures,
        method: HttpMethod::Get,
        path: "/fapi/v1/feeBurn",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_futures_download_id_for_futures_transaction_history",
        market: BinanceMarket::Futures,
        symbol_market: BinanceMarket::Futures,
        method: HttpMethod::Get,
        path: "/fapi/v1/income/asyn",
        public: false,
        api_key: false,
        allowed: &["startTime", "endTime", "recvWindow"],
        fields: &[
            Field {
                key: "startTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_futures_futures_transaction_history_download_link_by_id",
        market: BinanceMarket::Futures,
        symbol_market: BinanceMarket::Futures,
        method: HttpMethod::Get,
        path: "/fapi/v1/income/asyn/id",
        public: false,
        api_key: false,
        allowed: &["downloadId", "recvWindow"],
        fields: &[
            Field {
                key: "downloadId",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "futures_futures_tradfi_perps_contract",
        market: BinanceMarket::Futures,
        symbol_market: BinanceMarket::Futures,
        method: HttpMethod::Post,
        path: "/fapi/v1/stock/contract",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "spot_my_filters",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/api/v3/myFilters",
        public: false,
        api_key: false,
        allowed: &["symbol", "recvWindow"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'd',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "pm_pro_fund_auto_collection",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/portfolio/auto-collection",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "pm_pro_fund_collection_by_asset",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/portfolio/asset-collection",
        public: false,
        api_key: false,
        allowed: &["asset", "recvWindow"],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_pm_pro_delta_mode_status",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/portfolio/delta-mode",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "pm_pro_switch_delta_mode",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/portfolio/delta-mode",
        public: false,
        api_key: false,
        allowed: &["deltaEnabled", "recvWindow"],
        fields: &[
            Field {
                key: "deltaEnabled",
                kind: 's',
                required: true,
                choices: &["true", "false"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "fetch_address_verification_list",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/addressVerify/list",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "change_auto_compound_status",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/dci/product/auto_compound/edit-status",
        public: false,
        api_key: false,
        allowed: &["positionId", "autoCompoundPlan", "recvWindow"],
        fields: &[
            Field {
                key: "positionId",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "autoCompoundPlan",
                kind: 's',
                required: true,
                choices: &["NONE", "STANDARD", "ADVANCED"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "check_dual_investment_accounts",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/dci/product/accounts",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "subscribe_dual_investment_products",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/dci/product/subscribe",
        public: false,
        api_key: false,
        allowed: &[
            "id",
            "orderId",
            "depositAmount",
            "autoCompoundPlan",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "id",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "orderId",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "depositAmount",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "autoCompoundPlan",
                kind: 's',
                required: true,
                choices: &["NONE", "STANDARD", "ADVANCED"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_bfusd_account",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/bfusd/account",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_bfusd_quota_details",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/bfusd/quota",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_bfusd_rewards_history",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/bfusd/history/rewardsHistory",
        public: false,
        api_key: false,
        allowed: &["startTime", "endTime", "current", "size", "recvWindow"],
        fields: &[
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "current",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "size",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_bfusd_subscription_history",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/bfusd/history/subscriptionHistory",
        public: false,
        api_key: false,
        allowed: &[
            "asset",
            "startTime",
            "endTime",
            "current",
            "size",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: false,
                choices: &["USDC", "USDT"],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "current",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "size",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "redeem_bfusd",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/bfusd/redeem",
        public: false,
        api_key: false,
        allowed: &["amount", "type", "recvWindow"],
        fields: &[
            Field {
                key: "amount",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "type",
                kind: 's',
                required: true,
                choices: &["FAST", "STANDARD"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "subscribe_bfusd",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/bfusd/subscribe",
        public: false,
        api_key: false,
        allowed: &["asset", "amount", "recvWindow"],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "amount",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_collateral_record",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/simple-earn/flexible/history/collateralRecord",
        public: false,
        api_key: false,
        allowed: &[
            "productId",
            "startTime",
            "endTime",
            "current",
            "size",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "productId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "current",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "size",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_flexible_personal_left_quota",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/simple-earn/flexible/personalLeftQuota",
        public: false,
        api_key: false,
        allowed: &["productId", "recvWindow"],
        fields: &[
            Field {
                key: "productId",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_flexible_subscription_preview",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/simple-earn/flexible/subscriptionPreview",
        public: false,
        api_key: false,
        allowed: &["productId", "amount", "recvWindow"],
        fields: &[
            Field {
                key: "productId",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "amount",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_locked_personal_left_quota",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/simple-earn/locked/personalLeftQuota",
        public: false,
        api_key: false,
        allowed: &["projectId", "recvWindow"],
        fields: &[
            Field {
                key: "projectId",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_locked_subscription_preview",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/simple-earn/locked/subscriptionPreview",
        public: false,
        api_key: false,
        allowed: &["projectId", "amount", "autoSubscribe", "recvWindow"],
        fields: &[
            Field {
                key: "projectId",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "amount",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "autoSubscribe",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "set_flexible_auto_subscribe",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/simple-earn/flexible/setAutoSubscribe",
        public: false,
        api_key: false,
        allowed: &["productId", "autoSubscribe", "recvWindow"],
        fields: &[
            Field {
                key: "productId",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "autoSubscribe",
                kind: 'b',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "set_locked_auto_subscribe",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/simple-earn/locked/setAutoSubscribe",
        public: false,
        api_key: false,
        allowed: &["positionId", "autoSubscribe", "recvWindow"],
        fields: &[
            Field {
                key: "positionId",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "autoSubscribe",
                kind: 'b',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_rwusd_account",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/rwusd/account",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_rwusd_quota_details",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/rwusd/quota",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_rwusd_rewards_history",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/rwusd/history/rewardsHistory",
        public: false,
        api_key: false,
        allowed: &["startTime", "endTime", "current", "size", "recvWindow"],
        fields: &[
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "current",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "size",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_rwusd_subscription_history",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/rwusd/history/subscriptionHistory",
        public: false,
        api_key: false,
        allowed: &[
            "asset",
            "startTime",
            "endTime",
            "current",
            "size",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: false,
                choices: &["USDC", "USDT"],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "current",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "size",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "redeem_rwusd",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/rwusd/redeem",
        public: false,
        api_key: false,
        allowed: &["amount", "type", "recvWindow"],
        fields: &[
            Field {
                key: "amount",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "type",
                kind: 's',
                required: true,
                choices: &["FAST", "STANDARD"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "subscribe_rwusd",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/rwusd/subscribe",
        public: false,
        api_key: false,
        allowed: &["asset", "amount", "recvWindow"],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: true,
                choices: &["USDT", "USDC"],
            },
            Field {
                key: "amount",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
];
