//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "get_api_key_permissions",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/account/apiRestrictions",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "create_margin_special_key",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/margin/apiKey",
        public: false,
        api_key: false,
        allowed: &[
            "apiName",
            "symbol",
            "ip",
            "publicKey",
            "permissionMode",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "apiName",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "ip",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "publicKey",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "permissionMode",
                kind: 's',
                required: false,
                choices: &["TRADE", "READ"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "delete_margin_special_key",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Delete,
        path: "/sapi/v1/margin/apiKey",
        public: false,
        api_key: false,
        allowed: &["apiName", "symbol", "recvWindow"],
        fields: &[
            Field {
                key: "apiName",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "edit_margin_ip_for_special_key",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Put,
        path: "/sapi/v1/margin/apiKey/ip",
        public: false,
        api_key: false,
        allowed: &["ip", "symbol", "recvWindow"],
        fields: &[
            Field {
                key: "ip",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_margin_special_key",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/apiKey",
        public: false,
        api_key: false,
        allowed: &["symbol", "recvWindow"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_margin_special_key_list",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/api-key-list",
        public: false,
        api_key: false,
        allowed: &["symbol", "recvWindow"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
];
