//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "get_coin_futures_income_history",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/income",
        public: false,
        api_key: false,
        allowed: &[
            "symbol",
            "incomeType",
            "startTime",
            "endTime",
            "page",
            "limit",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "incomeType",
                kind: 's',
                required: false,
                choices: &[
                    "TRANSFER",
                    "WELCOME_BONUS",
                    "FUNDING_FEE",
                    "REALIZED_PNL",
                    "COMMISSION",
                    "INSURANCE_CLEAR",
                    "DELIVERED_SETTELMENT",
                ],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "page",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_commission_rate",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/commissionRate",
        public: false,
        api_key: false,
        allowed: &["symbol", "recvWindow"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_aggregate_trades",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/aggTrades",
        public: true,
        api_key: false,
        allowed: &["symbol", "fromId", "startTime", "endTime", "limit"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "fromId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_continuous_klines",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/continuousKlines",
        public: true,
        api_key: false,
        allowed: &[
            "pair",
            "contractType",
            "interval",
            "startTime",
            "endTime",
            "limit",
        ],
        fields: &[
            Field {
                key: "pair",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "contractType",
                kind: 's',
                required: true,
                choices: &["PERPETUAL", "CURRENT_QUARTER", "NEXT_QUARTER"],
            },
            Field {
                key: "interval",
                kind: 's',
                required: true,
                choices: &[
                    "1m", "3m", "5m", "15m", "30m", "1h", "2h", "4h", "6h", "8h", "12h", "1d",
                    "3d", "1w", "1M",
                ],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_funding_info",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/fundingInfo",
        public: true,
        api_key: false,
        allowed: &[],
        fields: &[],
    },
    Endpoint {
        name: "get_coin_futures_index_price_klines",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/indexPriceKlines",
        public: true,
        api_key: false,
        allowed: &["pair", "interval", "startTime", "endTime", "limit"],
        fields: &[
            Field {
                key: "pair",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "interval",
                kind: 's',
                required: true,
                choices: &[
                    "1m", "3m", "5m", "15m", "30m", "1h", "2h", "4h", "6h", "8h", "12h", "1d",
                    "3d", "1w", "1M",
                ],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_mark_price_klines",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/markPriceKlines",
        public: true,
        api_key: false,
        allowed: &["symbol", "interval", "startTime", "endTime", "limit"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "interval",
                kind: 's',
                required: true,
                choices: &[
                    "1m", "3m", "5m", "15m", "30m", "1h", "2h", "4h", "6h", "8h", "12h", "1d",
                    "3d", "1w", "1M",
                ],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_open_interest",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/openInterest",
        public: true,
        api_key: false,
        allowed: &["symbol"],
        fields: &[Field {
            key: "symbol",
            kind: 's',
            required: true,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_coin_futures_premium_index_klines",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/premiumIndexKlines",
        public: true,
        api_key: false,
        allowed: &["symbol", "interval", "startTime", "endTime", "limit"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "interval",
                kind: 's',
                required: true,
                choices: &[
                    "1m", "3m", "5m", "15m", "30m", "1h", "2h", "4h", "6h", "8h", "12h", "1d",
                    "3d", "1w", "1M",
                ],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_book_ticker",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/ticker/bookTicker",
        public: true,
        api_key: false,
        allowed: &["symbol", "pair"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "pair",
                kind: 's',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_24h_ticker",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/ticker/24hr",
        public: true,
        api_key: false,
        allowed: &["symbol", "pair"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "pair",
                kind: 's',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "adjust_coin_futures_position_margin",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Post,
        path: "/dapi/v1/positionMargin",
        public: false,
        api_key: false,
        allowed: &["symbol", "amount", "type", "positionSide", "recvWindow"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "amount",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "type",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "positionSide",
                kind: 's',
                required: false,
                choices: &["BOTH", "LONG", "SHORT"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_adl_quantiles",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/adlQuantile",
        public: false,
        api_key: false,
        allowed: &["symbol", "recvWindow"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_force_orders",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/forceOrders",
        public: false,
        api_key: false,
        allowed: &[
            "symbol",
            "autoCloseType",
            "startTime",
            "endTime",
            "limit",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "autoCloseType",
                kind: 's',
                required: false,
                choices: &["LIQUIDATION", "ADL"],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_download_id_for_futures_order_history",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/order/asyn",
        public: false,
        api_key: false,
        allowed: &["startTime", "endTime", "recvWindow"],
        fields: &[
            Field {
                key: "startTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_download_id_for_futures_trade_history",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/trade/asyn",
        public: false,
        api_key: false,
        allowed: &["startTime", "endTime", "recvWindow"],
        fields: &[
            Field {
                key: "startTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_download_id_for_futures_transaction_history",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/income/asyn",
        public: false,
        api_key: false,
        allowed: &["startTime", "endTime", "recvWindow"],
        fields: &[
            Field {
                key: "startTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_futures_order_history_download_link_by_id",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/order/asyn/id",
        public: false,
        api_key: false,
        allowed: &["downloadId", "recvWindow"],
        fields: &[
            Field {
                key: "downloadId",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_futures_trade_download_link_by_id",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/trade/asyn/id",
        public: false,
        api_key: false,
        allowed: &["downloadId", "recvWindow"],
        fields: &[
            Field {
                key: "downloadId",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_futures_transaction_history_download_link_by_id",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/income/asyn/id",
        public: false,
        api_key: false,
        allowed: &["downloadId", "recvWindow"],
        fields: &[
            Field {
                key: "downloadId",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "coin_futures_old_trades_lookup",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/historicalTrades",
        public: true,
        api_key: true,
        allowed: &["symbol", "limit", "fromId"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "fromId",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_coin_futures_index_price_constituents",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/constituents",
        public: true,
        api_key: false,
        allowed: &["symbol"],
        fields: &[Field {
            key: "symbol",
            kind: 's',
            required: true,
            choices: &[],
        }],
    },
    Endpoint {
        name: "coin_futures_taker_buy_sell_volume",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/futures/data/takerBuySellVol",
        public: true,
        api_key: false,
        allowed: &[
            "pair",
            "contractType",
            "period",
            "limit",
            "startTime",
            "endTime",
        ],
        fields: &[
            Field {
                key: "pair",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "contractType",
                kind: 's',
                required: true,
                choices: &["ALL", "PERPETUAL", "CURRENT_QUARTER", "NEXT_QUARTER"],
            },
            Field {
                key: "period",
                kind: 's',
                required: true,
                choices: &["5m", "15m", "30m", "1h", "2h", "4h", "6h", "12h", "1d"],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "coin_futures_test_connectivity",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/ping",
        public: true,
        api_key: false,
        allowed: &[],
        fields: &[],
    },
    Endpoint {
        name: "get_coin_futures_order_modify_history",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/orderAmendment",
        public: false,
        api_key: false,
        allowed: &[
            "symbol",
            "orderId",
            "origClientOrderId",
            "startTime",
            "endTime",
            "limit",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "orderId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "origClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_coin_futures_position_margin_change_history",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/positionMargin/history",
        public: false,
        api_key: false,
        allowed: &[
            "symbol",
            "type",
            "startTime",
            "endTime",
            "limit",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "type",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_coin_futures_current_open_order",
        market: BinanceMarket::CoinFutures,
        symbol_market: BinanceMarket::CoinFutures,
        method: HttpMethod::Get,
        path: "/dapi/v1/openOrder",
        public: false,
        api_key: false,
        allowed: &["symbol", "orderId", "origClientOrderId", "recvWindow"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "orderId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "origClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
];
