//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "futures_accept_the_offered_quote",
        market: BinanceMarket::Futures,
        symbol_market: BinanceMarket::Futures,
        method: HttpMethod::Post,
        path: "/fapi/v1/convert/acceptQuote",
        public: false,
        api_key: false,
        allowed: &["quoteId", "recvWindow"],
        fields: &[
            Field {
                key: "quoteId",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "futures_list_all_convert_pairs",
        market: BinanceMarket::Futures,
        symbol_market: BinanceMarket::Futures,
        method: HttpMethod::Get,
        path: "/fapi/v1/convert/exchangeInfo",
        public: true,
        api_key: false,
        allowed: &["fromAsset", "toAsset"],
        fields: &[
            Field {
                key: "fromAsset",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "toAsset",
                kind: 's',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "futures_order_status",
        market: BinanceMarket::Futures,
        symbol_market: BinanceMarket::Futures,
        method: HttpMethod::Get,
        path: "/fapi/v1/convert/orderStatus",
        public: false,
        api_key: false,
        allowed: &["orderId", "quoteId"],
        fields: &[
            Field {
                key: "orderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "quoteId",
                kind: 's',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "futures_send_quote_request",
        market: BinanceMarket::Futures,
        symbol_market: BinanceMarket::Futures,
        method: HttpMethod::Post,
        path: "/fapi/v1/convert/getQuote",
        public: false,
        api_key: false,
        allowed: &[
            "fromAsset",
            "toAsset",
            "fromAmount",
            "toAmount",
            "validTime",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "fromAsset",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "toAsset",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "fromAmount",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "toAmount",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "validTime",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "wallet_dust_convert",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/asset/dust-convert/convert",
        public: false,
        api_key: false,
        allowed: &[
            "asset",
            "accountType",
            "clientId",
            "targetAsset",
            "thirdPartyClientId",
            "dustQuotaAssetToTargetAssetPrice",
        ],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "accountType",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "clientId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "targetAsset",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "thirdPartyClientId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "dustQuotaAssetToTargetAssetPrice",
                kind: 'd',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "wallet_dust_convertible_assets",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/asset/dust-convert/query-convertible-assets",
        public: false,
        api_key: false,
        allowed: &[
            "targetAsset",
            "accountType",
            "dustQuotaAssetToTargetAssetPrice",
        ],
        fields: &[
            Field {
                key: "targetAsset",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "accountType",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "dustQuotaAssetToTargetAssetPrice",
                kind: 'd',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "wallet_dustlog",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/asset/dribblet",
        public: false,
        api_key: false,
        allowed: &["accountType", "startTime", "endTime", "recvWindow"],
        fields: &[
            Field {
                key: "accountType",
                kind: 's',
                required: false,
                choices: &["SPOT", "MARGIN"],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_wallet_assets_that_can_be_converted_into_bnb",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/asset/dust-btc",
        public: false,
        api_key: false,
        allowed: &["accountType", "recvWindow"],
        fields: &[
            Field {
                key: "accountType",
                kind: 's',
                required: false,
                choices: &["SPOT", "MARGIN"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
];
