//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "get_deposit_address",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/capital/deposit/address",
        public: false,
        api_key: false,
        allowed: &["coin", "network", "amount", "recvWindow"],
        fields: &[
            Field {
                key: "coin",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "network",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "amount",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_deposit_history",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/capital/deposit/hisrec",
        public: false,
        api_key: false,
        allowed: &[
            "includeSource",
            "coin",
            "status",
            "startTime",
            "endTime",
            "offset",
            "limit",
            "recvWindow",
            "txId",
        ],
        fields: &[
            Field {
                key: "includeSource",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "coin",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "status",
                kind: 'i',
                required: false,
                choices: &["0", "1", "2", "6", "7", "8"],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "offset",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "txId",
                kind: 's',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "wallet_fetch_deposit_address_list_with_network",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/capital/deposit/address/list",
        public: false,
        api_key: false,
        allowed: &["coin", "network"],
        fields: &[
            Field {
                key: "coin",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "network",
                kind: 's',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "wallet_one_click_arrival_deposit_apply",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/capital/deposit/credit-apply",
        public: false,
        api_key: false,
        allowed: &["depositId", "txId", "subAccountId", "subUserId"],
        fields: &[
            Field {
                key: "depositId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "txId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "subAccountId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "subUserId",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
];
