//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "get_pm_margin_loan_records",
        market: BinanceMarket::PortfolioMargin,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/papi/v1/margin/marginLoan",
        public: false,
        api_key: false,
        allowed: &[
            "asset",
            "txId",
            "startTime",
            "endTime",
            "current",
            "size",
            "archived",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "txId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "current",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "size",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "archived",
                kind: 's',
                required: false,
                choices: &["true", "false"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_pm_margin_repayment_records",
        market: BinanceMarket::PortfolioMargin,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/papi/v1/margin/repayLoan",
        public: false,
        api_key: false,
        allowed: &[
            "asset",
            "txId",
            "startTime",
            "endTime",
            "current",
            "size",
            "archived",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "txId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "current",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "size",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "archived",
                kind: 's',
                required: false,
                choices: &["true", "false"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "change_pm_auto_repay_futures_status",
        market: BinanceMarket::PortfolioMargin,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/papi/v1/repay-futures-switch",
        public: false,
        api_key: false,
        allowed: &["autoRepay", "recvWindow"],
        fields: &[
            Field {
                key: "autoRepay",
                kind: 's',
                required: true,
                choices: &["true", "false"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_pm_auto_repay_futures_status",
        market: BinanceMarket::PortfolioMargin,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/papi/v1/repay-futures-switch",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "repay_pm_futures_negative_balance",
        market: BinanceMarket::PortfolioMargin,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/papi/v1/repay-futures-negative-balance",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "margin_liquidation_loan_repay",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/margin/liquidation-loan/repay",
        public: false,
        api_key: false,
        allowed: &["asset", "amount", "recvWindow"],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "amount",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_margin_liquidation_loan",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/liquidation-loan",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "query_margin_liquidation_loan_repay_history",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/liquidation-loan/repay-history",
        public: false,
        api_key: false,
        allowed: &["startTime", "endTime", "current", "size", "recvWindow"],
        fields: &[
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "current",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "size",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "change_pm_pro_auto_repay_futures_status",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/portfolio/repay-futures-switch",
        public: false,
        api_key: false,
        allowed: &["autoRepay", "recvWindow"],
        fields: &[
            Field {
                key: "autoRepay",
                kind: 's',
                required: true,
                choices: &["true", "false"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_pm_pro_auto_repay_futures_status",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/portfolio/repay-futures-switch",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "pm_pro_portfolio_margin_pro_bankruptcy_loan_repay",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/portfolio/repay",
        public: false,
        api_key: false,
        allowed: &["from", "recvWindow"],
        fields: &[
            Field {
                key: "from",
                kind: 's',
                required: false,
                choices: &["SPOT", "MARGIN"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_pm_pro_portfolio_margin_pro_bankruptcy_loan_amount",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/portfolio/pmLoan",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "query_pm_pro_portfolio_margin_pro_bankruptcy_loan_repay_history",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/portfolio/pmloan-history",
        public: false,
        api_key: false,
        allowed: &["startTime", "endTime", "size", "current", "recvWindow"],
        fields: &[
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "size",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "current",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "repay_pm_pro_futures_negative_balance",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/portfolio/repay-futures-negative-balance",
        public: false,
        api_key: false,
        allowed: &["from", "recvWindow"],
        fields: &[
            Field {
                key: "from",
                kind: 's',
                required: false,
                choices: &["SPOT", "MARGIN"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
];
