//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "disable_isolated_margin_account",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Delete,
        path: "/sapi/v1/margin/isolated/account",
        public: false,
        api_key: false,
        allowed: &["symbol", "recvWindow"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "enable_isolated_margin_account",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/margin/isolated/account",
        public: false,
        api_key: false,
        allowed: &["symbol", "recvWindow"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_futures_multi_assets_mode",
        market: BinanceMarket::Futures,
        symbol_market: BinanceMarket::Futures,
        method: HttpMethod::Get,
        path: "/fapi/v1/multiAssetsMargin",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "set_futures_multi_assets_mode",
        market: BinanceMarket::Futures,
        symbol_market: BinanceMarket::Futures,
        method: HttpMethod::Post,
        path: "/fapi/v1/multiAssetsMargin",
        public: false,
        api_key: false,
        allowed: &["multiAssetsMargin", "recvWindow"],
        fields: &[
            Field {
                key: "multiAssetsMargin",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "adjust_futures_position_margin",
        market: BinanceMarket::Futures,
        symbol_market: BinanceMarket::Futures,
        method: HttpMethod::Post,
        path: "/fapi/v1/positionMargin",
        public: false,
        api_key: false,
        allowed: &[
            "symbol",
            "amount",
            "type",
            "positionSide",
            "recvWindow",
            "product_symbol",
        ],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "amount",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "type",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "positionSide",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_margin_risk_coefficients",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/tradeCoeff",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_margin_capital_flow",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/capital-flow",
        public: false,
        api_key: false,
        allowed: &[
            "asset",
            "symbol",
            "type",
            "startTime",
            "endTime",
            "fromId",
            "limit",
            "recvWindow",
            "product_symbol",
        ],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "type",
                kind: 's',
                required: false,
                choices: &[
                    "TRANSFER",
                    "BORROW",
                    "REPAY",
                    "BUY_INCOME",
                    "BUY_EXPENSE",
                    "SELL_INCOME",
                    "SELL_EXPENSE",
                    "TRADING_COMMISSION",
                    "BUY_LIQUIDATION",
                    "SELL_LIQUIDATION",
                    "REPAY_LIQUIDATION",
                    "OTHER_LIQUIDATION",
                    "LIQUIDATION_FEE",
                    "SMALL_BALANCE_CONVERT",
                    "COMMISSION_RETURN",
                    "SMALL_CONVERT",
                ],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "fromId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_margin_delist_schedule",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/delist-schedule",
        public: true,
        api_key: true,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_margin_liquidation_records",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/forceLiquidationRec",
        public: false,
        api_key: false,
        allowed: &[
            "startTime",
            "endTime",
            "isolatedSymbol",
            "current",
            "size",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "isolatedSymbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "current",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "size",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "cancel_margin_order_list",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Delete,
        path: "/sapi/v1/margin/orderList",
        public: false,
        api_key: false,
        allowed: &[
            "symbol",
            "isIsolated",
            "orderListId",
            "listClientOrderId",
            "newClientOrderId",
            "recvWindow",
            "product_symbol",
        ],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "isIsolated",
                kind: 's',
                required: false,
                choices: &["TRUE", "FALSE"],
            },
            Field {
                key: "orderListId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "listClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "newClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_margin_order_rate_limits",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/rateLimit/order",
        public: false,
        api_key: false,
        allowed: &["isIsolated", "symbol", "recvWindow", "product_symbol"],
        fields: &[
            Field {
                key: "isIsolated",
                kind: 's',
                required: false,
                choices: &["TRUE", "FALSE"],
            },
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_margin_all_order_lists",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/allOrderList",
        public: false,
        api_key: false,
        allowed: &[
            "isIsolated",
            "symbol",
            "fromId",
            "startTime",
            "endTime",
            "limit",
            "recvWindow",
            "product_symbol",
        ],
        fields: &[
            Field {
                key: "isIsolated",
                kind: 's',
                required: false,
                choices: &["TRUE", "FALSE"],
            },
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "fromId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_margin_order_list",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/orderList",
        public: false,
        api_key: false,
        allowed: &[
            "isIsolated",
            "symbol",
            "orderListId",
            "origClientOrderId",
            "recvWindow",
            "product_symbol",
        ],
        fields: &[
            Field {
                key: "isIsolated",
                kind: 's',
                required: false,
                choices: &["TRUE", "FALSE"],
            },
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "orderListId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "origClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_margin_open_order_lists",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/openOrderList",
        public: false,
        api_key: false,
        allowed: &["isIsolated", "symbol", "recvWindow", "product_symbol"],
        fields: &[
            Field {
                key: "isIsolated",
                kind: 's',
                required: false,
                choices: &["TRUE", "FALSE"],
            },
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "close_margin_listen_key",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Delete,
        path: "/sapi/v1/margin/listen-key",
        public: false,
        api_key: true,
        allowed: &[],
        fields: &[],
    },
    Endpoint {
        name: "keep_alive_margin_listen_key",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Put,
        path: "/sapi/v1/margin/listen-key",
        public: false,
        api_key: true,
        allowed: &["listenKey"],
        fields: &[Field {
            key: "listenKey",
            kind: 's',
            required: true,
            choices: &[],
        }],
    },
    Endpoint {
        name: "create_margin_listen_key",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/margin/listen-key",
        public: false,
        api_key: true,
        allowed: &[],
        fields: &[],
    },
    Endpoint {
        name: "place_margin_oto",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/margin/order/oto",
        public: false,
        api_key: false,
        allowed: &[
            "symbol",
            "workingType",
            "workingSide",
            "workingPrice",
            "workingQuantity",
            "workingIcebergQty",
            "pendingType",
            "pendingSide",
            "pendingQuantity",
            "isIsolated",
            "listClientOrderId",
            "newOrderRespType",
            "sideEffectType",
            "selfTradePreventionMode",
            "autoRepayAtCancel",
            "workingClientOrderId",
            "workingTimeInForce",
            "pendingClientOrderId",
            "pendingPrice",
            "pendingStopPrice",
            "pendingTrailingDelta",
            "pendingIcebergQty",
            "pendingTimeInForce",
            "product_symbol",
        ],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "workingType",
                kind: 's',
                required: true,
                choices: &["LIMIT", "LIMIT_MAKER"],
            },
            Field {
                key: "workingSide",
                kind: 's',
                required: true,
                choices: &["BUY", "SELL"],
            },
            Field {
                key: "workingPrice",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "workingQuantity",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "workingIcebergQty",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "pendingType",
                kind: 's',
                required: true,
                choices: &[
                    "LIMIT",
                    "MARKET",
                    "STOP_LOSS",
                    "STOP_LOSS_LIMIT",
                    "TAKE_PROFIT",
                    "TAKE_PROFIT_LIMIT",
                    "LIMIT_MAKER",
                ],
            },
            Field {
                key: "pendingSide",
                kind: 's',
                required: true,
                choices: &["BUY", "SELL"],
            },
            Field {
                key: "pendingQuantity",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "isIsolated",
                kind: 's',
                required: false,
                choices: &["TRUE", "FALSE"],
            },
            Field {
                key: "listClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "newOrderRespType",
                kind: 's',
                required: false,
                choices: &["ACK", "RESULT", "FULL"],
            },
            Field {
                key: "sideEffectType",
                kind: 's',
                required: false,
                choices: &["NO_SIDE_EFFECT", "MARGIN_BUY", "AUTO_BORROW_REPAY"],
            },
            Field {
                key: "selfTradePreventionMode",
                kind: 's',
                required: false,
                choices: &["EXPIRE_TAKER", "EXPIRE_MAKER", "EXPIRE_BOTH", "NONE"],
            },
            Field {
                key: "autoRepayAtCancel",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "workingClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "workingTimeInForce",
                kind: 's',
                required: false,
                choices: &["GTC", "IOC", "FOK"],
            },
            Field {
                key: "pendingClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingPrice",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingStopPrice",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingTrailingDelta",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingIcebergQty",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingTimeInForce",
                kind: 's',
                required: false,
                choices: &["GTC", "IOC", "FOK"],
            },
        ],
    },
    Endpoint {
        name: "get_futures_position_margin_change_history",
        market: BinanceMarket::Futures,
        symbol_market: BinanceMarket::Futures,
        method: HttpMethod::Get,
        path: "/fapi/v1/positionMargin/history",
        public: false,
        api_key: false,
        allowed: &[
            "symbol",
            "type",
            "startTime",
            "endTime",
            "limit",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "type",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "adjust_margin_cross_margin_max_leverage",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/margin/max-leverage",
        public: false,
        api_key: false,
        allowed: &["maxLeverage"],
        fields: &[Field {
            key: "maxLeverage",
            kind: 'i',
            required: true,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_margin_bnb_burn_status",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/bnbBurn",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "query_margin_cross_margin_fee_data",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/crossMarginData",
        public: false,
        api_key: false,
        allowed: &["vipLevel", "coin", "recvWindow"],
        fields: &[
            Field {
                key: "vipLevel",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "coin",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_margin_enabled_isolated_margin_account_limit",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/isolated/accountLimit",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "query_margin_isolated_margin_fee_data",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/isolatedMarginData",
        public: false,
        api_key: false,
        allowed: &["vipLevel", "symbol", "recvWindow"],
        fields: &[
            Field {
                key: "vipLevel",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_margin_future_hourly_interest_rate",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/next-hourly-interest-rate",
        public: false,
        api_key: false,
        allowed: &["assets", "isIsolated"],
        fields: &[
            Field {
                key: "assets",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "isIsolated",
                kind: 's',
                required: true,
                choices: &["TRUE", "FALSE"],
            },
        ],
    },
    Endpoint {
        name: "query_margin_margin_interest_rate_history",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/interestRateHistory",
        public: false,
        api_key: false,
        allowed: &["asset", "vipLevel", "startTime", "endTime", "recvWindow"],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "vipLevel",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "margin_cross_margin_collateral_ratio",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/crossMarginCollateralRatio",
        public: true,
        api_key: true,
        allowed: &[],
        fields: &[],
    },
    Endpoint {
        name: "get_margin_limit_price_pairs",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/limit-price-pairs",
        public: true,
        api_key: true,
        allowed: &[],
        fields: &[],
    },
    Endpoint {
        name: "get_margin_list_schedule",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/list-schedule",
        public: true,
        api_key: true,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_margin_margin_asset_risk_based_liquidation_ratio",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/risk-based-liquidation-ratio",
        public: true,
        api_key: true,
        allowed: &[],
        fields: &[],
    },
    Endpoint {
        name: "get_margin_margin_restricted_assets",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/restricted-asset",
        public: true,
        api_key: true,
        allowed: &[],
        fields: &[],
    },
    Endpoint {
        name: "query_margin_isolated_margin_tier_data",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/isolatedMarginTier",
        public: false,
        api_key: false,
        allowed: &["symbol", "tier", "recvWindow"],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "tier",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_margin_liability_coin_leverage_bracket_in_cross_margin_pro_mode",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/leverageBracket",
        public: true,
        api_key: true,
        allowed: &[],
        fields: &[],
    },
    Endpoint {
        name: "query_margin_margin_available_inventory",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/available-inventory",
        public: false,
        api_key: false,
        allowed: &["type"],
        fields: &[Field {
            key: "type",
            kind: 's',
            required: true,
            choices: &["MARGIN", "ISOLATED"],
        }],
    },
    Endpoint {
        name: "margin_exit_special_key_mode",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/margin/exit-special-key-mode",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_margin_small_liability_exchange_coin_list",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/exchange-small-liability",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_margin_small_liability_exchange_history",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/exchange-small-liability-history",
        public: false,
        api_key: false,
        allowed: &["current", "size", "startTime", "endTime", "recvWindow"],
        fields: &[
            Field {
                key: "current",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "size",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "margin_margin_manual_liquidation",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/margin/manual-liquidation",
        public: false,
        api_key: false,
        allowed: &["type", "symbol", "recvWindow"],
        fields: &[
            Field {
                key: "type",
                kind: 's',
                required: true,
                choices: &["MARGIN", "ISOLATED"],
            },
            Field {
                key: "symbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_margin_prevented_matches",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/myPreventedMatches",
        public: false,
        api_key: false,
        allowed: &[
            "symbol",
            "preventedMatchId",
            "orderId",
            "fromPreventedMatchId",
            "isIsolated",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "preventedMatchId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "orderId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "fromPreventedMatchId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "isIsolated",
                kind: 's',
                required: false,
                choices: &["TRUE", "FALSE"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "margin_small_liability_exchange",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/margin/exchange-small-liability",
        public: false,
        api_key: false,
        allowed: &["assetNames", "recvWindow"],
        fields: &[
            Field {
                key: "assetNames",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "delete_pm_pro_margin_call_level",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Delete,
        path: "/sapi/v1/portfolio/margin-call-level",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_pm_pro_margin_call_level",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/portfolio/margin-call-level",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "set_pm_pro_margin_call_level",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/portfolio/margin-call-level",
        public: false,
        api_key: false,
        allowed: &["marginCallLevel", "recvWindow"],
        fields: &[
            Field {
                key: "marginCallLevel",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
];
