//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "get_options_cancel_countdown",
        market: BinanceMarket::Options,
        symbol_market: BinanceMarket::Options,
        method: HttpMethod::Get,
        path: "/eapi/v1/countdownCancelAll",
        public: false,
        api_key: false,
        allowed: &["underlying", "recvWindow"],
        fields: &[
            Field {
                key: "underlying",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "set_options_cancel_countdown",
        market: BinanceMarket::Options,
        symbol_market: BinanceMarket::Options,
        method: HttpMethod::Post,
        path: "/eapi/v1/countdownCancelAll",
        public: false,
        api_key: false,
        allowed: &["underlying", "countdownTime", "recvWindow"],
        fields: &[
            Field {
                key: "underlying",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "countdownTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "send_options_cancel_heartbeat",
        market: BinanceMarket::Options,
        symbol_market: BinanceMarket::Options,
        method: HttpMethod::Post,
        path: "/eapi/v1/countdownCancelAllHeartBeat",
        public: false,
        api_key: false,
        allowed: &["underlyings", "recvWindow"],
        fields: &[
            Field {
                key: "underlyings",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_options_mmp_config",
        market: BinanceMarket::Options,
        symbol_market: BinanceMarket::Options,
        method: HttpMethod::Get,
        path: "/eapi/v1/mmp",
        public: false,
        api_key: false,
        allowed: &["underlying", "recvWindow"],
        fields: &[
            Field {
                key: "underlying",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "reset_options_mmp",
        market: BinanceMarket::Options,
        symbol_market: BinanceMarket::Options,
        method: HttpMethod::Post,
        path: "/eapi/v1/mmpReset",
        public: false,
        api_key: false,
        allowed: &["underlying", "recvWindow"],
        fields: &[
            Field {
                key: "underlying",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "set_options_mmp_config",
        market: BinanceMarket::Options,
        symbol_market: BinanceMarket::Options,
        method: HttpMethod::Post,
        path: "/eapi/v1/mmpSet",
        public: false,
        api_key: false,
        allowed: &[
            "underlying",
            "windowTimeInMilliseconds",
            "frozenTimeInMilliseconds",
            "qtyLimit",
            "deltaLimit",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "underlying",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "windowTimeInMilliseconds",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "frozenTimeInMilliseconds",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "qtyLimit",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "deltaLimit",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "tradfi_options_contract",
        market: BinanceMarket::Options,
        symbol_market: BinanceMarket::Options,
        method: HttpMethod::Post,
        path: "/eapi/v1/stock/contract",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "set_locked_product_redeem_option",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/simple-earn/locked/setRedeemOption",
        public: false,
        api_key: false,
        allowed: &["positionId", "redeemTo", "recvWindow"],
        fields: &[
            Field {
                key: "positionId",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "redeemTo",
                kind: 's',
                required: true,
                choices: &["SPOT", "FLEXIBLE"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
];
