//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "place_margin_oco",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/margin/order/oco",
        public: false,
        api_key: false,
        allowed: &[
            "symbol",
            "side",
            "quantity",
            "price",
            "stopPrice",
            "isIsolated",
            "listClientOrderId",
            "limitClientOrderId",
            "limitIcebergQty",
            "stopClientOrderId",
            "stopLimitPrice",
            "stopIcebergQty",
            "stopLimitTimeInForce",
            "newOrderRespType",
            "sideEffectType",
            "selfTradePreventionMode",
            "autoRepayAtCancel",
            "recvWindow",
            "product_symbol",
        ],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "side",
                kind: 's',
                required: true,
                choices: &["BUY", "SELL"],
            },
            Field {
                key: "quantity",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "price",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "stopPrice",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "isIsolated",
                kind: 's',
                required: false,
                choices: &["TRUE", "FALSE"],
            },
            Field {
                key: "listClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "limitClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "limitIcebergQty",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "stopClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "stopLimitPrice",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "stopIcebergQty",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "stopLimitTimeInForce",
                kind: 's',
                required: false,
                choices: &["GTC", "FOK", "IOC"],
            },
            Field {
                key: "newOrderRespType",
                kind: 's',
                required: false,
                choices: &["ACK", "RESULT", "FULL"],
            },
            Field {
                key: "sideEffectType",
                kind: 's',
                required: false,
                choices: &[
                    "NO_SIDE_EFFECT",
                    "MARGIN_BUY",
                    "AUTO_REPAY",
                    "AUTO_BORROW_REPAY",
                ],
            },
            Field {
                key: "selfTradePreventionMode",
                kind: 's',
                required: false,
                choices: &["EXPIRE_TAKER", "EXPIRE_MAKER", "EXPIRE_BOTH", "NONE"],
            },
            Field {
                key: "autoRepayAtCancel",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "place_margin_otoco",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/margin/order/otoco",
        public: false,
        api_key: false,
        allowed: &[
            "symbol",
            "workingType",
            "workingSide",
            "workingPrice",
            "workingQuantity",
            "pendingSide",
            "pendingQuantity",
            "pendingAboveType",
            "isIsolated",
            "sideEffectType",
            "autoRepayAtCancel",
            "listClientOrderId",
            "newOrderRespType",
            "selfTradePreventionMode",
            "workingClientOrderId",
            "workingIcebergQty",
            "workingTimeInForce",
            "pendingAboveClientOrderId",
            "pendingAbovePrice",
            "pendingAboveStopPrice",
            "pendingAboveTrailingDelta",
            "pendingAboveIcebergQty",
            "pendingAboveTimeInForce",
            "pendingBelowType",
            "pendingBelowClientOrderId",
            "pendingBelowPrice",
            "pendingBelowStopPrice",
            "pendingBelowTrailingDelta",
            "pendingBelowIcebergQty",
            "pendingBelowTimeInForce",
            "product_symbol",
        ],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "workingType",
                kind: 's',
                required: true,
                choices: &["LIMIT", "LIMIT_MAKER"],
            },
            Field {
                key: "workingSide",
                kind: 's',
                required: true,
                choices: &["BUY", "SELL"],
            },
            Field {
                key: "workingPrice",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "workingQuantity",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "pendingSide",
                kind: 's',
                required: true,
                choices: &["BUY", "SELL"],
            },
            Field {
                key: "pendingQuantity",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "pendingAboveType",
                kind: 's',
                required: true,
                choices: &["LIMIT_MAKER", "STOP_LOSS", "STOP_LOSS_LIMIT"],
            },
            Field {
                key: "isIsolated",
                kind: 's',
                required: false,
                choices: &["TRUE", "FALSE"],
            },
            Field {
                key: "sideEffectType",
                kind: 's',
                required: false,
                choices: &["NO_SIDE_EFFECT", "MARGIN_BUY", "AUTO_BORROW_REPAY"],
            },
            Field {
                key: "autoRepayAtCancel",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "listClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "newOrderRespType",
                kind: 's',
                required: false,
                choices: &["ACK", "RESULT", "FULL"],
            },
            Field {
                key: "selfTradePreventionMode",
                kind: 's',
                required: false,
                choices: &["EXPIRE_TAKER", "EXPIRE_MAKER", "EXPIRE_BOTH", "NONE"],
            },
            Field {
                key: "workingClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "workingIcebergQty",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "workingTimeInForce",
                kind: 's',
                required: false,
                choices: &["GTC", "IOC", "FOK"],
            },
            Field {
                key: "pendingAboveClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingAbovePrice",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingAboveStopPrice",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingAboveTrailingDelta",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingAboveIcebergQty",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingAboveTimeInForce",
                kind: 's',
                required: false,
                choices: &["GTC", "IOC", "FOK"],
            },
            Field {
                key: "pendingBelowType",
                kind: 's',
                required: false,
                choices: &["LIMIT_MAKER", "STOP_LOSS", "STOP_LOSS_LIMIT"],
            },
            Field {
                key: "pendingBelowClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingBelowPrice",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingBelowStopPrice",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingBelowTrailingDelta",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingBelowIcebergQty",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingBelowTimeInForce",
                kind: 's',
                required: false,
                choices: &["GTC", "IOC", "FOK"],
            },
        ],
    },
    Endpoint {
        name: "place_spot_opoco",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/api/v3/orderList/opoco",
        public: false,
        api_key: false,
        allowed: &[
            "symbol",
            "workingType",
            "workingSide",
            "workingPrice",
            "workingQuantity",
            "pendingSide",
            "pendingAboveType",
            "listClientOrderId",
            "newOrderRespType",
            "selfTradePreventionMode",
            "workingClientOrderId",
            "workingIcebergQty",
            "workingTimeInForce",
            "workingStrategyId",
            "workingStrategyType",
            "workingPegPriceType",
            "workingPegOffsetType",
            "workingPegOffsetValue",
            "pendingAboveClientOrderId",
            "pendingAbovePrice",
            "pendingAboveStopPrice",
            "pendingAboveTrailingDelta",
            "pendingAboveIcebergQty",
            "pendingAboveTimeInForce",
            "pendingAboveStrategyId",
            "pendingAboveStrategyType",
            "pendingAbovePegPriceType",
            "pendingAbovePegOffsetType",
            "pendingAbovePegOffsetValue",
            "pendingBelowType",
            "pendingBelowClientOrderId",
            "pendingBelowPrice",
            "pendingBelowStopPrice",
            "pendingBelowTrailingDelta",
            "pendingBelowIcebergQty",
            "pendingBelowTimeInForce",
            "pendingBelowStrategyId",
            "pendingBelowStrategyType",
            "pendingBelowPegPriceType",
            "pendingBelowPegOffsetType",
            "pendingBelowPegOffsetValue",
            "recvWindow",
            "product_symbol",
        ],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "workingType",
                kind: 's',
                required: true,
                choices: &["LIMIT", "LIMIT_MAKER"],
            },
            Field {
                key: "workingSide",
                kind: 's',
                required: true,
                choices: &["BUY", "SELL"],
            },
            Field {
                key: "workingPrice",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "workingQuantity",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "pendingSide",
                kind: 's',
                required: true,
                choices: &["BUY", "SELL"],
            },
            Field {
                key: "pendingAboveType",
                kind: 's',
                required: true,
                choices: &[
                    "STOP_LOSS_LIMIT",
                    "STOP_LOSS",
                    "LIMIT_MAKER",
                    "TAKE_PROFIT",
                    "TAKE_PROFIT_LIMIT",
                ],
            },
            Field {
                key: "listClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "newOrderRespType",
                kind: 's',
                required: false,
                choices: &["ACK", "RESULT", "FULL"],
            },
            Field {
                key: "selfTradePreventionMode",
                kind: 's',
                required: false,
                choices: &[
                    "NONE",
                    "EXPIRE_TAKER",
                    "EXPIRE_MAKER",
                    "EXPIRE_BOTH",
                    "DECREMENT",
                    "TRANSFER",
                ],
            },
            Field {
                key: "workingClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "workingIcebergQty",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "workingTimeInForce",
                kind: 's',
                required: false,
                choices: &["GTC", "IOC", "FOK"],
            },
            Field {
                key: "workingStrategyId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "workingStrategyType",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "workingPegPriceType",
                kind: 's',
                required: false,
                choices: &["PRIMARY_PEG", "MARKET_PEG"],
            },
            Field {
                key: "workingPegOffsetType",
                kind: 's',
                required: false,
                choices: &["PRICE_LEVEL"],
            },
            Field {
                key: "workingPegOffsetValue",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingAboveClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingAbovePrice",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingAboveStopPrice",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingAboveTrailingDelta",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingAboveIcebergQty",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingAboveTimeInForce",
                kind: 's',
                required: false,
                choices: &["GTC", "IOC", "FOK"],
            },
            Field {
                key: "pendingAboveStrategyId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingAboveStrategyType",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingAbovePegPriceType",
                kind: 's',
                required: false,
                choices: &["PRIMARY_PEG", "MARKET_PEG"],
            },
            Field {
                key: "pendingAbovePegOffsetType",
                kind: 's',
                required: false,
                choices: &["PRICE_LEVEL"],
            },
            Field {
                key: "pendingAbovePegOffsetValue",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingBelowType",
                kind: 's',
                required: false,
                choices: &[
                    "STOP_LOSS",
                    "STOP_LOSS_LIMIT",
                    "TAKE_PROFIT",
                    "TAKE_PROFIT_LIMIT",
                ],
            },
            Field {
                key: "pendingBelowClientOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingBelowPrice",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingBelowStopPrice",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingBelowTrailingDelta",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingBelowIcebergQty",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingBelowTimeInForce",
                kind: 's',
                required: false,
                choices: &["GTC", "IOC", "FOK"],
            },
            Field {
                key: "pendingBelowStrategyId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingBelowStrategyType",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingBelowPegPriceType",
                kind: 's',
                required: false,
                choices: &["PRIMARY_PEG", "MARKET_PEG"],
            },
            Field {
                key: "pendingBelowPegOffsetType",
                kind: 's',
                required: false,
                choices: &["PRICE_LEVEL"],
            },
            Field {
                key: "pendingBelowPegOffsetValue",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'd',
                required: false,
                choices: &[],
            },
        ],
    },
];
