//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "create_a_virtual_sub_account",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/sub-account/virtualSubAccount",
        public: false,
        api_key: false,
        allowed: &["subAccountString", "recvWindow"],
        fields: &[
            Field {
                key: "subAccountString",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "enable_futures_for_sub_account",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/sub-account/futures/enable",
        public: false,
        api_key: false,
        allowed: &["email", "recvWindow"],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "enable_options_for_sub_account",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/sub-account/eoptions/enable",
        public: false,
        api_key: false,
        allowed: &["email", "recvWindow"],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "add_ip_restriction_for_sub_account_api_key",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v2/sub-account/subAccountApi/ipRestriction",
        public: false,
        api_key: false,
        allowed: &[
            "email",
            "subAccountApiKey",
            "status",
            "ipAddress",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "subAccountApiKey",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "status",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "ipAddress",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "create_sub_account_api_key",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/sub-account/subAccountApi",
        public: false,
        api_key: false,
        allowed: &[
            "email",
            "apiName",
            "status",
            "canTrade",
            "canMarginLoanRepay",
            "canFuturesTrade",
            "canUniversalTransfer",
            "canVanillaOptions",
            "ipAddress",
            "thirdPartyName",
            "publicKey",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "apiName",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "status",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "canTrade",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "canMarginLoanRepay",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "canFuturesTrade",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "canUniversalTransfer",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "canVanillaOptions",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "ipAddress",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "thirdPartyName",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "publicKey",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "delete_ip_list_for_a_sub_account_api_key",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Delete,
        path: "/sapi/v1/sub-account/subAccountApi/ipRestriction/ipList",
        public: false,
        api_key: false,
        allowed: &["email", "subAccountApiKey", "ipAddress", "recvWindow"],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "subAccountApiKey",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "ipAddress",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "delete_sub_account_api_key",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Delete,
        path: "/sapi/v1/sub-account/subAccountApi",
        public: false,
        api_key: false,
        allowed: &["email", "subAccountApiKey", "recvWindow"],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "subAccountApiKey",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_ip_restriction_for_a_sub_account_api_key",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/sub-account/subAccountApi/ipRestriction",
        public: false,
        api_key: false,
        allowed: &["email", "subAccountApiKey", "recvWindow"],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "subAccountApiKey",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "modify_sub_account_api_key_permission",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/sub-account/subAccountApiPermission",
        public: false,
        api_key: false,
        allowed: &[
            "email",
            "subAccountApiKey",
            "canTrade",
            "canMarginLoanRepay",
            "canFuturesTrade",
            "canUniversalTransfer",
            "canVanillaOptions",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "subAccountApiKey",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "canTrade",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "canMarginLoanRepay",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "canFuturesTrade",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "canUniversalTransfer",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "canVanillaOptions",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_sub_account_api_key",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/sub-account/subAccountApi",
        public: false,
        api_key: false,
        allowed: &["email", "subAccountApiKey", "page", "size", "recvWindow"],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "subAccountApiKey",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "page",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "size",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_move_position_history_for_sub_account",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/sub-account/futures/move-position",
        public: false,
        api_key: false,
        allowed: &[
            "symbol",
            "page",
            "rows",
            "productType",
            "startTime",
            "endTime",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "symbol",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "page",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "rows",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "productType",
                kind: 's',
                required: false,
                choices: &["UM", "OPTION"],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_sub_account_deposit_address",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/capital/deposit/subAddress",
        public: false,
        api_key: false,
        allowed: &["email", "coin", "network", "amount", "recvWindow"],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "coin",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "network",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "amount",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_sub_account_deposit_history",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/capital/deposit/subHisrec",
        public: false,
        api_key: false,
        allowed: &[
            "email",
            "includeSource",
            "coin",
            "status",
            "startTime",
            "endTime",
            "limit",
            "offset",
            "recvWindow",
            "txId",
        ],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "includeSource",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "coin",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "status",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "offset",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "txId",
                kind: 's',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "move_position_for_sub_account",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/sub-account/futures/move-position",
        public: false,
        api_key: false,
        allowed: &[
            "fromUserEmail",
            "toUserEmail",
            "productType",
            "orderArgs",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "fromUserEmail",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "toUserEmail",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "productType",
                kind: 's',
                required: true,
                choices: &["UM", "OPTION"],
            },
            Field {
                key: "orderArgs",
                kind: 'j',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "deposit_assets_into_the_managed_sub_account",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/managed-subaccount/deposit",
        public: false,
        api_key: false,
        allowed: &["toEmail", "asset", "amount", "recvWindow"],
        fields: &[
            Field {
                key: "toEmail",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "asset",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "amount",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_managed_sub_account_deposit_address",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/managed-subaccount/deposit/address",
        public: false,
        api_key: false,
        allowed: &["email", "coin", "network", "amount", "recvWindow"],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "coin",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "network",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "amount",
                kind: 'd',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_managed_sub_account_asset_details",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/managed-subaccount/asset",
        public: false,
        api_key: false,
        allowed: &["email", "recvWindow"],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_managed_sub_account_futures_asset_details",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/managed-subaccount/fetch-future-asset",
        public: false,
        api_key: false,
        allowed: &["email", "accountType"],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "accountType",
                kind: 's',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_managed_sub_account_list",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/managed-subaccount/info",
        public: false,
        api_key: false,
        allowed: &["email", "page", "limit", "recvWindow"],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "page",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_managed_sub_account_margin_asset_details",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/managed-subaccount/marginAsset",
        public: false,
        api_key: false,
        allowed: &["email", "accountType"],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "accountType",
                kind: 's',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_managed_sub_account_snapshot",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/managed-subaccount/accountSnapshot",
        public: false,
        api_key: false,
        allowed: &[
            "email",
            "type",
            "startTime",
            "endTime",
            "limit",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "type",
                kind: 's',
                required: true,
                choices: &["SPOT", "MARGIN", "FUTURES"],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
];
