//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "pm_bnb_transfer",
        market: BinanceMarket::PortfolioMargin,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/papi/v1/bnb-transfer",
        public: false,
        api_key: false,
        allowed: &["amount", "transferSide", "recvWindow"],
        fields: &[
            Field {
                key: "amount",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "transferSide",
                kind: 's',
                required: true,
                choices: &["TO_UM", "FROM_UM"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_margin_cross_margin_transfer_history",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/margin/transfer",
        public: false,
        api_key: false,
        allowed: &[
            "asset",
            "type",
            "startTime",
            "endTime",
            "current",
            "size",
            "isolatedSymbol",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "type",
                kind: 's',
                required: false,
                choices: &["ROLL_IN", "ROLL_OUT"],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "current",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "size",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "isolatedSymbol",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "wallet_dust_transfer",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/asset/dust",
        public: false,
        api_key: false,
        allowed: &["asset", "accountType", "recvWindow"],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "accountType",
                kind: 's',
                required: false,
                choices: &["SPOT", "MARGIN"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "pm_pro_bnb_transfer",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/portfolio/bnb-transfer",
        public: false,
        api_key: false,
        allowed: &["amount", "transferSide", "recvWindow"],
        fields: &[
            Field {
                key: "amount",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "transferSide",
                kind: 's',
                required: true,
                choices: &["TO_UM", "FROM_UM"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_user_delegation_history",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/asset/custody/transfer-history",
        public: false,
        api_key: false,
        allowed: &[
            "email",
            "startTime",
            "endTime",
            "type",
            "asset",
            "current",
            "size",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "type",
                kind: 's',
                required: false,
                choices: &["DELEGATE", "UNDELEGATE"],
            },
            Field {
                key: "asset",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "current",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "size",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "query_managed_sub_account_transfer_log_master_account_investor",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/managed-subaccount/queryTransLogForInvestor",
        public: false,
        api_key: false,
        allowed: &[
            "email",
            "startTime",
            "endTime",
            "page",
            "limit",
            "transfers",
            "transferFunctionAccountType",
        ],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "page",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "transfers",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "transferFunctionAccountType",
                kind: 's',
                required: false,
                choices: &[
                    "SPOT",
                    "MARGIN",
                    "ISOLATED_MARGIN",
                    "USDT_FUTURE",
                    "COIN_FUTURE",
                ],
            },
        ],
    },
    Endpoint {
        name: "query_managed_sub_account_transfer_log_master_account_trading",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/managed-subaccount/queryTransLogForTradeParent",
        public: false,
        api_key: false,
        allowed: &[
            "email",
            "startTime",
            "endTime",
            "page",
            "limit",
            "transfers",
            "transferFunctionAccountType",
        ],
        fields: &[
            Field {
                key: "email",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "page",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "transfers",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "transferFunctionAccountType",
                kind: 's',
                required: false,
                choices: &[
                    "SPOT",
                    "MARGIN",
                    "ISOLATED_MARGIN",
                    "USDT_FUTURE",
                    "COIN_FUTURE",
                ],
            },
        ],
    },
    Endpoint {
        name: "query_managed_sub_account_transfer_log_sub_account_trading",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/managed-subaccount/query-trans-log",
        public: false,
        api_key: false,
        allowed: &[
            "startTime",
            "endTime",
            "page",
            "limit",
            "transfers",
            "transferFunctionAccountType",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "startTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "page",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "transfers",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "transferFunctionAccountType",
                kind: 's',
                required: false,
                choices: &[
                    "SPOT",
                    "MARGIN",
                    "ISOLATED_MARGIN",
                    "USDT_FUTURE",
                    "COIN_FUTURE",
                ],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_transferable_earn_asset_balance_for_portfolio_margin",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/portfolio/earn-asset-balance",
        public: false,
        api_key: false,
        allowed: &["asset", "transferType", "recvWindow"],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "transferType",
                kind: 's',
                required: true,
                choices: &["EARN_TO_FUTURE", "FUTURE_TO_EARN"],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "transfer_ldusdt_rwusd_for_portfolio_margin",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/portfolio/earn-asset-transfer",
        public: false,
        api_key: false,
        allowed: &["asset", "transferType", "amount", "recvWindow"],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: true,
                choices: &["LDUSDT", "RWUSD"],
            },
            Field {
                key: "transferType",
                kind: 's',
                required: true,
                choices: &["EARN_TO_FUTURE", "FUTURE_TO_EARN"],
            },
            Field {
                key: "amount",
                kind: 'd',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
];
