//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "check_questionnaire_requirements",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/localentity/questionnaire-requirements",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_travel_rule_deposit_history",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/localentity/deposit/history",
        public: false,
        api_key: false,
        allowed: &[
            "trId",
            "txId",
            "tranId",
            "network",
            "coin",
            "travelRuleStatus",
            "pendingQuestionnaire",
            "startTime",
            "endTime",
            "offset",
            "limit",
        ],
        fields: &[
            Field {
                key: "trId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "txId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "tranId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "network",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "coin",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "travelRuleStatus",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "pendingQuestionnaire",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "offset",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_travel_rule_deposit_history_v2",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v2/localentity/deposit/history",
        public: false,
        api_key: false,
        allowed: &[
            "depositId",
            "txId",
            "network",
            "coin",
            "retrieveQuestionnaire",
            "startTime",
            "endTime",
            "offset",
            "limit",
        ],
        fields: &[
            Field {
                key: "depositId",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "txId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "network",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "coin",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "retrieveQuestionnaire",
                kind: 'b',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "offset",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_country_list",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/localentity/country/list",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_region_list",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/localentity/region/list",
        public: false,
        api_key: false,
        allowed: &["countryCode", "recvWindow"],
        fields: &[
            Field {
                key: "countryCode",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "submit_deposit_questionnaire_travel_rule",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Put,
        path: "/sapi/v1/localentity/deposit/provide-info",
        public: false,
        api_key: false,
        allowed: &["tranId", "questionnaire"],
        fields: &[
            Field {
                key: "tranId",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "questionnaire",
                kind: 's',
                required: true,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "submit_deposit_questionnaire_v2",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Put,
        path: "/sapi/v2/localentity/deposit/provide-info",
        public: false,
        api_key: false,
        allowed: &["depositId", "questionnaire"],
        fields: &[
            Field {
                key: "depositId",
                kind: 'i',
                required: true,
                choices: &[],
            },
            Field {
                key: "questionnaire",
                kind: 's',
                required: true,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "vasp_list",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/localentity/vasp",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "get_travel_rule_withdrawal_history",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/localentity/withdraw/history",
        public: false,
        api_key: false,
        allowed: &[
            "trId",
            "txId",
            "withdrawOrderId",
            "network",
            "coin",
            "travelRuleStatus",
            "offset",
            "limit",
            "startTime",
            "endTime",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "trId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "txId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "withdrawOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "network",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "coin",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "travelRuleStatus",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "offset",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_travel_rule_withdrawal_history_v2",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v2/localentity/withdraw/history",
        public: false,
        api_key: false,
        allowed: &[
            "trId",
            "txId",
            "withdrawOrderId",
            "network",
            "coin",
            "travelRuleStatus",
            "offset",
            "limit",
            "startTime",
            "endTime",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "trId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "txId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "withdrawOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "network",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "coin",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "travelRuleStatus",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "offset",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
];
