//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "wallet_account_info",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/account/info",
        public: false,
        api_key: false,
        allowed: &["recvWindow"],
        fields: &[Field {
            key: "recvWindow",
            kind: 'i',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "wallet_daily_account_snapshot",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/accountSnapshot",
        public: false,
        api_key: false,
        allowed: &["type", "startTime", "endTime", "limit", "recvWindow"],
        fields: &[
            Field {
                key: "type",
                kind: 's',
                required: true,
                choices: &["SPOT", "MARGIN", "FUTURES"],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "wallet_asset_detail",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/asset/assetDetail",
        public: false,
        api_key: false,
        allowed: &["asset", "recvWindow"],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "wallet_asset_dividend_record",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/asset/assetDividend",
        public: false,
        api_key: false,
        allowed: &["asset", "startTime", "endTime", "limit", "recvWindow"],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "get_wallet_open_symbol_list",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/spot/open-symbol-list",
        public: true,
        api_key: true,
        allowed: &[],
        fields: &[],
    },
    Endpoint {
        name: "get_wallet_spot_asset_tags",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/spot/asset/tags",
        public: true,
        api_key: true,
        allowed: &["tag"],
        fields: &[Field {
            key: "tag",
            kind: 's',
            required: false,
            choices: &[],
        }],
    },
    Endpoint {
        name: "toggle_wallet_bnb_burn_on_spot_trade_and_margin_interest",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Post,
        path: "/sapi/v1/bnbBurn",
        public: false,
        api_key: false,
        allowed: &["spotBNBBurn", "interestBNBBurn", "recvWindow"],
        fields: &[
            Field {
                key: "spotBNBBurn",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "interestBNBBurn",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
];
