//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "get_pm_margin_transferable_amount",
        market: BinanceMarket::PortfolioMargin,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/papi/v1/margin/maxWithdraw",
        public: false,
        api_key: false,
        allowed: &["asset", "recvWindow"],
        fields: &[
            Field {
                key: "asset",
                kind: 's',
                required: true,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
    Endpoint {
        name: "fetch_withdraw_address_list",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/capital/withdraw/address/list",
        public: false,
        api_key: false,
        allowed: &[],
        fields: &[],
    },
    Endpoint {
        name: "fetch_withdraw_quota",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/capital/withdraw/quota",
        public: false,
        api_key: false,
        allowed: &[],
        fields: &[],
    },
    Endpoint {
        name: "get_withdrawal_history",
        market: BinanceMarket::Spot,
        symbol_market: BinanceMarket::Spot,
        method: HttpMethod::Get,
        path: "/sapi/v1/capital/withdraw/history",
        public: false,
        api_key: false,
        allowed: &[
            "coin",
            "withdrawOrderId",
            "status",
            "offset",
            "limit",
            "idList",
            "startTime",
            "endTime",
            "recvWindow",
        ],
        fields: &[
            Field {
                key: "coin",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "withdrawOrderId",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "status",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "offset",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "limit",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "idList",
                kind: 's',
                required: false,
                choices: &[],
            },
            Field {
                key: "startTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "endTime",
                kind: 'i',
                required: false,
                choices: &[],
            },
            Field {
                key: "recvWindow",
                kind: 'i',
                required: false,
                choices: &[],
            },
        ],
    },
];
