use super::KucoinClient;
crate::exchanges::impl_exchange_method_wrappers! {
    @extend; KucoinClient;
    public [];
    private [
        get_v1_accounts_account_id(account_id => "accountId"),
        get_ua_v2_affiliate_query_invitees(),
        get_ua_v2_affiliate_query_my_commission(),
        get_ua_v2_affiliate_query_transaction_by_uid(uid => "uid"),
        get_ua_v2_affiliate_query_transaction_by_time(trade_start_at => "tradeStartAt", trade_end_at => "tradeEndAt"),
        get_ua_v2_affiliate_query_kumining(),
        get_v2_affiliate_query_invitees(),
        get_v2_affiliate_query_my_commission(),
        get_v2_affiliate_query_transaction_by_uid(uid => "uid"),
        get_v2_affiliate_query_transaction_by_time(trade_start_at => "tradeStartAt", trade_end_at => "tradeEndAt"),
        get_v2_affiliate_query_kumining(),
        /// API withdrawals have no second confirmation; they execute on submit.
        post_v2_broker_withdrawal(body => "body"),
        get_v2_broker_api_rebate_download(begin => "begin", end => "end", trade_type => "tradeType"),
        get_v2_broker_query_my_commission(),
        get_v2_broker_query_user(),
        get_v2_broker_query_detail_by_uid(),
        get_v1_broker_nd_rebate_download(begin => "begin", end => "end", trade_type => "tradeType"),
        get_v3_broker_nd_rebate_download(begin => "begin", end => "end", trade_type => "tradeType"),
        post_kyc_nd_broker_proxy_client_submit(client_uid => "clientUid", first_name => "firstName", last_name => "lastName", issue_country => "issueCountry", birth_date => "birthDate", identity_type => "identityType", identity_number => "identityNumber", expire_date => "expireDate", face_photo => "facePhoto"),
        get_kyc_nd_broker_proxy_client_status_list(client_uids => "clientUids"),
        get_kyc_nd_broker_proxy_client_status_page(),
        get_v1_broker_nd_info(begin => "begin", end => "end", trade_type => "tradeType"),
        post_v1_broker_nd_account(account_name => "accountName"),
        get_v1_broker_nd_account(),
        post_v1_broker_nd_account_apikey(uid => "uid", passphrase => "passphrase", label => "label"),
        get_v1_broker_nd_account_apikey(uid => "uid"),
        post_v1_broker_nd_account_update_apikey(uid => "uid", label => "label", api_key => "apiKey"),
        delete_v1_broker_nd_account_apikey(uid => "uid", api_key => "apiKey"),
        post_v1_broker_nd_transfer(currency => "currency", amount => "amount", direction => "direction", account_type => "accountType", special_uid => "specialUid", special_account_type => "specialAccountType", client_oid => "clientOid"),
        get_v3_broker_nd_transfer_detail(order_id => "orderId"),
        get_v1_asset_ndbroker_deposit_list(),
        get_v3_broker_nd_deposit_detail(currency => "currency", hash => "hash"),
        get_v3_broker_nd_withdraw_detail(withdrawal_id => "withdrawalId"),
        post_v1_broker_nd_mark_up(trade_type => "tradeType", maker_mark_up => "makerMarkUp", taker_mark_up => "takerMarkUp", effective_type => "effectiveType"),
        get_v1_broker_nd_mark_up(),
        post_v1_copy_trade_futures_orders(client_oid => "clientOid", side => "side", symbol => "symbol", type_ => "type", size => "size"),
        post_v1_copy_trade_futures_orders_test(client_oid => "clientOid", side => "side", symbol => "symbol", leverage => "leverage", type_ => "type", size => "size"),
        post_v1_copy_trade_futures_st_orders(client_oid => "clientOid", side => "side", symbol => "symbol", leverage => "leverage", type_ => "type", size => "size"),
        delete_v1_copy_trade_futures_orders(),
        delete_v1_copy_trade_futures_orders_client_order(symbol => "symbol", client_oid => "clientOid"),
        get_v1_copy_trade_futures_get_max_open_size(symbol => "symbol", price => "price", leverage => "leverage"),
        get_v1_copy_trade_futures_position_margin_max_withdraw_margin(symbol => "symbol"),
        post_v1_copy_trade_futures_position_margin_deposit_margin(symbol => "symbol", margin => "margin", biz_no => "bizNo"),
        post_v1_copy_trade_futures_position_margin_withdraw_margin(symbol => "symbol", withdraw_amount => "withdrawAmount"),
        post_v1_copy_trade_futures_position_risk_limit_level_change(symbol => "symbol", level => "level"),
        post_v1_copy_trade_futures_position_margin_auto_deposit_status(symbol => "symbol", status => "status"),
        post_v1_copy_trade_futures_position_change_margin_mode(symbol => "symbol", margin_mode => "marginMode"),
        post_v2_copy_trade_futures_change_cross_user_leverage(symbol => "symbol", leverage => "leverage"),
        post_v2_copy_trade_get_cross_mode_margin_requirement(symbol => "symbol", leverage => "leverage", position_value => "positionValue"),
        post_v2_copy_trade_position_switch_position_mode(position_mode => "positionMode"),
    ];
}
