use super::client::KucoinClient;

crate::exchanges::impl_exchange_method_wrappers! {
    KucoinClient;
    public [
        get_futures_all_tickers(),
        get_futures_mark_price(product_symbol => "product_symbol"),
        get_futures_server_time(),
        get_futures_service_status(),
        get_margin_mark_price(product_symbol => "product_symbol"),
        get_margin_mark_prices(),
        get_spot_server_time(),
        get_spot_service_status(),
        get_uta_borrowable_currencies(),
        get_uta_collateral_ratios(),
        get_uta_current_funding_rates(),
        get_uta_funding_rate_history(product_symbol => "product_symbol", start_at => "startAt", end_at => "endAt"),
        get_uta_index_prices(product_symbol => "product_symbol"),
        get_uta_interest_rate_index(product_symbol => "product_symbol"),
        get_uta_klines(product_symbol => "product_symbol", trade_type => "tradeType", interval => "interval"),
        get_uta_service_status(trade_type => "tradeType"),
        get_uta_tickers(trade_type => "tradeType"),
        get_uta_trade_statistics(),
        get_uta_public_trades(trade_type => "tradeType", product_symbol => "product_symbol"),
        get_uta_instruments(trade_type => "tradeType"),
        get_futures_current_funding_rate(product_symbol => "product_symbol"),
        get_futures_public_funding_history(product_symbol => "product_symbol", from_ => "from", to => "to"),
        get_futures_contract(product_symbol => "product_symbol"),
        get_futures_contracts(),
        get_futures_kline(product_symbol => "product_symbol", timeframe => "timeframe"),
        get_futures_open_interest(product_symbol => "product_symbol"),
        get_uta_position_tiers(),
        get_futures_orderbook(product_symbol => "product_symbol"),
        get_futures_public_trades(product_symbol => "product_symbol"),
        get_futures_ticker(product_symbol => "product_symbol"),
        get_spot_all_tickers(),
        get_spot_instrument_info(),
        get_spot_kline(product_symbol => "product_symbol", timeframe => "timeframe"),
        get_spot_orderbook(product_symbol => "product_symbol"),
        get_spot_public_trades(product_symbol => "product_symbol"),
        get_spot_ticker(product_symbol => "product_symbol"),
        get_cross_margin_symbols(),
        get_isolated_margin_symbols(),
        get_margin_collateral_ratio(),
        get_margin_available_inventory(),
        get_margin_loan_market_interest_rate(currency => "currency"),
    ];
    private [
        place_spot_order_sync(product_symbol => "product_symbol", side => "side", type_ => "type"),
        place_spot_batch_orders_sync(orders => "orders"),
        cancel_spot_order_sync(product_symbol => "product_symbol", order_id => "orderId"),
        cancel_spot_order_by_client_oid_sync(product_symbol => "product_symbol", client_oid => "clientOid"),
        get_futures_account_ledgers(),
        get_margin_hf_account_ledgers(),
        get_spot_account_ledgers(),
        get_spot_hf_account_ledgers(),
        get_deposit_history(currency => "currency"),
        get_margin_currency_risk_limits(),
        get_spot_full_orderbook(product_symbol => "product_symbol"),
        get_uta_account_ledgers(account_type => "accountType"),
        get_classic_account_balances_v2(account_type => "accountType"),
        transfer_uta_accounts(client_oid => "clientOid", transfer_type => "transferType", currency => "currency", amount => "amount", from_account_type => "fromAccountType", from_account_tag => "fromAccountTag", to_account_type => "toAccountType", to_account_tag => "toAccountTag"),
        get_uta_account_mode(),
        get_uta_all_rate_limits(),
        get_uta_rate_limits(uids => "uids"),
        get_uta_rate_limit_cap(),
        get_uta_borrowing_rates_limits(currency => "currency"),
        get_uta_interest_history(account_type => "accountType"),
        get_uta_orderbook(trade_type => "tradeType", product_symbol => "product_symbol", limit => "limit"),
        get_uta_transfer_quota(account_type => "accountType", currency => "currency"),
        place_futures_batch_orders(orders => "orders"),
        cancel_futures_batch_orders(),
        set_futures_batch_margin_mode(margin_mode => "marginMode", symbols => "symbols"),
        get_spot_stop_order_by_client_oid(client_oid => "clientOid"),
        cancel_spot_order_by_client_oid(product_symbol => "product_symbol", client_oid => "clientOid"),
        cancel_spot_partial_order(product_symbol => "product_symbol", cancel_size => "cancelSize", order_id => "orderId"),
        get_spot_order(product_symbol => "product_symbol", order_id => "orderId"),
        get_spot_order_by_client_oid(product_symbol => "product_symbol", client_oid => "clientOid"),
        get_spot_active_order_symbols(),
        get_spot_active_orders(product_symbol => "product_symbol"),
        get_spot_closed_orders(product_symbol => "product_symbol"),
        place_spot_stop_order(side => "side", product_symbol => "product_symbol", type_ => "type", stop_price => "stopPrice"),
        cancel_spot_stop_order_by_client_oid(client_oid => "clientOid"),
        cancel_spot_stop_order(order_id => "orderId"),
        cancel_spot_stop_orders(),
        get_spot_stop_orders(),
        get_spot_stop_order(order_id => "orderId"),
        place_spot_oco_order(client_oid => "clientOid", side => "side", product_symbol => "product_symbol", price => "price", size => "size", stop_price => "stopPrice", limit_price => "limitPrice"),
        cancel_spot_oco_order(order_id => "orderId"),
        cancel_spot_oco_order_by_client_oid(client_oid => "clientOid"),
        cancel_spot_oco_orders(),
        get_spot_oco_order(order_id => "orderId"),
        get_spot_oco_order_by_client_oid(client_oid => "clientOid"),
        get_spot_oco_order_details(order_id => "orderId"),
        get_spot_oco_orders(),
        place_margin_order(client_oid => "clientOid", side => "side", product_symbol => "product_symbol"),
        test_margin_order(client_oid => "clientOid", side => "side", product_symbol => "product_symbol"),
        cancel_margin_order(product_symbol => "product_symbol", order_id => "orderId"),
        cancel_margin_order_by_client_oid(product_symbol => "product_symbol", client_oid => "clientOid"),
        cancel_margin_orders_by_symbol(product_symbol => "product_symbol", trade_type => "tradeType"),
        get_margin_active_order_symbols(trade_type => "tradeType"),
        get_margin_open_orders(product_symbol => "product_symbol", trade_type => "tradeType"),
        get_margin_closed_orders(product_symbol => "product_symbol", trade_type => "tradeType"),
        get_margin_trade_history(product_symbol => "product_symbol", trade_type => "tradeType"),
        get_margin_order(product_symbol => "product_symbol", order_id => "orderId"),
        get_margin_order_by_client_oid(product_symbol => "product_symbol", client_oid => "clientOid"),
        place_margin_stop_order(client_oid => "clientOid", side => "side", product_symbol => "product_symbol", is_isolated => "isIsolated", auto_borrow => "autoBorrow", auto_repay => "autoRepay", stop_price => "stopPrice"),
        cancel_margin_stop_order_by_client_oid(client_oid => "clientOid"),
        cancel_margin_stop_orders(trade_type => "tradeType"),
        get_margin_stop_orders(),
        get_margin_stop_order(order_id => "orderId"),
        get_margin_stop_order_by_client_oid(client_oid => "clientOid"),
        place_margin_oco_order(client_oid => "clientOid", side => "side", product_symbol => "product_symbol", price => "price", size => "size", stop_price => "stopPrice", limit_price => "limitPrice", is_isolated => "isIsolated"),
        cancel_margin_oco_order(order_id => "orderId"),
        cancel_margin_oco_order_by_client_oid(client_oid => "clientOid"),
        cancel_margin_oco_orders(),
        get_margin_oco_order(order_id => "orderId"),
        get_margin_oco_order_by_client_oid(client_oid => "clientOid"),
        get_margin_oco_order_details(order_id => "orderId"),
        get_margin_oco_orders(page_size => "pageSize", current_page => "currentPage"),
        place_futures_tpsl_order(client_oid => "clientOid", product_symbol => "product_symbol"),
        cancel_futures_stop_orders(),
        get_futures_recent_closed_orders(),
        get_futures_stop_orders(),
        get_futures_margin_mode(product_symbol => "product_symbol"),
        set_futures_margin_mode(product_symbol => "product_symbol", margin_mode => "marginMode"),
        set_futures_position_mode(position_mode => "positionMode"),
        get_futures_max_open_size(product_symbol => "product_symbol", price => "price", leverage => "leverage"),
        get_futures_position_history(),
        get_futures_max_withdraw_margin(product_symbol => "product_symbol"),
        add_futures_isolated_margin(product_symbol => "product_symbol", margin => "margin", biz_no => "bizNo"),
        remove_futures_isolated_margin(product_symbol => "product_symbol", withdraw_amount => "withdrawAmount"),
        get_futures_cross_margin_risk_limit(product_symbol => "product_symbol"),
        get_futures_cross_margin_requirement(product_symbol => "product_symbol", position_value => "positionValue"),
        get_futures_isolated_margin_risk_limit(product_symbol => "product_symbol"),
        set_futures_isolated_margin_risk_limit(product_symbol => "product_symbol", level => "level"),
        get_futures_funding_history(product_symbol => "product_symbol"),
        batch_cancel_uta_orders(trade_type => "tradeType", cancel_order_list => "cancelOrderList"),
        cancel_uta_orders_by_symbol(trade_type => "tradeType", product_symbol => "product_symbol", order_filter => "orderFilter"),
        get_uta_margin_mode(),
        set_uta_margin_mode(product_symbol => "product_symbol", margin_mode => "marginMode"),
        modify_uta_position_margin(product_symbol => "product_symbol", type_ => "type", amount => "amount"),
        get_uta_max_order_quantity(trade_type => "tradeType", product_symbol => "product_symbol"),
        get_uta_leverage(trade_type => "tradeType"),
        modify_uta_futures_leverage(product_symbol => "product_symbol", leverage => "leverage"),
        modify_uta_cross_margin_leverage(leverage => "leverage"),
        get_uta_position_history(),
        get_uta_funding_history(),
        place_uta_order(trade_type => "tradeType", product_symbol => "product_symbol", side => "side", order_type => "orderType", size => "size", size_unit => "sizeUnit"),
        cancel_uta_order(trade_type => "tradeType", product_symbol => "product_symbol"),
        amend_uta_order(product_symbol => "product_symbol"),
        get_uta_order_detail(trade_type => "tradeType", product_symbol => "product_symbol"),
        get_uta_open_orders(trade_type => "tradeType"),
        get_uta_order_history(trade_type => "tradeType"),
        get_uta_trade_history(trade_type => "tradeType"),
        get_uta_positions(),
        get_uta_account_balance(),
        get_uta_account_overview(),

        get_futures_fee_rates(product_symbol => "product_symbol"),
        get_spot_fee_rates(product_symbol => "product_symbol"),
        get_uta_fee_rates(trade_type => "tradeType", symbol => "symbol"),
        cancel_futures_all_orders(product_symbol => "product_symbol"),
        cancel_futures_order(order_id => "orderId"),
        cancel_futures_order_by_client_oid(client_oid => "clientOid", product_symbol => "product_symbol"),
        cancel_spot_all_orders(),
        set_dcp(timeout => "timeout"),
        get_dcp(),
        cancel_spot_all_orders_by_symbol(product_symbol => "product_symbol"),
        cancel_spot_order(order_id => "orderId", product_symbol => "product_symbol"),
        flex_transfer(currency => "currency", amount => "amount", from_account_type => "fromAccountType", to_account_type => "toAccountType"),
        get_account_balance(),
        get_subaccounts(),
        get_subaccount_balance(sub_user_id => "subUserId"),
        get_spot_subaccount_balances(),
        get_futures_subaccount_balances(),
        get_uta_subaccounts(),
        get_uta_subaccount_currency_assets(),
        get_futures_account(),
        get_futures_cross_margin_leverage(product_symbol => "product_symbol"),
        get_futures_open_order_value(product_symbol => "product_symbol"),
        get_futures_order(order_id => "orderId"),
        get_futures_order_by_client_oid(client_oid => "clientOid"),
        get_futures_order_list(),
        get_futures_position(product_symbol => "product_symbol"),
        get_futures_position_mode(),
        get_futures_positions(),
        get_futures_recent_trade_history(),
        get_futures_trade_history(),
        get_spot_open_orders(product_symbol => "product_symbol"),
        get_spot_trade_history(product_symbol => "product_symbol"),
        get_transfer_quotas(currency => "currency", account_type => "account_type"),
        get_cross_margin_account(),
        get_isolated_margin_account(),
        get_margin_borrow_interest_rate(),
        borrow_margin(currency => "currency", size => "size"),
        get_margin_borrow_history(),
        repay_margin(currency => "currency", size => "size"),
        get_margin_repay_history(),
        get_margin_interest_history(),
        modify_margin_leverage(leverage => "leverage"),
        get_margin_loan_market(),
        purchase_margin_lending(currency => "currency", size => "size", interest_rate => "interestRate"),
        modify_margin_lending_purchase(currency => "currency", purchase_order_no => "purchaseOrderNo", interest_rate => "interestRate"),
        get_margin_lending_purchase_orders(),
        redeem_margin_lending(currency => "currency", size => "size", purchase_order_no => "purchaseOrderNo"),
        get_margin_lending_redeem_orders(),
        get_dual_investment_products(),
        purchase_earn(product_id => "productId", amount => "amount", account_type => "accountType"),
        get_earn_redeem_preview(order_id => "orderId", from_account_type => "fromAccountType"),
        redeem_earn(order_id => "orderId"),
        get_earn_savings_products(),
        get_earn_promotion_products(),
        get_earn_staking_products(),
        get_earn_kcs_staking_products(),
        get_earn_eth_staking_products(),
        get_earn_account_holdings(),
        purchase_structured_earn(product_id => "productId", invest_currency => "investCurrency", invest_amount => "investAmount", account_type => "accountType"),
        get_structured_earn_orders(),
        modify_futures_cross_margin_leverage(product_symbol => "product_symbol", leverage => "leverage"),
        place_futures_limit_buy_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_futures_limit_order(product_symbol => "product_symbol", side => "side", size => "size", price => "price"),
        place_futures_limit_sell_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_futures_market_buy_order(product_symbol => "product_symbol", size => "size"),
        place_futures_market_order(product_symbol => "product_symbol", side => "side", size => "size"),
        place_futures_market_sell_order(product_symbol => "product_symbol", size => "size"),
        place_futures_order(product_symbol => "product_symbol", side => "side", type_ => "type", size => "size"),
        test_futures_order(product_symbol => "product_symbol", side => "side", type_ => "type", size => "size"),
        place_futures_post_only_limit_buy_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_futures_post_only_limit_order(product_symbol => "product_symbol", side => "side", size => "size", price => "price"),
        place_futures_post_only_limit_sell_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_spot_batch_limit_orders(orders => "orders"),
        place_spot_batch_market_orders(orders => "orders"),
        place_spot_batch_orders(orders => "orders"),
        place_spot_limit_buy_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_spot_limit_order(product_symbol => "product_symbol", side => "side", size => "size", price => "price"),
        place_spot_limit_sell_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_spot_market_buy_order(product_symbol => "product_symbol"),
        place_spot_market_order(product_symbol => "product_symbol", side => "side"),
        place_spot_market_sell_order(product_symbol => "product_symbol"),
        place_spot_order(product_symbol => "product_symbol", side => "side", type_ => "type"),
        test_spot_order(product_symbol => "product_symbol", side => "side", type_ => "type"),
        alter_spot_order(product_symbol => "product_symbol"),
        place_spot_post_only_limit_buy_order(product_symbol => "product_symbol", size => "size", price => "price"),
        place_spot_post_only_limit_order(product_symbol => "product_symbol", side => "side", size => "size", price => "price"),
        place_spot_post_only_limit_sell_order(product_symbol => "product_symbol", size => "size", price => "price"),
    ];
}

crate::exchanges::impl_exchange_method_wrappers! { @extend; KucoinClient; public [
get_convert_currencies(),
get_convert_symbol(from_currency => "fromCurrency",to_currency => "toCurrency"),
get_futures_interest_rate_index(symbol => "symbol"),
get_futures_premium_index(symbol => "symbol"),
get_margin_config(),
get_announcements(),
get_call_auction_info(symbol => "symbol"),
get_call_auction_part_order_book(size => "size",symbol => "symbol"),
get_spot_currency_v3(currency => "currency"),
get_fiat_price(),
get_market_list(),
get_spot_symbol_v2(symbol => "symbol"),
get_uta_currencies(),
get_uta_currency(currency => "currency"),
get_uta_fiat_price(base => "base"),
get_uta_announcements(),
get_uta_call_auction_info(symbol => "symbol"),
get_uta_client_ip_address(),
get_uta_kyc_regions(),
]; private [
get_apikey_info(),
create_deposit_address_v3(currency => "currency",chain => "chain"),
get_deposit_addresses_v3(currency => "currency"),
add_sub_account_api(passphrase => "passphrase",remark => "remark",sub_name => "subName"),
delete_sub_account_api(api_key => "apiKey",sub_name => "subName",passphrase => "passphrase"),
get_sub_account_api_list(sub_name => "subName"),
modify_sub_account_api(passphrase => "passphrase",sub_name => "subName",api_key => "apiKey"),
add_sub_account_futures_permission(uid => "uid"),
add_sub_account_margin_permission(uid => "uid"),
get_basic_fee(),
add_convert_limit_order(client_order_id => "clientOrderId",from_currency => "fromCurrency",to_currency => "toCurrency",from_currency_size => "fromCurrencySize",to_currency_size => "toCurrencySize"),
add_convert_order(client_order_id => "clientOrderId",quote_id => "quoteId"),
cancel_convert_limit_order(),
get_convert_limit_order_detail(),
get_convert_limit_order_detail_list(),
get_convert_limit_quote(from_currency => "fromCurrency",to_currency => "toCurrency"),
get_convert_order_detail(),
get_convert_order_history(),
get_convert_quote(from_currency => "fromCurrency",to_currency => "toCurrency"),
add_uta_sub_account(password => "password",sub_name => "subName",access => "access"),
add_uta_sub_account_api(sub_name => "subName",passphrase => "passphrase",remark => "remark"),
get_uta_apikey_info(),
delete_uta_sub_account_api(api_key => "apiKey",sub_name => "subName",passphrase => "passphrase"),
get_uta_deposit_address(currency => "currency"),
get_uta_deposit_history(),
set_uta_kcs_fee_deduction(enabled => "enabled"),
modify_uta_sub_account_api(sub_name => "subName",api_key => "apiKey",passphrase => "passphrase"),
set_uta_rate_limit(list => "list"),
get_uta_sub_account_api_list(api_key => "apiKey",sub_name => "subName"),
set_uta_sub_account_transfer_permission(sub_uids => "subUids",sub_to_sub => "subToSub"),
]; }

crate::exchanges::impl_exchange_method_wrappers! { @extend; KucoinClient; public [
get_spot_24h_statistics(symbol => "symbol"),
get_client_ip_address(),
get_kyc_regions(),
get_spot_index_price(symbol => "symbol"),
get_futures_24h_statistics(),
]; private [
get_account_info(),
get_spot_account_type(),
add_sub_account(password => "password",sub_name => "subName",access => "access"),
]; }

crate::exchanges::impl_exchange_method_wrappers! { @extend; KucoinClient; public [
get_uta_oe_scurrency(),
get_uta_oes_currency(),
]; private [
get_withdrawal_history_by_id(withdrawal_id => "withdrawalId"),
get_withdrawal_history(currency => "currency"),
get_withdrawal_quotas(currency => "currency"),
get_loan_info(),
get_accounts(),
get_otc_loan_accounts(),
get_discount_rate_configs(),
get_uta_oes_custody_quota(),
get_uta_accounts(),
get_uta_discount_rate_configs(),
get_uta_loan_info(),
get_uta_withdrawal_history(),
get_uta_withdrawal_quotas(currency => "currency",withdraw_type => "withdrawType"),
]; }

crate::exchanges::impl_exchange_method_wrappers! {@extend;KucoinClient;public [];private [set_uta_account_mode(account_type => "accountType")];}

crate::exchanges::impl_exchange_method_wrappers! {@extend;KucoinClient;public [get_currencies_v3()];private [];}
