//! Endpoint-specific request schemas extracted from official OKX documentation.
use super::RiskEndpoint;
pub(super) fn endpoint(name: &str) -> Option<RiskEndpoint> {
    Some(match name {
        "reset_mmp" => RiskEndpoint {
            path: "/api/v5/account/mmp-reset",
            post: true,
            public: false,
            keys: &["instType", "instFamily"],
            required: &["instFamily"],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"instType":{"type":"string"},"instFamily":{"type":"string"}},"required":["instFamily"]}"#,
            ),
        },
        "set_mmp_config" => RiskEndpoint {
            path: "/api/v5/account/mmp-config",
            post: true,
            public: false,
            keys: &["instFamily", "timeInterval", "frozenInterval", "qtyLimit"],
            required: &["instFamily", "timeInterval", "frozenInterval", "qtyLimit"],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"instFamily":{"type":"string"},"timeInterval":{"type":"string"},"frozenInterval":{"type":"string"},"qtyLimit":{"type":"string"}},"required":["instFamily","timeInterval","frozenInterval","qtyLimit"]}"#,
            ),
        },
        "get_mmp_config" => RiskEndpoint {
            path: "/api/v5/account/mmp-config",
            post: false,
            public: false,
            keys: &["instFamily"],
            required: &[],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"instFamily":{"type":"string"}},"required":[]}"#,
            ),
        },
        "get_glp_today_performance" => RiskEndpoint {
            path: "/api/v5/users/glp/todayperformance",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            bools: &[],
            schema: Some(r#"{"type":"object","properties":{},"required":[]}"#),
        },
        "get_glp_historical_performance" => RiskEndpoint {
            path: "/api/v5/users/glp/historicalperformance",
            post: false,
            public: false,
            keys: &["program", "begin", "end", "limit"],
            required: &["program"],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"program":{"type":"string"},"begin":{"type":"string"},"end":{"type":"string"},"limit":{"type":"string"}},"required":["program"]}"#,
            ),
        },
        "mass_cancel_options_orders" => RiskEndpoint {
            path: "/api/v5/trade/mass-cancel",
            post: true,
            public: false,
            keys: &["instType", "instFamily", "lockInterval"],
            required: &["instType", "instFamily"],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"instType":{"type":"string"},"instFamily":{"type":"string"},"lockInterval":{"type":"string"}},"required":["instType","instFamily"]}"#,
            ),
        },
        "create_rfq_quote" => RiskEndpoint {
            path: "/api/v5/rfq/create-quote",
            post: true,
            public: false,
            keys: &[
                "rfqId",
                "clQuoteId",
                "tag",
                "anonymous",
                "quoteSide",
                "expiresIn",
                "legs",
            ],
            required: &["rfqId", "quoteSide", "legs"],
            bools: &["anonymous"],
            schema: Some(
                r#"{"type":"object","properties":{"rfqId":{"type":"string"},"clQuoteId":{"type":"string"},"tag":{"type":"string"},"anonymous":{"type":"boolean"},"quoteSide":{"type":"string"},"expiresIn":{"type":"string"},"legs":{"type":"array","items":{"type":"object","properties":{"instId":{"type":"string"},"tdMode":{"type":"string"},"ccy":{"type":"string"},"sz":{"type":"string"},"px":{"type":"string"},"side":{"type":"string"},"posSide":{"type":"string"},"tgtCcy":{"type":"string"},"tradeQuoteCcy":{"type":"string"}},"required":["instId","sz","px","side"]}}},"required":["rfqId","quoteSide","legs"]}"#,
            ),
        },
        "cancel_rfq_quote" => RiskEndpoint {
            path: "/api/v5/rfq/cancel-quote",
            post: true,
            public: false,
            keys: &["quoteId", "clQuoteId", "rfqId"],
            required: &[],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"quoteId":{"type":"string"},"clQuoteId":{"type":"string"},"rfqId":{"type":"string"}},"required":[]}"#,
            ),
        },
        "get_rfq_maker_instrument_settings" => RiskEndpoint {
            path: "/api/v5/rfq/maker-instrument-settings",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            bools: &[],
            schema: Some(r#"{"type":"object","properties":{},"required":[]}"#),
        },
        "set_rfq_maker_instrument_settings" => RiskEndpoint {
            path: "/api/v5/rfq/maker-instrument-settings",
            post: true,
            public: false,
            keys: &["instType", "includeAll", "data"],
            required: &["instType", "data"],
            bools: &["includeAll"],
            schema: Some(
                r#"{"type":"object","properties":{"instType":{"type":"string"},"includeAll":{"type":"boolean"},"data":{"type":"array","items":{"type":"object","properties":{"instFamily":{"type":"string"},"instId":{"type":"string"},"maxBlockSz":{"type":"string"},"makerPxBand":{"type":"string"}},"required":[]}}},"required":["instType","data"]}"#,
            ),
        },
        "reset_rfq_mmp" => RiskEndpoint {
            path: "/api/v5/rfq/mmp-reset",
            post: true,
            public: false,
            keys: &[],
            required: &[],
            bools: &[],
            schema: Some(r#"{"type":"object","properties":{},"required":[]}"#),
        },
        "set_rfq_mmp_config" => RiskEndpoint {
            path: "/api/v5/rfq/mmp-config",
            post: true,
            public: false,
            keys: &["timeInterval", "frozenInterval", "countLimit"],
            required: &["timeInterval", "frozenInterval", "countLimit"],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"timeInterval":{"type":"string"},"frozenInterval":{"type":"string"},"countLimit":{"type":"string"}},"required":["timeInterval","frozenInterval","countLimit"]}"#,
            ),
        },
        "get_rfq_mmp_config" => RiskEndpoint {
            path: "/api/v5/rfq/mmp-config",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            bools: &[],
            schema: Some(r#"{"type":"object","properties":{},"required":[]}"#),
        },
        "cancel_rfq_batch_quotes" => RiskEndpoint {
            path: "/api/v5/rfq/cancel-batch-quotes",
            post: true,
            public: false,
            keys: &["quoteIds", "clQuoteIds"],
            required: &[],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"quoteIds":{"type":"array","items":{"type":"string"}},"clQuoteIds":{"type":"array","items":{"type":"string"}}},"required":[]}"#,
            ),
        },
        "cancel_all_rfq_quotes" => RiskEndpoint {
            path: "/api/v5/rfq/cancel-all-quotes",
            post: true,
            public: false,
            keys: &[],
            required: &[],
            bools: &[],
            schema: Some(r#"{"type":"object","properties":{},"required":[]}"#),
        },
        "set_rfq_cancel_all_after" => RiskEndpoint {
            path: "/api/v5/rfq/cancel-all-after",
            post: true,
            public: false,
            keys: &["timeOut"],
            required: &["timeOut"],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"timeOut":{"type":"string"}},"required":["timeOut"]}"#,
            ),
        },
        "get_mm_instrument_types" => RiskEndpoint {
            path: "/api/v5/public/mm-instrument-types",
            post: false,
            public: true,
            keys: &["instType", "instId"],
            required: &[],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"instType":{"type":"string"},"instId":{"type":"string"}},"required":[]}"#,
            ),
        },
        "create_withdrawal" => RiskEndpoint {
            path: "/api/v5/asset/withdrawal",
            post: true,
            public: false,
            keys: &[
                "ccy",
                "amt",
                "dest",
                "toAddr",
                "toAddrType",
                "chain",
                "areaCode",
                "rcvrInfo",
                "clientId",
            ],
            required: &["ccy", "amt", "dest", "toAddr"],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"ccy":{"type":"string"},"amt":{"type":"string"},"dest":{"type":"string"},"toAddr":{"type":"string"},"toAddrType":{"type":"string"},"chain":{"type":"string"},"areaCode":{"type":"string"},"rcvrInfo":{"type":"object","properties":{"walletType":{"type":"string"},"exchId":{"type":"string"},"rcvrFirstName":{"type":"string"},"rcvrLastName":{"type":"string"},"rcvrCountry":{"type":"string"},"rcvrCountrySubDivision":{"type":"string"},"rcvrTownName":{"type":"string"},"rcvrStreetName":{"type":"string"}},"required":["walletType"]},"clientId":{"type":"string"}},"required":["ccy","amt","dest","toAddr"]}"#,
            ),
        },
        "cancel_withdrawal" => RiskEndpoint {
            path: "/api/v5/asset/cancel-withdrawal",
            post: true,
            public: false,
            keys: &["wdId"],
            required: &["wdId"],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"wdId":{"type":"string"}},"required":["wdId"]}"#,
            ),
        },
        "create_fiat_withdrawal" => RiskEndpoint {
            path: "/api/v5/fiat/create-withdrawal",
            post: true,
            public: false,
            keys: &["paymentAcctId", "ccy", "amt", "paymentMethod", "clientId"],
            required: &["paymentAcctId", "ccy", "amt", "paymentMethod", "clientId"],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"paymentAcctId":{"type":"string"},"ccy":{"type":"string"},"amt":{"type":"string"},"paymentMethod":{"type":"string"},"clientId":{"type":"string"}},"required":["paymentAcctId","ccy","amt","paymentMethod","clientId"]}"#,
            ),
        },
        "cancel_fiat_withdrawal" => RiskEndpoint {
            path: "/api/v5/fiat/cancel-withdrawal",
            post: true,
            public: false,
            keys: &["ordId"],
            required: &["ordId"],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"ordId":{"type":"string"}},"required":["ordId"]}"#,
            ),
        },
        "get_affiliate_performance_summary" => RiskEndpoint {
            path: "/api/v5/affiliate/performance/summary",
            post: false,
            public: false,
            keys: &["periodType", "begin", "end"],
            required: &[],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"periodType":{"type":"string"},"begin":{"type":"string"},"end":{"type":"string"}},"required":[]}"#,
            ),
        },
        "get_affiliate_invitee_detail" => RiskEndpoint {
            path: "/api/v5/affiliate/invitee/detail",
            post: false,
            public: false,
            keys: &["uid", "periodType"],
            required: &["uid"],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"uid":{"type":"string"},"periodType":{"type":"string"}},"required":["uid"]}"#,
            ),
        },
        "get_affiliate_invitee_list" => RiskEndpoint {
            path: "/api/v5/affiliate/invitee/list",
            post: false,
            public: false,
            keys: &[
                "page",
                "limit",
                "periodType",
                "begin",
                "end",
                "keyword",
                "commissionCategory",
                "orderBy",
                "orderDir",
                "kycStatus",
                "subAffiliateUid",
                "uid",
                "joinTimeBegin",
                "joinTimeEnd",
            ],
            required: &[],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"page":{"type":"string"},"limit":{"type":"string"},"periodType":{"type":"string"},"begin":{"type":"string"},"end":{"type":"string"},"keyword":{"type":"string"},"commissionCategory":{"type":"string"},"orderBy":{"type":"string"},"orderDir":{"type":"string"},"kycStatus":{"type":"string"},"subAffiliateUid":{"type":"string"},"uid":{"type":"string"},"joinTimeBegin":{"type":"string"},"joinTimeEnd":{"type":"string"}},"required":[]}"#,
            ),
        },
        "get_affiliate_links" => RiskEndpoint {
            path: "/api/v5/affiliate/link/list",
            post: false,
            public: false,
            keys: &["page", "limit", "linkType", "linkStatus"],
            required: &[],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"page":{"type":"string"},"limit":{"type":"string"},"linkType":{"type":"string"},"linkStatus":{"type":"string"}},"required":[]}"#,
            ),
        },
        "get_affiliate_co_inviters" => RiskEndpoint {
            path: "/api/v5/affiliate/co-inviter/list",
            post: false,
            public: false,
            keys: &["page", "limit", "linkStatus"],
            required: &[],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"page":{"type":"string"},"limit":{"type":"string"},"linkStatus":{"type":"string"}},"required":[]}"#,
            ),
        },
        "get_sub_affiliates" => RiskEndpoint {
            path: "/api/v5/affiliate/sub-affiliate/list",
            post: false,
            public: false,
            keys: &[
                "page",
                "limit",
                "keyword",
                "commissionCategory",
                "orderBy",
                "orderDir",
            ],
            required: &[],
            bools: &[],
            schema: Some(
                r#"{"type":"object","properties":{"page":{"type":"string"},"limit":{"type":"string"},"keyword":{"type":"string"},"commissionCategory":{"type":"string"},"orderBy":{"type":"string"},"orderDir":{"type":"string"}},"required":[]}"#,
            ),
        },
        _ => return None,
    })
}
