use super::RiskEndpoint;
pub(super) fn endpoint(name: &str) -> Option<RiskEndpoint> {
    Some(match name {
        "get_server_time" => RiskEndpoint {
            path: "/api/v5/public/time",
            post: false,
            public: true,
            keys: &[],
            required: &[],
            bools: &[],
            schema: None,
        },
        "set_isolated_mode" => RiskEndpoint {
            path: "/api/v5/account/set-isolated-mode",
            post: true,
            public: false,
            keys: &["isoMode", "type"],
            required: &["isoMode", "type"],
            bools: &[],
            schema: None,
        },
        "get_account_risk_state" => RiskEndpoint {
            path: "/api/v5/account/risk-state",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            bools: &[],
            schema: None,
        },
        "get_greeks" => RiskEndpoint {
            path: "/api/v5/account/greeks",
            post: false,
            public: false,
            keys: &["ccy"],
            required: &[],
            bools: &[],
            schema: None,
        },
        "get_pm_position_tiers" => RiskEndpoint {
            path: "/api/v5/account/position-tiers",
            post: false,
            public: false,
            keys: &["instType", "instFamily"],
            required: &["instType", "instFamily"],
            bools: &[],
            schema: None,
        },
        "set_account_level" => RiskEndpoint {
            path: "/api/v5/account/set-account-level",
            post: true,
            public: false,
            keys: &["acctLv"],
            required: &["acctLv"],
            bools: &[],
            schema: None,
        },
        "get_collateral_assets" => RiskEndpoint {
            path: "/api/v5/account/collateral-assets",
            post: false,
            public: false,
            keys: &["ccy", "collateralEnabled"],
            required: &[],
            bools: &["collateralEnabled"],
            schema: None,
        },
        "get_ticker" => RiskEndpoint {
            path: "/api/v5/market/ticker",
            post: false,
            public: true,
            keys: &["instId", "product_symbol"],
            required: &["instId"],
            bools: &[],
            schema: None,
        },
        "get_full_orderbook" => RiskEndpoint {
            path: "/api/v5/market/books-full",
            post: false,
            public: true,
            keys: &["instId", "sz", "product_symbol"],
            required: &["instId"],
            bools: &[],
            schema: None,
        },
        "get_candles_history" => RiskEndpoint {
            path: "/api/v5/market/history-candles",
            post: false,
            public: true,
            keys: &[
                "instId",
                "after",
                "before",
                "bar",
                "limit",
                "adjust",
                "product_symbol",
            ],
            required: &["instId"],
            bools: &[],
            schema: None,
        },
        "get_trades_history" => RiskEndpoint {
            path: "/api/v5/market/history-trades",
            post: false,
            public: true,
            keys: &[
                "instId",
                "type",
                "after",
                "before",
                "limit",
                "product_symbol",
            ],
            required: &["instId"],
            bools: &[],
            schema: None,
        },
        "amend_spread_order" => RiskEndpoint {
            path: "/api/v5/sprd/amend-order",
            post: true,
            public: false,
            keys: &["ordId", "clOrdId", "reqId", "newSz", "newPx"],
            required: &[],
            bools: &[],
            schema: None,
        },
        "get_estimated_delivery_price" => RiskEndpoint {
            path: "/api/v5/public/estimated-price",
            post: false,
            public: true,
            keys: &["instId", "product_symbol"],
            required: &["instId"],
            bools: &[],
            schema: None,
        },
        "get_discount_rates" => RiskEndpoint {
            path: "/api/v5/public/discount-rate-interest-free-quota",
            post: false,
            public: true,
            keys: &["ccy"],
            required: &[],
            bools: &[],
            schema: None,
        },
        "convert_contract_coin" => RiskEndpoint {
            path: "/api/v5/public/convert-contract-coin",
            post: false,
            public: true,
            keys: &[
                "type",
                "instId",
                "sz",
                "px",
                "unit",
                "opType",
                "product_symbol",
            ],
            required: &["instId", "sz"],
            bools: &[],
            schema: None,
        },
        "get_index_tickers" => RiskEndpoint {
            path: "/api/v5/market/index-tickers",
            post: false,
            public: true,
            keys: &["quoteCcy", "instId", "product_symbol"],
            required: &[],
            bools: &[],
            schema: None,
        },
        "get_mark_price_candles" => RiskEndpoint {
            path: "/api/v5/market/mark-price-candles",
            post: false,
            public: true,
            keys: &[
                "instId",
                "after",
                "before",
                "bar",
                "limit",
                "product_symbol",
            ],
            required: &["instId"],
            bools: &[],
            schema: None,
        },
        "get_asset_bill_history" => RiskEndpoint {
            path: "/api/v5/asset/bills-history",
            post: false,
            public: false,
            keys: &[
                "ccy",
                "type",
                "thirdPartyType",
                "clientId",
                "after",
                "before",
                "limit",
                "pagingType",
            ],
            required: &[],
            bools: &[],
            schema: None,
        },
        "get_convert_currency_pair" => RiskEndpoint {
            path: "/api/v5/asset/convert/currency-pair",
            post: false,
            public: false,
            keys: &["fromCcy", "toCcy", "convertMode"],
            required: &["fromCcy", "toCcy"],
            bools: &[],
            schema: None,
        },
        "estimate_convert_quote" => RiskEndpoint {
            path: "/api/v5/asset/convert/estimate-quote",
            post: true,
            public: false,
            keys: &[
                "baseCcy",
                "quoteCcy",
                "side",
                "rfqSz",
                "rfqSzCcy",
                "clQReqId",
                "convertMode",
            ],
            required: &["baseCcy", "quoteCcy", "side", "rfqSz", "rfqSzCcy"],
            bools: &[],
            schema: None,
        },
        "execute_convert_trade" => RiskEndpoint {
            path: "/api/v5/asset/convert/trade",
            post: true,
            public: false,
            keys: &[
                "quoteId",
                "baseCcy",
                "quoteCcy",
                "side",
                "sz",
                "szCcy",
                "clTReqId",
                "convertMode",
            ],
            required: &["quoteId", "baseCcy", "quoteCcy", "side", "sz", "szCcy"],
            bools: &[],
            schema: None,
        },
        "get_system_status" => RiskEndpoint {
            path: "/api/v5/system/status",
            post: false,
            public: true,
            keys: &["state"],
            required: &[],
            bools: &[],
            schema: None,
        },
        "set_fee_type" => RiskEndpoint {
            path: "/api/v5/account/set-fee-type",
            post: true,
            public: false,
            keys: &["feeType"],
            required: &["feeType"],
            bools: &[],
            schema: None,
        },
        "set_risk_offset_amount" => RiskEndpoint {
            path: "/api/v5/account/set-riskOffset-amt",
            post: true,
            public: false,
            keys: &["ccy", "clSpotInUseAmt"],
            required: &["ccy", "clSpotInUseAmt"],
            bools: &[],
            schema: None,
        },
        "activate_options" => RiskEndpoint {
            path: "/api/v5/account/activate-option",
            post: true,
            public: false,
            keys: &[],
            required: &[],
            bools: &[],
            schema: None,
        },
        "set_auto_loan" => RiskEndpoint {
            path: "/api/v5/account/set-auto-loan",
            post: true,
            public: false,
            keys: &["autoLoan"],
            required: &[],
            bools: &["autoLoan"],
            schema: None,
        },
        "preset_account_level_switch" => RiskEndpoint {
            path: "/api/v5/account/account-level-switch-preset",
            post: true,
            public: false,
            keys: &["acctLv", "lever"],
            required: &["acctLv"],
            bools: &[],
            schema: None,
        },
        "precheck_account_level_switch" => RiskEndpoint {
            path: "/api/v5/account/set-account-switch-precheck",
            post: false,
            public: false,
            keys: &["acctLv"],
            required: &["acctLv"],
            bools: &[],
            schema: None,
        },
        "set_collateral_assets" => RiskEndpoint {
            path: "/api/v5/account/set-collateral-assets",
            post: true,
            public: false,
            keys: &["type", "collateralEnabled", "ccyList"],
            required: &["type", "collateralEnabled"],
            bools: &["collateralEnabled"],
            schema: None,
        },
        "set_settlement_currency" => RiskEndpoint {
            path: "/api/v5/account/set-settle-currency",
            post: true,
            public: false,
            keys: &["settleCcy"],
            required: &["settleCcy"],
            bools: &[],
            schema: None,
        },
        "set_trading_config" => RiskEndpoint {
            path: "/api/v5/account/set-trading-config",
            post: true,
            public: false,
            keys: &["type", "stgyType"],
            required: &["type"],
            bools: &[],
            schema: None,
        },
        "precheck_delta_neutral" => RiskEndpoint {
            path: "/api/v5/account/precheck-set-delta-neutral",
            post: false,
            public: false,
            keys: &["stgyType"],
            required: &["stgyType"],
            bools: &[],
            schema: None,
        },
        "get_repayment_currencies" => RiskEndpoint {
            path: "/api/v5/trade/one-click-repay-currency-list-v2",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            bools: &[],
            schema: None,
        },
        "repay_debt" => RiskEndpoint {
            path: "/api/v5/trade/one-click-repay-v2",
            post: true,
            public: false,
            keys: &["debtCcy", "repayCcyList"],
            required: &["debtCcy", "repayCcyList"],
            bools: &[],
            schema: None,
        },
        "get_repayment_history" => RiskEndpoint {
            path: "/api/v5/trade/one-click-repay-history-v2",
            post: false,
            public: false,
            keys: &["after", "before", "limit"],
            required: &[],
            bools: &[],
            schema: None,
        },
        "get_spread_order_history_archive" => RiskEndpoint {
            path: "/api/v5/sprd/orders-history-archive",
            post: false,
            public: false,
            keys: &[
                "sprdId",
                "ordType",
                "state",
                "instType",
                "instFamily",
                "beginId",
                "endId",
                "begin",
                "end",
                "limit",
            ],
            required: &[],
            bools: &[],
            schema: None,
        },
        // https://www.okx.com/docs-v5/en/#trading-account-rest-api-get-bill-types
        "get_bill_types" => RiskEndpoint {
            path: "/api/v5/account/subtypes",
            post: false,
            public: false,
            keys: &["type"],
            required: &[],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"type\":{\"type\":\"string\"}},\"required\":[]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#trading-account-rest-api-position-builder-new
        "simulate_positions" => RiskEndpoint {
            path: "/api/v5/account/position-builder",
            post: true,
            public: false,
            keys: &[
                "acctLv",
                "inclRealPosAndEq",
                "lever",
                "simPos",
                "simAsset",
                "greeksType",
                "idxVol",
            ],
            required: &[],
            bools: &["inclRealPosAndEq"],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"acctLv\":{\"type\":\"string\"},\"inclRealPosAndEq\":{\"type\":\"boolean\"},\"lever\":{\"type\":\"string\"},\"simPos\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"instId\":{\"type\":\"string\"},\"pos\":{\"type\":\"string\"},\"avgPx\":{\"type\":\"string\"},\"lever\":{\"type\":\"string\"}},\"required\":[\"instId\",\"pos\",\"avgPx\"]}},\"simAsset\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"ccy\":{\"type\":\"string\"},\"amt\":{\"type\":\"string\"}},\"required\":[\"ccy\",\"amt\"]}},\"greeksType\":{\"type\":\"string\"},\"idxVol\":{\"type\":\"string\"}},\"required\":[]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#trading-account-rest-api-position-builder-trend-graph
        "get_position_margin_graph" => RiskEndpoint {
            path: "/api/v5/account/position-builder-graph",
            post: true,
            public: false,
            keys: &[
                "inclRealPosAndEq",
                "simPos",
                "simAsset",
                "type",
                "mmrConfig",
            ],
            required: &["type", "mmrConfig"],
            bools: &["inclRealPosAndEq"],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"inclRealPosAndEq\":{\"type\":\"boolean\"},\"simPos\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"instId\":{\"type\":\"string\"},\"pos\":{\"type\":\"string\"},\"avgPx\":{\"type\":\"string\"},\"lever\":{\"type\":\"string\"}},\"required\":[\"instId\",\"pos\",\"avgPx\"]}},\"simAsset\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"ccy\":{\"type\":\"string\"},\"amt\":{\"type\":\"string\"}},\"required\":[\"ccy\",\"amt\"]}},\"type\":{\"type\":\"string\"},\"mmrConfig\":{\"type\":\"object\",\"properties\":{\"acctLv\":{\"type\":\"string\"},\"lever\":{\"type\":\"string\"}},\"required\":[]}},\"required\":[\"type\",\"mmrConfig\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#trading-account-rest-api-move-positions
        "move_positions" => RiskEndpoint {
            path: "/api/v5/account/move-positions",
            post: true,
            public: false,
            keys: &["fromAcct", "toAcct", "legs", "clientId"],
            required: &["fromAcct", "toAcct", "legs", "clientId"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"fromAcct\":{\"type\":\"string\"},\"toAcct\":{\"type\":\"string\"},\"legs\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"from\":{\"type\":\"object\",\"properties\":{\"posId\":{\"type\":\"string\"},\"sz\":{\"type\":\"string\"},\"side\":{\"type\":\"string\"}},\"required\":[\"posId\",\"sz\",\"side\"]},\"to\":{\"type\":\"object\",\"properties\":{\"tdMode\":{\"type\":\"string\"},\"posSide\":{\"type\":\"string\"},\"ccy\":{\"type\":\"string\"}},\"required\":[]}},\"required\":[\"from\",\"to\"]}},\"clientId\":{\"type\":\"string\"}},\"required\":[\"fromAcct\",\"toAcct\",\"legs\",\"clientId\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#trading-account-rest-api-get-move-positions-history
        "get_move_positions_history" => RiskEndpoint {
            path: "/api/v5/account/move-positions-history",
            post: false,
            public: false,
            keys: &[
                "blockTdId",
                "clientId",
                "beginTs",
                "endTs",
                "limit",
                "state",
            ],
            required: &[],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"blockTdId\":{\"type\":\"string\"},\"clientId\":{\"type\":\"string\"},\"beginTs\":{\"type\":\"string\"},\"endTs\":{\"type\":\"string\"},\"limit\":{\"type\":\"string\"},\"state\":{\"type\":\"string\"}},\"required\":[]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#trading-account-rest-api-adjust-demo-account-balance
        "adjust_demo_balance" => RiskEndpoint {
            path: "/api/v5/account/demo-adjust-balance",
            post: true,
            public: false,
            keys: &["type", "adjustments"],
            required: &["type", "adjustments"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"type\":{\"type\":\"string\"},\"adjustments\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"ccy\":{\"type\":\"string\"},\"amt\":{\"type\":\"string\"}},\"required\":[\"ccy\",\"amt\"]}}},\"required\":[\"type\",\"adjustments\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#order-book-trading-market-data-get-rpi-order-book
        "get_books_rpi" => RiskEndpoint {
            path: "/api/v5/market/books-rpi",
            post: false,
            public: true,
            keys: &["instId", "sz"],
            required: &["instId"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"instId\":{\"type\":\"string\"},\"sz\":{\"type\":\"string\"}},\"required\":[\"instId\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#order-book-trading-market-data-get-24h-total-volume
        "get_platform_24_volume" => RiskEndpoint {
            path: "/api/v5/market/platform-24-volume",
            post: false,
            public: true,
            keys: &[],
            required: &[],
            bools: &[],
            schema: Some("{\"type\":\"object\",\"properties\":{},\"required\":[]}"),
        },
        // https://www.okx.com/docs-v5/en/#order-book-trading-market-data-get-call-auction-details
        "get_call_auction_details" => RiskEndpoint {
            path: "/api/v5/market/call-auction-details",
            post: false,
            public: true,
            keys: &["instId"],
            required: &["instId"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"instId\":{\"type\":\"string\"}},\"required\":[\"instId\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#block-trading-rest-api-create-rfq
        "rfq_create_rfq" => RiskEndpoint {
            path: "/api/v5/rfq/create-rfq",
            post: true,
            public: false,
            keys: &[
                "counterparties",
                "anonymous",
                "clRfqId",
                "tag",
                "allowPartialExecution",
                "legs",
                "acctAlloc",
            ],
            required: &["counterparties", "legs"],
            bools: &["anonymous", "allowPartialExecution"],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"counterparties\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"properties\":{},\"required\":[]}},\"anonymous\":{\"type\":\"boolean\"},\"clRfqId\":{\"type\":\"string\"},\"tag\":{\"type\":\"string\"},\"allowPartialExecution\":{\"type\":\"boolean\"},\"legs\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"instId\":{\"type\":\"string\"},\"tdMode\":{\"type\":\"string\"},\"ccy\":{\"type\":\"string\"},\"sz\":{\"type\":\"string\"},\"lmtPx\":{\"type\":\"string\"},\"side\":{\"type\":\"string\"},\"posSide\":{\"type\":\"string\"},\"tgtCcy\":{\"type\":\"string\"},\"tradeQuoteCcy\":{\"type\":\"string\"}},\"required\":[\"instId\",\"sz\",\"side\"]}},\"acctAlloc\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"acct\":{\"type\":\"string\"},\"legs\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"sz\":{\"type\":\"string\"},\"instId\":{\"type\":\"string\"},\"tdMode\":{\"type\":\"string\"},\"ccy\":{\"type\":\"string\"},\"posSide\":{\"type\":\"string\"}},\"required\":[\"sz\",\"instId\"]}}},\"required\":[\"acct\",\"legs\"]}}},\"required\":[\"counterparties\",\"legs\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#block-trading-rest-api-get-counterparties
        "get_rfq_counterparties" => RiskEndpoint {
            path: "/api/v5/rfq/counterparties",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            bools: &[],
            schema: Some("{\"type\":\"object\",\"properties\":{},\"required\":[]}"),
        },
        // https://www.okx.com/docs-v5/en/#block-trading-rest-api-cancel-rfq
        "rfq_cancel_rfq" => RiskEndpoint {
            path: "/api/v5/rfq/cancel-rfq",
            post: true,
            public: false,
            keys: &["rfqId", "clRfqId"],
            required: &[],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"rfqId\":{\"type\":\"string\"},\"clRfqId\":{\"type\":\"string\"}},\"required\":[]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#block-trading-rest-api-cancel-multiple-rfqs
        "rfq_cancel_batch_rfqs" => RiskEndpoint {
            path: "/api/v5/rfq/cancel-batch-rfqs",
            post: true,
            public: false,
            keys: &["rfqIds", "clRfqIds"],
            required: &[],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"rfqIds\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"properties\":{},\"required\":[]}},\"clRfqIds\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"properties\":{},\"required\":[]}}},\"required\":[]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#block-trading-rest-api-cancel-all-rfqs
        "rfq_cancel_all_rfqs" => RiskEndpoint {
            path: "/api/v5/rfq/cancel-all-rfqs",
            post: true,
            public: false,
            keys: &[],
            required: &[],
            bools: &[],
            schema: Some("{\"type\":\"object\",\"properties\":{},\"required\":[]}"),
        },
        // https://www.okx.com/docs-v5/en/#block-trading-rest-api-execute-quote
        "rfq_execute_quote" => RiskEndpoint {
            path: "/api/v5/rfq/execute-quote",
            post: true,
            public: false,
            keys: &["rfqId", "quoteId", "legs"],
            required: &["rfqId", "quoteId"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"rfqId\":{\"type\":\"string\"},\"quoteId\":{\"type\":\"string\"},\"legs\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"instId\":{\"type\":\"string\"},\"sz\":{\"type\":\"string\"}},\"required\":[\"instId\",\"sz\"]}}},\"required\":[\"rfqId\",\"quoteId\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#block-trading-rest-api-get-rfqs
        "get_rfq_rfqs" => RiskEndpoint {
            path: "/api/v5/rfq/rfqs",
            post: false,
            public: false,
            keys: &["rfqId", "clRfqId", "state", "beginId", "endId", "limit"],
            required: &[],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"rfqId\":{\"type\":\"string\"},\"clRfqId\":{\"type\":\"string\"},\"state\":{\"type\":\"string\"},\"beginId\":{\"type\":\"string\"},\"endId\":{\"type\":\"string\"},\"limit\":{\"type\":\"string\"}},\"required\":[]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#block-trading-rest-api-get-quotes
        "get_rfq_quotes" => RiskEndpoint {
            path: "/api/v5/rfq/quotes",
            post: false,
            public: false,
            keys: &[
                "rfqId",
                "clRfqId",
                "quoteId",
                "clQuoteId",
                "state",
                "beginId",
                "endId",
                "limit",
            ],
            required: &[],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"rfqId\":{\"type\":\"string\"},\"clRfqId\":{\"type\":\"string\"},\"quoteId\":{\"type\":\"string\"},\"clQuoteId\":{\"type\":\"string\"},\"state\":{\"type\":\"string\"},\"beginId\":{\"type\":\"string\"},\"endId\":{\"type\":\"string\"},\"limit\":{\"type\":\"string\"}},\"required\":[]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#block-trading-rest-api-get-trades
        "get_rfq_trades" => RiskEndpoint {
            path: "/api/v5/rfq/trades",
            post: false,
            public: false,
            keys: &[
                "rfqId",
                "clRfqId",
                "quoteId",
                "blockTdId",
                "clQuoteId",
                "beginId",
                "endId",
                "beginTs",
                "endTs",
                "limit",
                "isSuccessful",
            ],
            required: &[],
            bools: &["isSuccessful"],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"rfqId\":{\"type\":\"string\"},\"clRfqId\":{\"type\":\"string\"},\"quoteId\":{\"type\":\"string\"},\"blockTdId\":{\"type\":\"string\"},\"clQuoteId\":{\"type\":\"string\"},\"beginId\":{\"type\":\"string\"},\"endId\":{\"type\":\"string\"},\"beginTs\":{\"type\":\"string\"},\"endTs\":{\"type\":\"string\"},\"limit\":{\"type\":\"string\"},\"isSuccessful\":{\"type\":\"boolean\"}},\"required\":[]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#block-trading-rest-api-get-block-tickers
        "get_block_tickers" => RiskEndpoint {
            path: "/api/v5/market/block-tickers",
            post: false,
            public: true,
            keys: &["instType", "instFamily"],
            required: &["instType"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"instType\":{\"type\":\"string\"},\"instFamily\":{\"type\":\"string\"}},\"required\":[\"instType\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#block-trading-rest-api-get-block-ticker
        "get_block_ticker" => RiskEndpoint {
            path: "/api/v5/market/block-ticker",
            post: false,
            public: true,
            keys: &["instId"],
            required: &["instId"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"instId\":{\"type\":\"string\"}},\"required\":[\"instId\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#block-trading-rest-api-get-public-multi-leg-transactions-of-block-trades
        "get_rfq_public_trades" => RiskEndpoint {
            path: "/api/v5/rfq/public-trades",
            post: false,
            public: true,
            keys: &["beginId", "endId", "limit"],
            required: &[],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"beginId\":{\"type\":\"string\"},\"endId\":{\"type\":\"string\"},\"limit\":{\"type\":\"string\"}},\"required\":[]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#block-trading-rest-api-get-public-single-leg-transactions-of-block-trades
        "get_block_trades" => RiskEndpoint {
            path: "/api/v5/public/block-trades",
            post: false,
            public: true,
            keys: &["instId"],
            required: &["instId"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"instId\":{\"type\":\"string\"}},\"required\":[\"instId\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#public-data-rest-api-get-estimated-future-settlement-price
        "get_estimated_settlement_info" => RiskEndpoint {
            path: "/api/v5/public/estimated-settlement-info",
            post: false,
            public: true,
            keys: &["instId"],
            required: &["instId"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"instId\":{\"type\":\"string\"}},\"required\":[\"instId\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#public-data-rest-api-get-futures-settlement-history
        "get_settlement_history" => RiskEndpoint {
            path: "/api/v5/public/settlement-history",
            post: false,
            public: true,
            keys: &["instFamily", "after", "before", "limit"],
            required: &["instFamily"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"instFamily\":{\"type\":\"string\"},\"after\":{\"type\":\"string\"},\"before\":{\"type\":\"string\"},\"limit\":{\"type\":\"string\"}},\"required\":[\"instFamily\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#public-data-rest-api-get-security-fund
        "get_insurance_fund" => RiskEndpoint {
            path: "/api/v5/public/insurance-fund",
            post: false,
            public: true,
            keys: &[
                "instType",
                "type",
                "instFamily",
                "ccy",
                "before",
                "after",
                "limit",
            ],
            required: &["instType"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"instType\":{\"type\":\"string\"},\"type\":{\"type\":\"string\"},\"instFamily\":{\"type\":\"string\"},\"ccy\":{\"type\":\"string\"},\"before\":{\"type\":\"string\"},\"after\":{\"type\":\"string\"},\"limit\":{\"type\":\"string\"}},\"required\":[\"instType\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#public-data-rest-api-get-premium-history
        "get_premium_history" => RiskEndpoint {
            path: "/api/v5/public/premium-history",
            post: false,
            public: true,
            keys: &["instId", "after", "before", "limit"],
            required: &["instId"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"instId\":{\"type\":\"string\"},\"after\":{\"type\":\"string\"},\"before\":{\"type\":\"string\"},\"limit\":{\"type\":\"string\"}},\"required\":[\"instId\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#public-data-rest-api-get-index-candlesticks
        "get_index_candles" => RiskEndpoint {
            path: "/api/v5/market/index-candles",
            post: false,
            public: true,
            keys: &["instId", "after", "before", "bar", "limit"],
            required: &["instId"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"instId\":{\"type\":\"string\"},\"after\":{\"type\":\"string\"},\"before\":{\"type\":\"string\"},\"bar\":{\"type\":\"string\"},\"limit\":{\"type\":\"string\"}},\"required\":[\"instId\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#public-data-rest-api-get-index-candlesticks-history
        "get_history_index_candles" => RiskEndpoint {
            path: "/api/v5/market/history-index-candles",
            post: false,
            public: true,
            keys: &["instId", "after", "before", "bar", "limit"],
            required: &["instId"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"instId\":{\"type\":\"string\"},\"after\":{\"type\":\"string\"},\"before\":{\"type\":\"string\"},\"bar\":{\"type\":\"string\"},\"limit\":{\"type\":\"string\"}},\"required\":[\"instId\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#public-data-rest-api-get-mark-price-candlesticks-history
        "get_history_mark_price_candles" => RiskEndpoint {
            path: "/api/v5/market/history-mark-price-candles",
            post: false,
            public: true,
            keys: &["instId", "after", "before", "bar", "limit"],
            required: &["instId"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"instId\":{\"type\":\"string\"},\"after\":{\"type\":\"string\"},\"before\":{\"type\":\"string\"},\"bar\":{\"type\":\"string\"},\"limit\":{\"type\":\"string\"}},\"required\":[\"instId\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#public-data-rest-api-get-exchange-rate
        "get_exchange_rate" => RiskEndpoint {
            path: "/api/v5/market/exchange-rate",
            post: false,
            public: true,
            keys: &[],
            required: &[],
            bools: &[],
            schema: Some("{\"type\":\"object\",\"properties\":{},\"required\":[]}"),
        },
        // https://www.okx.com/docs-v5/en/#public-data-rest-api-get-index-components
        "get_index_components" => RiskEndpoint {
            path: "/api/v5/market/index-components",
            post: false,
            public: true,
            keys: &["index"],
            required: &["index"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"index\":{\"type\":\"string\"}},\"required\":[\"index\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#public-data-rest-api-get-economic-calendar-data
        "get_economic_calendar" => RiskEndpoint {
            path: "/api/v5/public/economic-calendar",
            post: false,
            public: true,
            keys: &["region", "importance", "before", "after", "limit"],
            required: &[],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"region\":{\"type\":\"string\"},\"importance\":{\"type\":\"string\"},\"before\":{\"type\":\"string\"},\"after\":{\"type\":\"string\"},\"limit\":{\"type\":\"string\"}},\"required\":[]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#public-data-rest-api-get-historical-market-data
        "get_market_data_history" => RiskEndpoint {
            path: "/api/v5/public/market-data-history",
            post: false,
            public: true,
            keys: &[
                "module",
                "instType",
                "instIdList",
                "instFamilyList",
                "dateAggrType",
                "begin",
                "end",
            ],
            required: &["module", "instType", "dateAggrType", "begin", "end"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"module\":{\"type\":\"string\"},\"instType\":{\"type\":\"string\"},\"instIdList\":{\"type\":\"string\"},\"instFamilyList\":{\"type\":\"string\"},\"dateAggrType\":{\"type\":\"string\"},\"begin\":{\"type\":\"string\"},\"end\":{\"type\":\"string\"}},\"required\":[\"module\",\"instType\",\"dateAggrType\",\"begin\",\"end\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#public-data-rest-api-get-delta-hedge-currencies
        "get_delta_hedge_currencies" => RiskEndpoint {
            path: "/api/v5/public/delta-hedge-currencies",
            post: false,
            public: true,
            keys: &["ccy"],
            required: &[],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"ccy\":{\"type\":\"string\"}},\"required\":[]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#trading-statistics-rest-api-get-margin-long-short-ratio
        "get_loan_ratio" => RiskEndpoint {
            path: "/api/v5/rubik/stat/margin/loan-ratio",
            post: false,
            public: true,
            keys: &["ccy", "begin", "end", "period"],
            required: &["ccy"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"ccy\":{\"type\":\"string\"},\"begin\":{\"type\":\"string\"},\"end\":{\"type\":\"string\"},\"period\":{\"type\":\"string\"}},\"required\":[\"ccy\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#funding-account-rest-api-get-non-tradable-assets
        "get_non_tradable_assets" => RiskEndpoint {
            path: "/api/v5/asset/non-tradable-assets",
            post: false,
            public: false,
            keys: &["ccy"],
            required: &[],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"ccy\":{\"type\":\"string\"}},\"required\":[]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#sub-account-rest-api-create-sub-account
        "create_sub_account" => RiskEndpoint {
            path: "/api/v5/users/subaccount/create-subaccount",
            post: true,
            public: false,
            keys: &["subAcct", "type", "label", "pwd"],
            required: &["subAcct", "type"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"subAcct\":{\"type\":\"string\"},\"type\":{\"type\":\"string\"},\"label\":{\"type\":\"string\"},\"pwd\":{\"type\":\"string\"}},\"required\":[\"subAcct\",\"type\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#sub-account-rest-api-create-an-api-key-for-a-sub-account
        "create_sub_account_api_key" => RiskEndpoint {
            path: "/api/v5/users/subaccount/apikey",
            post: true,
            public: false,
            keys: &["subAcct", "label", "passphrase", "perm", "ip"],
            required: &["subAcct", "label", "passphrase"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"subAcct\":{\"type\":\"string\"},\"label\":{\"type\":\"string\"},\"passphrase\":{\"type\":\"string\"},\"perm\":{\"type\":\"string\"},\"ip\":{\"type\":\"string\"}},\"required\":[\"subAcct\",\"label\",\"passphrase\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#sub-account-rest-api-query-the-api-key-of-a-sub-account
        "get_sub_account_api_keys" => RiskEndpoint {
            path: "/api/v5/users/subaccount/apikey",
            post: false,
            public: false,
            keys: &["subAcct", "apiKey"],
            required: &["subAcct"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"subAcct\":{\"type\":\"string\"},\"apiKey\":{\"type\":\"string\"}},\"required\":[\"subAcct\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#sub-account-rest-api-reset-the-api-key-of-a-sub-account
        "modify_sub_account_api_key" => RiskEndpoint {
            path: "/api/v5/users/subaccount/modify-apikey",
            post: true,
            public: false,
            keys: &["subAcct", "apiKey", "label", "perm", "ip"],
            required: &["subAcct", "apiKey"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"subAcct\":{\"type\":\"string\"},\"apiKey\":{\"type\":\"string\"},\"label\":{\"type\":\"string\"},\"perm\":{\"type\":\"string\"},\"ip\":{\"type\":\"string\"}},\"required\":[\"subAcct\",\"apiKey\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#sub-account-rest-api-delete-the-api-key-of-sub-accounts
        "delete_sub_account_api_key" => RiskEndpoint {
            path: "/api/v5/users/subaccount/delete-apikey",
            post: true,
            public: false,
            keys: &["subAcct", "apiKey"],
            required: &["subAcct", "apiKey"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"subAcct\":{\"type\":\"string\"},\"apiKey\":{\"type\":\"string\"}},\"required\":[\"subAcct\",\"apiKey\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#sub-account-rest-api-set-permission-of-transfer-out
        "set_sub_account_transfer_out" => RiskEndpoint {
            path: "/api/v5/users/subaccount/set-transfer-out",
            post: true,
            public: false,
            keys: &["subAcct", "canTransOut"],
            required: &["subAcct"],
            bools: &["canTransOut"],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"subAcct\":{\"type\":\"string\"},\"canTransOut\":{\"type\":\"boolean\"}},\"required\":[\"subAcct\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#announcement-get-announcements
        "get_announcements" => RiskEndpoint {
            path: "/api/v5/support/announcements",
            post: false,
            public: true,
            keys: &["annType", "page"],
            required: &[],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"annType\":{\"type\":\"string\"},\"page\":{\"type\":\"string\"}},\"required\":[]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#announcement-get-announcement-types
        "get_announcement_types" => RiskEndpoint {
            path: "/api/v5/support/announcement-types",
            post: false,
            public: true,
            keys: &[],
            required: &[],
            bools: &[],
            schema: Some("{\"type\":\"object\",\"properties\":{},\"required\":[]}"),
        },
        _ => return None,
    })
}
