use super::client::OkxClient;

crate::exchanges::impl_exchange_method_wrappers! {
    OkxClient;
    public [
        get_server_time(),
        get_ticker(product_symbol => "product_symbol"),
        get_full_orderbook(product_symbol => "product_symbol"),
        get_candles_history(product_symbol => "product_symbol"),
        get_trades_history(product_symbol => "product_symbol"),
        get_estimated_delivery_price(product_symbol => "product_symbol"),
        get_discount_rates(),
        convert_contract_coin(product_symbol => "product_symbol", sz => "sz"),
        get_index_tickers(),
        get_mark_price_candles(product_symbol => "product_symbol"),
        get_system_status(),
        get_price_limit(product_symbol => "product_symbol"),
        get_mark_price(inst_type => "instType"),
        get_spread_spreads(),
        get_spread_books(sprd_id => "sprdId"),
        get_spread_ticker(sprd_id => "sprdId"),
        get_spread_public_trades(sprd_id => "sprdId"),
        get_spread_candles(sprd_id => "sprdId"),
        get_spread_history_candles(sprd_id => "sprdId"),
        get_candles_ticks(product_symbol => "product_symbol"),
        get_contract_long_short_ratio(product_symbol => "product_symbol"),
        get_contract_open_interest_history(product_symbol => "product_symbol"),
        get_contract_taker_volume(product_symbol => "product_symbol"),
        get_contracts_open_interest_and_volume(ccy => "ccy"),
        get_delivery_exercise_history(inst_type => "instType"),
        get_option_summary(),
        get_option_tick_bands(),
        get_option_trades(),
        get_option_family_trades(inst_family => "instFamily"),
        get_options_open_interest_and_volume(ccy => "ccy"),
        get_option_put_call_ratio(ccy => "ccy"),
        get_option_open_interest_and_volume_by_expiry(ccy => "ccy"),
        get_option_open_interest_and_volume_by_strike(ccy => "ccy", expiry_time => "expTime"),
        get_option_taker_block_volume(ccy => "ccy"),
        get_funding_rate(product_symbol => "product_symbol"),
        get_funding_rate_history(product_symbol => "product_symbol"),
        get_long_short_ratio(ccy => "ccy"),
        get_open_interest(inst_type => "instType"),
        get_orderbook(product_symbol => "product_symbol"),
        get_position_tiers(inst_type => "instType", td_mode => "tdMode"),
        get_public_instruments(inst_type => "instType"),
        get_public_underlying(inst_type => "instType"),
        get_public_trades(product_symbol => "product_symbol"),
        get_taker_volume(ccy => "ccy"),
        get_tickers(inst_type => "instType"),
        get_top_trader_long_short_account_ratio(product_symbol => "product_symbol"),
        get_top_trader_long_short_position_ratio(product_symbol => "product_symbol"),
        get_trading_data_support_coin(),
        get_public_borrow_info(),
        get_public_borrow_history(),
        get_eth_staking_apy_history(days => "days"),
        get_sol_staking_apy_history(days => "days"),
    ];
    private [
set_fee_type(fee_type => "feeType"),
set_risk_offset_amount(ccy => "ccy",cl_spot_in_use_amt => "clSpotInUseAmt"),
activate_options(),
set_auto_loan(),
preset_account_level_switch(acct_lv => "acctLv"),
precheck_account_level_switch(acct_lv => "acctLv"),
set_collateral_assets(type_ => "type",collateral_enabled => "collateralEnabled"),
set_settlement_currency(settle_ccy => "settleCcy"),
set_trading_config(type_ => "type"),
precheck_delta_neutral(stgy_type => "stgyType"),
get_repayment_currencies(),
repay_debt(debt_ccy => "debtCcy",repay_ccy_list => "repayCcyList"),
get_repayment_history(),
get_spread_order_history_archive(),

        set_isolated_mode(iso_mode => "isoMode", type_ => "type"),
        get_account_risk_state(),
        get_greeks(),
        get_pm_position_tiers(inst_type => "instType", inst_family => "instFamily"),
        set_account_level(acct_lv => "acctLv"),
        get_collateral_assets(),
        amend_spread_order(),
        get_asset_bill_history(),
        get_convert_currency_pair(from_ccy => "fromCcy", to_ccy => "toCcy"),
        estimate_convert_quote(base_ccy => "baseCcy", quote_ccy => "quoteCcy", side => "side", rfq_sz => "rfqSz", rfq_sz_ccy => "rfqSzCcy"),
        execute_convert_trade(quote_id => "quoteId", base_ccy => "baseCcy", quote_ccy => "quoteCcy", side => "side", sz => "sz", sz_ccy => "szCcy"),
        place_algo_order(product_symbol => "product_symbol", trade_mode => "tdMode", side => "side", order_type => "ordType"),
        amend_algo_order(product_symbol => "product_symbol"),
        cancel_algo_orders(orders => "orders"),
        get_algo_order(),
        get_pending_algo_orders(order_type => "ordType"),
        get_algo_order_history(order_type => "ordType"),
        adjust_position_margin(product_symbol => "product_symbol", position_side => "posSide", type_ => "type", amount => "amt"),
        place_spread_order(sprd_id => "sprdId", side => "side", order_type => "ordType", size => "sz"),
        cancel_spread_order(order_id => "ordId"),
        cancel_all_spread_orders(),
        get_spread_order(order_id => "ordId"),
        get_spread_orders_pending(),
        get_spread_orders_history(),
        get_spread_trades(),
        set_spread_cancel_all_after(time_out => "timeOut"),
        amend_multiple_orders(orders => "orders"),
        amend_order(product_symbol => "product_symbol"),
        cancel_all_orders(),
        cancel_batch_orders(orders => "orders"),
        cancel_order(product_symbol => "product_symbol"),
        close_positions(product_symbol => "product_symbol", mgn_mode => "mgnMode"),
        funds_transfer(ccy => "ccy", amt => "amt", from_account => "from_account", to_account => "to_account"),
        get_account_balance(),
        get_account_bills(),
        get_account_bills_archive(),
        get_account_bills_history_archive(year => "year", quarter => "quarter"),
        get_account_config(),
        get_account_instruments(inst_type => "instType"),
        get_account_rate_limit(),
        get_easy_convert_currencies(),
        get_easy_convert_history(),
        place_easy_convert(from_ccy => "fromCcy", to_ccy => "toCcy"),
        get_adjust_leverage(inst_type => "instType", mgn_mode => "mgnMode", lever => "lever"),
        get_asset_valuation(),
        get_balances(),
        get_bills(),
        get_convert_currencies(),
        get_convert_history(),
        get_currencies(),
        get_deposit_address(ccy => "ccy"),
        get_deposit_history(),
        get_deposit_withdraw_status(),
        get_exchange_list(),
        get_futures_fee_rates(),
        get_margin_fee_rates(),
        get_option_fee_rates(),
        get_spot_fee_rates(),
        get_swap_fee_rates(),
        get_fills(),
        get_fills_history(inst_type => "instType"),
        get_interest_accrued(),
        get_interest_limits(),
        get_interest_rate(),
        spot_manual_borrow_repay(ccy => "ccy", side => "side", amt => "amt"),
        set_spot_auto_repay(auto_repay => "autoRepay"),
        get_spot_borrow_repay_history(),
        get_saving_balance(),
        purchase_redeem_savings(ccy => "ccy", amt => "amt", side => "side"),
        // Deprecated: set-lending-rate is no longer in the OKX v5 docs.
        set_savings_lending_rate(ccy => "ccy", rate => "rate"),
        get_savings_lending_history(),
        set_auto_earn(ccy => "ccy", action => "action"),
        get_staking_offers(),
        purchase_staking(product_id => "productId", invest_data => "investData"),
        redeem_staking(ord_id => "ordId", protocol_type => "protocolType"),
        cancel_staking(ord_id => "ordId", protocol_type => "protocolType"),
        get_active_staking_orders(),
        get_staking_order_history(),
        get_eth_staking_product_info(),
        purchase_eth_staking(amt => "amt"),
        redeem_eth_staking(amt => "amt"),
        cancel_eth_staking_redemption(ord_id => "ordId"),
        get_eth_staking_balance(),
        get_eth_staking_history(),
        get_sol_staking_product_info(),
        purchase_sol_staking(amt => "amt"),
        redeem_sol_staking(amt => "amt"),
        get_sol_staking_balance(),
        get_sol_staking_history(),
        get_subaccount_list(),
        get_subaccount_trading_balance(sub_account => "subAcct"),
        get_subaccount_funding_balance(sub_account => "subAcct"),
        get_subaccount_bills(sub_account => "subAcct"),
        transfer_between_subaccounts(ccy => "ccy", amt => "amt", from_account => "from_account", to_account => "to_account", from_subaccount => "fromSubAccount", to_subaccount => "toSubAccount"),
        get_entrusted_subaccount_list(),
        // Deprecated: subaccount/interest-limits is no longer in the OKX v5 docs.
        get_subaccount_interest_limits(sub_account => "subAcct"),
        get_flexible_loan_borrow_currencies(),
        get_flexible_loan_collateral_assets(),
        get_flexible_loan_max_loan(borrow_ccy => "borrowCcy", supported_collateral => "supCollateral"),
        get_flexible_loan_max_collateral_redeem(ccy => "ccy"),
        adjust_flexible_loan_collateral(adjustment_type => "type", collateral_ccy => "collateralCcy", collateral_amt => "collateralAmt"),
        get_flexible_loan_info(),
        get_flexible_loan_history(),
        get_flexible_loan_interest_accrued(),
        borrow_flexible_loan(loan_data => "loanData", client_order_id => "clOrdId"),
        repay_flexible_loan(order_id => "ordId", ccy => "ccy", amt => "amt", client_order_id => "clOrdId"),
        get_flexible_loan_emode_info(),
        get_dual_investment_currency_pairs(),
        get_dual_investment_products(base_ccy => "baseCcy", quote_ccy => "quoteCcy", option_type => "optType"),
        request_dual_investment_quote(product_id => "productId", notional_size => "notionalSz", notional_ccy => "notionalCcy"),
        trade_dual_investment(quote_id => "quoteId"),
        request_dual_investment_redeem_quote(order_id => "ordId"),
        redeem_dual_investment(order_id => "ordId", quote_id => "quoteId"),
        get_dual_investment_order_status(order_id => "ordId"),
        get_dual_investment_order_history(),
        get_okusd_limits(),
        get_okusd_account(),
        get_okusd_rate_history(),
        get_okusd_subscribe_history(),
        get_okusd_redeem_history(),
        get_okusd_rewards_history(),
        subscribe_okusd(amt => "amt", client_order_id => "clOrdId"),
        redeem_okusd(amt => "amt", redeem_type => "redeemType", client_order_id => "clOrdId"),
        get_leverage(mgn_mode => "mgnMode"),
        get_max_avail_size(product_symbol => "product_symbol", td_mode => "tdMode"),
        get_max_loan(mgn_mode => "mgnMode"),
        get_max_order_size(product_symbol => "product_symbol", td_mode => "tdMode"),
        get_max_withdrawal(),
        get_monthly_statement(month => "month"),
        get_order(product_symbol => "product_symbol"),
        get_order_list(),
        get_orders_history(inst_type => "instType"),
        get_orders_history_archive(inst_type => "instType"),
        get_position_risk(),
        get_positions(),
        get_positions_history(),
        get_transfer_state(),
        place_batch_orders(orders => "orders"),
        place_limit_buy_order(product_symbol => "product_symbol", td_mode => "tdMode", sz => "sz", px => "px"),
        place_limit_order(product_symbol => "product_symbol", td_mode => "tdMode", side => "side", sz => "sz", px => "px"),
        place_limit_sell_order(product_symbol => "product_symbol", td_mode => "tdMode", sz => "sz", px => "px"),
        place_market_buy_order(product_symbol => "product_symbol", td_mode => "tdMode", sz => "sz"),
        place_market_order(product_symbol => "product_symbol", td_mode => "tdMode", side => "side", sz => "sz"),
        place_market_sell_order(product_symbol => "product_symbol", td_mode => "tdMode", sz => "sz"),
        place_order(product_symbol => "product_symbol", td_mode => "tdMode", side => "side", ord_type => "ordType", sz => "sz"),
        pre_check_order(product_symbol => "product_symbol", td_mode => "tdMode", side => "side", ord_type => "ordType", sz => "sz"),
        place_post_only_limit_buy_order(product_symbol => "product_symbol", td_mode => "tdMode", sz => "sz", px => "px"),
        place_post_only_limit_order(product_symbol => "product_symbol", td_mode => "tdMode", side => "side", sz => "sz", px => "px"),
        place_post_only_limit_sell_order(product_symbol => "product_symbol", td_mode => "tdMode", sz => "sz", px => "px"),
        post_account_bills_history_archive(year => "year", quarter => "quarter"),
        post_monthly_statement(),
        set_greeks(greeks_type => "greeksType"),
        set_cancel_all_after(time_out => "timeOut"),
        set_leverage(lever => "lever", mgn_mode => "mgnMode"),
        set_position_mode(pos_mode => "posMode"),
    ];
}

crate::exchanges::impl_exchange_method_wrappers! { @extend; OkxClient; public [
get_books_rpi(inst_id => "instId"),
get_platform_24_volume(),
get_call_auction_details(inst_id => "instId"),
get_block_tickers(inst_type => "instType"),
get_block_ticker(inst_id => "instId"),
get_rfq_public_trades(),
get_block_trades(inst_id => "instId"),
get_estimated_settlement_info(inst_id => "instId"),
get_settlement_history(inst_family => "instFamily"),
get_insurance_fund(inst_type => "instType"),
get_premium_history(inst_id => "instId"),
get_index_candles(inst_id => "instId"),
get_history_index_candles(inst_id => "instId"),
get_history_mark_price_candles(inst_id => "instId"),
get_exchange_rate(),
get_index_components(index => "index"),
get_economic_calendar(),
get_market_data_history(module => "module",inst_type => "instType",date_aggr_type => "dateAggrType",begin => "begin",end => "end"),
get_delta_hedge_currencies(),
get_loan_ratio(ccy => "ccy"),
get_announcements(),
get_announcement_types(),
]; private [
get_bill_types(),
simulate_positions(),
get_position_margin_graph(type_ => "type",mmr_config => "mmrConfig"),
move_positions(from_acct => "fromAcct",to_acct => "toAcct",legs => "legs",client_id => "clientId"),
get_move_positions_history(),
adjust_demo_balance(type_ => "type",adjustments => "adjustments"),
rfq_create_rfq(counterparties => "counterparties",legs => "legs"),
get_rfq_counterparties(),
rfq_cancel_rfq(),
rfq_cancel_batch_rfqs(),
rfq_cancel_all_rfqs(),
rfq_execute_quote(rfq_id => "rfqId",quote_id => "quoteId"),
get_rfq_rfqs(),
get_rfq_quotes(),
get_rfq_trades(),
get_non_tradable_assets(),
create_sub_account(sub_acct => "subAcct",type_ => "type"),
create_sub_account_api_key(sub_acct => "subAcct",label => "label",passphrase => "passphrase"),
get_sub_account_api_keys(sub_acct => "subAcct"),
modify_sub_account_api_key(sub_acct => "subAcct",api_key => "apiKey"),
delete_sub_account_api_key(sub_acct => "subAcct",api_key => "apiKey"),
set_sub_account_transfer_out(sub_acct => "subAcct"),
]; }

crate::exchanges::impl_exchange_method_wrappers! { @extend; OkxClient; public [
get_trading_bot_grid_ai_param(algo_ord_type => "algoOrdType",inst_id => "instId"),
trading_bot_grid_min_investment(inst_id => "instId",algo_ord_type => "algoOrdType",max_px => "maxPx",min_px => "minPx",grid_num => "gridNum",run_type => "runType"),
get_trading_bot_public_rsi_back_testing(inst_id => "instId",timeframe => "timeframe",thold => "thold",time_period => "timePeriod"),
get_trading_bot_grid_grid_quantity(inst_id => "instId",run_type => "runType",algo_ord_type => "algoOrdType",max_px => "maxPx",min_px => "minPx"),
get_copytrading_public_config(),
get_copytrading_public_lead_traders(),
get_copytrading_public_weekly_pnl(unique_code => "uniqueCode"),
get_copytrading_public_pnl(unique_code => "uniqueCode",last_days => "lastDays"),
get_copytrading_public_stats(unique_code => "uniqueCode",last_days => "lastDays"),
get_copytrading_public_preference_currency(unique_code => "uniqueCode"),
get_copytrading_public_current_subpositions(unique_code => "uniqueCode"),
get_copytrading_public_subpositions_history(unique_code => "uniqueCode"),
get_copytrading_public_copy_traders(unique_code => "uniqueCode"),
get_public_event_contract_series(),
get_public_event_contract_events(series_id => "seriesId"),
get_public_event_contract_markets(series_id => "seriesId"),
get_public_interest_rate_loan_quota(),
]; private [
trading_bot_grid_order_algo(inst_id => "instId",algo_ord_type => "algoOrdType",max_px => "maxPx",min_px => "minPx",grid_num => "gridNum"),
trading_bot_grid_amend_algo_basic_param(algo_id => "algoId",min_px => "minPx",max_px => "maxPx",grid_num => "gridNum"),
trading_bot_grid_amend_order_algo(algo_id => "algoId",inst_id => "instId"),
trading_bot_grid_stop_order_algo(orders => "orders"),
trading_bot_grid_close_position(algo_id => "algoId",mkt_close => "mktClose"),
trading_bot_grid_cancel_close_order(algo_id => "algoId",ord_id => "ordId"),
trading_bot_grid_order_instant_trigger(algo_id => "algoId"),
get_trading_bot_grid_orders_algo_pending(algo_ord_type => "algoOrdType"),
get_trading_bot_grid_orders_algo_history(algo_ord_type => "algoOrdType"),
get_trading_bot_grid_orders_algo_details(algo_ord_type => "algoOrdType",algo_id => "algoId"),
get_trading_bot_grid_sub_orders(algo_ord_type => "algoOrdType",algo_id => "algoId",type_ => "type"),
get_trading_bot_grid_positions(algo_ord_type => "algoOrdType",algo_id => "algoId"),
trading_bot_grid_withdraw_income(algo_id => "algoId"),
trading_bot_grid_compute_margin_balance(algo_id => "algoId",type_ => "type"),
trading_bot_grid_margin_balance(algo_id => "algoId",type_ => "type"),
trading_bot_grid_adjust_investment(algo_id => "algoId",amt => "amt"),
trading_bot_grid_copy_order_algo(inst_id => "instId",algo_ord_type => "algoOrdType",source_algo_id => "sourceAlgoId"),
trading_bot_dca_create(inst_id => "instId",algo_ord_type => "algoOrdType",init_ord_amt => "initOrdAmt",max_safety_ords => "maxSafetyOrds",tp_pct => "tpPct",lever => "lever",trigger_params => "triggerParams"),
trading_bot_dca_amend_order_algo(algo_id => "algoId",px_steps => "pxSteps",px_steps_mult => "pxStepsMult",vol_mult => "volMult",tp_pct => "tpPct",sl_pct => "slPct",init_ord_amt => "initOrdAmt",safety_ord_amt => "safetyOrdAmt",max_safety_ords => "maxSafetyOrds",reserve_funds => "reserveFunds",trigger_params => "triggerParams"),
trading_bot_dca_stop(algo_id => "algoId",algo_ord_type => "algoOrdType",stop_type => "stopType"),
get_trading_bot_dca_ongoing_list(algo_ord_type => "algoOrdType"),
get_trading_bot_dca_history_list(algo_ord_type => "algoOrdType"),
get_trading_bot_dca_orders(algo_id => "algoId",algo_ord_type => "algoOrdType"),
trading_bot_dca_orders_manual_buy(algo_id => "algoId",algo_ord_type => "algoOrdType",price => "price",amt => "amt"),
trading_bot_dca_settings_reinvestment(algo_id => "algoId",algo_ord_type => "algoOrdType",allow_reinvest => "allowReinvest"),
trading_bot_dca_settings_take_profit(algo_id => "algoId",algo_ord_type => "algoOrdType",tp_price => "tpPrice"),
get_trading_bot_dca_position_details(algo_id => "algoId",algo_ord_type => "algoOrdType"),
get_trading_bot_dca_cycle_list(algo_id => "algoId",algo_ord_type => "algoOrdType"),
trading_bot_dca_margin_add(algo_id => "algoId",amt => "amt"),
trading_bot_dca_margin_reduce(algo_id => "algoId",amt => "amt"),
trading_bot_signal_create_signal(signal_chan_name => "signalChanName"),
get_trading_bot_signal_signals(signal_source_type => "signalSourceType"),
trading_bot_signal_order_algo(signal_chan_id => "signalChanId",lever => "lever",invest_amt => "investAmt",sub_ord_type => "subOrdType"),
trading_bot_signal_stop_order_algo(orders => "orders"),
trading_bot_signal_margin_balance(algo_id => "algoId",type_ => "type",amt => "amt"),
trading_bot_signal_amend_tpsl(algo_id => "algoId",exit_setting_param => "exitSettingParam"),
trading_bot_signal_set_instruments(algo_id => "algoId",inst_ids => "instIds",include_all => "includeAll"),
get_trading_bot_signal_orders_algo_details(algo_ord_type => "algoOrdType",algo_id => "algoId"),
get_trading_bot_signal_orders_algo_pending(algo_ord_type => "algoOrdType",after => "after"),
get_trading_bot_signal_orders_algo_history(algo_ord_type => "algoOrdType",algo_id => "algoId",after => "after"),
get_trading_bot_signal_positions(algo_ord_type => "algoOrdType",algo_id => "algoId"),
get_trading_bot_signal_positions_history(algo_id => "algoId"),
trading_bot_signal_close_position(algo_id => "algoId",inst_id => "instId"),
trading_bot_signal_sub_order(inst_id => "instId",algo_id => "algoId",side => "side",ord_type => "ordType",sz => "sz"),
trading_bot_signal_cancel_sub_order(algo_id => "algoId",inst_id => "instId",signal_ord_id => "signalOrdId"),
get_trading_bot_signal_sub_orders(algo_id => "algoId",algo_ord_type => "algoOrdType"),
get_trading_bot_signal_event_history(algo_id => "algoId"),
trading_bot_recurring_order_algo(stgy_name => "stgyName",recurring_list => "recurringList",period => "period",recurring_time => "recurringTime",time_zone => "timeZone",amt => "amt",investment_ccy => "investmentCcy",td_mode => "tdMode"),
trading_bot_recurring_amend_order_algo(algo_id => "algoId",stgy_name => "stgyName"),
trading_bot_recurring_stop_order_algo(orders => "orders"),
get_trading_bot_recurring_orders_algo_pending(),
get_trading_bot_recurring_orders_algo_history(),
get_trading_bot_recurring_orders_algo_details(algo_id => "algoId"),
get_trading_bot_recurring_sub_orders(algo_id => "algoId"),
trading_bot_recurring_amend_recurring_time(algo_id => "algoId",recurring_time_type => "recurringTimeType",time_zone => "timeZone",period => "period"),
trading_bot_recurring_amend_recurring_amount(algo_id => "algoId",amount => "amount"),
trading_bot_recurring_add_investment(algo_id => "algoId",amount => "amount"),
trading_bot_recurring_pause(algo_id => "algoId"),
trading_bot_recurring_restart(algo_id => "algoId"),
trading_bot_recurring_amend_price_range(algo_id => "algoId",recurring_list => "recurringList"),
get_copytrading_current_subpositions(),
get_copytrading_subpositions_history(),
copytrading_algo_order(sub_pos_id => "subPosId"),
copytrading_close_subposition(sub_pos_id => "subPosId"),
get_copytrading_instruments(),
copytrading_set_instruments(inst_id => "instId"),
get_copytrading_profit_sharing_details(),
get_copytrading_total_profit_sharing(),
get_copytrading_unrealized_profit_sharing_details(),
get_copytrading_total_unrealized_profit_sharing(),
copytrading_amend_profit_sharing_ratio(profit_sharing_ratio => "profitSharingRatio"),
get_copytrading_config(),
copytrading_first_copy_settings(unique_code => "uniqueCode",copy_mgn_mode => "copyMgnMode",copy_inst_id_type => "copyInstIdType",copy_total_amt => "copyTotalAmt",sub_pos_close_type => "subPosCloseType"),
copytrading_amend_copy_settings(unique_code => "uniqueCode",copy_mgn_mode => "copyMgnMode",copy_inst_id_type => "copyInstIdType",copy_total_amt => "copyTotalAmt",sub_pos_close_type => "subPosCloseType"),
copytrading_stop_copy_trading(unique_code => "uniqueCode",sub_pos_close_type => "subPosCloseType"),
get_copytrading_copy_settings(unique_code => "uniqueCode"),
get_copytrading_current_lead_traders(),
get_asset_withdrawal_history(),
get_fiat_deposit_payment_methods(ccy => "ccy"),
get_fiat_withdrawal_payment_methods(ccy => "ccy"),
get_fiat_withdrawal_order_history(),
get_fiat_withdrawal(ord_id => "ordId"),
get_fiat_deposit_order_history(),
get_fiat_deposit(ord_id => "ordId"),
get_fiat_buy_sell_currencies(),
get_fiat_buy_sell_currency_pair(from_ccy => "fromCcy",to_ccy => "toCcy"),
fiat_buy_sell_quote(side => "side",from_ccy => "fromCcy",to_ccy => "toCcy",rfq_amt => "rfqAmt",rfq_ccy => "rfqCcy"),
fiat_buy_sell_trade(quote_id => "quoteId",side => "side",from_ccy => "fromCcy",to_ccy => "toCcy",rfq_amt => "rfqAmt",rfq_ccy => "rfqCcy",payment_method => "paymentMethod",cl_ord_id => "clOrdId"),
get_fiat_buy_sell_history(),
get_account_subaccount_max_withdrawal(sub_acct => "subAcct"),
get_asset_subaccount_managed_subaccount_bills(),
get_finance_stable_rewards_product_info(ccy => "ccy"),
get_finance_stable_rewards_balance(),
get_finance_stable_rewards_apy_history(ccy => "ccy"),
]; }

mod business_methods {
    use crate::exchanges::okx::client::OkxClient;
    crate::exchanges::impl_exchange_method_wrappers! {
        @extend;
        OkxClient;
        public [
            get_mm_instrument_types(),
        ];
        private [
            reset_mmp(inst_family => "instFamily"),
            set_mmp_config(inst_family => "instFamily", time_interval => "timeInterval", frozen_interval => "frozenInterval", qty_limit => "qtyLimit"),
            get_mmp_config(),
            get_glp_today_performance(),
            get_glp_historical_performance(program => "program"),
            mass_cancel_options_orders(inst_type => "instType", inst_family => "instFamily"),
            create_rfq_quote(rfq_id => "rfqId", quote_side => "quoteSide", legs => "legs"),
            cancel_rfq_quote(),
            get_rfq_maker_instrument_settings(),
            set_rfq_maker_instrument_settings(inst_type => "instType", data => "data"),
            reset_rfq_mmp(),
            set_rfq_mmp_config(time_interval => "timeInterval", frozen_interval => "frozenInterval", count_limit => "countLimit"),
            get_rfq_mmp_config(),
            cancel_rfq_batch_quotes(),
            cancel_all_rfq_quotes(),
            set_rfq_cancel_all_after(time_out => "timeOut"),
            /// API withdrawals and external transfers have no second confirmation; they execute on submit.
            create_withdrawal(ccy => "ccy", amt => "amt", dest => "dest", to_addr => "toAddr"),
            cancel_withdrawal(wd_id => "wdId"),
            /// API withdrawals and external transfers have no second confirmation; they execute on submit.
            create_fiat_withdrawal(payment_acct_id => "paymentAcctId", ccy => "ccy", amt => "amt", payment_method => "paymentMethod", client_id => "clientId"),
            cancel_fiat_withdrawal(ord_id => "ordId"),
            get_affiliate_performance_summary(),
            get_affiliate_invitee_detail(uid => "uid"),
            get_affiliate_invitee_list(),
            get_affiliate_links(),
            get_affiliate_co_inviters(),
            get_sub_affiliates(),
        ];
    }
}
