use super::client::OkxClient;

crate::exchanges::impl_exchange_method_wrappers! {
    OkxClient;
    public [
        get_candles_ticks(product_symbol => "product_symbol"),
        get_contract_long_short_ratio(product_symbol => "product_symbol"),
        get_contract_open_interest_history(product_symbol => "product_symbol"),
        get_contract_taker_volume(product_symbol => "product_symbol"),
        get_contracts_open_interest_and_volume(ccy => "ccy"),
        get_delivery_exercise_history(inst_type => "instType"),
        get_option_summary(),
        get_option_tick_bands(),
        get_option_trades(),
        get_option_family_trades(inst_family => "instFamily"),
        get_options_open_interest_and_volume(ccy => "ccy"),
        get_option_put_call_ratio(ccy => "ccy"),
        get_option_open_interest_and_volume_by_expiry(ccy => "ccy"),
        get_option_open_interest_and_volume_by_strike(ccy => "ccy", expiry_time => "expTime"),
        get_option_taker_block_volume(ccy => "ccy"),
        get_funding_rate(product_symbol => "product_symbol"),
        get_funding_rate_history(product_symbol => "product_symbol"),
        get_long_short_ratio(ccy => "ccy"),
        get_open_interest(inst_type => "instType"),
        get_orderbook(product_symbol => "product_symbol"),
        get_position_tiers(inst_type => "instType", td_mode => "tdMode"),
        get_public_instruments(inst_type => "instType"),
        get_public_trades(product_symbol => "product_symbol"),
        get_taker_volume(ccy => "ccy"),
        get_tickers(inst_type => "instType"),
        get_top_trader_long_short_account_ratio(product_symbol => "product_symbol"),
        get_top_trader_long_short_position_ratio(product_symbol => "product_symbol"),
        get_trading_data_support_coin(),
        get_public_borrow_info(),
        get_public_borrow_history(),
        get_eth_staking_apy_history(days => "days"),
        get_sol_staking_apy_history(days => "days"),
    ];
    private [
        amend_multiple_orders(orders => "orders"),
        amend_order(product_symbol => "product_symbol"),
        cancel_all_orders(),
        cancel_batch_orders(orders => "orders"),
        cancel_order(product_symbol => "product_symbol"),
        close_positions(product_symbol => "product_symbol", mgn_mode => "mgnMode"),
        funds_transfer(ccy => "ccy", amt => "amt", from_account => "from_account", to_account => "to_account"),
        get_account_balance(),
        get_account_bills(),
        get_account_bills_archive(),
        get_account_bills_history_archive(year => "year", quarter => "quarter"),
        get_account_config(),
        get_account_instruments(inst_type => "instType"),
        get_account_rate_limit(),
        get_adjust_leverage(inst_type => "instType", mgn_mode => "mgnMode", lever => "lever"),
        get_asset_valuation(),
        get_balances(),
        get_bills(),
        get_convert_currencies(),
        get_convert_history(),
        get_currencies(),
        get_deposit_address(ccy => "ccy"),
        get_deposit_history(),
        get_deposit_withdraw_status(),
        get_exchange_list(),
        get_futures_fee_rates(),
        get_margin_fee_rates(),
        get_option_fee_rates(),
        get_spot_fee_rates(),
        get_swap_fee_rates(),
        get_fills(),
        get_fills_history(inst_type => "instType"),
        get_interest_accrued(),
        get_interest_limits(),
        get_interest_rate(),
        spot_manual_borrow_repay(ccy => "ccy", side => "side", amt => "amt"),
        set_spot_auto_repay(auto_repay => "autoRepay"),
        get_spot_borrow_repay_history(),
        get_saving_balance(),
        purchase_redeem_savings(ccy => "ccy", amt => "amt", side => "side"),
        set_savings_lending_rate(ccy => "ccy", rate => "rate"),
        get_savings_lending_history(),
        set_auto_earn(ccy => "ccy", action => "action"),
        get_staking_offers(),
        purchase_staking(product_id => "productId", invest_data => "investData"),
        redeem_staking(ord_id => "ordId", protocol_type => "protocolType"),
        cancel_staking(ord_id => "ordId", protocol_type => "protocolType"),
        get_active_staking_orders(),
        get_staking_order_history(),
        get_eth_staking_product_info(),
        purchase_eth_staking(amt => "amt"),
        redeem_eth_staking(amt => "amt"),
        cancel_eth_staking_redemption(ord_id => "ordId"),
        get_eth_staking_balance(),
        get_eth_staking_history(),
        get_sol_staking_product_info(),
        purchase_sol_staking(amt => "amt"),
        redeem_sol_staking(amt => "amt"),
        get_sol_staking_balance(),
        get_sol_staking_history(),
        get_subaccount_list(),
        get_subaccount_trading_balance(sub_account => "subAcct"),
        get_subaccount_funding_balance(sub_account => "subAcct"),
        get_subaccount_bills(sub_account => "subAcct"),
        transfer_between_subaccounts(ccy => "ccy", amt => "amt", from_account => "from_account", to_account => "to_account", from_subaccount => "fromSubAccount", to_subaccount => "toSubAccount"),
        get_entrusted_subaccount_list(),
        get_subaccount_interest_limits(sub_account => "subAcct"),
        get_flexible_loan_borrow_currencies(),
        get_flexible_loan_collateral_assets(),
        get_flexible_loan_max_loan(borrow_ccy => "borrowCcy", supported_collateral => "supCollateral"),
        get_flexible_loan_max_collateral_redeem(ccy => "ccy"),
        adjust_flexible_loan_collateral(adjustment_type => "type", collateral_ccy => "collateralCcy", collateral_amt => "collateralAmt"),
        get_flexible_loan_info(),
        get_flexible_loan_history(),
        get_flexible_loan_interest_accrued(),
        borrow_flexible_loan(loan_data => "loanData", client_order_id => "clOrdId"),
        repay_flexible_loan(order_id => "ordId", ccy => "ccy", amt => "amt", client_order_id => "clOrdId"),
        get_flexible_loan_emode_info(),
        get_dual_investment_currency_pairs(),
        get_dual_investment_products(base_ccy => "baseCcy", quote_ccy => "quoteCcy", option_type => "optType"),
        request_dual_investment_quote(product_id => "productId", notional_size => "notionalSz", notional_ccy => "notionalCcy"),
        trade_dual_investment(quote_id => "quoteId"),
        request_dual_investment_redeem_quote(order_id => "ordId"),
        redeem_dual_investment(order_id => "ordId", quote_id => "quoteId"),
        get_dual_investment_order_status(order_id => "ordId"),
        get_dual_investment_order_history(),
        get_okusd_limits(),
        get_okusd_account(),
        get_okusd_rate_history(),
        get_okusd_subscribe_history(),
        get_okusd_redeem_history(),
        get_okusd_rewards_history(),
        subscribe_okusd(amt => "amt", client_order_id => "clOrdId"),
        redeem_okusd(amt => "amt", redeem_type => "redeemType", client_order_id => "clOrdId"),
        get_leverage(mgn_mode => "mgnMode"),
        get_max_avail_size(product_symbol => "product_symbol", td_mode => "tdMode"),
        get_max_loan(mgn_mode => "mgnMode"),
        get_max_order_size(product_symbol => "product_symbol", td_mode => "tdMode"),
        get_max_withdrawal(),
        get_monthly_statement(month => "month"),
        get_order(product_symbol => "product_symbol"),
        get_order_list(),
        get_orders_history(inst_type => "instType"),
        get_orders_history_archive(inst_type => "instType"),
        get_position_risk(),
        get_positions(),
        get_positions_history(),
        get_transfer_state(),
        place_batch_orders(orders => "orders"),
        place_limit_buy_order(product_symbol => "product_symbol", td_mode => "tdMode", sz => "sz", px => "px"),
        place_limit_order(product_symbol => "product_symbol", td_mode => "tdMode", side => "side", sz => "sz", px => "px"),
        place_limit_sell_order(product_symbol => "product_symbol", td_mode => "tdMode", sz => "sz", px => "px"),
        place_market_buy_order(product_symbol => "product_symbol", td_mode => "tdMode", sz => "sz"),
        place_market_order(product_symbol => "product_symbol", td_mode => "tdMode", side => "side", sz => "sz"),
        place_market_sell_order(product_symbol => "product_symbol", td_mode => "tdMode", sz => "sz"),
        place_order(product_symbol => "product_symbol", td_mode => "tdMode", side => "side", ord_type => "ordType", sz => "sz"),
        pre_check_order(product_symbol => "product_symbol", td_mode => "tdMode", side => "side", ord_type => "ordType", sz => "sz"),
        place_post_only_limit_buy_order(product_symbol => "product_symbol", td_mode => "tdMode", sz => "sz", px => "px"),
        place_post_only_limit_order(product_symbol => "product_symbol", td_mode => "tdMode", side => "side", sz => "sz", px => "px"),
        place_post_only_limit_sell_order(product_symbol => "product_symbol", td_mode => "tdMode", sz => "sz", px => "px"),
        post_account_bills_history_archive(year => "year", quarter => "quarter"),
        post_monthly_statement(),
        set_greeks(greeks_type => "greeksType"),
        set_cancel_all_after(time_out => "timeOut"),
        set_leverage(lever => "lever", mgn_mode => "mgnMode"),
        set_position_mode(pos_mode => "posMode"),
    ];
}
