use super::AsterClient;

crate::exchanges::impl_exchange_method_wrappers! {
    AsterClient;
    public [];
    private [
        get_spot_account() => get_spot_account_with,
        get_spot_transaction_history() => get_spot_transaction_history_with,
        transfer_spot_futures(amount => "amount", asset => "asset", client_tran_id => "clientTranId", kind_type => "kindType") => transfer_spot_futures_with,
        get_futures_position_mode() => get_futures_position_mode_with,
        set_futures_position_mode(dual_side_position => "dualSidePosition") => set_futures_position_mode_with,
        get_futures_stp_mode() => get_futures_stp_mode_with,
        set_futures_stp_mode(stp_mode => "stpMode") => set_futures_stp_mode_with,
        get_futures_multi_assets_mode() => get_futures_multi_assets_mode_with,
        set_futures_multi_assets_mode(multi_assets_margin => "multiAssetsMargin") => set_futures_multi_assets_mode_with,
        get_futures_balance() => get_futures_balance_with,
        get_futures_account() => get_futures_account_with,
        modify_futures_position_margin(product_symbol => "product_symbol", amount => "amount", type_ => "type_") => modify_futures_position_margin_with,
        get_futures_position_margin_history(product_symbol => "product_symbol") => get_futures_position_margin_history_with,
        get_futures_position_risk() => get_futures_position_risk_with,
        get_futures_user_trades(product_symbol => "product_symbol") => get_futures_user_trades_with,
        get_futures_income() => get_futures_income_with,
        get_futures_leverage_bracket() => get_futures_leverage_bracket_with,
        get_futures_adl_quantile() => get_futures_adl_quantile_with,
        get_futures_force_orders() => get_futures_force_orders_with,
        get_spot_commission_rate(product_symbol => "product_symbol") => get_spot_commission_rate_with,
        get_futures_commission_rate(product_symbol => "product_symbol") => get_futures_commission_rate_with,
        update_futures_mmp(product_symbol => "product_symbol", window_time_in_milliseconds => "windowTimeInMilliseconds", frozen_time_in_milliseconds => "frozenTimeInMilliseconds") => update_futures_mmp_with,
        get_futures_mmp(product_symbol => "product_symbol") => get_futures_mmp_with,
        delete_futures_mmp(product_symbol => "product_symbol") => delete_futures_mmp_with,
        reset_futures_mmp(product_symbol => "product_symbol") => reset_futures_mmp_with,
        create_spot_listen_key() => create_spot_listen_key_with,
        keep_alive_spot_listen_key(listen_key => "listenKey") => keep_alive_spot_listen_key_with,
        close_spot_listen_key(listen_key => "listenKey") => close_spot_listen_key_with,
        create_futures_listen_key() => create_futures_listen_key_with,
        keep_alive_futures_listen_key() => keep_alive_futures_listen_key_with,
        close_futures_listen_key() => close_futures_listen_key_with,
        place_spot_order(product_symbol => "product_symbol", side => "side", type_ => "type_") => place_spot_order_with,
        cancel_spot_order(product_symbol => "product_symbol") => cancel_spot_order_with,
        get_spot_order(product_symbol => "product_symbol") => get_spot_order_with,
        get_spot_open_order(product_symbol => "product_symbol") => get_spot_open_order_with,
        get_spot_open_orders() => get_spot_open_orders_with,
        cancel_all_spot_open_orders(product_symbol => "product_symbol") => cancel_all_spot_open_orders_with,
        get_spot_all_orders(product_symbol => "product_symbol") => get_spot_all_orders_with,
        get_spot_user_trades() => get_spot_user_trades_with,
        place_futures_order(product_symbol => "product_symbol", side => "side", type_ => "type_") => place_futures_order_with,
        modify_futures_order(product_symbol => "product_symbol", quantity => "quantity", price => "price") => modify_futures_order_with,
        place_futures_chase_order(product_symbol => "product_symbol", side => "side", quantity_unit => "quantityUnit", quantity => "quantity", chase_offset => "chaseOffset", chase_offset_type => "chaseOffsetType") => place_futures_chase_order_with,
        place_futures_batch_orders(batch_orders => "batchOrders") => place_futures_batch_orders_with,
        get_futures_order(product_symbol => "product_symbol") => get_futures_order_with,
        cancel_futures_order(product_symbol => "product_symbol") => cancel_futures_order_with,
        cancel_all_futures_open_orders(product_symbol => "product_symbol") => cancel_all_futures_open_orders_with,
        cancel_futures_batch_orders(product_symbol => "product_symbol") => cancel_futures_batch_orders_with,
        set_futures_countdown_cancel_all(product_symbol => "product_symbol", countdown_time => "countdownTime") => set_futures_countdown_cancel_all_with,
        get_futures_open_order(product_symbol => "product_symbol") => get_futures_open_order_with,
        get_futures_open_orders() => get_futures_open_orders_with,
        get_futures_all_orders(product_symbol => "product_symbol") => get_futures_all_orders_with,
        set_futures_leverage(product_symbol => "product_symbol", leverage => "leverage") => set_futures_leverage_with,
        set_futures_margin_type(product_symbol => "product_symbol", margin_type => "marginType") => set_futures_margin_type_with,
        place_futures_strategy_order(client_strategy_id => "clientStrategyId", strategy_type => "strategyType", sub_order_list => "subOrderList") => place_futures_strategy_order_with,
        update_futures_strategy_order(strategy_id => "strategyId", strategy_type => "strategyType", sub_order_list => "subOrderList") => update_futures_strategy_order_with,
        get_futures_strategy_open_order(strategy_type => "strategyType") => get_futures_strategy_open_order_with,
        get_futures_strategy_history_order(strategy_type => "strategyType") => get_futures_strategy_history_order_with
    ];
}
