//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "get_futures_liquidity_pool_statistics",
        path: "/api/charts/v1/analytics/liquidity-pool",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: true,
        symbol_key: None,
        allowed: &["since", "interval", "to"],
        fields: &[
            Field {
                key: "since",
                kind: "integer",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "interval",
                kind: "integer",
                required: true,
                values: &[
                    "60", "300", "900", "1800", "3600", "14400", "43200", "86400", "604800",
                ],
                minimum: 1,
            },
            Field {
                key: "to",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
        ],
    },
    Endpoint {
        name: "get_futures_market_price",
        path: "/api/history/v3/market/{tradeable}/price",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: true,
        symbol_key: None,
        allowed: &[
            "tradeable",
            "since",
            "before",
            "sort",
            "continuation_token",
            "count",
        ],
        fields: &[
            Field {
                key: "tradeable",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "since",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "before",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "sort",
                kind: "string",
                required: false,
                values: &["asc", "desc"],
                minimum: 0,
            },
            Field {
                key: "continuation_token",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "count",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 1,
            },
        ],
    },
    Endpoint {
        name: "get_futures_market_orders",
        path: "/api/history/v3/market/{tradeable}/orders",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: true,
        symbol_key: None,
        allowed: &[
            "tradeable",
            "since",
            "before",
            "sort",
            "continuation_token",
            "count",
        ],
        fields: &[
            Field {
                key: "tradeable",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "since",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "before",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "sort",
                kind: "string",
                required: false,
                values: &["asc", "desc"],
                minimum: 0,
            },
            Field {
                key: "continuation_token",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "count",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 1,
            },
        ],
    },
    Endpoint {
        name: "get_futures_market_executions",
        path: "/api/history/v3/market/{tradeable}/executions",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: true,
        symbol_key: None,
        allowed: &[
            "tradeable",
            "since",
            "before",
            "sort",
            "continuation_token",
            "count",
        ],
        fields: &[
            Field {
                key: "tradeable",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "since",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "before",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "sort",
                kind: "string",
                required: false,
                values: &["asc", "desc"],
                minimum: 0,
            },
            Field {
                key: "continuation_token",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "count",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 1,
            },
        ],
    },
    Endpoint {
        name: "get_futures_chart_resolutions",
        path: "/api/charts/v1/{tick_type}/{symbol}",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: true,
        symbol_key: None,
        allowed: &["tick_type", "symbol"],
        fields: &[
            Field {
                key: "tick_type",
                kind: "string",
                required: true,
                values: &["spot", "mark", "trade"],
                minimum: 0,
            },
            Field {
                key: "symbol",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
        ],
    },
    Endpoint {
        name: "get_futures_chart_markets",
        path: "/api/charts/v1/{tick_type}",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: true,
        symbol_key: None,
        allowed: &["tick_type"],
        fields: &[Field {
            key: "tick_type",
            kind: "string",
            required: true,
            values: &["spot", "mark", "trade"],
            minimum: 0,
        }],
    },
    Endpoint {
        name: "get_futures_chart_types",
        path: "/api/charts/v1/",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: true,
        symbol_key: None,
        allowed: &[],
        fields: &[],
    },
    Endpoint {
        name: "get_futures_instrument_status",
        path: "/derivatives/api/v3/instruments/{symbol}/status",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: true,
        allowed: &["symbol", "product_symbol"],
        fields: &[Field {
            key: "symbol",
            kind: "string",
            required: true,
            values: &[],
            minimum: 0,
        }],
        symbol_key: Some("symbol"),
    },
    Endpoint {
        name: "get_futures_instrument_statuses",
        path: "/derivatives/api/v3/instruments/status",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: true,
        allowed: &["contractType"],
        fields: &[Field {
            key: "contractType",
            kind: "array",
            required: false,
            values: &[
                "futures_inverse",
                "futures_vanilla",
                "flexible_futures",
                "options",
                "all",
            ],
            minimum: 0,
        }],
        symbol_key: None,
    },
    Endpoint {
        name: "get_spot_level3_orderbook",
        path: "/0/private/Level3",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["pair", "depth", "product_symbol"],
        fields: &[
            Field {
                key: "pair",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "depth",
                kind: "integer",
                required: false,
                values: &["0", "10", "25", "100", "250", "1000"],
                minimum: 0,
            },
        ],
        symbol_key: Some("pair"),
    },
    Endpoint {
        name: "get_spot_grouped_orderbook",
        path: "/0/public/GroupedBook",
        method: HttpMethod::Get,
        auth: KrakenAuth::Spot,
        public: true,
        allowed: &["pair", "depth", "grouping", "product_symbol"],
        fields: &[
            Field {
                key: "pair",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "depth",
                kind: "integer",
                required: false,
                values: &["10", "25", "100", "250", "1000"],
                minimum: 0,
            },
            Field {
                key: "grouping",
                kind: "integer",
                required: false,
                values: &["1", "5", "10", "25", "50", "100", "250", "500", "1000"],
                minimum: 0,
            },
        ],
        symbol_key: Some("pair"),
    },
    Endpoint {
        name: "get_spot_maintenance_schedule",
        path: "/0/public/MaintenanceSchedule",
        method: HttpMethod::Get,
        auth: KrakenAuth::Spot,
        public: true,
        allowed: &[],
        fields: &[],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_trading_instruments",
        path: "/derivatives/api/v3/trading/instruments",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &["contractType"],
        fields: &[Field {
            key: "contractType",
            kind: "array",
            required: false,
            values: &[
                "futures_inverse",
                "futures_vanilla",
                "flexible_futures",
                "options",
                "all",
            ],
            minimum: 0,
        }],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_market_analytics",
        path: "/api/charts/v1/analytics/{symbol}/{analytics_type}",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: true,
        allowed: &["symbol", "analytics_type", "since", "interval", "to"],
        fields: &[
            Field {
                key: "symbol",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "analytics_type",
                kind: "string",
                required: true,
                values: &[
                    "open-interest",
                    "aggressor-differential",
                    "trade-volume",
                    "trade-count",
                    "liquidation-volume",
                    "rolling-volatility",
                    "long-short-ratio",
                    "long-short-info",
                    "cvd",
                    "top-traders",
                    "orderbook",
                    "spreads",
                    "liquidity",
                    "slippage",
                    "future-basis",
                    "funding",
                ],
                minimum: 0,
            },
            Field {
                key: "since",
                kind: "integer",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "interval",
                kind: "integer",
                required: true,
                values: &[
                    "60", "300", "900", "1800", "3600", "14400", "43200", "86400", "604800",
                ],
                minimum: 0,
            },
            Field {
                key: "to",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_ticker",
        path: "/derivatives/api/v3/tickers/{symbol}",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: true,
        allowed: &["symbol"],
        fields: &[Field {
            key: "symbol",
            kind: "string",
            required: true,
            values: &[],
            minimum: 0,
        }],
        symbol_key: None,
    },
];
