//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "edit_spot_order",
        path: "/0/private/EditOrder",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        symbol_key: Some("pair"),
        allowed: &[
            "pair",
            "txid",
            "userref",
            "volume",
            "displayvol",
            "asset_class",
            "price",
            "price2",
            "oflags",
            "deadline",
            "cancel_response",
            "validate",
            "product_symbol",
        ],
        fields: &[
            Field {
                key: "pair",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "txid",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "userref",
                kind: "signed_integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "volume",
                kind: "positive",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "displayvol",
                kind: "positive",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "asset_class",
                kind: "string",
                required: false,
                values: &["tokenized_asset"],
                minimum: 0,
            },
            Field {
                key: "price",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "price2",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "oflags",
                kind: "string",
                required: false,
                values: &["post"],
                minimum: 0,
            },
            Field {
                key: "deadline",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "cancel_response",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "validate",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
        ],
    },
    Endpoint {
        name: "get_spot_trades_info",
        path: "/0/private/QueryTrades",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["txid", "trades", "rebase_multiplier"],
        fields: &[
            Field {
                key: "txid",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "trades",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "rebase_multiplier",
                kind: "string",
                required: false,
                values: &["rebased", "base"],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_order_events",
        path: "/api/history/v3/orders",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[
            "since",
            "before",
            "sort",
            "continuation_token",
            "count",
            "tradeable",
            "opened",
            "closed",
            "product_symbol",
        ],
        fields: &[
            Field {
                key: "since",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "before",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "sort",
                kind: "string",
                required: false,
                values: &["asc", "desc"],
                minimum: 0,
            },
            Field {
                key: "continuation_token",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "count",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 1,
            },
            Field {
                key: "tradeable",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "opened",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "closed",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: Some("tradeable"),
    },
    Endpoint {
        name: "get_futures_position_events",
        path: "/api/history/v3/positions",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[
            "since",
            "before",
            "sort",
            "continuation_token",
            "count",
            "opened",
            "closed",
            "increased",
            "decreased",
            "reversed",
            "no_change",
            "trades",
            "funding_realization",
            "settlement",
            "tradeable",
            "product_symbol",
        ],
        fields: &[
            Field {
                key: "since",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "before",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "sort",
                kind: "string",
                required: false,
                values: &["asc", "desc"],
                minimum: 0,
            },
            Field {
                key: "continuation_token",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "count",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 1,
            },
            Field {
                key: "opened",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "closed",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "increased",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "decreased",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "reversed",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "no_change",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "trades",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "funding_realization",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "settlement",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "tradeable",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: Some("tradeable"),
    },
    Endpoint {
        name: "get_spot_order_amends",
        path: "/0/private/OrderAmends",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["order_id", "rebase_multiplier"],
        fields: &[
            Field {
                key: "order_id",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "rebase_multiplier",
                kind: "string",
                required: false,
                values: &["rebased", "base"],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_futures_self_trade_strategy",
        path: "/derivatives/api/v3/self-trade-strategy",
        method: HttpMethod::Get,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[],
        fields: &[],
        symbol_key: None,
    },
    Endpoint {
        name: "set_futures_self_trade_strategy",
        path: "/derivatives/api/v3/self-trade-strategy",
        method: HttpMethod::Put,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &["strategy"],
        fields: &[Field {
            key: "strategy",
            kind: "string",
            required: true,
            values: &[
                "REJECT_TAKER",
                "CANCEL_MAKER_SELF",
                "CANCEL_MAKER_CHILD",
                "CANCEL_MAKER_ANY",
            ],
            minimum: 0,
        }],
        symbol_key: None,
    },
    Endpoint {
        name: "get_spot_post_trade_data",
        path: "/0/public/PostTrade",
        method: HttpMethod::Get,
        auth: KrakenAuth::Spot,
        public: true,
        allowed: &["symbol", "from_ts", "to_ts", "count"],
        fields: &[
            Field {
                key: "symbol",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "from_ts",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "to_ts",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "count",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 1,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_spot_pre_trade_data",
        path: "/0/public/PreTrade",
        method: HttpMethod::Get,
        auth: KrakenAuth::Spot,
        public: true,
        allowed: &["symbol"],
        fields: &[Field {
            key: "symbol",
            kind: "string",
            required: true,
            values: &[],
            minimum: 0,
        }],
        symbol_key: None,
    },
];
