//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "transfer_spot_sub_account",
        path: "/0/private/AccountTransfer",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["asset", "asset_class", "amount", "from", "to"],
        fields: &[
            Field {
                key: "asset",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "asset_class",
                kind: "string",
                required: false,
                values: &["currency", "tokenized_asset"],
                minimum: 0,
            },
            Field {
                key: "amount",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "from",
                kind: "string",
                required: true,
                values: &[],
                minimum: 1,
            },
            Field {
                key: "to",
                kind: "string",
                required: true,
                values: &[],
                minimum: 1,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "transfer_futures_sub_account",
        path: "/derivatives/api/v3/transfer/subaccount",
        method: HttpMethod::Post,
        auth: KrakenAuth::Futures,
        public: false,
        allowed: &[
            "fromUser",
            "toUser",
            "fromAccount",
            "toAccount",
            "unit",
            "amount",
        ],
        fields: &[
            Field {
                key: "fromUser",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "toUser",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "fromAccount",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "toAccount",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "unit",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "amount",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
];
