//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "get_withdrawal_addresses",
        path: "/0/private/WithdrawAddresses",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["asset", "aclass", "method", "key", "verified"],
        fields: &[
            Field {
                key: "asset",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "aclass",
                kind: "string",
                required: false,
                values: &["currency", "tokenized_asset"],
                minimum: 0,
            },
            Field {
                key: "method",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "key",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "verified",
                kind: "boolean",
                required: false,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_withdrawal_information",
        path: "/0/private/WithdrawInfo",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["asset", "key", "amount"],
        fields: &[
            Field {
                key: "asset",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "key",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "amount",
                kind: "string",
                required: true,
                values: &[],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_withdrawal_methods",
        path: "/0/private/WithdrawMethods",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &["asset", "aclass", "network", "rebase_multiplier"],
        fields: &[
            Field {
                key: "asset",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "aclass",
                kind: "string",
                required: false,
                values: &["currency", "tokenized_asset"],
                minimum: 0,
            },
            Field {
                key: "network",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "rebase_multiplier",
                kind: "string",
                required: false,
                values: &["rebased", "base"],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
    Endpoint {
        name: "get_withdrawal_status",
        path: "/0/private/WithdrawStatus",
        method: HttpMethod::Post,
        auth: KrakenAuth::Spot,
        public: false,
        allowed: &[
            "asset",
            "aclass",
            "method",
            "start",
            "end",
            "cursor",
            "limit",
            "rebase_multiplier",
        ],
        fields: &[
            Field {
                key: "asset",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "aclass",
                kind: "string",
                required: false,
                values: &["currency", "tokenized_asset"],
                minimum: 0,
            },
            Field {
                key: "method",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "start",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "end",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "cursor",
                kind: "string",
                required: false,
                values: &[],
                minimum: 0,
            },
            Field {
                key: "limit",
                kind: "integer",
                required: false,
                values: &[],
                minimum: 1,
            },
            Field {
                key: "rebase_multiplier",
                kind: "string",
                required: false,
                values: &["rebased", "base"],
                minimum: 0,
            },
        ],
        symbol_key: None,
    },
];
