"""Lighter public API endpoints."""

from enum import Enum


class Public(str, Enum):
    """Lighter public REST endpoints."""

    STATUS = "/"
    INFO = "/info"
    ACCOUNT = "/api/v1/account"
    ACCOUNT_ACTIVE_ORDERS = "/api/v1/accountActiveOrders"
    ACCOUNT_INACTIVE_ORDERS = "/api/v1/accountInactiveOrders"
    ACCOUNT_LIMITS = "/api/v1/accountLimits"
    ACCOUNTS_BY_L1_ADDRESS = "/api/v1/accountsByL1Address"
    ACCOUNT_METADATA = "/api/v1/accountMetadata"
    ANNOUNCEMENT = "/api/v1/announcement"
    API_KEYS = "/api/v1/apikeys"
    ASSET_DETAILS = "/api/v1/assetDetails"
    CANDLES = "/api/v1/candles"
    DEPOSIT_HISTORY = "/api/v1/deposit/history"
    DEPOSIT_NETWORKS = "/api/v1/deposit/networks"
    EXCHANGE_METRICS = "/api/v1/exchangeMetrics"
    EXCHANGE_STATS = "/api/v1/exchangeStats"
    EXECUTE_STATS = "/api/v1/executeStats"
    EXPORT = "/api/v1/export"
    FASTBRIDGE_INFO = "/api/v1/fastbridge/info"
    FASTWITHDRAW_INFO = "/api/v1/fastwithdraw/info"
    FUNDING_RATES = "/api/v1/funding-rates"
    FUNDINGS = "/api/v1/fundings"
    L1_METADATA = "/api/v1/l1Metadata"
    LAYER1_BASIC_INFO = "/api/v1/layer1BasicInfo"
    LEASE_OPTIONS = "/api/v1/leaseOptions"
    LEASES = "/api/v1/leases"
    LIQUIDATIONS = "/api/v1/liquidations"
    ORDER_BOOK_DETAILS = "/api/v1/orderBookDetails"
    ORDER_BOOK_ORDERS = "/api/v1/orderBookOrders"
    ORDER_BOOKS = "/api/v1/orderBooks"
    PARTNER_STATS = "/api/v1/partnerStats"
    PNL = "/api/v1/pnl"
    POSITION_FUNDING = "/api/v1/positionFunding"
    PUBLIC_POOLS_METADATA = "/api/v1/publicPoolsMetadata"
    RECENT_TRADES = "/api/v1/recentTrades"
    REFERRAL_POINTS = "/api/v1/referral/points"
    REFERRAL_USER_REFERRALS = "/api/v1/referral/userReferrals"
    SEND_TX = "/api/v1/sendTx"
    SEND_TX_BATCH = "/api/v1/sendTxBatch"
    SYSTEM_CONFIG = "/api/v1/systemConfig"
    TOKENLIST = "/api/v1/tokenlist"
    TOKENS = "/api/v1/tokens"
    TRADES = "/api/v1/trades"
    TRANSFER_FEE_INFO = "/api/v1/transferFeeInfo"
    TRANSFER_HISTORY = "/api/v1/transfer/history"
    GET_MAKER_ONLY_API_KEYS = "/api/v1/getMakerOnlyApiKeys"
    NEXT_NONCE = "/api/v1/nextNonce"
    WITHDRAW_HISTORY = "/api/v1/withdraw/history"
    WITHDRAWAL_DELAY = "/api/v1/withdrawalDelay"

    def __str__(self) -> str:
        return self.value
