//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "get_futures_estimated_open_count" => Endpoint {
            path: "/api/v2/mix/account/open-count",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "productType",
                "marginCoin",
                "openAmount",
                "openPrice",
                "leverage",
            ],
            required: &[
                "symbol",
                "productType",
                "marginCoin",
                "openAmount",
                "openPrice",
            ],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-liquidation-price
        "get_futures_liquidation_price" => Endpoint {
            path: "/api/v2/mix/account/liq-price",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "productType",
                "marginCoin",
                "posSide",
                "orderType",
                "openAmount",
                "openPrice",
            ],
            required: &[
                "symbol",
                "productType",
                "marginCoin",
                "posSide",
                "orderType",
                "openAmount",
            ],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-max-openable-quantity
        "get_futures_max_open_quantity" => Endpoint {
            path: "/api/v2/mix/account/max-open",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "productType",
                "marginCoin",
                "posSide",
                "orderType",
                "openPrice",
            ],
            required: &[
                "symbol",
                "productType",
                "marginCoin",
                "posSide",
                "orderType",
            ],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-usdt-m-futures-interest-history
        "get_futures_interest_history" => Endpoint {
            path: "/api/v2/mix/account/interest-history",
            post: false,
            public: false,
            fields: &[
                "productType",
                "startTime",
                "endTime",
                "coin",
                "idLessThan",
                "limit",
            ],
            required: &["productType", "startTime", "endTime"],
            arrays: &[],
            limit: Some(100),
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#change-the-product-line-leverage
        "set_futures_asset_mode" => Endpoint {
            path: "/api/v2/mix/account/set-asset-mode",
            post: true,
            public: false,
            fields: &["productType", "assetMode"],
            required: &["productType", "assetMode"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#union-convert
        "get_futures_union_config" => Endpoint {
            path: "/api/v2/mix/account/union-config",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-isolated-symbols
        "get_uta_funding_records" => Endpoint {
            path: "/api/v3/account/funding-financial-records",
            post: false,
            public: false,
            fields: &["coin", "type", "startTime", "endTime", "limit", "cursor"],
            required: &[],
            arrays: &[],
            limit: Some(100),
            days: Some(30),
        },
        // https://www.bitget.com/docs/catalog/account/assets-balance#get-account-fee-rate
        "get_uta_fee_rate" => Endpoint {
            path: "/api/v3/account/fee-rate",
            post: false,
            public: false,
            fields: &["symbol", "category"],
            required: &["symbol", "category"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/assets-balance#get-max-transferable
        "set_uta_collateral_type" => Endpoint {
            path: "/api/v3/account/set-collateral-type",
            post: true,
            public: false,
            fields: &["collateralType", "collateralCoins", "allowCashplus"],
            required: &["collateralType"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/account-settings#get-account-setting
        "get_uta_settings" => Endpoint {
            path: "/api/v3/account/settings",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/account-settings#get-delta-info
        "get_uta_delta_info" => Endpoint {
            path: "/api/v3/account/delta-info",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-Repayable-Coins
        "get_uta_payment_coins" => Endpoint {
            path: "/api/v3/account/payment-coins",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Borrow
        "get_uta_max_open_available" => Endpoint {
            path: "/api/v3/account/max-open-available",
            post: true,
            public: false,
            fields: &[
                "category",
                "symbol",
                "orderType",
                "side",
                "price",
                "size",
                "autoBorrow",
            ],
            required: &["category", "symbol", "orderType", "side"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/position-management#get-move-position-history
        "get_uta_eligible_discount_rates" => Endpoint {
            path: "/api/v3/account/eligible-discount-rate",
            post: false,
            public: false,
            fields: &["coin"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-Eligible-Loan-Info
        "set_uta_account_mode" => Endpoint {
            path: "/api/v3/account/adjust-account-mode",
            post: true,
            public: false,
            fields: &["mode", "deltaSwitch", "targetUid"],
            required: &["mode"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/position-management#get-position-adl-rank
        "set_uta_fee_deduction" => Endpoint {
            path: "/api/v3/account/switch-deduct",
            post: true,
            public: false,
            fields: &["deduct"],
            required: &["deduct"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/account-settings#get-deduct-info
        "get_uta_fee_deduction" => Endpoint {
            path: "/api/v3/account/deduct-info",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/account-settings#switch-account
        "upgrade_to_uta" => Endpoint {
            path: "/api/v3/account/switch",
            post: true,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/account-settings#get-switch-status
        "get_uta_upgrade_status" => Endpoint {
            path: "/api/v3/account/switch-status",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-switch-union-usdt
        "get_classic_account_upgrade_status" => Endpoint {
            path: "/api/v2/spot/account/upgrade-status",
            post: false,
            public: false,
            fields: &["subUid"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#upgrade-account
        "upgrade_classic_account" => Endpoint {
            path: "/api/v2/spot/account/upgrade",
            post: true,
            public: false,
            fields: &["subUid"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#get-bgb-deduct-info
        "get_spot_fee_deduction" => Endpoint {
            path: "/api/v2/spot/account/deduct-info",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#switch-bgb-deduct
        "set_spot_fee_deduction" => Endpoint {
            path: "/api/v2/spot/account/switch-deduct",
            post: true,
            public: false,
            fields: &["deduct"],
            required: &["deduct"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#modify-deposit-account
        "get_uta_rate_limit_quota" => Endpoint {
            path: "/api/v3/user/rate-limit-quota",
            post: false,
            public: false,
            fields: &["category", "uid", "cursor", "limit"],
            required: &["category"],
            arrays: &[],
            limit: Some(100),
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/rate-limit-quota#set-ratelimit-quota
        "uta_set_rate_limit_quota" => Endpoint {
            path: "/api/v3/user/set-rate-limit-quota",
            post: true,
            public: false,
            fields: &["category", "uids", "quota"],
            required: &["category", "uids", "quota"],
            arrays: &["uids"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/small-assets#get-small-assets-history
        "uta_delete_sub" => Endpoint {
            path: "/api/v3/user/delete-sub",
            post: true,
            public: false,
            fields: &["subUid"],
            required: &["subUid"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/sub-accounts#freeze-or-unfreeze-sub-account
        "uta_freeze_sub" => Endpoint {
            path: "/api/v3/user/freeze-sub",
            post: true,
            public: false,
            fields: &["subUid", "operation"],
            required: &["subUid", "operation"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/sub-accounts#create-sub-account-api-key
        "uta_create_sub_api" => Endpoint {
            path: "/api/v3/user/create-sub-api",
            post: true,
            public: false,
            fields: &["subUid", "note", "type", "passphrase", "permissions", "ips"],
            required: &["subUid", "note", "type", "passphrase", "permissions", "ips"],
            arrays: &["permissions", "ips"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/sub-accounts#modify-sub-account-api-key
        "uta_update_sub_api" => Endpoint {
            path: "/api/v3/user/update-sub-api",
            post: true,
            public: false,
            fields: &["apiKey", "passphrase", "type", "permissions", "ips"],
            required: &["apiKey", "passphrase"],
            arrays: &["permissions", "ips"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/sub-accounts#delete-sub-account-api-key
        "uta_delete_sub_api" => Endpoint {
            path: "/api/v3/user/delete-sub-api",
            post: true,
            public: false,
            fields: &["apiKey"],
            required: &["apiKey"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/sub-accounts#get-sub-account-api-keys
        "get_uta_sub_api_list" => Endpoint {
            path: "/api/v3/user/sub-api-list",
            post: false,
            public: false,
            fields: &["subUid", "limit", "cursor"],
            required: &["subUid"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-common-vsubaccount/classic-common-vsubaccount#create-virtual-subaccount
        _ => return None,
    })
}
