//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "get_classic_account_bot_assets" => Endpoint {
            path: "/api/v2/account/bot-assets",
            post: false,
            public: false,
            fields: &["accountType"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#get-withdrawal-records
        "uta_trade_grid_add_investment" => Endpoint {
            path: "/api/v3/trade/grid/add-investment",
            post: true,
            public: false,
            fields: &[
                "category",
                "botId",
                "coin",
                "size",
                "fundsSource",
                "adjustType",
                "reinvestProfit",
            ],
            required: &["category", "botId", "coin", "size", "fundsSource"],
            arrays: &["fundsSource"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/grid-trading#get-grid-bot-detail
        "get_uta_trade_grid_bot_detail" => Endpoint {
            path: "/api/v3/trade/grid/bot-detail",
            post: false,
            public: false,
            fields: &["botId"],
            required: &["botId"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/grid-trading#close-grid-bot
        "uta_trade_grid_close_bot" => Endpoint {
            path: "/api/v3/trade/grid/close-bot",
            post: true,
            public: false,
            fields: &["botId"],
            required: &["botId"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/grid-trading#create-grid-bot
        "uta_trade_grid_create_bot" => Endpoint {
            path: "/api/v3/trade/grid/create-bot",
            post: true,
            public: false,
            fields: &[
                "category",
                "symbol",
                "maxPrice",
                "minPrice",
                "gridNum",
                "gridOrderMode",
                "investmentAmount",
                "fundsSource",
                "slippage",
                "autoTransferProfits",
                "gridType",
                "leverage",
                "autoReserveMargin",
                "reservedMargin",
                "triggerCondition",
                "triggerParams",
                "triggerPrice",
                "terminationCondition",
                "terminationParams",
                "terminationSell",
                "stopLoss",
                "takeProfit",
                "trailingGrid",
                "movingAverageGains",
                "stopUpwardPrice",
                "hodlMode",
                "marketOpen",
                "lossReserve",
            ],
            required: &[
                "category",
                "symbol",
                "maxPrice",
                "minPrice",
                "gridNum",
                "gridOrderMode",
                "investmentAmount",
                "fundsSource",
                "slippage",
                "autoTransferProfits",
            ],
            arrays: &[
                "investmentAmount",
                "fundsSource",
                "triggerParams",
                "terminationParams",
            ],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/grid-trading#create-neutral-grid-bot
        "uta_trade_grid_create_neutral_bot" => Endpoint {
            path: "/api/v3/trade/grid/create-neutral-bot",
            post: true,
            public: false,
            fields: &[
                "category",
                "symbol",
                "maxPrice",
                "minPrice",
                "gridNum",
                "gridOrderMode",
                "fundsSource",
                "leverage",
                "investmentAmount",
                "triggerPrice",
                "stopLoss",
                "takeProfit",
                "autoTransferProfits",
            ],
            required: &[
                "category",
                "symbol",
                "maxPrice",
                "minPrice",
                "gridNum",
                "gridOrderMode",
                "fundsSource",
            ],
            arrays: &["fundsSource", "investmentAmount"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/grid-trading#get-grid-bot-order-details
        "get_uta_trade_grid_list_details" => Endpoint {
            path: "/api/v3/trade/grid/list-details",
            post: false,
            public: false,
            fields: &["category", "botId"],
            required: &["category", "botId"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/grid-trading#modify-grid-bot-parameters
        "uta_trade_grid_modify_bot" => Endpoint {
            path: "/api/v3/trade/grid/modify-bot",
            post: true,
            public: false,
            fields: &[
                "botId",
                "category",
                "takeProfit",
                "stopLoss",
                "terminationCondition",
                "terminationParams",
                "hodlMode",
                "autoTransferProfits",
            ],
            required: &["botId"],
            arrays: &["terminationParams"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/grid-trading#modify-grid-interval-and-grid-number
        "uta_trade_grid_modify_grid_interval" => Endpoint {
            path: "/api/v3/trade/grid/modify-grid-interval",
            post: true,
            public: false,
            fields: &["category", "botId", "maxPrice", "minPrice", "gridNum"],
            required: &["category", "botId", "maxPrice", "minPrice", "gridNum"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/grid-trading#modify-neutral-grid-bot-parameters
        "uta_trade_grid_modify_neutral_bot" => Endpoint {
            path: "/api/v3/trade/grid/modify-neutral-bot",
            post: true,
            public: false,
            fields: &[
                "botId",
                "category",
                "takeProfit",
                "stopLoss",
                "autoTransferProfits",
            ],
            required: &["botId", "category"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/grid-trading#modify-neutral-grid-interval-and-grid-number
        "uta_trade_grid_modify_neutral_grid_interval" => Endpoint {
            path: "/api/v3/trade/grid/modify-neutral-grid-interval",
            post: true,
            public: false,
            fields: &["category", "botId", "maxPrice", "minPrice", "gridNum"],
            required: &["category", "botId", "maxPrice", "minPrice", "gridNum"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/grid-trading#get-neutral-grid-bot-detail
        "get_uta_trade_grid_neutral_bot_detail" => Endpoint {
            path: "/api/v3/trade/grid/neutral-bot-detail",
            post: false,
            public: false,
            fields: &["botId"],
            required: &["botId"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/grid-trading#get-neutral-grid-bot-order-details
        "get_uta_trade_grid_neutral_list_details" => Endpoint {
            path: "/api/v3/trade/grid/neutral-list-details",
            post: false,
            public: false,
            fields: &["category", "botId"],
            required: &["category", "botId"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/grid-trading#validate-neutral-grid-parameters
        "uta_trade_grid_validate_neutral" => Endpoint {
            path: "/api/v3/trade/grid/validate-neutral",
            post: true,
            public: false,
            fields: &[
                "category",
                "symbol",
                "maxPrice",
                "minPrice",
                "gridNum",
                "gridOrderMode",
                "leverage",
                "investmentAmount",
                "triggerPrice",
                "stopLoss",
                "takeProfit",
                "autoTransferProfits",
            ],
            required: &[
                "category",
                "symbol",
                "maxPrice",
                "minPrice",
                "gridNum",
                "gridOrderMode",
            ],
            arrays: &["investmentAmount"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/grid-trading#validate-grid-parameters
        "uta_trade_grid_validate" => Endpoint {
            path: "/api/v3/trade/grid/validate",
            post: true,
            public: false,
            fields: &[
                "category",
                "symbol",
                "maxPrice",
                "minPrice",
                "gridNum",
                "gridOrderMode",
                "investmentAmount",
                "autoTransferProfits",
                "gridType",
                "leverage",
                "reservedMargin",
                "triggerCondition",
                "triggerParams",
                "triggerPrice",
                "terminationCondition",
                "terminationParams",
                "stopLoss",
                "takeProfit",
                "trailingGrid",
                "movingAverageGains",
                "stopUpwardPrice",
                "hodlMode",
                "marketOpen",
                "lossReserve",
            ],
            required: &[
                "category",
                "symbol",
                "maxPrice",
                "minPrice",
                "gridNum",
                "gridOrderMode",
                "investmentAmount",
                "autoTransferProfits",
            ],
            arrays: &["investmentAmount", "triggerParams", "terminationParams"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/reality/basic-info#get-company-overview
        _ => return None,
    })
}
