//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "get_classic_earn_elite_product" => Endpoint {
            path: "/api/v2/earn/elite/product",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-elite/classic-earn-elite#elite-subscribe
        "classic_earn_elite_subscribe" => Endpoint {
            path: "/api/v2/earn/elite/subscribe",
            post: true,
            public: false,
            fields: &["productSubId", "amount", "coin", "paymentAccount"],
            required: &["productSubId", "amount"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-elite/classic-earn-elite#get-elite-subscribe-result
        "get_classic_earn_elite_subscribe_result" => Endpoint {
            path: "/api/v2/earn/elite/subscribe-result",
            post: false,
            public: false,
            fields: &["orderId"],
            required: &["orderId"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-elite/classic-earn-elite#get-elite-subscribe-info
        "get_classic_earn_elite_subscribe_info" => Endpoint {
            path: "/api/v2/earn/elite/subscribe-info",
            post: false,
            public: false,
            fields: &["productId"],
            required: &["productId"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-elite/classic-earn-elite#elite-redeem
        "classic_earn_elite_redeem" => Endpoint {
            path: "/api/v2/earn/elite/redeem",
            post: true,
            public: false,
            fields: &[
                "productId",
                "productSubId",
                "redeemType",
                "amount",
                "receiveAccount",
                "advancedSettle",
                "coin",
            ],
            required: &[
                "productId",
                "productSubId",
                "redeemType",
                "amount",
                "receiveAccount",
            ],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-elite/classic-earn-elite#get-redeem-info
        "get_classic_earn_elite_redeem_info" => Endpoint {
            path: "/api/v2/earn/elite/redeem-info",
            post: false,
            public: false,
            fields: &["productId"],
            required: &["productId"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-elite/classic-earn-elite#get-elite-assets
        "get_classic_earn_elite_assets" => Endpoint {
            path: "/api/v2/earn/elite/assets",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-elite/classic-earn-elite#get-elite-records
        "get_classic_earn_elite_records" => Endpoint {
            path: "/api/v2/earn/elite/records",
            post: false,
            public: false,
            fields: &["type", "startTime", "endTime", "limit", "cursor"],
            required: &["type"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-loan/classic-earn-loan#get-currency-list
        "get_classic_earn_loan_public_coin_infos" => Endpoint {
            path: "/api/v2/earn/loan/public/coinInfos",
            post: false,
            public: true,
            fields: &["coin"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-loan/classic-earn-loan#get-est-interest-and-borrowable
        "get_classic_earn_loan_public_hour_interest" => Endpoint {
            path: "/api/v2/earn/loan/public/hour-interest",
            post: false,
            public: true,
            fields: &["loanCoin", "pledgeCoin", "daily", "pledgeAmount"],
            required: &["loanCoin", "pledgeCoin", "daily", "pledgeAmount"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-loan/classic-earn-loan#borrow
        "classic_earn_loan_borrow" => Endpoint {
            path: "/api/v2/earn/loan/borrow",
            post: true,
            public: false,
            fields: &[
                "loanCoin",
                "pledgeCoin",
                "daily",
                "pledgeAmount",
                "loanAmount",
            ],
            required: &["loanCoin", "pledgeCoin", "daily"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-loan/classic-earn-loan#get-loan-orders
        "get_classic_earn_loan_ongoing_orders" => Endpoint {
            path: "/api/v2/earn/loan/ongoing-orders",
            post: false,
            public: false,
            fields: &["orderId", "loanCoin", "pledgeCoin"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-loan/classic-earn-loan#repay
        "classic_earn_loan_repay" => Endpoint {
            path: "/api/v2/earn/loan/repay",
            post: true,
            public: false,
            fields: &["orderId", "repayAll", "amount", "repayUnlock"],
            required: &["orderId", "repayAll"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-loan/classic-earn-loan#get-repay-history
        "get_classic_earn_loan_repay_history" => Endpoint {
            path: "/api/v2/earn/loan/repay-history",
            post: false,
            public: false,
            fields: &[
                "startTime",
                "endTime",
                "orderId",
                "loanCoin",
                "pledgeCoin",
                "pageNo",
                "pageSize",
            ],
            required: &["startTime", "endTime"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-loan/classic-earn-loan#modify-pledge-rate
        "classic_earn_loan_revise_pledge" => Endpoint {
            path: "/api/v2/earn/loan/revise-pledge",
            post: true,
            public: false,
            fields: &["orderId", "amount", "pledgeCoin", "reviseType"],
            required: &["orderId", "amount", "pledgeCoin", "reviseType"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-loan/classic-earn-loan#get-pledge-rate-history
        "get_classic_earn_loan_revise_history" => Endpoint {
            path: "/api/v2/earn/loan/revise-history",
            post: false,
            public: false,
            fields: &[
                "startTime",
                "endTime",
                "orderId",
                "reviseSide",
                "pledgeCoin",
                "pageNo",
                "pageSize",
            ],
            required: &["startTime", "endTime"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-loan/classic-earn-loan#get-loan-history
        "get_classic_earn_loan_borrow_history" => Endpoint {
            path: "/api/v2/earn/loan/borrow-history",
            post: false,
            public: false,
            fields: &[
                "startTime",
                "endTime",
                "orderId",
                "loanCoin",
                "pledgeCoin",
                "status",
                "pageNo",
                "pageSize",
            ],
            required: &["startTime", "endTime"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-loan/classic-earn-loan#get-debts
        "get_classic_earn_loan_debts" => Endpoint {
            path: "/api/v2/earn/loan/debts",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/earn-classic-loan/classic-earn-loan#get-liquidation-records
        "get_classic_earn_loan_reduces" => Endpoint {
            path: "/api/v2/earn/loan/reduces",
            post: false,
            public: false,
            fields: &[
                "startTime",
                "endTime",
                "orderId",
                "loanCoin",
                "pledgeCoin",
                "status",
                "pageNo",
                "pageSize",
            ],
            required: &["startTime", "endTime"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/grid-trading#add-investment-amount
        _ => return None,
    })
}
