//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "borrow_cross_margin_asset" => Endpoint {
            path: "/api/v2/margin/crossed/account/borrow",
            post: true,
            public: false,
            fields: &["coin", "borrowAmount", "clientOid"],
            required: &["coin", "borrowAmount"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#cross-repay
        "repay_cross_margin_asset" => Endpoint {
            path: "/api/v2/margin/crossed/account/repay",
            post: true,
            public: false,
            fields: &["coin", "repayAmount"],
            required: &["coin", "repayAmount"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#get-cross-risk-rate
        "get_cross_margin_max_borrowable" => Endpoint {
            path: "/api/v2/margin/crossed/account/max-borrowable-amount",
            post: false,
            public: false,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#get-cross-max-transferable
        "flash_repay_cross_margin_assets" => Endpoint {
            path: "/api/v2/margin/crossed/account/flash-repay",
            post: true,
            public: false,
            fields: &["coin"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#get-cross-flash-repay-result
        "get_cross_margin_flash_repay_result" => Endpoint {
            path: "/api/v2/margin/crossed/account/query-flash-repay-status",
            post: true,
            public: false,
            fields: &["idList"],
            required: &["idList"],
            arrays: &["idList"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#get-cross-interest-rate-and-max-borrowable
        "get_cross_margin_borrow_history" => Endpoint {
            path: "/api/v2/margin/crossed/borrow-history",
            post: false,
            public: false,
            fields: &[
                "startTime",
                "loanId",
                "coin",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-record/classic-margin-cross-record#get-cross-repay-history
        "get_cross_margin_repay_history" => Endpoint {
            path: "/api/v2/margin/crossed/repay-history",
            post: false,
            public: false,
            fields: &[
                "startTime",
                "repayId",
                "coin",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-record/classic-margin-cross-record#get-cross-interest-history
        "borrow_isolated_margin_asset" => Endpoint {
            path: "/api/v2/margin/isolated/account/borrow",
            post: true,
            public: false,
            fields: &["symbol", "coin", "borrowAmount", "clientOid"],
            required: &["symbol", "coin", "borrowAmount"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#isolated-repay
        "repay_isolated_margin_asset" => Endpoint {
            path: "/api/v2/margin/isolated/account/repay",
            post: true,
            public: false,
            fields: &["repayAmount", "coin", "symbol", "clientOid"],
            required: &["repayAmount", "coin", "symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#get-isolated-risk-rate
        "get_isolated_margin_max_borrowable" => Endpoint {
            path: "/api/v2/margin/isolated/account/max-borrowable-amount",
            post: false,
            public: false,
            fields: &["symbol"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#get-isolated-max-transferable
        "flash_repay_isolated_margin_assets" => Endpoint {
            path: "/api/v2/margin/isolated/account/flash-repay",
            post: true,
            public: false,
            fields: &["symbolList"],
            required: &[],
            arrays: &["symbolList"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#query-isolated-flash-repayment-result
        "get_isolated_margin_flash_repay_result" => Endpoint {
            path: "/api/v2/margin/isolated/account/query-flash-repay-status",
            post: true,
            public: false,
            fields: &["idList"],
            required: &["idList"],
            arrays: &["idList"],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#get-isolated-interest-rate-and-max-borrowable
        "get_isolated_margin_borrow_history" => Endpoint {
            path: "/api/v2/margin/isolated/borrow-history",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "loanId",
                "coin",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-record/classic-margin-isolated-record#get-isolated-repayment-history
        "get_isolated_margin_repay_history" => Endpoint {
            path: "/api/v2/margin/isolated/repay-history",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "repayId",
                "coin",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-record/classic-margin-isolated-record#get-isolated-interest-history
        "get_uta_margin_loan_rates" => Endpoint {
            path: "/api/v3/market/margin-loans",
            post: false,
            public: true,
            fields: &["coin", "level"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Position-Tier-Data
        "get_uta_repayable_coins" => Endpoint {
            path: "/api/v3/account/repayable-coins",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-Payment-Coins
        "borrow_uta_asset" => Endpoint {
            path: "/api/v3/account/borrow",
            post: true,
            public: false,
            fields: &["coin", "amount", "clientOid"],
            required: &["coin", "amount"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-Max-Borrowable
        "get_uta_max_borrowable" => Endpoint {
            path: "/api/v3/account/max-borrowable",
            post: false,
            public: false,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-OI-Limit
        "set_uta_repay_mode" => Endpoint {
            path: "/api/v3/account/set-repay-mode",
            post: true,
            public: false,
            fields: &["repayMode"],
            required: &["repayMode"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-Eligible-Discount-Rate
        "get_uta_eligible_loan_info" => Endpoint {
            path: "/api/v3/account/eligible-loan-info",
            post: false,
            public: false,
            fields: &["coin"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-Eligible-Margin-Tier
        "get_uta_margin_loan_growth" => Endpoint {
            path: "/api/v3/market/margin-loan-growth",
            post: false,
            public: true,
            fields: &["symbol", "period", "coin"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/trading-stats#get-isolated-margin-borrowing-ratio-data
        "get_uta_margin_isolated_borrow" => Endpoint {
            path: "/api/v3/market/margin-isolated-borrow",
            post: false,
            public: true,
            fields: &["symbol", "period"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/trading-stats#get-futures-active-buy-sell-volume-data
        _ => return None,
    })
}
