//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "set_futures_auto_margin" => Endpoint {
            path: "/api/v2/mix/account/set-auto-margin",
            post: true,
            public: false,
            fields: &["symbol", "autoMargin", "marginCoin", "holdSide"],
            required: &["symbol", "autoMargin", "marginCoin", "holdSide"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#set-usdt-m-futures-asset-mode
        "get_cross_margin_assets" => Endpoint {
            path: "/api/v2/margin/crossed/account/assets",
            post: false,
            public: false,
            fields: &["coin"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#cross-borrow
        "get_cross_margin_risk_rate" => Endpoint {
            path: "/api/v2/margin/crossed/account/risk-rate",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#get-cross-max-borrowable
        "get_cross_margin_interest_rate_limits" => Endpoint {
            path: "/api/v2/margin/crossed/interest-rate-and-limit",
            post: false,
            public: false,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#get-cross-tier-configuration
        "get_cross_margin_tiers" => Endpoint {
            path: "/api/v2/margin/crossed/tier-data",
            post: false,
            public: false,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-record/classic-margin-cross-record#get-cross-borrow-history
        "get_cross_margin_interest_history" => Endpoint {
            path: "/api/v2/margin/crossed/interest-history",
            post: false,
            public: false,
            fields: &["startTime", "coin", "endTime", "limit", "idLessThan"],
            required: &["startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-record/classic-margin-cross-record#get-cross-liquidation-history
        "get_cross_margin_liquidation_history" => Endpoint {
            path: "/api/v2/margin/crossed/liquidation-history",
            post: false,
            public: false,
            fields: &["startTime", "endTime", "limit", "idLessThan"],
            required: &["startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-record/classic-margin-cross-record#get-cross-financial-history
        "get_cross_margin_financial_records" => Endpoint {
            path: "/api/v2/margin/crossed/financial-records",
            post: false,
            public: false,
            fields: &[
                "startTime",
                "marginType",
                "coin",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-trade/classic-margin-cross-trade#cross-place-order
        "place_cross_margin_order" => Endpoint {
            path: "/api/v2/margin/crossed/place-order",
            post: true,
            public: false,
            fields: &[
                "symbol",
                "orderType",
                "loanType",
                "force",
                "side",
                "price",
                "baseSize",
                "quoteSize",
                "clientOid",
                "stpMode",
            ],
            required: &["symbol", "orderType", "loanType", "force", "side"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-trade/classic-margin-cross-trade#cross-cancel-order
        "cancel_cross_margin_order" => Endpoint {
            path: "/api/v2/margin/crossed/cancel-order",
            post: true,
            public: false,
            fields: &["symbol", "orderId", "clientOid"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-trade/classic-margin-cross-trade#get-cross-current-orders
        "get_cross_margin_open_orders" => Endpoint {
            path: "/api/v2/margin/crossed/open-orders",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "orderId",
                "clientOid",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-trade/classic-margin-cross-trade#get-cross-history-orders
        "get_cross_margin_order_history" => Endpoint {
            path: "/api/v2/margin/crossed/history-orders",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "orderId",
                "enterPointSource",
                "clientOid",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-trade/classic-margin-cross-trade#get-cross-order-fills
        "get_cross_margin_fills" => Endpoint {
            path: "/api/v2/margin/crossed/fills",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "orderId",
                "idLessThan",
                "endTime",
                "limit",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#get-isolated-account-asset
        "get_isolated_margin_assets" => Endpoint {
            path: "/api/v2/margin/isolated/account/assets",
            post: false,
            public: false,
            fields: &["symbol"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#isolated-borrow
        "get_isolated_margin_risk_rate" => Endpoint {
            path: "/api/v2/margin/isolated/account/risk-rate",
            post: false,
            public: false,
            fields: &["symbol", "pageNum", "pageSize"],
            required: &[],
            arrays: &[],
            limit: Some(500),
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#get-isolated-max-borrowable
        "get_isolated_margin_interest_rate_limits" => Endpoint {
            path: "/api/v2/margin/isolated/interest-rate-and-limit",
            post: false,
            public: false,
            fields: &["symbol"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#get-isolated-tier-configuration
        "get_isolated_margin_tiers" => Endpoint {
            path: "/api/v2/margin/isolated/tier-data",
            post: false,
            public: false,
            fields: &["symbol"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-record/classic-margin-isolated-record#get-isolated-borrow-history
        "get_isolated_margin_interest_history" => Endpoint {
            path: "/api/v2/margin/isolated/interest-history",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "coin",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-record/classic-margin-isolated-record#get-isolated-liquidation-history
        "get_isolated_margin_liquidation_history" => Endpoint {
            path: "/api/v2/margin/isolated/liquidation-history",
            post: false,
            public: false,
            fields: &["symbol", "startTime", "endTime", "limit", "idLessThan"],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-record/classic-margin-isolated-record#get-isolated-financial-history
        "get_isolated_margin_financial_records" => Endpoint {
            path: "/api/v2/margin/isolated/financial-records",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "marginType",
                "coin",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-trade/classic-margin-isolated-trade#isolated-place-order
        "place_isolated_margin_order" => Endpoint {
            path: "/api/v2/margin/isolated/place-order",
            post: true,
            public: false,
            fields: &[
                "symbol",
                "orderType",
                "loanType",
                "force",
                "side",
                "price",
                "baseSize",
                "quoteSize",
                "clientOid",
                "stpMode",
            ],
            required: &["symbol", "orderType", "loanType", "force", "side"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-trade/classic-margin-isolated-trade#isolated-cancel-order
        "cancel_isolated_margin_order" => Endpoint {
            path: "/api/v2/margin/isolated/cancel-order",
            post: true,
            public: false,
            fields: &["symbol", "orderId", "clientOid"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-trade/classic-margin-isolated-trade#get-isolated-current-orders
        "get_isolated_margin_open_orders" => Endpoint {
            path: "/api/v2/margin/isolated/open-orders",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "orderId",
                "clientOid",
                "endTime",
                "limit",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-trade/classic-margin-isolated-trade#get-isolated-orders-history
        "get_isolated_margin_order_history" => Endpoint {
            path: "/api/v2/margin/isolated/history-orders",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "orderId",
                "enterPointSource",
                "clientOid",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-trade/classic-margin-isolated-trade#get-isolated-order-fills
        "get_isolated_margin_fills" => Endpoint {
            path: "/api/v2/margin/isolated/fills",
            post: false,
            public: false,
            fields: &[
                "symbol",
                "startTime",
                "orderId",
                "idLessThan",
                "endTime",
                "limit",
            ],
            required: &["symbol", "startTime"],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/market/derivatives#get-funding-rate-history
        "get_uta_eligible_margin_tiers" => Endpoint {
            path: "/api/v3/account/eligible-margin-tier",
            post: false,
            public: false,
            fields: &["coin"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-Eligible-Symbols
        "get_futures_margin_mode_switch_quota" => Endpoint {
            path: "/api/v2/mix/account/switch-union-usdt",
            post: false,
            public: false,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-trade/classic-margin-cross-trade#get-cross-liquidation-orders
        "get_cross_margin_liquidation_orders" => Endpoint {
            path: "/api/v2/margin/crossed/liquidation-order",
            post: false,
            public: false,
            fields: &[
                "type",
                "symbol",
                "fromCoin",
                "toCoin",
                "startTime",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &[],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-trade/classic-margin-isolated-trade#get-isolated-liquidation-orders
        "get_isolated_margin_liquidation_orders" => Endpoint {
            path: "/api/v2/margin/isolated/liquidation-order",
            post: false,
            public: false,
            fields: &[
                "type",
                "symbol",
                "fromCoin",
                "toCoin",
                "startTime",
                "endTime",
                "limit",
                "idLessThan",
            ],
            required: &[],
            arrays: &[],
            limit: Some(500),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#get-upgrade-status
        "get_classic_interest_rate_record" => Endpoint {
            path: "/api/v2/margin/interest-rate-record",
            post: false,
            public: true,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-common/classic-margin-common#get-support-currencies
        "get_classic_margin_currencies" => Endpoint {
            path: "/api/v2/margin/currencies",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-convert/classic-spot-convert#get-convert-coins
        "get_uta_margin_long_short" => Endpoint {
            path: "/api/v3/market/margin-long-short",
            post: false,
            public: true,
            fields: &["symbol", "period", "coin"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/trading-stats#get-margin-loan-growth-rate-data
        _ => return None,
    })
}
