//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "get_futures_trade_history" => Endpoint {
            path: "/api/v2/mix/market/fills-history",
            post: false,
            public: true,
            fields: &[
                "symbol",
                "productType",
                "limit",
                "idLessThan",
                "startTime",
                "endTime",
            ],
            required: &["symbol", "productType"],
            arrays: &[],
            limit: Some(1000),
            days: Some(7),
        },
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#get-historical-index-price-candlestick
        "get_futures_index_candle_history" => Endpoint {
            path: "/api/v2/mix/market/history-index-candles",
            post: false,
            public: true,
            fields: &[
                "symbol",
                "productType",
                "granularity",
                "startTime",
                "endTime",
                "limit",
            ],
            required: &["symbol", "productType", "granularity"],
            arrays: &[],
            limit: Some(200),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#get-historical-mark-price-candlestick
        "get_futures_mark_candle_history" => Endpoint {
            path: "/api/v2/mix/market/history-mark-candles",
            post: false,
            public: true,
            fields: &[
                "symbol",
                "productType",
                "granularity",
                "startTime",
                "endTime",
                "limit",
            ],
            required: &["symbol", "productType", "granularity"],
            arrays: &[],
            limit: Some(200),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#get-next-funding-time
        "get_futures_next_funding_time" => Endpoint {
            path: "/api/v2/mix/market/funding-time",
            post: false,
            public: true,
            fields: &["symbol", "productType"],
            required: &["symbol", "productType"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#get-contract-oi-limit
        "get_futures_open_interest_limit" => Endpoint {
            path: "/api/v2/mix/market/oi-limit",
            post: false,
            public: true,
            fields: &["productType", "symbol"],
            required: &["productType"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-position/classic-contract-position#get-position-tier
        "get_futures_position_tiers" => Endpoint {
            path: "/api/v2/mix/market/query-position-lever",
            post: false,
            public: true,
            fields: &["productType", "symbol"],
            required: &["productType", "symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#get-discount-rate
        "get_futures_discount_rates" => Endpoint {
            path: "/api/v2/mix/market/discount-rate",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#get-interest-exchange-rate
        "get_futures_interest_exchange_rates" => Endpoint {
            path: "/api/v2/mix/market/exchange-rate",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#get-interest-rate-history
        "get_futures_interest_rate_history" => Endpoint {
            path: "/api/v2/mix/market/union-interest-rate-history",
            post: false,
            public: true,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-market/classic-contract-market#vip-fee-rate
        "get_futures_vip_fee_rates" => Endpoint {
            path: "/api/v2/mix/market/vip-fee-rate",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-subaccount-assets
        "get_futures_isolated_symbols" => Endpoint {
            path: "/api/v2/mix/account/isolated-symbols",
            post: false,
            public: false,
            fields: &["productType"],
            required: &["productType"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-position/classic-contract-position#get-historical-position
        "get_uta_funding_rate_history" => Endpoint {
            path: "/api/v3/market/history-fund-rate",
            post: false,
            public: true,
            fields: &["category", "symbol", "cursor", "limit"],
            required: &["category", "symbol"],
            arrays: &[],
            limit: Some(100),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/market/derivatives#get-index-price-components
        "get_uta_index_components" => Endpoint {
            path: "/api/v3/market/index-components",
            post: false,
            public: true,
            fields: &["symbol"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Margin-Loans
        "get_uta_position_tiers" => Endpoint {
            path: "/api/v3/market/position-tier",
            post: false,
            public: true,
            fields: &["category", "symbol", "coin"],
            required: &["category"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Contracts-Oi
        "get_uta_open_interest_limit" => Endpoint {
            path: "/api/v3/market/oi-limit",
            post: false,
            public: true,
            fields: &["symbol", "category"],
            required: &["category"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Discount-Rate
        "get_uta_discount_rates" => Endpoint {
            path: "/api/v3/market/discount-rate",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/market-data#get-rpi-order-book
        "get_uta_rpi_orderbook" => Endpoint {
            path: "/api/v3/market/rpi-orderbook",
            post: false,
            public: true,
            fields: &["category", "symbol", "limit"],
            required: &["category", "symbol"],
            arrays: &[],
            limit: Some(1000),
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/market-data#get-rpi-symbols
        "get_uta_rpi_symbols" => Endpoint {
            path: "/api/v3/market/rpi-symbols",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/assets-balance#get-account-funding-assets
        "get_uta_account_open_interest_limit" => Endpoint {
            path: "/api/v3/account/open-interest-limit",
            post: false,
            public: false,
            fields: &["symbol", "category"],
            required: &["symbol", "category"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/transfer/Get-Transfer-Coins
        "get_uta_eligible_symbols" => Endpoint {
            path: "/api/v3/account/eligible-symbols",
            post: false,
            public: false,
            fields: &["symbol"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/Get-Convert-Records
        "get_server_time" => Endpoint {
            path: "/api/v2/public/time",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: Some(100),
            days: None,
        },
        // https://www.bitget.com/legacy-docs/classic/common/public/Get-All-Trade-Rate
        "get_uta_cash_dividend_records" => Endpoint {
            path: "/api/v3/market/cash-dividend-records",
            post: false,
            public: true,
            fields: &["symbol", "type", "cursor", "limit"],
            required: &["symbol", "type"],
            arrays: &[],
            limit: Some(100),
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Risk-Reserve
        "get_uta_risk_reserve" => Endpoint {
            path: "/api/v3/market/risk-reserve",
            post: false,
            public: true,
            fields: &["category", "symbol", "marginCoin"],
            required: &["category", "symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Risk-Reserve-All
        "get_uta_all_risk_reserves" => Endpoint {
            path: "/api/v3/market/risk-reserve-all",
            post: false,
            public: true,
            fields: &["category"],
            required: &["category"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Risk-Reserve-Hour
        "get_uta_hourly_risk_reserve" => Endpoint {
            path: "/api/v3/market/risk-reserve-hour",
            post: false,
            public: true,
            fields: &["category", "symbol", "marginCoin"],
            required: &["category", "symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/Get-Split-Records
        "get_uta_split_records" => Endpoint {
            path: "/api/v3/market/split-records",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/trading-data/Get-Futures-Account-Long-Short
        "get_uta_futures_long_short_ratio" => Endpoint {
            path: "/api/v3/market/futures-account-long-short",
            post: false,
            public: true,
            fields: &["symbol", "period"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/public/trading-data/Get-Spot-Whale-Net-Flow
        "get_uta_spot_whale_flow" => Endpoint {
            path: "/api/v3/market/spot-whale-flow",
            post: false,
            public: true,
            fields: &["symbol"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/deposit-withdrawal#get-deposit-address
        "get_classic_merge_depth" => Endpoint {
            path: "/api/v2/spot/market/merge-depth",
            post: false,
            public: true,
            fields: &["symbol", "precision", "limit"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-market/classic-spot-market#get-call-auction-information
        "get_classic_auction" => Endpoint {
            path: "/api/v2/spot/market/auction",
            post: false,
            public: true,
            fields: &["symbol"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-spot-market/classic-spot-market#get-vip-fee-rate
        "get_classic_vip_fee_rate" => Endpoint {
            path: "/api/v2/spot/market/vip-fee-rate",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/public-config#get-proof-of-reserves
        "get_uta_proof_of_reserves" => Endpoint {
            path: "/api/v3/market/proof-of-reserves",
            post: false,
            public: true,
            fields: &[],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/public-config#get-market-maker-score-weight
        "get_uta_score_weights" => Endpoint {
            path: "/api/v3/market/score-weights",
            post: false,
            public: true,
            fields: &["category"],
            required: &[],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/public-config#get-institution-fee-group
        "get_uta_fee_group" => Endpoint {
            path: "/api/v3/market/fee-group",
            post: false,
            public: true,
            fields: &["category", "group"],
            required: &["category"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/trading-stats#get-spot-fund-flow-data
        "get_uta_spot_fund_flow" => Endpoint {
            path: "/api/v3/market/spot-fund-flow",
            post: false,
            public: true,
            fields: &["symbol", "period"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/trading-stats#get-spot-24h-net-capital-inflow-data
        "get_uta_spot_net_flow" => Endpoint {
            path: "/api/v3/market/spot-net-flow",
            post: false,
            public: true,
            fields: &["symbol"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/trading-stats#get-margin-long-short-ratio-data
        "get_uta_futures_active_buy_sell" => Endpoint {
            path: "/api/v3/market/futures-active-buy-sell",
            post: false,
            public: true,
            fields: &["symbol", "period"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/trading-stats#get-futures-long-short-ratio-data
        "get_uta_futures_long_short" => Endpoint {
            path: "/api/v3/market/futures-long-short",
            post: false,
            public: true,
            fields: &["symbol", "period"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/market/trading-stats#get-futures-active-long-short-position-data
        "get_uta_futures_position_long_short" => Endpoint {
            path: "/api/v3/market/futures-position-long-short",
            post: false,
            public: true,
            fields: &["symbol", "period"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        "get_reality_company_overview" => Endpoint {
            path: "/api/v3/reality/market/company-overview",
            post: false,
            public: true,
            fields: &["code"],
            required: &["code"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/reality/basic-info#get-valuation-indicators
        "get_reality_valuation_indicators" => Endpoint {
            path: "/api/v3/reality/market/valuation-indicators",
            post: false,
            public: true,
            fields: &["code"],
            required: &["code"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/reality/basic-info#get-earnings-forecast
        "get_reality_earnings_forecast" => Endpoint {
            path: "/api/v3/reality/market/earnings-forecast",
            post: false,
            public: true,
            fields: &["code"],
            required: &["code"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/reality/basic-info#get-suspension-resumption-info
        "get_reality_suspension_resumption_info" => Endpoint {
            path: "/api/v3/reality/market/suspension-resumption-info",
            post: false,
            public: true,
            fields: &["code"],
            required: &["code"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/reality/basic-info#get-dividends
        "get_reality_dividends" => Endpoint {
            path: "/api/v3/reality/market/dividends",
            post: false,
            public: true,
            fields: &["code", "limit", "cursor"],
            required: &["code"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/reality/basic-info#get-share-capital-change
        "get_reality_share_capital_change" => Endpoint {
            path: "/api/v3/reality/market/share-capital-change",
            post: false,
            public: true,
            fields: &["code"],
            required: &["code"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/reality/basic-info#get-inner-trades
        "get_reality_inner_trades" => Endpoint {
            path: "/api/v3/reality/market/inner-trades",
            post: false,
            public: true,
            fields: &["code", "limit", "cursor"],
            required: &["code"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/reality/basic-info#get-executive-shareholdings
        "get_reality_executive_shareholdings" => Endpoint {
            path: "/api/v3/reality/market/executive-shareholdings",
            post: false,
            public: true,
            fields: &["code", "limit", "cursor"],
            required: &["code"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/reality/basic-info#get-sharehold-detail
        "get_reality_sharehold_detail" => Endpoint {
            path: "/api/v3/reality/market/sharehold-detail",
            post: false,
            public: true,
            fields: &["code", "limit", "cursor"],
            required: &["code"],
            arrays: &[],
            limit: None,
            days: None,
        },
        _ => return None,
    })
}
