//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "get_futures_union_transfer_limits" => Endpoint {
            path: "/api/v2/mix/account/transfer-limits",
            post: false,
            public: false,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-union-config
        "get_spot_sub_account_transfer_records" => Endpoint {
            path: "/api/v2/spot/account/sub-main-trans-record",
            post: false,
            public: false,
            fields: &[
                "coin",
                "role",
                "subUid",
                "startTime",
                "endTime",
                "clientOid",
                "limit",
                "idLessThan",
            ],
            required: &[],
            arrays: &[],
            limit: Some(100),
            days: Some(90),
        },
        // https://www.bitget.com/docs/catalog/classic-spot-account/classic-spot-account#get-sub-accounts-assets
        "transfer_spot_sub_account" => Endpoint {
            path: "/api/v2/spot/wallet/subaccount-transfer",
            post: true,
            public: false,
            fields: &[
                "fromType",
                "toType",
                "amount",
                "coin",
                "fromUserId",
                "toUserId",
                "symbol",
                "clientOid",
            ],
            required: &[
                "fromType",
                "toType",
                "amount",
                "coin",
                "fromUserId",
                "toUserId",
            ],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#get-cross-account-assets
        "get_cross_margin_max_transferable" => Endpoint {
            path: "/api/v2/margin/crossed/account/max-transfer-out-amount",
            post: false,
            public: false,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-cross-account/classic-margin-cross-account#cross-flash-repay
        "get_isolated_margin_max_transferable" => Endpoint {
            path: "/api/v2/margin/isolated/account/max-transfer-out-amount",
            post: false,
            public: false,
            fields: &["symbol"],
            required: &["symbol"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#isolated-flash-repay
        "get_uta_max_transferable" => Endpoint {
            path: "/api/v3/account/max-transferable",
            post: false,
            public: false,
            fields: &["coin"],
            required: &["coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/account/assets-balance#set-collateral-type
        "get_uta_transferable_coins" => Endpoint {
            path: "/api/v3/account/transferable-coins",
            post: false,
            public: false,
            fields: &["fromType", "toType"],
            required: &["fromType", "toType"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/docs/catalog/trading/position-management#get-max-open-available
        "get_uta_position_transfer_history" => Endpoint {
            path: "/api/v3/account/move-position-history",
            post: false,
            public: false,
            fields: &[
                "category",
                "symbol",
                "startTime",
                "endTime",
                "cursor",
                "limit",
            ],
            required: &["category"],
            arrays: &[],
            limit: Some(100),
            days: Some(90),
        },
        // https://www.bitget.com/legacy-docs/uta/account/Set-Repay-Mode
        "transfer_uta_account" => Endpoint {
            path: "/api/v3/account/transfer",
            post: true,
            public: false,
            fields: &[
                "fromType",
                "toType",
                "amount",
                "coin",
                "symbol",
                "allowBorrow",
                "clientOid",
            ],
            required: &["fromType", "toType", "amount", "coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/transfer/Sub-Master-Transfer
        "transfer_uta_sub_to_master" => Endpoint {
            path: "/api/v3/account/sub-master-transfer",
            post: true,
            public: false,
            fields: &["fromType", "toType", "amount", "coin", "clientOid"],
            required: &["fromType", "toType", "amount", "coin"],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/transfer/SubAccount-Transfer
        "transfer_uta_sub_account" => Endpoint {
            path: "/api/v3/account/sub-transfer",
            post: true,
            public: false,
            fields: &[
                "fromType",
                "toType",
                "amount",
                "coin",
                "fromUserId",
                "toUserId",
                "clientOid",
                "allowBorrow",
            ],
            required: &[
                "fromType",
                "toType",
                "amount",
                "coin",
                "fromUserId",
                "toUserId",
                "clientOid",
            ],
            arrays: &[],
            limit: None,
            days: None,
        },
        // https://www.bitget.com/legacy-docs/uta/account/transfer/SubAccount-Transfer-Get
        "get_uta_sub_account_transfer_records" => Endpoint {
            path: "/api/v3/account/sub-transfer-record",
            post: false,
            public: false,
            fields: &[
                "subUid",
                "role",
                "coin",
                "startTime",
                "endTime",
                "clientOid",
                "limit",
                "cursor",
            ],
            required: &[],
            arrays: &[],
            limit: Some(100),
            days: Some(90),
        },
        // https://www.bitget.com/legacy-docs/uta/account/sub-account/SubAccount-Get
        _ => return None,
    })
}
