//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "get_coin_swap_contracts" => Endpoint {
            path: "/openApi/cswap/v1/market/contracts",
            verb: "GET",
            public: true,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_coin_swap_orderbook" => Endpoint {
            path: "/openApi/cswap/v1/market/depth",
            verb: "GET",
            public: true,
            fields: &["product_symbol", "limit", "recvWindow"],
            required: &["product_symbol"],
            integers: &["limit", "recvWindow"],
        },
        "get_coin_swap_kline" => Endpoint {
            path: "/openApi/cswap/v1/market/klines",
            verb: "GET",
            public: true,
            fields: &[
                "product_symbol",
                "interval",
                "startTime",
                "endTime",
                "limit",
                "recvWindow",
            ],
            required: &["product_symbol", "interval"],
            integers: &["startTime", "endTime", "limit", "recvWindow"],
        },
        "get_coin_swap_premium_index" => Endpoint {
            path: "/openApi/cswap/v1/market/premiumIndex",
            verb: "GET",
            public: true,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_coin_swap_open_interest" => Endpoint {
            path: "/openApi/cswap/v1/market/openInterest",
            verb: "GET",
            public: true,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_coin_swap_ticker" => Endpoint {
            path: "/openApi/cswap/v1/market/ticker",
            verb: "GET",
            public: true,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "place_coin_swap_order" => Endpoint {
            path: "/openApi/cswap/v1/trade/order",
            verb: "POST",
            public: false,
            fields: &[
                "product_symbol",
                "side",
                "type_",
                "positionSide",
                "quantity",
                "price",
                "stopPrice",
                "timeInForce",
                "clientOrderId",
                "workingType",
                "takeProfit",
                "stopLoss",
                "recvWindow",
            ],
            required: &["product_symbol", "side", "type_"],
            integers: &["recvWindow"],
        },
        "cancel_coin_swap_order" => Endpoint {
            path: "/openApi/cswap/v1/trade/cancelOrder",
            verb: "DELETE",
            public: false,
            fields: &["product_symbol", "orderId", "clientOrderId", "recvWindow"],
            required: &["product_symbol"],
            integers: &["orderId", "recvWindow"],
        },
        "cancel_coin_swap_all_orders" => Endpoint {
            path: "/openApi/cswap/v1/trade/allOpenOrders",
            verb: "POST",
            public: false,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "close_coin_swap_all_positions" => Endpoint {
            path: "/openApi/cswap/v1/trade/closeAllPositions",
            verb: "POST",
            public: false,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_coin_swap_open_orders" => Endpoint {
            path: "/openApi/cswap/v1/trade/openOrders",
            verb: "GET",
            public: false,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_coin_swap_order" => Endpoint {
            path: "/openApi/cswap/v1/trade/orderDetail",
            verb: "GET",
            public: false,
            fields: &["product_symbol", "orderId", "clientOrderId", "recvWindow"],
            required: &["product_symbol"],
            integers: &["orderId", "recvWindow"],
        },
        "get_coin_swap_order_history" => Endpoint {
            path: "/openApi/cswap/v1/trade/orderHistory",
            verb: "GET",
            public: false,
            fields: &[
                "limit",
                "product_symbol",
                "orderId",
                "startTime",
                "endTime",
                "recvWindow",
            ],
            required: &["limit"],
            integers: &["limit", "orderId", "startTime", "endTime", "recvWindow"],
        },
        "get_coin_swap_fills" => Endpoint {
            path: "/openApi/cswap/v1/trade/allFillOrders",
            verb: "GET",
            public: false,
            fields: &["orderId", "pageIndex", "pageSize", "recvWindow"],
            required: &["orderId"],
            integers: &["pageIndex", "pageSize", "recvWindow"],
        },
        "get_coin_swap_force_orders" => Endpoint {
            path: "/openApi/cswap/v1/trade/forceOrders",
            verb: "GET",
            public: false,
            fields: &[
                "product_symbol",
                "autoCloseType",
                "startTime",
                "endTime",
                "limit",
                "recvWindow",
            ],
            required: &[],
            integers: &["startTime", "endTime", "limit", "recvWindow"],
        },
        "get_coin_swap_leverage" => Endpoint {
            path: "/openApi/cswap/v1/trade/leverage",
            verb: "GET",
            public: false,
            fields: &["product_symbol", "recvWindow"],
            required: &["product_symbol"],
            integers: &["recvWindow"],
        },
        "set_coin_swap_leverage" => Endpoint {
            path: "/openApi/cswap/v1/trade/leverage",
            verb: "POST",
            public: false,
            fields: &["product_symbol", "side", "leverage", "recvWindow"],
            required: &["product_symbol", "side", "leverage"],
            integers: &["recvWindow"],
        },
        "get_coin_swap_margin_type" => Endpoint {
            path: "/openApi/cswap/v1/trade/marginType",
            verb: "GET",
            public: false,
            fields: &["product_symbol", "recvWindow"],
            required: &["product_symbol"],
            integers: &["recvWindow"],
        },
        "set_coin_swap_margin_type" => Endpoint {
            path: "/openApi/cswap/v1/trade/marginType",
            verb: "POST",
            public: false,
            fields: &["product_symbol", "marginType", "recvWindow"],
            required: &["product_symbol", "marginType"],
            integers: &["recvWindow"],
        },
        "adjust_coin_swap_position_margin" => Endpoint {
            path: "/openApi/cswap/v1/trade/positionMargin",
            verb: "POST",
            public: false,
            fields: &[
                "product_symbol",
                "positionSide",
                "amount",
                "type_",
                "recvWindow",
            ],
            required: &["product_symbol", "positionSide", "amount", "type_"],
            integers: &["type_", "recvWindow"],
        },
        "get_coin_swap_commission_rate" => Endpoint {
            path: "/openApi/cswap/v1/user/commissionRate",
            verb: "GET",
            public: false,
            fields: &["recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_coin_swap_balance" => Endpoint {
            path: "/openApi/cswap/v1/user/balance",
            verb: "GET",
            public: false,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_coin_swap_positions" => Endpoint {
            path: "/openApi/cswap/v1/user/positions",
            verb: "GET",
            public: false,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        _ => return None,
    })
}
