//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "create_sub_account" => Endpoint {
            path: "/openApi/subAccount/v1/create",
            verb: "POST",
            public: false,
            fields: &["subAccountString", "note", "recvWindow"],
            required: &["subAccountString"],
            integers: &["recvWindow"],
        },
        "set_sub_account_frozen" => Endpoint {
            path: "/openApi/subAccount/v1/updateStatus",
            verb: "POST",
            public: false,
            fields: &["subUid", "freeze", "recvWindow"],
            required: &["subUid", "freeze"],
            integers: &["subUid", "recvWindow"],
        },
        "create_sub_account_api_key" => Endpoint {
            path: "/openApi/subAccount/v1/apiKey/create",
            verb: "POST",
            public: false,
            fields: &["subUid", "note", "permissions", "ipAddresses", "recvWindow"],
            required: &["subUid", "note", "permissions"],
            integers: &["subUid", "recvWindow"],
        },
        "modify_sub_account_api_key" => Endpoint {
            path: "/openApi/subAccount/v1/apiKey/edit",
            verb: "POST",
            public: false,
            fields: &[
                "subUid",
                "apiKey",
                "note",
                "permissions",
                "ipAddresses",
                "recvWindow",
            ],
            required: &["subUid", "apiKey", "note", "permissions"],
            integers: &["subUid", "recvWindow"],
        },
        "delete_sub_account_api_key" => Endpoint {
            path: "/openApi/subAccount/v1/apiKey/del",
            verb: "POST",
            public: false,
            fields: &["subUid", "apiKey", "recvWindow"],
            required: &["subUid", "apiKey"],
            integers: &["subUid", "recvWindow"],
        },
        "get_sub_account_deposit_addresses" => Endpoint {
            path: "/openApi/wallets/v1/capital/subAccount/deposit/address",
            verb: "GET",
            public: false,
            fields: &["coin", "subUid", "offset", "limit", "recvWindow"],
            required: &["coin", "subUid"],
            integers: &["subUid", "offset", "limit", "recvWindow"],
        },
        "get_sub_account_deposit_history" => Endpoint {
            path: "/openApi/wallets/v1/capital/deposit/subHisrec",
            verb: "GET",
            public: false,
            fields: &[
                "coin",
                "subUid",
                "txId",
                "status",
                "startTime",
                "endTime",
                "offset",
                "limit",
                "recvWindow",
            ],
            required: &[],
            integers: &[
                "subUid",
                "status",
                "startTime",
                "endTime",
                "offset",
                "limit",
                "recvWindow",
            ],
        },
        "create_sub_account_deposit_address" => Endpoint {
            path: "/openApi/wallets/v1/capital/deposit/createSubAddress",
            verb: "POST",
            public: false,
            fields: &["coin", "subUid", "network", "walletType", "recvWindow"],
            required: &["coin", "subUid", "network", "walletType"],
            integers: &["subUid", "walletType", "recvWindow"],
        },
        _ => return None,
    })
}
