use super::Endpoint;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "get_coin_swap_contracts" => Endpoint {
            path: "/openApi/cswap/v1/market/contracts",
            verb: "GET",
            public: true,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_coin_swap_orderbook" => Endpoint {
            path: "/openApi/cswap/v1/market/depth",
            verb: "GET",
            public: true,
            fields: &["product_symbol", "limit", "recvWindow"],
            required: &["product_symbol"],
            integers: &["limit", "recvWindow"],
        },
        "get_coin_swap_kline" => Endpoint {
            path: "/openApi/cswap/v1/market/klines",
            verb: "GET",
            public: true,
            fields: &[
                "product_symbol",
                "interval",
                "startTime",
                "endTime",
                "limit",
                "recvWindow",
            ],
            required: &["product_symbol", "interval"],
            integers: &["startTime", "endTime", "limit", "recvWindow"],
        },
        "get_coin_swap_premium_index" => Endpoint {
            path: "/openApi/cswap/v1/market/premiumIndex",
            verb: "GET",
            public: true,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_coin_swap_open_interest" => Endpoint {
            path: "/openApi/cswap/v1/market/openInterest",
            verb: "GET",
            public: true,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_coin_swap_ticker" => Endpoint {
            path: "/openApi/cswap/v1/market/ticker",
            verb: "GET",
            public: true,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "place_coin_swap_order" => Endpoint {
            path: "/openApi/cswap/v1/trade/order",
            verb: "POST",
            public: false,
            fields: &[
                "product_symbol",
                "side",
                "type_",
                "positionSide",
                "quantity",
                "price",
                "stopPrice",
                "timeInForce",
                "clientOrderId",
                "workingType",
                "takeProfit",
                "stopLoss",
                "recvWindow",
            ],
            required: &["product_symbol", "side", "type_"],
            integers: &["recvWindow"],
        },
        "cancel_coin_swap_order" => Endpoint {
            path: "/openApi/cswap/v1/trade/cancelOrder",
            verb: "DELETE",
            public: false,
            fields: &["product_symbol", "orderId", "clientOrderId", "recvWindow"],
            required: &["product_symbol"],
            integers: &["orderId", "recvWindow"],
        },
        "cancel_coin_swap_all_orders" => Endpoint {
            path: "/openApi/cswap/v1/trade/allOpenOrders",
            verb: "POST",
            public: false,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "close_coin_swap_all_positions" => Endpoint {
            path: "/openApi/cswap/v1/trade/closeAllPositions",
            verb: "POST",
            public: false,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_coin_swap_open_orders" => Endpoint {
            path: "/openApi/cswap/v1/trade/openOrders",
            verb: "GET",
            public: false,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_coin_swap_order" => Endpoint {
            path: "/openApi/cswap/v1/trade/orderDetail",
            verb: "GET",
            public: false,
            fields: &["product_symbol", "orderId", "clientOrderId", "recvWindow"],
            required: &["product_symbol"],
            integers: &["orderId", "recvWindow"],
        },
        "get_coin_swap_order_history" => Endpoint {
            path: "/openApi/cswap/v1/trade/orderHistory",
            verb: "GET",
            public: false,
            fields: &[
                "limit",
                "product_symbol",
                "orderId",
                "startTime",
                "endTime",
                "recvWindow",
            ],
            required: &["limit"],
            integers: &["limit", "orderId", "startTime", "endTime", "recvWindow"],
        },
        "get_coin_swap_fills" => Endpoint {
            path: "/openApi/cswap/v1/trade/allFillOrders",
            verb: "GET",
            public: false,
            fields: &["orderId", "pageIndex", "pageSize", "recvWindow"],
            required: &["orderId"],
            integers: &["pageIndex", "pageSize", "recvWindow"],
        },
        "get_coin_swap_force_orders" => Endpoint {
            path: "/openApi/cswap/v1/trade/forceOrders",
            verb: "GET",
            public: false,
            fields: &[
                "product_symbol",
                "autoCloseType",
                "startTime",
                "endTime",
                "limit",
                "recvWindow",
            ],
            required: &[],
            integers: &["startTime", "endTime", "limit", "recvWindow"],
        },
        "get_coin_swap_leverage" => Endpoint {
            path: "/openApi/cswap/v1/trade/leverage",
            verb: "GET",
            public: false,
            fields: &["product_symbol", "recvWindow"],
            required: &["product_symbol"],
            integers: &["recvWindow"],
        },
        "set_coin_swap_leverage" => Endpoint {
            path: "/openApi/cswap/v1/trade/leverage",
            verb: "POST",
            public: false,
            fields: &["product_symbol", "side", "leverage", "recvWindow"],
            required: &["product_symbol", "side", "leverage"],
            integers: &["recvWindow"],
        },
        "get_coin_swap_margin_type" => Endpoint {
            path: "/openApi/cswap/v1/trade/marginType",
            verb: "GET",
            public: false,
            fields: &["product_symbol", "recvWindow"],
            required: &["product_symbol"],
            integers: &["recvWindow"],
        },
        "set_coin_swap_margin_type" => Endpoint {
            path: "/openApi/cswap/v1/trade/marginType",
            verb: "POST",
            public: false,
            fields: &["product_symbol", "marginType", "recvWindow"],
            required: &["product_symbol", "marginType"],
            integers: &["recvWindow"],
        },
        "adjust_coin_swap_position_margin" => Endpoint {
            path: "/openApi/cswap/v1/trade/positionMargin",
            verb: "POST",
            public: false,
            fields: &[
                "product_symbol",
                "positionSide",
                "amount",
                "type_",
                "recvWindow",
            ],
            required: &["product_symbol", "positionSide", "amount", "type_"],
            integers: &["type_", "recvWindow"],
        },
        "get_coin_swap_commission_rate" => Endpoint {
            path: "/openApi/cswap/v1/user/commissionRate",
            verb: "GET",
            public: false,
            fields: &["recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_coin_swap_balance" => Endpoint {
            path: "/openApi/cswap/v1/user/balance",
            verb: "GET",
            public: false,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_coin_swap_positions" => Endpoint {
            path: "/openApi/cswap/v1/user/positions",
            verb: "GET",
            public: false,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_spot_historical_kline" => Endpoint {
            path: "/openApi/market/his/v1/kline",
            verb: "GET",
            public: true,
            fields: &[
                "product_symbol",
                "interval",
                "startTime",
                "endTime",
                "limit",
                "recvWindow",
            ],
            required: &["product_symbol", "interval"],
            integers: &["startTime", "endTime", "limit", "recvWindow"],
        },
        "place_spot_oco" => Endpoint {
            path: "/openApi/spot/v1/oco/order",
            verb: "POST",
            public: false,
            fields: &[
                "product_symbol",
                "side",
                "quantity",
                "limitPrice",
                "triggerPrice",
                "orderPrice",
                "listClientOrderId",
                "aboveClientOrderId",
                "belowClientOrderId",
                "recvWindow",
            ],
            required: &[
                "product_symbol",
                "side",
                "quantity",
                "limitPrice",
                "triggerPrice",
                "orderPrice",
            ],
            integers: &["recvWindow"],
        },
        "cancel_spot_oco" => Endpoint {
            path: "/openApi/spot/v1/oco/cancel",
            verb: "POST",
            public: false,
            fields: &["orderId", "clientOrderId", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_spot_oco" => Endpoint {
            path: "/openApi/spot/v1/oco/orderList",
            verb: "GET",
            public: false,
            fields: &["orderListId", "clientOrderId", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_spot_open_oco" => Endpoint {
            path: "/openApi/spot/v1/oco/openOrderList",
            verb: "GET",
            public: false,
            fields: &["pageIndex", "pageSize", "recvWindow"],
            required: &["pageIndex", "pageSize"],
            integers: &["pageIndex", "pageSize", "recvWindow"],
        },
        "get_spot_oco_history" => Endpoint {
            path: "/openApi/spot/v1/oco/historyOrderList",
            verb: "GET",
            public: false,
            fields: &[
                "pageIndex",
                "pageSize",
                "startTime",
                "endTime",
                "recvWindow",
            ],
            required: &["pageIndex", "pageSize"],
            integers: &[
                "pageIndex",
                "pageSize",
                "startTime",
                "endTime",
                "recvWindow",
            ],
        },
        "get_deposit_history" => Endpoint {
            path: "/openApi/api/v3/capital/deposit/hisrec",
            verb: "GET",
            public: false,
            fields: &[
                "coin",
                "status",
                "startTime",
                "endTime",
                "offset",
                "limit",
                "txId",
                "recvWindow",
            ],
            required: &[],
            integers: &[
                "status",
                "startTime",
                "endTime",
                "offset",
                "limit",
                "recvWindow",
            ],
        },
        "get_swap_server_time" => Endpoint {
            path: "/openApi/swap/v2/server/time",
            verb: "GET",
            public: true,
            fields: &[],
            required: &[],
            integers: &[],
        },
        "get_swap_price_ticker" => Endpoint {
            path: "/openApi/swap/v1/ticker/price",
            verb: "GET",
            public: true,
            fields: &["product_symbol", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_spot_historical_trades" => Endpoint {
            path: "/openApi/market/his/v1/trade",
            verb: "GET",
            public: true,
            fields: &["product_symbol", "limit", "fromId", "recvWindow"],
            required: &["product_symbol"],
            integers: &["limit", "recvWindow"],
        },
        "get_coin_network_config" => Endpoint {
            path: "/openApi/wallets/v1/capital/config/getall",
            verb: "GET",
            public: false,
            fields: &["coin", "displayName", "recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_deposit_addresses" => Endpoint {
            path: "/openApi/wallets/v1/capital/deposit/address",
            verb: "GET",
            public: false,
            fields: &["coin", "offset", "limit", "recvWindow"],
            required: &["coin"],
            integers: &["offset", "limit", "recvWindow"],
        },
        "get_deposit_risk_records" => Endpoint {
            path: "/openApi/wallets/v1/capital/deposit/riskRecords",
            verb: "GET",
            public: false,
            fields: &["recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_swap_historical_trades" => Endpoint {
            path: "/openApi/swap/v1/market/historicalTrades",
            verb: "GET",
            public: true,
            fields: &["product_symbol", "fromId", "limit", "recvWindow"],
            required: &["product_symbol"],
            integers: &["fromId", "limit", "recvWindow"],
        },
        "reverse_swap_position" => Endpoint {
            path: "/openApi/swap/v1/trade/reverse",
            verb: "POST",
            public: false,
            fields: &[
                "type_",
                "product_symbol",
                "triggerPrice",
                "workingType",
                "recvWindow",
            ],
            required: &["type_", "product_symbol"],
            integers: &["recvWindow"],
        },
        "adjust_simulated_trading_balance" => Endpoint {
            path: "/openApi/swap/v2/trade/getVst",
            verb: "POST",
            public: false,
            fields: &["adjustType", "amount", "recvWindow"],
            required: &[],
            integers: &["amount", "recvWindow"],
        },
        "get_standard_futures_positions" => Endpoint {
            path: "/openApi/contract/v1/allPosition",
            verb: "GET",
            public: false,
            fields: &["recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_standard_futures_orders" => Endpoint {
            path: "/openApi/contract/v1/allOrders",
            verb: "GET",
            public: false,
            fields: &[
                "product_symbol",
                "orderId",
                "startTime",
                "endTime",
                "limit",
                "recvWindow",
            ],
            required: &["product_symbol"],
            integers: &["orderId", "startTime", "endTime", "limit", "recvWindow"],
        },
        "get_standard_futures_balance" => Endpoint {
            path: "/openApi/contract/v1/balance",
            verb: "GET",
            public: false,
            fields: &["recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "get_api_permissions" => Endpoint {
            path: "/openApi/v1/account/apiPermissions",
            verb: "GET",
            public: false,
            fields: &["recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "create_sub_account" => Endpoint {
            path: "/openApi/subAccount/v1/create",
            verb: "POST",
            public: false,
            fields: &["subAccountString", "note", "recvWindow"],
            required: &["subAccountString"],
            integers: &["recvWindow"],
        },
        "set_sub_account_frozen" => Endpoint {
            path: "/openApi/subAccount/v1/updateStatus",
            verb: "POST",
            public: false,
            fields: &["subUid", "freeze", "recvWindow"],
            required: &["subUid", "freeze"],
            integers: &["subUid", "recvWindow"],
        },
        "create_sub_account_api_key" => Endpoint {
            path: "/openApi/subAccount/v1/apiKey/create",
            verb: "POST",
            public: false,
            fields: &["subUid", "note", "permissions", "ipAddresses", "recvWindow"],
            required: &["subUid", "note", "permissions"],
            integers: &["subUid", "recvWindow"],
        },
        "modify_sub_account_api_key" => Endpoint {
            path: "/openApi/subAccount/v1/apiKey/edit",
            verb: "POST",
            public: false,
            fields: &[
                "subUid",
                "apiKey",
                "note",
                "permissions",
                "ipAddresses",
                "recvWindow",
            ],
            required: &["subUid", "apiKey", "note", "permissions"],
            integers: &["subUid", "recvWindow"],
        },
        "delete_sub_account_api_key" => Endpoint {
            path: "/openApi/subAccount/v1/apiKey/del",
            verb: "POST",
            public: false,
            fields: &["subUid", "apiKey", "recvWindow"],
            required: &["subUid", "apiKey"],
            integers: &["subUid", "recvWindow"],
        },
        "set_sub_account_transfer_authorization" => Endpoint {
            path: "/openApi/account/v1/innerTransfer/authorizeSubAccount",
            verb: "POST",
            public: false,
            fields: &["subUids", "transferable", "recvWindow"],
            required: &["subUids", "transferable"],
            integers: &["recvWindow"],
        },
        "get_sub_account_deposit_addresses" => Endpoint {
            path: "/openApi/wallets/v1/capital/subAccount/deposit/address",
            verb: "GET",
            public: false,
            fields: &["coin", "subUid", "offset", "limit", "recvWindow"],
            required: &["coin", "subUid"],
            integers: &["subUid", "offset", "limit", "recvWindow"],
        },
        "get_sub_account_deposit_history" => Endpoint {
            path: "/openApi/wallets/v1/capital/deposit/subHisrec",
            verb: "GET",
            public: false,
            fields: &[
                "coin",
                "subUid",
                "txId",
                "status",
                "startTime",
                "endTime",
                "offset",
                "limit",
                "recvWindow",
            ],
            required: &[],
            integers: &[
                "subUid",
                "status",
                "startTime",
                "endTime",
                "offset",
                "limit",
                "recvWindow",
            ],
        },
        "get_api_restrictions" => Endpoint {
            path: "/openApi/v1/account/apiRestrictions",
            verb: "GET",
            public: false,
            fields: &["recvWindow"],
            required: &[],
            integers: &["recvWindow"],
        },
        "create_sub_account_deposit_address" => Endpoint {
            path: "/openApi/wallets/v1/capital/deposit/createSubAddress",
            verb: "POST",
            public: false,
            fields: &["coin", "subUid", "network", "walletType", "recvWindow"],
            required: &["coin", "subUid", "network", "walletType"],
            integers: &["subUid", "walletType", "recvWindow"],
        },
        "get_withdrawal_history" => Endpoint {
            path: "/openApi/api/v3/capital/withdraw/history",
            verb: "GET",
            public: false,
            fields: &[
                "id",
                "coin",
                "withdrawOrderId",
                "status",
                "startTime",
                "endTime",
                "offset",
                "limit",
                "txId",
                "recvWindow",
            ],
            required: &[],
            integers: &[
                "status",
                "startTime",
                "endTime",
                "offset",
                "limit",
                "recvWindow",
            ],
        },
        "get_internal_transfer_records" => Endpoint {
            path: "/openApi/wallets/v1/capital/innerTransfer/records",
            verb: "GET",
            public: false,
            fields: &[
                "coin",
                "id",
                "transferClientId",
                "startTime",
                "endTime",
                "offset",
                "limit",
                "recvWindow",
            ],
            required: &["coin"],
            integers: &["startTime", "endTime", "offset", "limit", "recvWindow"],
        },
        "get_sub_account_internal_transfer_records" => Endpoint {
            path: "/openApi/wallets/v1/capital/subAccount/innerTransfer/records",
            verb: "GET",
            public: false,
            fields: &[
                "coin",
                "transferClientId",
                "startTime",
                "endTime",
                "offset",
                "limit",
                "recvWindow",
            ],
            required: &["coin"],
            integers: &["startTime", "endTime", "offset", "limit", "recvWindow"],
        },
        _ => return None,
    })
}
