use serde_json::{Value, json};

use crate::crypto::hmac_sha256_hex;
use crate::exchange::{RequestSigner, ResponseValidator};
use crate::http::{HttpRequest, HttpResponse, RequestBody};
use crate::{DcexError, Result};

#[derive(Clone)]
pub(super) struct BingxSigner {
    pub(super) api_key: String,
    pub(super) api_secret: String,
}

impl RequestSigner for BingxSigner {
    fn sign(&self, request: &mut HttpRequest, timestamp_ms: u64) -> Result<()> {
        if let RequestBody::Json(value) = &mut request.body {
            let object = value.as_object_mut().ok_or_else(|| {
                DcexError::InvalidInput("BingX JSON body must be an object".into())
            })?;
            for (key, value) in request.query.drain(..) {
                if object.insert(key, Value::String(value)).is_some() {
                    return Err(DcexError::InvalidInput(
                        "duplicate BingX body/query field".into(),
                    ));
                }
            }
            if object.contains_key("signature") || object.contains_key("timestamp") {
                return Err(DcexError::InvalidInput(
                    "BingX timestamp and signature are generated by the signer".into(),
                ));
            }
            object.insert("timestamp".into(), Value::from(timestamp_ms));
            let mut fields = object
                .iter()
                .map(|(key, value)| {
                    let value = match value {
                        Value::Array(items) => items
                            .iter()
                            .map(|v| match v {
                                Value::String(_) | Value::Number(_) | Value::Bool(_) => {
                                    Ok(json_value_string(v))
                                }
                                _ => Err(DcexError::InvalidInput(
                                    "unsupported BingX JSON signing array".into(),
                                )),
                            })
                            .collect::<Result<Vec<_>>>()?
                            .join(","),
                        Value::Object(_) | Value::Null => {
                            return Err(DcexError::InvalidInput(
                                "unsupported BingX JSON signing value".into(),
                            ));
                        }
                        _ => json_value_string(value),
                    };
                    Ok((key.clone(), value))
                })
                .collect::<Result<Vec<_>>>()?;
            fields.sort_by(|a, b| a.0.cmp(&b.0));
            let payload = fields
                .iter()
                .map(|(k, v)| format!("{k}={v}"))
                .collect::<Vec<_>>()
                .join("&");
            object.insert(
                "signature".into(),
                Value::String(hmac_sha256_hex(
                    self.api_secret.as_bytes(),
                    payload.as_bytes(),
                )?),
            );
            request
                .headers
                .insert("X-BX-APIKEY".into(), self.api_key.clone());
            return Ok(());
        }
        request
            .query
            .push(("timestamp".to_string(), timestamp_ms.to_string()));
        request.query.sort_by(|left, right| left.0.cmp(&right.0));
        let payload = request
            .query
            .iter()
            .map(|(key, value)| format!("{key}={value}"))
            .collect::<Vec<_>>()
            .join("&");
        let signature = hmac_sha256_hex(self.api_secret.as_bytes(), payload.as_bytes())?;
        request.query.push(("signature".to_string(), signature));
        request
            .headers
            .insert("X-BX-APIKEY".to_string(), self.api_key.clone());
        Ok(())
    }
}

pub(super) struct BingxResponseValidator;

impl ResponseValidator for BingxResponseValidator {
    fn validate(&self, response: &HttpResponse) -> Result<Value> {
        let data = if response.body.is_empty() {
            json!({"code": 0})
        } else {
            response.json()?
        };
        let code = data
            .as_object()
            .and_then(|object| object.get("code"))
            .map(json_value_string)
            .unwrap_or_else(|| "0".to_string());
        if code != "0" {
            let message = data
                .as_object()
                .and_then(|object| object.get("msg"))
                .and_then(Value::as_str)
                .unwrap_or("");
            return Err(response.api_error("BingX", Some(&code), message));
        }
        response.ensure_success("BingX")?;
        Ok(data)
    }
}

pub(super) fn json_value_string(value: &Value) -> String {
    match value {
        Value::String(value) => value.clone(),
        Value::Number(value) => value.to_string(),
        Value::Bool(value) => value.to_string(),
        Value::Null => String::new(),
        Value::Array(_) | Value::Object(_) => value.to_string(),
    }
}
