use super::client::BingxClient;

crate::exchanges::impl_exchange_method_wrappers! {
    BingxClient;
    public [
        get_kline(product_symbol => "product_symbol", interval => "interval") => get_kline_with,
        get_mark_price_kline(product_symbol => "product_symbol", interval => "interval") => get_mark_price_kline_with,
        get_open_interest(product_symbol => "product_symbol") => get_open_interest_with,
        get_orderbook(product_symbol => "product_symbol") => get_orderbook_with,
        get_public_trades(product_symbol => "product_symbol") => get_public_trades_with,
        get_spot_book_ticker(product_symbol => "product_symbol") => get_spot_book_ticker_with,
        get_spot_instrument_info() => get_spot_instrument_info_with,
        get_spot_kline(product_symbol => "product_symbol", interval => "interval") => get_spot_kline_with,
        get_spot_kline_v2(product_symbol => "product_symbol", interval => "interval") => get_spot_kline_v2_with,
        get_spot_orderbook(product_symbol => "product_symbol") => get_spot_orderbook_with,
        get_spot_orderbook_v2(product_symbol => "product_symbol") => get_spot_orderbook_v2_with,
        get_spot_price_ticker(product_symbol => "product_symbol") => get_spot_price_ticker_with,
        get_spot_public_trades(product_symbol => "product_symbol") => get_spot_public_trades_with,
        get_spot_ticker(product_symbol => "product_symbol") => get_spot_ticker_with,
        get_swap_instrument_info() => get_swap_instrument_info_with,
        get_ticker() => get_ticker_with,
    ];
    private [
        asset_transfer(from_account => "fromAccount", to_account => "toAccount", asset => "asset", amount => "amount") => asset_transfer_with,
        cancel_spot_batch_orders(product_symbol => "product_symbol", order_ids => "orderIds") => cancel_spot_batch_orders_with,
        cancel_spot_open_orders() => cancel_spot_open_orders_with,
        cancel_spot_order(product_symbol => "product_symbol") => cancel_spot_order_with,
        cancel_swap_all_orders(product_symbol => "product_symbol") => cancel_swap_all_orders_with,
        cancel_swap_batch_order(product_symbol => "product_symbol") => cancel_swap_batch_order_with,
        cancel_swap_order(product_symbol => "product_symbol") => cancel_swap_order_with,
        change_margin_type(product_symbol => "product_symbol", margin_type => "marginType") => change_margin_type_with,
        close_swap_all_positions(product_symbol => "product_symbol") => close_swap_all_positions_with,
        close_swap_position(position_id => "positionId") => close_swap_position_with,
        get_account_balance() => get_account_balance_with,
        get_account_uid() => get_account_uid_with,
        get_all_account_balance() => get_all_account_balance_with,
        get_api_key_info(uid => "uid") => get_api_key_info_with,
        get_asset_transfer_records() => get_asset_transfer_records_with,
        get_fund_account_balance() => get_fund_account_balance_with,
        get_fund_flow() => get_fund_flow_with,
        get_leverage(product_symbol => "product_symbol") => get_leverage_with,
        get_listen_key() => get_listen_key_with,
        get_margin_type() => get_margin_type_with,
        get_open_orders() => get_open_orders_with,
        get_open_positions() => get_open_positions_with,
        get_order_detail(product_symbol => "product_symbol") => get_order_detail_with,
        get_order_history() => get_order_history_with,
        get_position_mode() => get_position_mode_with,
        get_spot_account_balance() => get_spot_account_balance_with,
        get_spot_commission_rate(product_symbol => "product_symbol") => get_spot_commission_rate_with,
        get_spot_my_trades(product_symbol => "product_symbol") => get_spot_my_trades_with,
        get_spot_open_orders(product_symbol => "product_symbol") => get_spot_open_orders_with,
        get_spot_order(product_symbol => "product_symbol") => get_spot_order_with,
        get_spot_order_history(product_symbol => "product_symbol") => get_spot_order_history_with,
        get_swap_account_balance() => get_swap_account_balance_with,
        get_transferable_coins(from_account => "fromAccount", to_account => "toAccount") => get_transferable_coins_with,
        keep_alive_listen_key(listen_key => "listen_key") => keep_alive_listen_key_with,
        place_spot_batch_order(data => "data") => place_spot_batch_order_with,
        place_spot_limit_buy_order(product_symbol => "product_symbol", quantity => "quantity", price => "price") => place_spot_limit_buy_order_with,
        place_spot_limit_order(product_symbol => "product_symbol", side => "side", quantity => "quantity", price => "price") => place_spot_limit_order_with,
        place_spot_limit_sell_order(product_symbol => "product_symbol", quantity => "quantity", price => "price") => place_spot_limit_sell_order_with,
        place_spot_market_buy_order(product_symbol => "product_symbol", quote_order_qty => "quoteOrderQty") => place_spot_market_buy_order_with,
        place_spot_market_sell_order(product_symbol => "product_symbol", quantity => "quantity") => place_spot_market_sell_order_with,
        place_spot_order(product_symbol => "product_symbol", side => "side", type_ => "type_") => place_spot_order_with,
        place_spot_post_only_buy_order(product_symbol => "product_symbol", quantity => "quantity", price => "price") => place_spot_post_only_buy_order_with,
        place_spot_post_only_order(product_symbol => "product_symbol", side => "side", quantity => "quantity", price => "price") => place_spot_post_only_order_with,
        place_spot_post_only_sell_order(product_symbol => "product_symbol", quantity => "quantity", price => "price") => place_spot_post_only_sell_order_with,
        place_swap_batch_order(batch_orders => "batchOrders") => place_swap_batch_order_with,
        place_swap_limit_buy_order(product_symbol => "product_symbol", quantity => "quantity", price => "price") => place_swap_limit_buy_order_with,
        place_swap_limit_order(product_symbol => "product_symbol", side => "side", quantity => "quantity", price => "price") => place_swap_limit_order_with,
        place_swap_limit_sell_order(product_symbol => "product_symbol", quantity => "quantity", price => "price") => place_swap_limit_sell_order_with,
        place_swap_market_buy_order(product_symbol => "product_symbol", quantity => "quantity") => place_swap_market_buy_order_with,
        place_swap_market_order(product_symbol => "product_symbol", side => "side", quantity => "quantity") => place_swap_market_order_with,
        place_swap_market_sell_order(product_symbol => "product_symbol", quantity => "quantity") => place_swap_market_sell_order_with,
        place_swap_order(product_symbol => "product_symbol", type_ => "type_", side => "side") => place_swap_order_with,
        place_swap_post_only_buy_order(product_symbol => "product_symbol", quantity => "quantity", price => "price") => place_swap_post_only_buy_order_with,
        place_swap_post_only_order(product_symbol => "product_symbol", side => "side", quantity => "quantity", price => "price") => place_swap_post_only_order_with,
        place_swap_post_only_sell_order(product_symbol => "product_symbol", quantity => "quantity", price => "price") => place_swap_post_only_sell_order_with,
        replace_swap_order(product_symbol => "product_symbol", order_id => "orderId", cancel_replace_mode => "cancelReplaceMode", type_ => "type_", side => "side", position_side => "positionSide") => replace_swap_order_with,
        set_leverage(product_symbol => "product_symbol", side => "side", leverage => "leverage") => set_leverage_with,
        set_position_mode(dual_side_position => "dualSidePosition") => set_position_mode_with,
        test_swap_order(product_symbol => "product_symbol", type_ => "type_", side => "side") => test_swap_order_with,
    ];
}
