//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<RiskEndpoint> {
    Some(match name {
        "get_dcp_info" => RiskEndpoint {
            path: "/v5/account/query-dcp-info",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "get_coin_greeks" => RiskEndpoint {
            path: "/v5/asset/coin-greeks",
            post: false,
            public: false,
            keys: &["baseCoin"],
            required: &[],
            integers: &[],
        },
        "set_collateral_coin" => RiskEndpoint {
            path: "/v5/account/set-collateral-switch",
            post: true,
            public: false,
            keys: &["coin", "collateralSwitch"],
            required: &["coin", "collateralSwitch"],
            integers: &[],
        },
        "batch_set_collateral_coins" => RiskEndpoint {
            path: "/v5/account/set-collateral-switch-batch",
            post: true,
            public: false,
            keys: &["request"],
            required: &["request"],
            integers: &[],
        },
        "get_asset_overview" => RiskEndpoint {
            path: "/v5/asset/asset-overview",
            post: false,
            public: false,
            keys: &["memberId", "valuationCurrency", "accountType"],
            required: &[],
            integers: &[],
        },
        "get_delivery_records" => RiskEndpoint {
            path: "/v5/asset/delivery-record",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "startTime",
                "endTime",
                "expDate",
                "limit",
                "cursor",
                "product_symbol",
            ],
            required: &["category"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_settlement_records" => RiskEndpoint {
            path: "/v5/asset/settlement-record",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "startTime",
                "endTime",
                "limit",
                "cursor",
                "product_symbol",
            ],
            required: &["category"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_funding_account_history" => RiskEndpoint {
            path: "/v5/asset/fundinghistory",
            post: false,
            public: false,
            keys: &["createTimeFrom", "createTimeTo", "limit", "cursor"],
            required: &[],
            integers: &[],
        },
        "get_total_members_assets" => RiskEndpoint {
            path: "/v5/asset/total-members-assets",
            post: false,
            public: false,
            keys: &["coin"],
            required: &[],
            integers: &[],
        },
        "get_smp_group" => RiskEndpoint {
            path: "/v5/account/smp-group",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "set_delta_mode" => RiskEndpoint {
            path: "/v5/account/set-delta-mode",
            post: true,
            public: false,
            keys: &["deltaEnable"],
            required: &["deltaEnable"],
            integers: &[],
        },
        "set_spot_hedging" => RiskEndpoint {
            path: "/v5/account/set-hedging-mode",
            post: true,
            public: false,
            keys: &["setHedgingMode"],
            required: &["setHedgingMode"],
            integers: &[],
        },
        "set_price_limit_behavior" => RiskEndpoint {
            path: "/v5/account/set-limit-px-action",
            post: true,
            public: false,
            keys: &["category", "modifyEnable"],
            required: &["category", "modifyEnable"],
            integers: &[],
        },
        "execute_small_balance_quote" => RiskEndpoint {
            path: "/v5/asset/covert/small-balance-execute",
            post: true,
            public: false,
            keys: &["quoteId"],
            required: &["quoteId"],
            integers: &[],
        },
        "get_small_balance_history" => RiskEndpoint {
            path: "/v5/asset/covert/small-balance-history",
            post: false,
            public: false,
            keys: &[
                "accountType",
                "quoteId",
                "startTime",
                "endTime",
                "cursor",
                "size",
            ],
            required: &[],
            integers: &[],
        },
        "request_small_balance_quote" => RiskEndpoint {
            path: "/v5/asset/covert/get-quote",
            post: true,
            public: false,
            keys: &["accountType", "fromCoinList", "toCoin"],
            required: &["accountType", "fromCoinList", "toCoin"],
            integers: &[],
        },
        "get_small_balance_coins" => RiskEndpoint {
            path: "/v5/asset/covert/small-balance-list",
            post: false,
            public: false,
            keys: &["accountType", "fromCoin"],
            required: &["accountType"],
            integers: &[],
        },
        "get_pre_upgrade_delivery_records" => RiskEndpoint {
            path: "/v5/pre-upgrade/asset/delivery-record",
            post: false,
            public: false,
            keys: &["category", "symbol", "expDate", "limit", "cursor"],
            required: &["category"],
            integers: &["limit"],
        },
        "get_pre_upgrade_executions" => RiskEndpoint {
            path: "/v5/pre-upgrade/execution/list",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "orderId",
                "orderLinkId",
                "baseCoin",
                "startTime",
                "endTime",
                "execType",
                "limit",
                "cursor",
            ],
            required: &["category"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_pre_upgrade_settlement_records" => RiskEndpoint {
            path: "/v5/pre-upgrade/asset/settlement-record",
            post: false,
            public: false,
            keys: &["category", "symbol", "limit", "cursor"],
            required: &["category"],
            integers: &["limit"],
        },
        "get_pre_upgrade_transaction_log" => RiskEndpoint {
            path: "/v5/pre-upgrade/account/transaction-log",
            post: false,
            public: false,
            keys: &[
                "category",
                "baseCoin",
                "type",
                "startTime",
                "endTime",
                "limit",
                "cursor",
            ],
            required: &["category"],
            integers: &["startTime", "endTime", "limit"],
        },
        "sign_trading_agreement" => RiskEndpoint {
            path: "/v5/user/agreement",
            post: true,
            public: false,
            keys: &["categoryV2", "agree"],
            required: &["categoryV2", "agree"],
            integers: &["categoryV2"],
        },
        "get_all_api_rate_limits" => RiskEndpoint {
            path: "/v5/apilimit/query-all",
            post: false,
            public: false,
            keys: &["limit", "cursor", "uids"],
            required: &[],
            integers: &[],
        },
        "get_api_rate_limit_cap" => RiskEndpoint {
            path: "/v5/apilimit/query-cap",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "get_api_rate_limits" => RiskEndpoint {
            path: "/v5/apilimit/query",
            post: false,
            public: false,
            keys: &["uids"],
            required: &["uids"],
            integers: &[],
        },
        "set_api_rate_limits" => RiskEndpoint {
            path: "/v5/apilimit/set",
            post: true,
            public: false,
            keys: &["list"],
            required: &["list"],
            integers: &[],
        },
        "get_spot_x_puzzle_project_list" => RiskEndpoint {
            path: "/v5/spot-x/puzzle/project/list",
            post: false,
            public: false,
            keys: &["status", "projectId", "activityCoin", "cursor", "limit"],
            required: &["status"],
            integers: &["status", "limit"],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/finance/spot-x/token-splash/token-splash-project-list.mdx
        "get_spot_x_token_splash_project_list" => RiskEndpoint {
            path: "/v5/spot-x/token-splash/project/list",
            post: false,
            public: false,
            keys: &["status", "projectId", "activityCoin", "cursor", "limit"],
            required: &["status"],
            integers: &["status", "limit"],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/finance/spot-x/token-splash/token-splash-user-activity-params.mdx
        "get_spot_x_token_splash_user_activity_params" => RiskEndpoint {
            path: "/v5/spot-x/token-splash/user/activity-params",
            post: false,
            public: false,
            keys: &["projectId", "activityCoin"],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/adjust-collateral.mdx
        _ => return None,
    })
}
