//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<RiskEndpoint> {
    Some(match name {
        "get_sub_account_deposit_address" => RiskEndpoint {
            path: "/v5/asset/deposit/query-sub-member-address",
            post: false,
            public: false,
            keys: &["coin", "chainType", "subMemberId"],
            required: &["coin", "chainType", "subMemberId"],
            integers: &[],
        },
        "create_sub_account_api_key" => RiskEndpoint {
            path: "/v5/user/create-sub-api",
            post: true,
            public: false,
            keys: &["subuid", "note", "readOnly", "ips", "permissions"],
            required: &["subuid", "readOnly", "permissions"],
            integers: &["subuid", "readOnly"],
        },
        "create_sub_account" => RiskEndpoint {
            path: "/v5/user/create-sub-member",
            post: true,
            public: false,
            keys: &["username", "password", "memberType", "switch", "note"],
            required: &["username", "memberType"],
            integers: &["memberType", "switch"],
        },
        "set_sub_account_frozen" => RiskEndpoint {
            path: "/v5/user/frozen-sub-member",
            post: true,
            public: false,
            keys: &["subuid", "frozen"],
            required: &["subuid", "frozen"],
            integers: &["subuid", "frozen"],
        },
        "get_sub_account_api_keys" => RiskEndpoint {
            path: "/v5/user/sub-apikeys",
            post: false,
            public: false,
            keys: &["subMemberId", "limit", "cursor"],
            required: &["subMemberId"],
            integers: &["limit"],
        },
        "modify_sub_account_api_key" => RiskEndpoint {
            path: "/v5/user/update-sub-api",
            post: true,
            public: false,
            keys: &["apikey", "readOnly", "ips", "permissions"],
            required: &[],
            integers: &["readOnly"],
        },
        "get_sub_accounts_paginated" => RiskEndpoint {
            path: "/v5/user/submembers",
            post: false,
            public: false,
            keys: &["pageSize", "nextCursor"],
            required: &[],
            integers: &[],
        },
        "delete_sub_account_api_key" => RiskEndpoint {
            path: "/v5/user/delete-sub-api",
            post: true,
            public: false,
            keys: &["apikey"],
            required: &[],
            integers: &[],
        },
        "delete_sub_account" => RiskEndpoint {
            path: "/v5/user/del-submember",
            post: true,
            public: false,
            keys: &["subMemberId"],
            required: &["subMemberId"],
            integers: &[],
        },
        "get_sub_accounts" => RiskEndpoint {
            path: "/v5/user/query-sub-members",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        _ => return None,
    })
}
