use super::HyperliquidClient;
crate::exchanges::impl_exchange_method_wrappers! {
    @extend; HyperliquidClient;
    public [
        get_outcome_templates(),
        get_user_to_multi_sig_signers(user => "user"),
        get_extra_agents(user => "user"),
    ];
    private [
        top_up_isolated_only_margin(action => "action"),
        user_outcome(action => "action"),
        validator_l1_stream(action => "action"),
        authorize_aqav2_role(action => "action"),
        claim_rewards(action => "action"),
        perp_deploy_register_asset2(action => "action"),
        perp_deploy_register_asset(action => "action"),
        perp_deploy_set_oracle(action => "action"),
        perp_deploy_set_funding_multipliers(action => "action"),
        perp_deploy_set_funding_interest_rates(action => "action"),
        perp_deploy_set_funding_clamps(action => "action"),
        perp_deploy_halt_trading(action => "action"),
        perp_deploy_insert_margin_table(action => "action"),
        perp_deploy_set_margin_table_ids(action => "action"),
        perp_deploy_set_fee_recipient(action => "action"),
        perp_deploy_set_open_interest_caps(action => "action"),
        perp_deploy_set_sub_deployers(action => "action"),
        perp_deploy_set_margin_modes(action => "action"),
        perp_deploy_set_deployer_fees(action => "action"),
        perp_deploy_set_perp_annotation(action => "action"),
        perp_deploy_disable_dex(action => "action", confirm => "confirm"),
        perp_deploy_star(action => "action"),
        spot_deploy_register_token2(action => "action"),
        spot_deploy_user_genesis(action => "action"),
        spot_deploy_genesis(action => "action"),
        spot_deploy_register_spot(action => "action"),
        spot_deploy_register_hyperliquidity(action => "action"),
        spot_deploy_set_deployer_trading_fee_share(action => "action"),
        spot_deploy_enable_quote_token(action => "action"),
        spot_deploy_enable_aligned_quote_token(action => "action"),
        spot_deploy_disable_quote_token(action => "action"),
        spot_deploy_disable_aligned_quote_token(action => "action"),
        spot_deploy_set_token_annotation(action => "action"),
        spot_deploy_set_deployer_label(action => "action"),
        activate_outcome_deployer(action => "action"),
        outcome_deploy(action => "action"),
        set_referrer(action => "action"),
        convert_to_multi_sig_user_signed(action => "action", nonce => "nonce", signature => "signature", confirm => "confirm"),
        c_signer_action(action => "action"),
        c_validator_action(action => "action"),
        multi_sig_signed(action => "action", nonce => "nonce", signature => "signature"),
        evm_user_modify(action => "action"),
        gossip_priority_bid(action => "action"),
    ];
}
