//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "set_uta_account_mode" => Endpoint {
            path: "/api/ua/v2/account/mode",
            method: HttpMethod::Post,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[Field {
                key: "accountType",
                kind: 's',
                required: true,
                path: false,
                choices: &["CLASSIC", "UNIFIED"],
                minimum: None,
                maximum: None,
            }],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/account-funding/get-account-ledgers-futures
        "get_futures_account_ledgers" => Endpoint {
            path: "/api/v1/transaction-history",
            method: HttpMethod::Get,
            market: KucoinMarket::Futures,
            public: false,
            fields: &[
                Field {
                    key: "currency",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "type",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[
                        "RealizedPNL",
                        "Deposit",
                        "Withdrawal",
                        "Transferin",
                        "TransferOut",
                    ],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "offset",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "forward",
                    kind: 'b',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "maxCount",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: None,
                },
                Field {
                    key: "startAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "endAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/account-funding/get-account-ledgers-marginhf
        "get_spot_account_ledgers" => Endpoint {
            path: "/api/v1/accounts/ledgers",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "currency",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "direction",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["in", "out"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "bizType",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "startAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "endAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "currentPage",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: None,
                },
                Field {
                    key: "pageSize",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(10),
                    maximum: Some(500),
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/account-funding/get-account-ledgers-tradehf
        "get_spot_hf_account_ledgers" => Endpoint {
            path: "/api/v1/hf/accounts/ledgers",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "currency",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "direction",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["in", "out"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "bizType",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[
                        "TRADE_EXCHANGE",
                        "TRANSFER",
                        "SUB_TRANSFER",
                        "RETURNED_FEES",
                        "DEDUCTION_FEES",
                        "OTHER",
                    ],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "lastId",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "limit",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: Some(200),
                },
                Field {
                    key: "startAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: Some(9999999999999),
                },
                Field {
                    key: "endAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: Some(9999999999999),
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/deposit/get-deposit-history
        "get_uta_account_ledgers" => Endpoint {
            path: "/api/ua/v2/account/ledger",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "accountType",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &["FUNDING", "SPOT", "FUTURES", "CROSS", "ISOLATED", "UNIFIED"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "businessType",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[
                        "TRADE_EXCHANGE",
                        "TRANSFER",
                        "SUB_TRANSFER",
                        "RETURNED_FEES",
                        "DEDUCTION_FEES",
                        "OTHER",
                        "SUB_TO_SUB_TRANSFER",
                        "SPOT_EXCHANGE",
                        "SPOT_EXCHANGE_REBATE",
                        "FUTURES_EXCHANGE_OPEN",
                        "FUTURES_EXCHANGE_CLOSE",
                        "FUTURES_EXCHANGE_REBATE",
                        "FUNDING_FEE",
                        "LIABILITY_INTEREST",
                        "KCS_DEDUCTION_FEES",
                        "KCS_RETURNED_FEES",
                        "AUTO_EXCHANGE_USER",
                    ],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "currency",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "direction",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["IN", "OUT"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "startAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "endAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "pageSize",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: Some(50),
                },
                Field {
                    key: "lastId",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/classic-account-balance
        "get_classic_account_balances_v2" => Endpoint {
            path: "/api/ua/v2/account/balance",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "accountSubtype",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "accountType",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &["FUNDING", "SPOT", "FUTURES", "CROSS", "ISOLATED"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "currency",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/flex-transfer
        "get_uta_account_mode" => Endpoint {
            path: "/api/ua/v2/account/mode",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-all-api-rate-limit
        "get_uta_all_rate_limits" => Endpoint {
            path: "/api/ua/v2/rate-limit/query-all",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-api-rate-limit
        "get_uta_rate_limits" => Endpoint {
            path: "/api/ua/v2/rate-limit/query",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[Field {
                key: "uids",
                kind: 's',
                required: true,
                path: false,
                choices: &[],
                minimum: None,
                maximum: None,
            }],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-api-rate-limit-cap
        "get_uta_rate_limit_cap" => Endpoint {
            path: "/api/ua/v2/rate-limit/query-cap",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-borrowable-currencies
        "get_uta_interest_history" => Endpoint {
            path: "/api/ua/v2/account/interest-history",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "accountType",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &["UNIFIED"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "currency",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "startTime",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "endTime",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "page",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: None,
                },
                Field {
                    key: "size",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: Some(1000),
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-interest-rate-index
        "get_basic_fee" => Endpoint {
            path: "/api/v1/base-fee",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[Field {
                key: "currencyType",
                kind: 'i',
                required: false,
                path: false,
                choices: &["0", "1"],
                minimum: Some(0),
                maximum: None,
            }],
        },
        // https://www.kucoin.com/docs-new/rest/convert/add-convert-limit-order
        "set_uta_kcs_fee_deduction" => Endpoint {
            path: "/api/ua/v2/account/fee/kcs-deduct",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[Field {
                key: "enabled",
                kind: 'b',
                required: true,
                path: false,
                choices: &[],
                minimum: None,
                maximum: None,
            }],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/modify-sub-api-key
        "set_uta_rate_limit" => Endpoint {
            path: "/api/ua/v2/rate-limit/set",
            method: HttpMethod::Post,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[Field {
                key: "list",
                kind: 'a',
                required: true,
                path: false,
                choices: &[],
                minimum: None,
                maximum: None,
            }],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/sub-api-keys
        "get_account_info" => Endpoint {
            path: "/api/v2/user-info",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/account-funding/get-account-type-spot
        "get_spot_account_type" => Endpoint {
            path: "/api/v1/hf/accounts/opened",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/3476608e0
        "get_uta_oes_custody_quota" => Endpoint {
            path: "/api/ua/v2/oes/custody-quota",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "custodian",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["BITGO_SG", "BITGO_SD", "CACTUS", "CEFFU"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "currency",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-oes-settlement-currency
        _ => return None,
    })
}
