//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "get_announcements" => Endpoint {
            path: "/api/v3/announcements",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[
                Field {
                    key: "currentPage",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: None,
                },
                Field {
                    key: "pageSize",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: None,
                },
                Field {
                    key: "annType",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[
                        "latest-announcements",
                        "futures-announcements",
                        "activities",
                        "product-updates",
                        "vip",
                        "maintenance-updates",
                        "delistings",
                        "others",
                        "api-campaigns",
                        "new-listings",
                    ],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "lang",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[
                        "zh_HK", "ja_JP", "ko_KR", "en_US", "pl_PL", "es_ES", "fr_FR", "ar_AE",
                        "it_IT", "id_ID", "nl_NL", "pt_PT", "vi_VN", "de_DE", "tr_TR", "ms_MY",
                        "ru_RU", "th_TH", "hi_IN", "bn_BD", "fil_PH", "ur_PK",
                    ],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "startTime",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "endTime",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/spot-trading/market-data/get-call-auction-info
        "get_uta_announcements" => Endpoint {
            path: "/api/ua/v2/market/announcement",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[
                Field {
                    key: "language",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[
                        "zh_HK", "ja_JP", "ko_KR", "en_US", "pl_PL", "es_ES", "fr_FR", "ar_AE",
                        "it_IT", "id_ID", "nl_NL", "pt_PT", "vi_VN", "de_DE", "tr_TR", "ms_MY",
                        "ru_RU", "th_TH", "hi_IN", "bn_BD", "fil_PH", "ur_PK",
                    ],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "type",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[
                        "latest-announcements",
                        "activities",
                        "product-updates",
                        "vip",
                        "maintenance-updates",
                        "delistings",
                        "others",
                        "api-campaigns",
                        "new-listings",
                        "futures-announcements",
                    ],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "pageNumber",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: None,
                },
                Field {
                    key: "pageSize",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: None,
                },
                Field {
                    key: "startTime",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "endTime",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-call-auction-info
        _ => return None,
    })
}
