//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "add_convert_limit_order" => Endpoint {
            path: "/api/v1/convert/limit/order",
            method: HttpMethod::Post,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "clientOrderId",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "accountType",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["BOTH", "FUNDING", "TRADING"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "fromCurrency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "toCurrency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "fromCurrencySize",
                    kind: 'd',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "toCurrencySize",
                    kind: 'd',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/convert/add-convert-order
        "add_convert_order" => Endpoint {
            path: "/api/v1/convert/order",
            method: HttpMethod::Post,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "clientOrderId",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "quoteId",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "accountType",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["BOTH", "FUNDING", "TRADING"],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/convert/cancel-convert-limit-order
        "cancel_convert_limit_order" => Endpoint {
            path: "/api/v1/convert/limit/order/cancel",
            method: HttpMethod::Delete,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "clientOrderId",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "orderId",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/convert/get-convert-currencies
        "get_convert_currencies" => Endpoint {
            path: "/api/v1/convert/currencies",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/rest/convert/get-convert-limit-order-detail
        "get_convert_limit_order_detail" => Endpoint {
            path: "/api/v1/convert/limit/order/detail",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "clientOrderId",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "orderId",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/convert/get-convert-limit-orders
        "get_convert_limit_order_detail_list" => Endpoint {
            path: "/api/v1/convert/limit/orders",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "startAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "endAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "page",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: None,
                },
                Field {
                    key: "pageSize",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: None,
                },
                Field {
                    key: "status",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["OPEN", "SUCCESS", "FAIL", "CANCELLED"],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/convert/get-convert-limit-quote
        "get_convert_limit_quote" => Endpoint {
            path: "/api/v1/convert/limit/quote",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "fromCurrency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "toCurrency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "fromCurrencySize",
                    kind: 'd',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "toCurrencySize",
                    kind: 'd',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/convert/get-convert-order-detail
        "get_convert_order_detail" => Endpoint {
            path: "/api/v1/convert/order/detail",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "clientOrderId",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "orderId",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/convert/get-convert-order-history
        "get_convert_order_history" => Endpoint {
            path: "/api/v1/convert/order/history",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "startAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "endAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "page",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: None,
                },
                Field {
                    key: "pageSize",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(20),
                    maximum: Some(100),
                },
                Field {
                    key: "status",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["OPEN", "SUCCESS", "FAIL"],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/convert/get-convert-quote
        "get_convert_quote" => Endpoint {
            path: "/api/v1/convert/quote",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "fromCurrency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "toCurrency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "fromCurrencySize",
                    kind: 'd',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "toCurrencySize",
                    kind: 'd',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/convert/get-convert-symbol
        "get_convert_symbol" => Endpoint {
            path: "/api/v1/convert/symbol",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[
                Field {
                    key: "fromCurrency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "toCurrency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "orderType",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["MARKET", "LIMIT"],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/futures-trading/market-data/get-interest-rate-index
        _ => return None,
    })
}
