//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "get_deposit_history" => Endpoint {
            path: "/api/v1/deposits",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "currency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "status",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[
                        "PROCESSING",
                        "SUCCESS",
                        "FAILURE",
                        "WAIT_TRM_MGT",
                        "TRM_MGT_REJECTED",
                    ],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "startAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "endAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "currentPage",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: None,
                },
                Field {
                    key: "pageSize",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(10),
                    maximum: Some(500),
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/futures-trading/market-data/get-all-tickers
        "create_deposit_address_v3" => Endpoint {
            path: "/api/v3/deposit-address/create",
            method: HttpMethod::Post,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "currency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "chain",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "to",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["main", "trade"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "amount",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/deposit/get-deposit-address-v3/en
        "get_deposit_addresses_v3" => Endpoint {
            path: "/api/v3/deposit-addresses",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "currency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "chain",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/sub-account-api/add-subaccount-api
        "get_uta_deposit_address" => Endpoint {
            path: "/api/ua/v2/asset/deposit/address",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "chain",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "currency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/deposit-history
        "get_uta_deposit_history" => Endpoint {
            path: "/api/ua/v2/asset/deposit/history",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "currency",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "id",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "status",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[
                        "FAILURE",
                        "PRE_SUCCESS",
                        "PROCESSING",
                        "RISK_MGT_REJECTED",
                        "ROLLBACK",
                        "ROLLBACKING",
                        "SUCCESS",
                        "TRM_MGT_REJECTED",
                        "WAIT_RISK_MGT",
                        "WAIT_TRM_MGT",
                    ],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "startAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "endAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "currentPage",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: None,
                },
                Field {
                    key: "pageSize",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: Some(50),
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/fiat-price
        _ => return None,
    })
}
