//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "get_currencies_v3" => Endpoint {
            path: "/api/v3/currencies",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[],
        },
        "get_futures_all_tickers" => Endpoint {
            path: "/api/v1/allTickers",
            method: HttpMethod::Get,
            market: KucoinMarket::Futures,
            public: true,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/rest/futures-trading/market-data/get-mark-price
        "get_futures_mark_price" => Endpoint {
            path: "/api/v1/mark-price/{symbol}/current",
            method: HttpMethod::Get,
            market: KucoinMarket::Futures,
            public: true,
            fields: &[Field {
                key: "symbol",
                kind: 's',
                required: true,
                path: true,
                choices: &[],
                minimum: None,
                maximum: None,
            }],
        },
        // https://www.kucoin.com/docs-new/rest/futures-trading/market-data/get-server-time
        "get_futures_server_time" => Endpoint {
            path: "/api/v1/timestamp",
            method: HttpMethod::Get,
            market: KucoinMarket::Futures,
            public: true,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/rest/futures-trading/market-data/get-service-status
        "get_futures_service_status" => Endpoint {
            path: "/api/v1/status",
            method: HttpMethod::Get,
            market: KucoinMarket::Futures,
            public: true,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/rest/margin-trading/market-data/get-mark-price-detail
        "get_spot_full_orderbook" => Endpoint {
            path: "/api/v3/market/orderbook/level2",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[Field {
                key: "symbol",
                kind: 's',
                required: true,
                path: false,
                choices: &[],
                minimum: None,
                maximum: None,
            }],
        },
        // https://www.kucoin.com/docs-new/rest/spot-trading/market-data/get-server-time
        "get_spot_server_time" => Endpoint {
            path: "/api/v1/timestamp",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/rest/spot-trading/market-data/get-service-status
        "get_spot_service_status" => Endpoint {
            path: "/api/v1/status",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/account-ledger
        "get_uta_collateral_ratios" => Endpoint {
            path: "/api/ua/v2/market/collateral-discount-ratio",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-current-funding
        "get_uta_current_funding_rates" => Endpoint {
            path: "/api/ua/v2/market/funding-rate",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[
                Field {
                    key: "symbol",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "productType",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["COIN-FUTURES", "USDC-FUTURES", "USDT-FUTURES"],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-history-funding-rate
        "get_uta_funding_rate_history" => Endpoint {
            path: "/api/ua/v2/market/funding-rate-history",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[
                Field {
                    key: "symbol",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "startAt",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "endAt",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-index-price
        "get_uta_index_prices" => Endpoint {
            path: "/api/ua/v2/market/index-price",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[
                Field {
                    key: "symbol",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "startAt",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "endAt",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "pageSize",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "lastId",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-interest-history-uta
        "get_uta_interest_rate_index" => Endpoint {
            path: "/api/ua/v2/market/interest-rate-index",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[
                Field {
                    key: "symbol",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "startAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "endAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "lastId",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "pageSize",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-klines
        "get_uta_klines" => Endpoint {
            path: "/api/ua/v2/market/kline",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[
                Field {
                    key: "symbol",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "tradeType",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &["SPOT", "FUTURES"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "klineType",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["TRADE", "MARK_PRICE", "INDEX_PRICE", "PREMIUM_INDEX"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "interval",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[
                        "1min", "3min", "5min", "15min", "30min", "1hour", "2hour", "4hour",
                        "6hour", "8hour", "12hour", "1day", "3day", "1week", "1month",
                    ],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "startAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "endAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-orderbook
        "get_uta_orderbook" => Endpoint {
            path: "/api/ua/v2/market/orderbook",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "tradeType",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &["SPOT", "FUTURES"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "symbol",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "limit",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &["20", "100", "FULL"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "rpiFilter",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &["0", "1"],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-service-status
        "get_uta_service_status" => Endpoint {
            path: "/api/ua/v2/server/status",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[Field {
                key: "tradeType",
                kind: 's',
                required: true,
                path: false,
                choices: &["SPOT", "FUTURES"],
                minimum: None,
                maximum: None,
            }],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-ticker
        "get_uta_tickers" => Endpoint {
            path: "/api/ua/v2/market/ticker",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[
                Field {
                    key: "tradeType",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &["SPOT", "FUTURES"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "symbol",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-trade-statistics
        "get_uta_trade_statistics" => Endpoint {
            path: "/api/ua/v2/trade-statistics",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-trades
        "get_uta_public_trades" => Endpoint {
            path: "/api/ua/v2/market/trade",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[
                Field {
                    key: "tradeType",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &["SPOT", "FUTURES"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "symbol",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/instrument
        "get_uta_instruments" => Endpoint {
            path: "/api/ua/v2/market/instrument",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[
                Field {
                    key: "symbol",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "tradeType",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &["SPOT", "FUTURES"],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/transfer-quota
        "get_futures_interest_rate_index" => Endpoint {
            path: "/api/v1/interest/query",
            method: HttpMethod::Get,
            market: KucoinMarket::Futures,
            public: true,
            fields: &[
                Field {
                    key: "symbol",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "startAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "endAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "reverse",
                    kind: 'b',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "offset",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "forward",
                    kind: 'b',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "maxCount",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: Some(100),
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/futures-trading/market-data/get-premium-index
        "get_futures_premium_index" => Endpoint {
            path: "/api/v1/premium/query",
            method: HttpMethod::Get,
            market: KucoinMarket::Futures,
            public: true,
            fields: &[
                Field {
                    key: "symbol",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "startAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "endAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "reverse",
                    kind: 'b',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "offset",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "forward",
                    kind: 'b',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "maxCount",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: Some(100),
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/margin-trading/market-data/get-margin-config
        "get_call_auction_info" => Endpoint {
            path: "/api/v1/market/callauctionData",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[Field {
                key: "symbol",
                kind: 's',
                required: true,
                path: false,
                choices: &[],
                minimum: None,
                maximum: None,
            }],
        },
        // https://www.kucoin.com/docs-new/rest/spot-trading/market-data/get-call-auction-part-orderbook
        "get_call_auction_part_order_book" => Endpoint {
            path: "/api/v1/market/orderbook/callauction/level2_{size}",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[
                Field {
                    key: "size",
                    kind: 'i',
                    required: true,
                    path: true,
                    choices: &["20", "100"],
                    minimum: Some(1),
                    maximum: None,
                },
                Field {
                    key: "symbol",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/spot-trading/market-data/get-currency
        "get_spot_currency_v3" => Endpoint {
            path: "/api/v3/currencies/{currency}",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[
                Field {
                    key: "currency",
                    kind: 's',
                    required: true,
                    path: true,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "chain",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/spot-trading/market-data/get-fiat-price
        "get_market_list" => Endpoint {
            path: "/api/v1/markets",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/rest/spot-trading/market-data/get-symbol
        "get_spot_symbol_v2" => Endpoint {
            path: "/api/v2/symbols/{symbol}",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[Field {
                key: "symbol",
                kind: 's',
                required: true,
                path: true,
                choices: &[],
                minimum: None,
                maximum: None,
            }],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/add-sub-account
        "get_uta_currencies" => Endpoint {
            path: "/api/ua/v2/asset/currencies",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[
                Field {
                    key: "chain",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "currencyList",
                    kind: 'a',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/currency
        "get_uta_currency" => Endpoint {
            path: "/api/ua/v2/market/currency",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[
                Field {
                    key: "chain",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "currency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/delete-sub-api-key
        "get_uta_call_auction_info" => Endpoint {
            path: "/api/ua/v2/market/call-auction-info",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[Field {
                key: "symbol",
                kind: 's',
                required: true,
                path: false,
                choices: &[],
                minimum: None,
                maximum: None,
            }],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-client-ip-address
        "get_uta_client_ip_address" => Endpoint {
            path: "/api/ua/v2/user/my-ip",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-kyc-region
        "get_uta_kyc_regions" => Endpoint {
            path: "/api/ua/v2/user/kyc-region",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/kcs-deduct
        "get_spot_24h_statistics" => Endpoint {
            path: "/api/v1/market/stats",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[Field {
                key: "symbol",
                kind: 's',
                required: true,
                path: false,
                choices: &[],
                minimum: None,
                maximum: None,
            }],
        },
        // https://www.kucoin.com/docs-new/rest/spot-trading/market-data/get-client-ip-address
        "get_client_ip_address" => Endpoint {
            path: "/api/v1/my-ip",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/withdrawals/get-kyc-regions
        "get_kyc_regions" => Endpoint {
            path: "/api/kyc/regions/v4",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/rest/futures-trading/market-data/get-spot-index-price
        "get_spot_index_price" => Endpoint {
            path: "/api/v1/index/query",
            method: HttpMethod::Get,
            market: KucoinMarket::Futures,
            public: true,
            fields: &[
                Field {
                    key: "symbol",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "startAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "endAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "reverse",
                    kind: 'b',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "offset",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "forward",
                    kind: 'b',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "maxCount",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: Some(100),
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/futures-trading/market-data/get-24hr-stats
        "get_futures_24h_statistics" => Endpoint {
            path: "/api/v1/trade-statistics",
            method: HttpMethod::Get,
            market: KucoinMarket::Futures,
            public: true,
            fields: &[],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/withdrawals/get-withdrawal-by-id
        "get_uta_oe_scurrency" => Endpoint {
            path: "/api/ua/v2/oes/currency",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: true,
            fields: &[
                Field {
                    key: "custodian",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["BITGO_SG", "BITGO_SD", "CACTUS", "CEFFU"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "currency",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/vip-lending/get-accounts
        _ => return None,
    })
}
