//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "add_sub_account_api" => Endpoint {
            path: "/api/v1/sub/api-key",
            method: HttpMethod::Post,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "passphrase",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "remark",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "permission",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "ipWhitelist",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "expire",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["-1", "30", "90", "180", "360"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "subName",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/sub-account-api/delete-subaccount-api
        "delete_sub_account_api" => Endpoint {
            path: "/api/v1/sub/api-key",
            method: HttpMethod::Delete,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "apiKey",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "subName",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "passphrase",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/sub-account-api/get-subaccount-api-list
        "get_sub_account_api_list" => Endpoint {
            path: "/api/v1/sub/api-key",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "apiKey",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "subName",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/sub-account-api/modify-subaccount-api
        "modify_sub_account_api" => Endpoint {
            path: "/api/v1/sub/api-key/update",
            method: HttpMethod::Post,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "passphrase",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "permission",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "ipWhitelist",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "expire",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["-1", "30", "90", "180", "360"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "subName",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "apiKey",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/sub-account/add-subaccount-futures-permission
        "add_sub_account_futures_permission" => Endpoint {
            path: "/api/v3/sub/user/futures/enable",
            method: HttpMethod::Post,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[Field {
                key: "uid",
                kind: 's',
                required: true,
                path: false,
                choices: &[],
                minimum: None,
                maximum: None,
            }],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/sub-account/add-subaccount-margin-permission
        "add_sub_account_margin_permission" => Endpoint {
            path: "/api/v3/sub/user/margin/enable",
            method: HttpMethod::Post,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[Field {
                key: "uid",
                kind: 's',
                required: true,
                path: false,
                choices: &[],
                minimum: None,
                maximum: None,
            }],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/trade-fee/get-basic-fee-spot-margin
        "add_uta_sub_account" => Endpoint {
            path: "/api/ua/v2/user/sub/create-sub-account",
            method: HttpMethod::Post,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "password",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "remarks",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "subName",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "access",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "mode",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["CLASSIC", "UNIFIED"],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/add-sub-api-key
        "add_uta_sub_account_api" => Endpoint {
            path: "/api/ua/v2/user/create-sub-api-key",
            method: HttpMethod::Post,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "subName",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "passphrase",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "remark",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "permission",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "ipWhitelist",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "expire",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["-1", "30", "90", "180", "360"],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/api-key
        "delete_uta_sub_account_api" => Endpoint {
            path: "/api/ua/v2/user/sub-api-key",
            method: HttpMethod::Delete,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "apiKey",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "subName",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "passphrase",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/deposit-address
        "modify_uta_sub_account_api" => Endpoint {
            path: "/api/ua/v2/user/modify-sub-api-key",
            method: HttpMethod::Post,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "subName",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "apiKey",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "passphrase",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "permission",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "ipWhitelist",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "expire",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["-1", "30", "90", "180", "360"],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/set-sub-accounts-api-rate-limit
        "get_uta_sub_account_api_list" => Endpoint {
            path: "/api/ua/v2/user/sub-api-key",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "apiKey",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "subName",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/transfer-permission
        "add_sub_account" => Endpoint {
            path: "/api/v2/sub/user/created",
            method: HttpMethod::Post,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "password",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "remarks",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "subName",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "access",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "mode",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &["CLASSIC", "UNIFIED"],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/spot-trading/market-data/get-24hr-stats
        _ => return None,
    })
}
