//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "transfer_uta_accounts" => Endpoint {
            path: "/api/ua/v2/account/transfer",
            method: HttpMethod::Post,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "clientOid",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "transferType",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &["INTERNAL", "PARENT_TO_SUB", "SUB_TO_PARENT", "SUB_TO_SUB"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "currency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "amount",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "fromUid",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "fromAccountType",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &["FUNDING", "UNIFIED", "FUTURES", "ISOLATED", "CROSS", "SPOT"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "fromAccountTag",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "toUid",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "toAccountType",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &["FUNDING", "UNIFIED", "FUTURES", "ISOLATED", "CROSS", "SPOT"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "toAccountTag",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/get-account-mode
        "get_uta_transfer_quota" => Endpoint {
            path: "/api/ua/v2/account/transfer-quota",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "accountType",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &["FUNDING", "SPOT", "FUTURES", "CROSS", "ISOLATED", "UNIFIED"],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "currency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "symbol",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/account-funding/get-apikey-info
        "set_uta_sub_account_transfer_permission" => Endpoint {
            path: "/api/ua/v2/sub-account/canTransferOut",
            method: HttpMethod::Post,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "subUids",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "subToSub",
                    kind: 'b',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/account-funding/get-account-summary-info
        _ => return None,
    })
}
