//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<Endpoint> {
    Some(match name {
        "get_withdrawal_history_by_id" => Endpoint {
            path: "/api/v1/withdrawals/{withdrawalId}",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[Field {
                key: "withdrawalId",
                kind: 's',
                required: true,
                path: true,
                choices: &[],
                minimum: None,
                maximum: None,
            }],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/withdrawals/get-withdrawal-history
        "get_withdrawal_history" => Endpoint {
            path: "/api/v1/withdrawals",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "currency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "status",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[
                        "PROCESSING",
                        "REVIEW",
                        "WALLET_PROCESSING",
                        "SUCCESS",
                        "FAILURE",
                    ],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "startAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "endAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "currentPage",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: None,
                },
                Field {
                    key: "pageSize",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(10),
                    maximum: Some(500),
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/account-info/withdrawals/get-withdrawal-quotas
        "get_withdrawal_quotas" => Endpoint {
            path: "/api/v1/withdrawals/quotas",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "currency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "chain",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        // https://www.kucoin.com/docs-new/rest/vip-lending/get-account-detail
        "get_uta_withdrawal_history" => Endpoint {
            path: "/api/ua/v2/asset/withdrawal/history",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "currency",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "id",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "status",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[
                        "FAILURE",
                        "PRE_SUCCESS",
                        "PROCESSING",
                        "RISK_MGT_REJECTED",
                        "ROLLBACK",
                        "ROLLBACKING",
                        "SUCCESS",
                        "TRM_MGT_REJECTED",
                        "WAIT_RISK_MGT",
                        "WAIT_TRM_MGT",
                    ],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "startAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "endAt",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(0),
                    maximum: None,
                },
                Field {
                    key: "currentPage",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: None,
                },
                Field {
                    key: "pageSize",
                    kind: 'i',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: Some(1),
                    maximum: Some(50),
                },
            ],
        },
        // https://www.kucoin.com/docs-new/v2/rest/ua/withdrawal-quota
        "get_uta_withdrawal_quotas" => Endpoint {
            path: "/api/ua/v2/withdrawals/quotas",
            method: HttpMethod::Get,
            market: KucoinMarket::Spot,
            public: false,
            fields: &[
                Field {
                    key: "chain",
                    kind: 's',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "currency",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "isInner",
                    kind: 'b',
                    required: false,
                    path: false,
                    choices: &[],
                    minimum: None,
                    maximum: None,
                },
                Field {
                    key: "withdrawType",
                    kind: 's',
                    required: true,
                    path: false,
                    choices: &["ADDRESS", "MAIL", "PHONE", "UID"],
                    minimum: None,
                    maximum: None,
                },
            ],
        },
        _ => return None,
    })
}
