"""Generated bybit account HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedAccountHTTP(MarketHTTP):
    """Account API methods."""

    async def get_user_aff_customer_info(
        self, *, uid: str, coin: str | None = None, business: str | None = None
    ) -> dict[str, Any]:
        """
        Get Affiliate User Info. GET /v5/user/aff-customer-info.

        Source: https://bybit-exchange.github.io/docs/v5/affiliate/affiliate-info

        Args:
            uid: The master account UID of affiliate's client
            coin: Coin type for filtering, e.g., `USDT
            business: Business line filter. `1`: Derivatives, `2`: Spot, `3`: ByFi, `4`: USDC, `5`:
                Options
        """
        return await self._native_private(
            "get_user_aff_customer_info",
            self._native_params(**{"uid": uid, "coin": coin, "business": business}),
        )

    async def request_demo_funds(
        self, *, adjust_type: int | None = None, uta_demo_apply_money: list[Any] | None = None
    ) -> dict[str, Any]:
        """
        Demo Trading Service. POST /v5/account/demo-apply-money.

        Source: https://bybit-exchange.github.io/docs/v5/demo

        Args:
            adjust_type: 0`(default): add demo funds; `1`: reduce demo funds
            uta_demo_apply_money:
        """
        return await self._native_private(
            "request_demo_funds",
            self._native_params(
                **{"adjustType": adjust_type, "utaDemoApplyMoney": uta_demo_apply_money}
            ),
        )

    async def create_demo_member(self) -> dict[str, Any]:
        """
        Demo Trading Service. POST /v5/user/create-demo-member.

        Source: https://bybit-exchange.github.io/docs/v5/demo
        """
        return await self._native_private("create_demo_member", [])

    async def get_ins_ip_changelog(
        self,
        *,
        start_time: str | None = None,
        end_time: str | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """
        Get Institution IP Change Log. GET /v5/ins/ip/changelog.

        Source: https://bybit-exchange.github.io/docs/v5/institution/ip-changelog

        Args:
            start_time: Filter start time, Unix timestamp in milliseconds
            end_time: Filter end time, Unix timestamp in milliseconds
            limit: Records per page. Range: [1, 50]. Default: 20
            cursor: Pagination cursor. Use the `nextPageCursor` value from the previous response
        """
        return await self._native_private(
            "get_ins_ip_changelog",
            self._native_params(
                **{"startTime": start_time, "endTime": end_time, "limit": limit, "cursor": cursor}
            ),
        )

    async def get_ins_whitelist_ip(self) -> dict[str, Any]:
        """
        Get Institution Whitelist IP. GET /v5/ins/whitelist/ip.

        Source: https://bybit-exchange.github.io/docs/v5/institution/whitelist-ip
        """
        return await self._native_private("get_ins_whitelist_ip", [])

    async def get_user_invitation_code(self) -> dict[str, Any]:
        """
        Get Referral Code. GET /v5/user/invitation/code.

        Source: https://bybit-exchange.github.io/docs/v5/user/referral-code
        """
        return await self._native_private("get_user_invitation_code", [])
