"""Generated bybit affiliate HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedAffiliateHTTP(MarketHTTP):
    """Affiliate API methods."""

    async def get_affiliate_affiliate_sub_list(
        self,
        *,
        cursor: str | None = None,
        size: int | None = None,
        start_date: str | None = None,
        end_date: str | None = None,
        sub_aff_id: int | None = None,
    ) -> dict[str, Any]:
        """
        Get Affiliate Sub-Affiliate List. GET /v5/affiliate/affiliate-sub-list.

        Source: https://bybit-exchange.github.io/docs/v5/affiliate/affiliate-sub-list

        Args:
            cursor: Cursor. Use the `nextPageCursor` token from the response to retrieve the next
                page of the result set
            size: Limit for data size per page. [`0`, `100`]. Default: `0
            start_date: Start date of the query period, format `YYYY-MM-DD`. The range between
                "startDate" and "endTime" cannot exceed 3 months
            end_date: End date of the query period, format `YYYY-MM-DD`. "startDate" and "endDate"
                must either both be provided or both be omitted. If both are omitted, it returns T-1
                data by default
            sub_aff_id: Sub-affiliate ID for exact lookup. Pass `0` or omit to return all
                sub-affiliates without filtering
        """
        return await self._native_private(
            "get_affiliate_affiliate_sub_list",
            self._native_params(
                **{
                    "cursor": cursor,
                    "size": size,
                    "startDate": start_date,
                    "endDate": end_date,
                    "subAffId": sub_aff_id,
                }
            ),
        )

    async def get_affiliate_aff_user_list(
        self,
        *,
        size: int | None = None,
        cursor: str | None = None,
        need_deposit: bool | None = None,
        need30: bool | None = None,
        need365: bool | None = None,
        start_date: str | None = None,
        end_date: str | None = None,
    ) -> dict[str, Any]:
        """
        Get Affiliate User List. GET /v5/affiliate/aff-user-list.

        Source: https://bybit-exchange.github.io/docs/v5/affiliate/affiliate-user-list

        Args:
            size: Limit for data size per page. [`0`, `100`]. Default: `0
            cursor: Cursor. Use the `nextPageCursor` token from the response to retrieve the next
                page of the result set
            need_deposit: true`: return deposit info; `false`(default): does not return deposit info
            need30: true`: return 30 days trading info; `false`(default): does not return 30 days
                trading info
            need365: true`: return 365 days trading info; `false`(default): does not return 365 days
                trading info
            start_date: Start date of the query period, format `YYYY-MM-DD
            end_date: End date of the query period, format `YYYY-MM-DD
        """
        return await self._native_private(
            "get_affiliate_aff_user_list",
            self._native_params(
                **{
                    "size": size,
                    "cursor": cursor,
                    "needDeposit": need_deposit,
                    "need30": need30,
                    "need365": need365,
                    "startDate": start_date,
                    "endDate": end_date,
                }
            ),
        )
