"""Generated bybit bots HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedBotsHTTP(MarketHTTP):
    """Bots API methods."""

    async def request_dca_close_bot(self, *, bot_id: str, close_mode: str) -> dict[str, Any]:
        """
        Close DCA Bot. POST /v5/dca/close-bot.

        Source: https://bybit-exchange.github.io/docs/v5/bot/dca/close

        Args:
            bot_id: DCA bot ID to close, obtained from Create Spot DCA Bot response
            close_mode: Asset settlement mode: `2` Base token, `3` Quote token (e.g. USDT)
        """
        return await self._native_private(
            "request_dca_close_bot",
            self._native_params(**{"bot_id": bot_id, "close_mode": close_mode}),
        )

    async def request_dca_create_bot(self, *, parameters: dict[str, Any]) -> dict[str, Any]:
        """
        Create DCA Bot. POST /v5/dca/create-bot.

        Source: https://bybit-exchange.github.io/docs/v5/bot/dca/create

        Args:
            parameters: DCA bot configuration object (see below)
        """
        return await self._native_private(
            "request_dca_create_bot", self._native_params(**{"parameters": parameters})
        )

    async def close_fcombobot(self, *, bot_id: str) -> dict[str, Any]:
        """
        Close Bot. POST /v5/fcombobot/close.

        Source: https://bybit-exchange.github.io/docs/v5/bot/futures-combo/close

        Args:
            bot_id: Bot ID to close, obtained from Create Futures Combo Bot response
        """
        return await self._native_private(
            "close_fcombobot", self._native_params(**{"bot_id": bot_id})
        )

    async def create_fcombobot(
        self,
        *,
        leverage: str,
        init_margin: str,
        adjust_position_mode: int,
        symbol_settings: list[Any],
        adjust_position_percent: str | None = None,
        adjust_position_time_interval: int | None = None,
        sl_percent: str | None = None,
        tp_percent: str | None = None,
        trailing_stop_percent: str | None = None,
    ) -> dict[str, Any]:
        """
        Create Bot. POST /v5/fcombobot/create.

        Source: https://bybit-exchange.github.io/docs/v5/bot/futures-combo/create

        Args:
            leverage: Position leverage multiplier (e.g. `"5"` means 5x). Must be >= 1
            init_margin: Initial investment in quote currency (decimal string, e.g. `"1000"` for
                1000 USDT)
            adjust_position_mode: Rebalancing trigger mode: `1` Time, `2` Percentage, `3` Time or
                Percentage, `4` Manual, `5` On settings change, `6` On transfer
            symbol_settings: Per-symbol portfolio configuration. At least one entry required. All
                `target_position_percent` must sum to 1
            adjust_position_percent: Rebalancing drift threshold as percentage, range: [0.01, 0.5]
                (e.g. `"0.05"` means rebalance when allocation drifts 5%). **Required** when mode
                includes percentage
            adjust_position_time_interval: Rebalancing time interval **in seconds**. **Required**
                when mode includes time. `30M`, `1H`, `4H`, `8H`, `12H`, `1D`, `3D`, `7D`, `14D`,
                `28D` convert to seconds
            sl_percent: Stop-loss as percentage of total margin (e.g. `"0.2"` means close when loss
                reaches 20%)
            tp_percent: Take-profit as percentage of total margin (e.g. `"0.5"` means close when
                profit reaches 50%)
            trailing_stop_percent: Trailing stop callback as percentage (e.g. `"0.05"` means 5%)
        """
        return await self._native_private(
            "create_fcombobot",
            self._native_params(
                **{
                    "leverage": leverage,
                    "init_margin": init_margin,
                    "adjust_position_mode": adjust_position_mode,
                    "symbol_settings": symbol_settings,
                    "adjust_position_percent": adjust_position_percent,
                    "adjust_position_time_interval": adjust_position_time_interval,
                    "sl_percent": sl_percent,
                    "tp_percent": tp_percent,
                    "trailing_stop_percent": trailing_stop_percent,
                }
            ),
        )

    async def get_fcombobot_detail(self, *, bot_id: str) -> dict[str, Any]:
        """
        Get Bot Detail. POST /v5/fcombobot/detail.

        Source: https://bybit-exchange.github.io/docs/v5/bot/futures-combo/get-detail

        Args:
            bot_id: Bot ID to query
        """
        return await self._native_private(
            "get_fcombobot_detail", self._native_params(**{"bot_id": bot_id})
        )

    async def get_fcombobot_getlimit(
        self,
        *,
        leverage: str,
        init_margin: str,
        adjust_position_mode: int,
        symbol_settings: list[Any],
        adjust_position_percent: str | None = None,
        adjust_position_time_interval: int | None = None,
        sl_percent: str | None = None,
        tp_percent: str | None = None,
        trailing_stop_percent: str | None = None,
        need_to_slippage: bool | None = None,
    ) -> dict[str, Any]:
        """
        Get Bot Parameter Limit. POST /v5/fcombobot/getlimit.

        Source: https://bybit-exchange.github.io/docs/v5/bot/futures-combo/get-limit

        Args:
            leverage: Position leverage multiplier (e.g. `"5"` means 5x). Must be >= 1
            init_margin: Initial investment in quote currency (decimal string)
            adjust_position_mode: Rebalancing trigger mode: `1` Time, `2` Percentage, `3` Time or %,
                `4` Manual, `5` On settings change, `6` On transfer
            symbol_settings: Per-symbol portfolio configuration
            adjust_position_percent: Rebalancing drift threshold as percentage
            adjust_position_time_interval: Rebalancing time interval in seconds
            sl_percent: Stop-loss as percentage (e.g. `"0.2"` means 20%)
            tp_percent: Take-profit as percentage (e.g. `"0.5"` means 50%)
            trailing_stop_percent: Trailing stop callback as percentage (e.g. `"0.05"` means 5%)
            need_to_slippage: Whether to include slippage calculation
        """
        return await self._native_private(
            "get_fcombobot_getlimit",
            self._native_params(
                **{
                    "leverage": leverage,
                    "init_margin": init_margin,
                    "adjust_position_mode": adjust_position_mode,
                    "symbol_settings": symbol_settings,
                    "adjust_position_percent": adjust_position_percent,
                    "adjust_position_time_interval": adjust_position_time_interval,
                    "sl_percent": sl_percent,
                    "tp_percent": tp_percent,
                    "trailing_stop_percent": trailing_stop_percent,
                    "need_to_slippage": need_to_slippage,
                }
            ),
        )

    async def close_fgridbot(self, *, bot_id: str) -> dict[str, Any]:
        """
        Close Grid Bot. POST /v5/fgridbot/close.

        Source: https://bybit-exchange.github.io/docs/v5/bot/futures-grid/close

        Args:
            bot_id: Bot ID to close, obtained from Create Futures Grid Bot response
        """
        return await self._native_private(
            "close_fgridbot", self._native_params(**{"bot_id": bot_id})
        )

    async def create_fgridbot(
        self,
        *,
        symbol: str,
        grid_mode: int,
        min_price: str,
        max_price: str,
        cell_number: int,
        leverage: str,
        grid_type: int,
        total_investment: str,
        take_profit_per: str | None = None,
        stop_loss_per: str | None = None,
        take_profit_price: str | None = None,
        stop_loss_price: str | None = None,
        tp_sl_type: int | None = None,
        entry_price: str | None = None,
        trailing_stop_per: str | None = None,
        move_up_price: str | None = None,
        move_down_price: str | None = None,
    ) -> dict[str, Any]:
        """
        Create Grid Bot. POST /v5/fgridbot/create.

        Source: https://bybit-exchange.github.io/docs/v5/bot/futures-grid/create

        Args:
            symbol: Trading pair symbol, uppercase only (e.g. `BTCUSDT`)
            grid_mode: Strategy direction: `1` Neutral, `2` Long, `3` Short
            min_price: Lower price bound of the grid range (decimal string)
            max_price: Upper price bound of the grid range (decimal string)
            cell_number: Number of grid levels, minimum 2
            leverage: Position leverage multiplier (e.g. `"5"` means 5x). Must be >= 1
            grid_type: Grid spacing type: `1` Arithmetic, `2` Geometric
            total_investment: Initial investment in quote currency (decimal string, e.g. `"1000"`
                for 1000 USDT)
            take_profit_per: Take-profit as percentage (e.g. `"0.2"` means 20%). Used when
                `tp_sl_type` includes percentage-based TP
            stop_loss_per: Stop-loss as percentage (e.g. `"0.1"` means 10%). Used when `tp_sl_type`
                includes percentage-based SL
            take_profit_price: Take-profit trigger price (decimal string). Used when `tp_sl_type`
                includes price-based TP
            stop_loss_price: Stop-loss trigger price (decimal string). Used when `tp_sl_type`
                includes price-based SL
            tp_sl_type: TP/SL trigger mode: `1` Both by %, `2` Both by price, `3` TP price+SL %, `4`
                TP %+SL price
            entry_price: Optional entry trigger price for delayed activation (decimal string)
            trailing_stop_per: Trailing stop exit as percentage (e.g. `"0.05"` means 5%)
            move_up_price: Move-up price for grid shifting, not applicable when "grid_type"=`2
            move_down_price: Move-down price for grid shifting, not applicable when "grid_type"=`2
        """
        return await self._native_private(
            "create_fgridbot",
            self._native_params(
                **{
                    "symbol": symbol,
                    "grid_mode": grid_mode,
                    "min_price": min_price,
                    "max_price": max_price,
                    "cell_number": cell_number,
                    "leverage": leverage,
                    "grid_type": grid_type,
                    "total_investment": total_investment,
                    "take_profit_per": take_profit_per,
                    "stop_loss_per": stop_loss_per,
                    "take_profit_price": take_profit_price,
                    "stop_loss_price": stop_loss_price,
                    "tp_sl_type": tp_sl_type,
                    "entry_price": entry_price,
                    "trailing_stop_per": trailing_stop_per,
                    "move_up_price": move_up_price,
                    "move_down_price": move_down_price,
                }
            ),
        )

    async def get_fgridbot_detail(self, *, bot_id: str) -> dict[str, Any]:
        """
        Get Grid Bot Detail. POST /v5/fgridbot/detail.

        Source: https://bybit-exchange.github.io/docs/v5/bot/futures-grid/get-detail

        Args:
            bot_id: Bot ID to query
        """
        return await self._native_private(
            "get_fgridbot_detail", self._native_params(**{"bot_id": bot_id})
        )

    async def request_fgridbot_validate(
        self,
        *,
        symbol: str,
        cell_number: int,
        min_price: str,
        max_price: str,
        leverage: str,
        grid_type: int,
        grid_mode: int,
        stop_loss_price: str | None = None,
        take_profit_price: str | None = None,
        tp_sl_type: int | None = None,
        entry_price: str | None = None,
        stop_loss_per: str | None = None,
        take_profit_per: str | None = None,
        trailing_stop_per: str | None = None,
        init_margin: str | None = None,
        move_up_price: str | None = None,
        move_down_price: str | None = None,
    ) -> dict[str, Any]:
        """
        Validate Grid Input. POST /v5/fgridbot/validate.

        Source: https://bybit-exchange.github.io/docs/v5/bot/futures-grid/validate-input

        Args:
            symbol: Trading pair symbol, uppercase only (e.g. `BTCUSDT`)
            cell_number: Number of grid levels, minimum 2
            min_price: Lower price bound of the grid range (decimal string)
            max_price: Upper price bound of the grid range (decimal string)
            leverage: Position leverage, must be >= 1 (e.g. `"5"`)
            grid_type: Grid spacing type: `1` Arithmetic, `2` Geometric
            grid_mode: Strategy direction: `1` Neutral, `2` Long, `3` Short
            stop_loss_price: Stop-loss trigger price (decimal string). Used when `tp_sl_type`
                includes price-based SL
            take_profit_price: Take-profit trigger price (decimal string). Used when `tp_sl_type`
                includes price-based TP
            tp_sl_type: TP/SL trigger mode: `1` Both %, `2` Both price, `3` TP price+SL %, `4` TP
                %+SL price
            entry_price: Entry trigger price for delayed activation (decimal string)
            stop_loss_per: Stop-loss as percentage (e.g. `"10"` means 10%). Used when `tp_sl_type`
                includes percentage-based SL
            take_profit_per: Take-profit as percentage (e.g. `"20"` means 20%). Used when
                `tp_sl_type` includes percentage-based TP
            trailing_stop_per: Trailing stop callback as percentage (e.g. `"5"` means 5%)
            init_margin: Initial margin amount in quote currency (decimal string)
            move_up_price: Move-up price for grid shifting
            move_down_price: Move-down price for grid shifting
        """
        return await self._native_private(
            "request_fgridbot_validate",
            self._native_params(
                **{
                    "symbol": symbol,
                    "cell_number": cell_number,
                    "min_price": min_price,
                    "max_price": max_price,
                    "leverage": leverage,
                    "grid_type": grid_type,
                    "grid_mode": grid_mode,
                    "stop_loss_price": stop_loss_price,
                    "take_profit_price": take_profit_price,
                    "tp_sl_type": tp_sl_type,
                    "entry_price": entry_price,
                    "stop_loss_per": stop_loss_per,
                    "take_profit_per": take_profit_per,
                    "trailing_stop_per": trailing_stop_per,
                    "init_margin": init_margin,
                    "move_up_price": move_up_price,
                    "move_down_price": move_down_price,
                }
            ),
        )

    async def close_fmartingalebot(self, *, bot_id: str) -> dict[str, Any]:
        """
        Close Martingale Bot. POST /v5/fmartingalebot/close.

        Source: https://bybit-exchange.github.io/docs/v5/bot/futures-martingale/close

        Args:
            bot_id: Bot ID to close, obtained from Create Futures Martingale Bot response
        """
        return await self._native_private(
            "close_fmartingalebot", self._native_params(**{"bot_id": bot_id})
        )

    async def create_fmartingalebot(
        self,
        *,
        symbol: str,
        martingale_mode: int,
        leverage: str,
        price_float_percent: str,
        add_position_percent: str,
        add_position_num: int,
        init_margin: str,
        round_tp_percent: str,
        auto_cycle_toggle: int | None = None,
        sl_percent: str | None = None,
        entry_price: str | None = None,
    ) -> dict[str, Any]:
        """
        Create Martingale Bot. POST /v5/fmartingalebot/create.

        Source: https://bybit-exchange.github.io/docs/v5/bot/futures-martingale/create

        Args:
            symbol: Trading pair symbol, uppercase only (e.g. `BTCUSDT`)
            martingale_mode: Strategy direction: `1` Long (buy dips), `2` Short (sell rallies)
            leverage: Position leverage multiplier (e.g. `"5"` means 5x). Must be >= 1
            price_float_percent: Price movement percentage to trigger a position add (e.g. `"0.015"`
                means add when price moves 1.5% against the position)
            add_position_percent: Position add scaling as percentage of base position size (e.g.
                `"1.1"` = 1.1x base; `"2"` = 2x base)
            add_position_num: Maximum number of position adds per round
            init_margin: Initial investment in quote currency (decimal string, e.g. `"1000"` for
                1000 USDT)
            round_tp_percent: Single round take-profit as percentage (e.g. `"0.03"` means close when
                profit reaches 3%)
            auto_cycle_toggle: Auto-cycle mode: `1` Enable (restart after TP), `2` Disable (stop
                after single TP)
            sl_percent: Stop-loss as percentage of total margin (e.g. `"0.2"` means close when loss
                reaches 20%). Leave empty if not set
            entry_price: Entry trigger price as absolute price (decimal string). Leave empty if not
                set
        """
        return await self._native_private(
            "create_fmartingalebot",
            self._native_params(
                **{
                    "symbol": symbol,
                    "martingale_mode": martingale_mode,
                    "leverage": leverage,
                    "price_float_percent": price_float_percent,
                    "add_position_percent": add_position_percent,
                    "add_position_num": add_position_num,
                    "init_margin": init_margin,
                    "round_tp_percent": round_tp_percent,
                    "auto_cycle_toggle": auto_cycle_toggle,
                    "sl_percent": sl_percent,
                    "entry_price": entry_price,
                }
            ),
        )

    async def get_fmartingalebot_detail(self, *, bot_id: str) -> dict[str, Any]:
        """
        Get Martingale Bot Detail. POST /v5/fmartingalebot/detail.

        Source: https://bybit-exchange.github.io/docs/v5/bot/futures-martingale/get-detail

        Args:
            bot_id: Bot ID to query
        """
        return await self._native_private(
            "get_fmartingalebot_detail", self._native_params(**{"bot_id": bot_id})
        )

    async def get_fmartingalebot_getlimit(
        self,
        *,
        symbol: str,
        martingale_mode: int,
        leverage: str,
        price_float_percent: str | None = None,
        add_position_percent: str | None = None,
        add_position_num: int | None = None,
        init_margin: str | None = None,
        round_tp_percent: str | None = None,
        sl_percent: str | None = None,
        entry_price: str | None = None,
        need_to_slippage: bool | None = None,
        auto_cycle_toggle: int | None = None,
    ) -> dict[str, Any]:
        """
        Get Bot Parameter Limit. POST /v5/fmartingalebot/getlimit.

        Source: https://bybit-exchange.github.io/docs/v5/bot/futures-martingale/get-limit

        Args:
            symbol: Trading pair symbol, uppercase only (e.g. `BTCUSDT`)
            martingale_mode: Strategy direction: `1` Long, `2` Short
            leverage: Position leverage multiplier (e.g. `"5"` means 5x). Must be >= 1
            price_float_percent: Price movement trigger as percentage (e.g. `"0.015"` means 1.5%)
            add_position_percent: Position add scaling as percentage of base position (e.g. `"1"` =
                1x)
            add_position_num: Maximum number of position adds per round
            init_margin: Initial investment in quote currency (decimal string)
            round_tp_percent: Single round take-profit as percentage (e.g. `"0.03"` means 3%)
            sl_percent: Stop-loss as percentage (e.g. `"0.2"` means 20%)
            entry_price: Entry trigger price (decimal string)
            need_to_slippage: Whether to include slippage calculation
            auto_cycle_toggle: Repeat cycles switch; official HTTP example uses integer 1.
        """
        return await self._native_private(
            "get_fmartingalebot_getlimit",
            self._native_params(
                **{
                    "symbol": symbol,
                    "martingale_mode": martingale_mode,
                    "leverage": leverage,
                    "price_float_percent": price_float_percent,
                    "add_position_percent": add_position_percent,
                    "add_position_num": add_position_num,
                    "init_margin": init_margin,
                    "round_tp_percent": round_tp_percent,
                    "sl_percent": sl_percent,
                    "entry_price": entry_price,
                    "need_to_slippage": need_to_slippage,
                    "auto_cycle_toggle": auto_cycle_toggle,
                }
            ),
        )

    async def request_grid_close_grid(self, *, grid_id: str, close_mode: str) -> dict[str, Any]:
        """
        Close Grid Bot. POST /v5/grid/close-grid.

        Official spec incomplete; not verified live. Uses documented grid_id/close_mode; the
        published example instead uses bot_id.
        Source: https://bybit-exchange.github.io/docs/v5/bot/spot-grid/close

        Args:
            grid_id: Grid bot ID to close, obtained from Create Spot Grid Bot response
            close_mode: Asset settlement mode: `2` Base token, `3` Quote token (e.g. USDT), `4` Base
                + Quote token
        """
        return await self._native_private(
            "request_grid_close_grid",
            self._native_params(**{"grid_id": grid_id, "close_mode": close_mode}),
        )

    async def request_grid_create_grid(
        self,
        *,
        symbol: str,
        max_price: str,
        min_price: str,
        cell_number: int,
        invest_mode: int | None = None,
        base_investment: str | None = None,
        quote_investment: str | None = None,
        entry_price: str | None = None,
        stop_loss_price: str | None = None,
        take_profit_price: str | None = None,
        ts_percent: str | None = None,
        enable_trailing: bool | None = None,
        limit_up_price: str | None = None,
    ) -> dict[str, Any]:
        """
        Create Grid Bot. POST /v5/grid/create-grid.

        Source: https://bybit-exchange.github.io/docs/v5/bot/spot-grid/create

        Args:
            symbol: Trading pair symbol, uppercase only (e.g. `BTCUSDT`)
            max_price: Upper bound of the grid price range (decimal string)
            min_price: Lower bound of the grid price range (decimal string)
            cell_number: Number of grid intervals, minimum 2
            invest_mode: Investment mode. `0`: Quote only (default), `1`: Base only, `2`: Base +
                Quote
            base_investment: Investment in base token (decimal string). **Required** when
                `invest_mode` is `1` or `2
            quote_investment: Investment in quote token (decimal string). **Required** when
                `invest_mode` is `0` or `2
            entry_price: Entry trigger price (decimal string). Bot activates when market price
                reaches this level
            stop_loss_price: Stop-loss trigger price (decimal string)
            take_profit_price: Take-profit trigger price (decimal string)
            ts_percent: Trailing stop callback ratio, range `[0, 0.99]` (e.g. `"0.05"` means 5%)
            enable_trailing: Enable grid trailing (auto-shift). Requires `cell_number >= 5`.
                Default: `false
            limit_up_price: Upper limit price for grid trailing (decimal string), usd when
                "enable_trailing"=`true
        """
        return await self._native_private(
            "request_grid_create_grid",
            self._native_params(
                **{
                    "symbol": symbol,
                    "max_price": max_price,
                    "min_price": min_price,
                    "cell_number": cell_number,
                    "invest_mode": invest_mode,
                    "base_investment": base_investment,
                    "quote_investment": quote_investment,
                    "entry_price": entry_price,
                    "stop_loss_price": stop_loss_price,
                    "take_profit_price": take_profit_price,
                    "ts_percent": ts_percent,
                    "enable_trailing": enable_trailing,
                    "limit_up_price": limit_up_price,
                }
            ),
        )

    async def get_grid_query_grid_detail(self, *, grid_id: str) -> dict[str, Any]:
        """
        Get Grid Bot Detail. POST /v5/grid/query-grid-detail.

        Source: https://bybit-exchange.github.io/docs/v5/bot/spot-grid/get-detail

        Args:
            grid_id: Grid bot ID to query
        """
        return await self._native_private(
            "get_grid_query_grid_detail", self._native_params(**{"grid_id": grid_id})
        )

    async def request_grid_validate_input(
        self,
        *,
        symbol: str,
        cell_number: int,
        min_price: str,
        max_price: str,
        invest_mode: int | None = None,
        base_investment: str | None = None,
        quote_investment: str | None = None,
        stop_loss: str | None = None,
        take_profit: str | None = None,
        entry_price: str | None = None,
        ts_percent: str | None = None,
        enable_trailing: bool | None = None,
        limit_up_price: str | None = None,
    ) -> dict[str, Any]:
        """
        Validate Grid Input. POST /v5/grid/validate-input.

        Source: https://bybit-exchange.github.io/docs/v5/bot/spot-grid/validate-input

        Args:
            symbol: Trading pair symbol, uppercase only (e.g. `BTCUSDT`)
            cell_number: Number of grid intervals, minimum 2
            min_price: Lower bound of the grid price range (decimal string)
            max_price: Upper bound of the grid price range. Must be greater than `min_price`
                (decimal string)
            invest_mode: Investment mode: `0` Quote only (default), `1` Base only, `2` Base + Quote
            base_investment: Investment in base token (decimal string). **Required** when
                `invest_mode` is `1` or `2
            quote_investment: Investment in quote token (decimal string). **Required** when
                `invest_mode` is `0` or `2
            stop_loss: Stop-loss as absolute price (decimal string)
            take_profit: Take-profit as absolute price (decimal string)
            entry_price: Entry trigger as absolute price (decimal string)
            ts_percent: Trailing stop callback ratio, range `[0, 0.99]` (e.g. `"0.05"` means 5%)
            enable_trailing: Whether to enable grid trailing. Requires `cell_number >= 5
            limit_up_price: Upper limit price for grid trailing (decimal string)
        """
        return await self._native_public(
            "request_grid_validate_input",
            self._native_params(
                **{
                    "symbol": symbol,
                    "cell_number": cell_number,
                    "min_price": min_price,
                    "max_price": max_price,
                    "invest_mode": invest_mode,
                    "base_investment": base_investment,
                    "quote_investment": quote_investment,
                    "stop_loss": stop_loss,
                    "take_profit": take_profit,
                    "entry_price": entry_price,
                    "ts_percent": ts_percent,
                    "enable_trailing": enable_trailing,
                    "limit_up_price": limit_up_price,
                }
            ),
        )
