"""Generated bybit card HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedCardHTTP(MarketHTTP):
    """Card API methods."""

    async def get_card_transaction_query_asset_records(
        self,
        *,
        status_code: str | None = None,
        limit: int | None = None,
        page: int | None = None,
        pan4: str | None = None,
        create_begin_time: int | None = None,
        create_end_time: int | None = None,
        merch_name: str | None = None,
        type_: str | None = None,
        txn_id: str | None = None,
        card_token: str | None = None,
        order_no: str | None = None,
    ) -> dict[str, Any]:
        """
        Query Asset Records. POST /v5/card/transaction/query-asset-records.

        Source: https://bybit-exchange.github.io/docs/v5/bybit-card/asset-records

        Args:
            status_code: Transaction status code. `0`: Pending, `1`: Cleared, `2`: Declined
            limit: Number of items per page. Default: `100`. Range: [`1`, `500`]
            page: Page number. Default: `1`. Min: `1
            pan4: Last 2/4 digits of card number, used to filter transactions of a specific card
            create_begin_time: Start time of transaction (Unix ms timestamp)
            create_end_time: End time of transaction (Unix ms timestamp)
            merch_name: Merchant name. Supports fuzzy search
            type_: Query type.`SIDE_QUERY_AUTH`: Authorization`SIDE_QUERY_FINANCIAL`: Clearing.
                Requires `txnId` and `orderNo`.`SIDE_QUERY_REFUND`: Refund. Requires `txnId` and
                `orderNo`.The following query types are available to all
                users:`SIDE_QUERY_AUTH_ALL`: All authorization
                transactions`SIDE_QUERY_AUTH_REVERSAL`: Authorization
                reversals`SIDE_QUERY_FINANCIAL_ALL`: All clearing
                transactions`SIDE_QUERY_FINANCIAL_REFUND`: Clearing refunds
            txn_id: Transaction ID. Exact match
            card_token: Card token, used to identify a specific card
            order_no: Order number. Exact match
        """
        return await self._native_private(
            "get_card_transaction_query_asset_records",
            self._native_params(
                **{
                    "statusCode": status_code,
                    "limit": limit,
                    "page": page,
                    "pan4": pan4,
                    "createBeginTime": create_begin_time,
                    "createEndTime": create_end_time,
                    "merchName": merch_name,
                    "type": type_,
                    "txnId": txn_id,
                    "cardToken": card_token,
                    "orderNo": order_no,
                }
            ),
        )

    async def get_card_reward_points_balance(self) -> dict[str, Any]:
        """
        Query Point Balance. POST /v5/card/reward/points/balance.

        Source: https://bybit-exchange.github.io/docs/v5/bybit-card/point/balance
        """
        return await self._native_private("get_card_reward_points_balance", [])

    async def get_card_reward_point_cashback_detail(self, *, biz_txn_id: str) -> dict[str, Any]:
        """
        Query Cashback Detail. POST /v5/card/reward/point/cashback/detail.

        Source: https://bybit-exchange.github.io/docs/v5/bybit-card/point/cashback-detail

        Args:
            biz_txn_id: Order ID
        """
        return await self._native_private(
            "get_card_reward_point_cashback_detail", self._native_params(**{"bizTxnId": biz_txn_id})
        )

    async def get_card_reward_mall_item_list(
        self,
        *,
        page_no: int | None = None,
        page_size: int | None = None,
        item_type: int | None = None,
        item_biz_type: int | None = None,
        order_by: int | None = None,
        asc: bool | None = None,
        source: int | None = None,
    ) -> dict[str, Any]:
        """
        Query Mall Item List. POST /v5/card/reward/mall/item/list.

        Source: https://bybit-exchange.github.io/docs/v5/bybit-card/point/item-list

        Args:
            page_no: Page number. Default: `1`. Min: `1
            page_size: Number of items per page. Default: `10`. Min: `1
            item_type: Item type. `1`: Virtual item, `2`: Physical item
            item_biz_type: Item sub-type. `1`: POINTS, `2`: CURRENCY
            order_by: Sort type. `1`: Priority, `2`: Listing time, `3`: Price
            asc: Whether to sort in ascending order
            source: Query source. `0`: Default, `1`: VIP item list
        """
        return await self._native_private(
            "get_card_reward_mall_item_list",
            self._native_params(
                **{
                    "pageNo": page_no,
                    "pageSize": page_size,
                    "itemType": item_type,
                    "itemBizType": item_biz_type,
                    "orderBy": order_by,
                    "asc": asc,
                    "source": source,
                }
            ),
        )

    async def get_card_reward_points_records(
        self,
        *,
        type_: str | None = None,
        page_size: int | None = None,
        page_no: int | None = None,
        start_time: int | None = None,
        end_time: int | None = None,
        out_order_id: str | None = None,
        biz_id: str | None = None,
        biz_txn_id: str | None = None,
        side: str | None = None,
    ) -> dict[str, Any]:
        """
        Query Point Records. POST /v5/card/reward/points/records.

        Source: https://bybit-exchange.github.io/docs/v5/bybit-card/point/records

        Args:
            type_: Point type filter
            page_size: Number of items per page. Default: `10`. Min: `1
            page_no: Page number. Default: `1`. Min: `1
            start_time: Start time (Unix timestamp)
            end_time: End time (Unix timestamp)
            out_order_id: External order ID
            biz_id: Point order ID
            biz_txn_id: consumeIdLifecycle
            side: Point direction. `1`: Earn points, `2`: Deduct points
        """
        return await self._native_private(
            "get_card_reward_points_records",
            self._native_params(
                **{
                    "type": type_,
                    "pageSize": page_size,
                    "pageNo": page_no,
                    "startTime": start_time,
                    "endTime": end_time,
                    "outOrderId": out_order_id,
                    "bizId": biz_id,
                    "bizTxnId": biz_txn_id,
                    "side": side,
                }
            ),
        )

    async def get_card_reward_points_tier(self) -> dict[str, Any]:
        """
        Query Tier Info. POST /v5/card/reward/points/tier.

        Source: https://bybit-exchange.github.io/docs/v5/bybit-card/point/tier
        """
        return await self._native_private("get_card_reward_points_tier", [])
