"""Generated bybit event HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedEventHTTP(MarketHTTP):
    """Event API methods."""

    async def get_event_instruments_info(
        self,
        *,
        symbol: str | None = None,
        status: str | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """
        Get Instrument Info. GET /v5/event/instruments-info.

        Source: https://bybit-exchange.github.io/docs/v5/event/market/instrument-info

        Args:
            symbol: Symbol name, e.g. `ETHUSDT-28AUG26-2450-2570-OUT
            status: PreLaunch`, `Trading`, `Delivering`, `Closed
            limit: Items per page. Default: `50`, range: [`1`, `100`]
            cursor: Pagination cursor. Use `nextPageCursor` from the previous response
        """
        return await self._native_public(
            "get_event_instruments_info",
            self._native_params(
                **{"symbol": symbol, "status": status, "limit": limit, "cursor": cursor}
            ),
        )

    async def get_event_orderbook(self, *, symbol: str) -> dict[str, Any]:
        """
        Get Orderbook. GET /v5/event/orderbook.

        Source: https://bybit-exchange.github.io/docs/v5/event/market/orderbook

        Args:
            symbol: Symbol name, e.g. `ETHUSDT-28AUG26-2450-2570-OUT
        """
        return await self._native_public(
            "get_event_orderbook", self._native_params(**{"symbol": symbol})
        )

    async def cancel_event_quote(
        self, *, order_link_id: str | None = None, order_id: str | None = None
    ) -> dict[str, Any]:
        """
        Cancel Quote. POST /v5/event/cancel.

        Source: https://bybit-exchange.github.io/docs/v5/event/trade/cancel-quote

        Args:
            order_link_id: User-defined order ID (Quote ID)
            order_id: Order ID
        """
        return await self._native_private(
            "cancel_event_quote",
            self._native_params(**{"orderLinkId": order_link_id, "orderId": order_id}),
        )

    async def get_event_trades(
        self,
        *,
        symbol: str,
        order_id: str | None = None,
        order_link_id: str | None = None,
        start_time: int | None = None,
        end_time: int | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """
        Get Event Contract Trade History. GET /v5/event/trades.

        Source: https://bybit-exchange.github.io/docs/v5/event/trade/execution

        Args:
            symbol: Symbol name, e.g. `ETHUSDT-28AUG26-2450-2570-OUT
            order_id: Order ID filter
            order_link_id: User-defined order ID
            start_time: Start time in milliseconds. Default: 7 days ago
            end_time: End time in milliseconds. Default: now
            limit: Number of items per page. Default: `50`, Range: [`1`, `100`]
            cursor: Pagination cursor
        """
        return await self._native_private(
            "get_event_trades",
            self._native_params(
                **{
                    "symbol": symbol,
                    "orderId": order_id,
                    "orderLinkId": order_link_id,
                    "startTime": start_time,
                    "endTime": end_time,
                    "limit": limit,
                    "cursor": cursor,
                }
            ),
        )

    async def get_event_order_realtime(
        self,
        *,
        symbol: str | None = None,
        order_id: str | None = None,
        order_link_id: str | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """
        Get Event Contract Active Orders. GET /v5/event/order-realtime.

        Source: https://bybit-exchange.github.io/docs/v5/event/trade/open-order

        Args:
            symbol: Symbol name, e.g. `ETHUSDT-28AUG26-2450-2570-OUT
            order_id: Order ID. If both `orderId` and `orderLinkId` are passed, `orderId` takes
                priority
            order_link_id: User-defined order ID
            limit: Number of items per page. Default: `20`, Range: [`1`, `50`]
            cursor: Pagination cursor. Use `nextPageCursor` from the response to retrieve the next
                page
        """
        return await self._native_private(
            "get_event_order_realtime",
            self._native_params(
                **{
                    "symbol": symbol,
                    "orderId": order_id,
                    "orderLinkId": order_link_id,
                    "limit": limit,
                    "cursor": cursor,
                }
            ),
        )

    async def get_event_order_list(
        self,
        *,
        symbol: str | None = None,
        order_id: str | None = None,
        order_link_id: str | None = None,
        start_time: int | None = None,
        end_time: int | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """
        Get Event Contract Order History. GET /v5/event/order-list.

        Source: https://bybit-exchange.github.io/docs/v5/event/trade/order-list

        Args:
            symbol: Symbol name, e.g. `ETHUSDT-28AUG26-2450-2570-OUT
            order_id: Order ID
            order_link_id: User-defined order ID
            start_time: Start time in milliseconds. Default: 7 days ago
            end_time: End time in milliseconds. Default: now
            limit: Number of items per page. Default: `50`, Range: [`1`, `100`]
            cursor: Pagination cursor
        """
        return await self._native_private(
            "get_event_order_list",
            self._native_params(
                **{
                    "symbol": symbol,
                    "orderId": order_id,
                    "orderLinkId": order_link_id,
                    "startTime": start_time,
                    "endTime": end_time,
                    "limit": limit,
                    "cursor": cursor,
                }
            ),
        )

    async def get_event_positions(
        self,
        *,
        symbol: str | None = None,
        base_coin: str | None = None,
        settle_coin: str | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """
        Get Event Contract Position Info. GET /v5/event/positions.

        Source: https://bybit-exchange.github.io/docs/v5/event/trade/position

        Args:
            symbol: Symbol name, e.g. `ETHUSDT-28AUG26-2450-2570-OUT`. If not passed, returns all
                Event Contract positions
            base_coin: Base coin filter, e.g. `BTC
            settle_coin: Settle coin filter, e.g. `USDT
            limit: Number of items per page. Default: `20`, Range: [`1`, `50`]
            cursor: Pagination cursor. Use `nextPageCursor` from the response to retrieve the next
                page
        """
        return await self._native_private(
            "get_event_positions",
            self._native_params(
                **{
                    "symbol": symbol,
                    "baseCoin": base_coin,
                    "settleCoin": settle_coin,
                    "limit": limit,
                    "cursor": cursor,
                }
            ),
        )

    async def get_event_settlements(
        self,
        *,
        symbol: str,
        order_id: str | None = None,
        start_time: int | None = None,
        end_time: int | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """
        Get Event Contract Settlement Records. GET /v5/event/settlements.

        Source: https://bybit-exchange.github.io/docs/v5/event/trade/settlement

        Args:
            symbol: Symbol name, e.g. `ETHUSDT-28AUG26-2450-2570-OUT
            order_id: Order ID filter
            start_time: Start time in milliseconds. Default: 7 days ago
            end_time: End time in milliseconds. Default: now
            limit: Number of items per page. Default: `50`, Range: [`1`, `100`]
            cursor: Pagination cursor
        """
        return await self._native_private(
            "get_event_settlements",
            self._native_params(
                **{
                    "symbol": symbol,
                    "orderId": order_id,
                    "startTime": start_time,
                    "endTime": end_time,
                    "limit": limit,
                    "cursor": cursor,
                }
            ),
        )

    async def submit_event_quote(
        self, *, symbol: str, order_link_id: str, gross_payout_ratio: str, amount: str
    ) -> dict[str, Any]:
        """
        Submit Quote. POST /v5/event/quotes.

        Source: https://bybit-exchange.github.io/docs/v5/event/trade/submit-quote

        Args:
            symbol: Symbol name, e.g. `ETHUSDT-28AUG26-2450-2570-OUT
            order_link_id: User-defined order ID
            gross_payout_ratio: Gross payout ratio reported by the institution
            amount: Amount for this quote (settle coin)
        """
        return await self._native_private(
            "submit_event_quote",
            self._native_params(
                **{
                    "symbol": symbol,
                    "orderLinkId": order_link_id,
                    "grossPayoutRatio": gross_payout_ratio,
                    "amount": amount,
                }
            ),
        )
