"""Generated bybit leveraged tokens HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedLeveragedTokensHTTP(MarketHTTP):
    """Leveraged tokens API methods."""

    async def get_spot_lever_token_info(self, *, lt_coin: str | None = None) -> dict[str, Any]:
        """
        Get Leverage Token Info. GET /v5/spot-lever-token/info.

        Source: https://bybit-exchange.github.io/docs/v5/lt/leverage-token-info

        Args:
            lt_coin: Abbreviation of the LT, such as `BTC3L
        """
        return await self._native_public(
            "get_spot_lever_token_info", self._native_params(**{"ltCoin": lt_coin})
        )
