"""Generated bybit loan HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedLoanHTTP(MarketHTTP):
    """Loan API methods."""

    async def request_ins_loan_association_uid(self, *, uid: str, operate: str) -> dict[str, Any]:
        """
        Bind Or Unbind UID. POST /v5/ins-loan/association-uid.

        Source: https://bybit-exchange.github.io/docs/v5/otc/bind-uid

        Args:
            uid: UID Binda) the key used must be from one of UIDs in the risk unit; b) input UID
                must not have an INS loanUnbinda) the key used must be from one of UIDs in the risk
                unit; b) input UID cannot be the same as the UID used to access the API
            operate: 0`: bind, `1`: unbind
        """
        return await self._native_private(
            "request_ins_loan_association_uid",
            self._native_params(**{"uid": uid, "operate": operate}),
        )

    async def get_ins_loan_coin_delta_amount(self, *, coin: str | None = None) -> dict[str, Any]:
        """
        Get Coin Delta Amount. GET /v5/ins-loan/coin-delta-amount.

        Source: https://bybit-exchange.github.io/docs/v5/otc/coin-delta-amount

        Args:
            coin: Coin name, uppercase only. e.g. `BTC`. If not passed, returns all coins
        """
        return await self._native_private(
            "get_ins_loan_coin_delta_amount", self._native_params(**{"coin": coin})
        )

    async def get_ins_loan_delay_liq_status(self) -> dict[str, Any]:
        """
        Get Delay Liquidation Status. GET /v5/ins-loan/delay-liq-status.

        Source: https://bybit-exchange.github.io/docs/v5/otc/delay-liq-status
        """
        return await self._native_private("get_ins_loan_delay_liq_status", [])

    async def get_ins_loan_loan_order(
        self,
        *,
        order_id: str | None = None,
        start_time: int | None = None,
        end_time: int | None = None,
        limit: int | None = None,
    ) -> dict[str, Any]:
        """
        Get Loan Orders. GET /v5/ins-loan/loan-order.

        Source: https://bybit-exchange.github.io/docs/v5/otc/loan-info

        Args:
            order_id: Loan order ID. If not passed, returns all orders sorted by `loanTime` in
                descending order
            start_time: The start timestamp (ms)
            end_time: The end timestamp (ms)
            limit: Limit for data size. [`1`, `100`], Default: `10
        """
        return await self._native_private(
            "get_ins_loan_loan_order",
            self._native_params(
                **{
                    "orderId": order_id,
                    "startTime": start_time,
                    "endTime": end_time,
                    "limit": limit,
                }
            ),
        )

    async def get_ins_loan_product_infos(self, *, product_id: str | None = None) -> dict[str, Any]:
        """
        Get Product Info. GET /v5/ins-loan/product-infos.

        Source: https://bybit-exchange.github.io/docs/v5/otc/margin-product-info

        Args:
            product_id: Product ID. If not passed, returns all products
        """
        return await self._native_public(
            "get_ins_loan_product_infos", self._native_params(**{"productId": product_id})
        )

    async def get_ins_loan_repaid_history(
        self,
        *,
        start_time: int | None = None,
        end_time: int | None = None,
        limit: int | None = None,
    ) -> dict[str, Any]:
        """
        Get Repayment Orders. GET /v5/ins-loan/repaid-history.

        Source: https://bybit-exchange.github.io/docs/v5/otc/repay-info

        Args:
            start_time: The start timestamp (ms)
            end_time: The end timestamp (ms)
            limit: Limit for data size. [`1`, `100`]. Default: `100
        """
        return await self._native_private(
            "get_ins_loan_repaid_history",
            self._native_params(**{"startTime": start_time, "endTime": end_time, "limit": limit}),
        )

    async def request_ins_loan_repay_loan(self, *, token: str, quantity: str) -> dict[str, Any]:
        """
        Repay. POST /v5/ins-loan/repay-loan.

        Source: https://bybit-exchange.github.io/docs/v5/otc/repay

        Args:
            token: Coin name
            quantity: The qty to be repaid
        """
        return await self._native_private(
            "request_ins_loan_repay_loan",
            self._native_params(**{"token": token, "quantity": quantity}),
        )
