"""Generated bybit pwm HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedPwmHTTP(MarketHTTP):
    """Pwm API methods."""

    async def get_earn_pwm_asset_manager_all_funds(
        self,
        *,
        coin: str | None = None,
        fund_id: str | None = None,
        status: str | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """
        Get All Funds. GET /v5/earn/pwm/asset-manager/all-funds.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/asset-manager/all-funds

        Args:
            coin: Filter by coin
            fund_id: Filter by fund ID. Only funds created by the institution via Open API can be
                queried
            status: Filter by status: `PendingSubscribe` / `Active` / `Closing` / `Closed
            limit: Page size. Default: `20`, max: `50
            cursor: Pagination cursor (uses fund ID as cursor)
        """
        return await self._native_private(
            "get_earn_pwm_asset_manager_all_funds",
            self._native_params(
                **{
                    "coin": coin,
                    "fundId": fund_id,
                    "status": status,
                    "limit": limit,
                    "cursor": cursor,
                }
            ),
        )

    async def get_earn_pwm_asset_manager_all_order(
        self,
        *,
        fund_id: str | None = None,
        order_type: str | None = None,
        status: str | None = None,
        start_time: int | None = None,
        end_time: int | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """
        Get All Fund Orders. GET /v5/earn/pwm/asset-manager/all-order.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/asset-manager/all-order

        Args:
            fund_id: Filter by fund ID. Returns orders for all managed funds if omitted
            order_type: Order type filter: `Subscribe` / `Redeem`. Returns all if omitted
            status: Order status filter: `Pending Review` / `Processing` / `Completed` / `Rejected`
                / `Failed`. Returns all if omitted
            start_time: Start time in milliseconds. See time range rules below
            end_time: End time in milliseconds. See time range rules below
            limit: Page size. Default: `20`, max: `50
            cursor: Pagination cursor (uses order `orderId` as cursor)
        """
        return await self._native_private(
            "get_earn_pwm_asset_manager_all_order",
            self._native_params(
                **{
                    "fundId": fund_id,
                    "orderType": order_type,
                    "status": status,
                    "startTime": start_time,
                    "endTime": end_time,
                    "limit": limit,
                    "cursor": cursor,
                }
            ),
        )

    async def request_earn_pwm_asset_manager_create_fund(
        self,
        *,
        fund_name: str,
        coin: str,
        profit_share_rate: str,
        management_fee_rate: str,
        fund_introduction: str | None = None,
        req_link_id: str,
    ) -> dict[str, Any]:
        """
        Create Fund (Pending Subscription). POST /v5/earn/pwm/asset-manager/create-fund.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/asset-manager/create-fund

        Args:
            fund_name: Fund name, 1–50 characters
            coin: Base coin. Supported values: `BTC`, `ETH`, `USDT`, `USDC`, `SOL`, `MNT`, `XRP
            profit_share_rate: High-watermark profit sharing rate (%), range: 0–100
            management_fee_rate: Management fee rate (annualized %), range: 0–100
            fund_introduction: Fund introduction ID (must be in the institution's allowed list)
            req_link_id: User-defined request ID, max 36 characters, used for idempotency
        """
        return await self._native_private(
            "request_earn_pwm_asset_manager_create_fund",
            self._native_params(
                **{
                    "fundName": fund_name,
                    "coin": coin,
                    "profitShareRate": profit_share_rate,
                    "managementFeeRate": management_fee_rate,
                    "fundIntroduction": fund_introduction,
                    "reqLinkId": req_link_id,
                }
            ),
        )

    async def request_earn_pwm_asset_manager_create_investment_plan(
        self,
        *,
        account_uid: str,
        plan_name: str,
        plan_type: str,
        investment_distribution: list[Any],
        req_link_id: str,
    ) -> dict[str, Any]:
        """
        Create Investment Plan. POST /v5/earn/pwm/asset-manager/create-investment-plan.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/asset-manager/create-investment-plan

        Args:
            account_uid: Target user UID
            plan_name: Investment plan name, max 50 characters
            plan_type: Plan type: `stable` / `advanced
            investment_distribution: Fund configuration list. At least 1 fund required
            req_link_id: User-defined request ID, max 36 characters, used for idempotency
        """
        return await self._native_private(
            "request_earn_pwm_asset_manager_create_investment_plan",
            self._native_params(
                **{
                    "accountUid": account_uid,
                    "planName": plan_name,
                    "planType": plan_type,
                    "investmentDistribution": investment_distribution,
                    "reqLinkId": req_link_id,
                }
            ),
        )

    async def request_earn_pwm_asset_manager_create_sub_account(
        self, *, fund_id: str, req_link_id: str
    ) -> dict[str, Any]:
        """
        Create Fund Sub-Account. POST /v5/earn/pwm/asset-manager/create-sub-account.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/asset-manager/create-sub-account

        Args:
            fund_id: Fund ID
            req_link_id: User-defined request ID, used to prevent duplicate creation
        """
        return await self._native_private(
            "request_earn_pwm_asset_manager_create_sub_account",
            self._native_params(**{"fundId": fund_id, "reqLinkId": req_link_id}),
        )

    async def get_earn_pwm_asset_manager_get_investment_plan(
        self,
        *,
        plan_id: str | None = None,
        status: str | None = None,
        subscription_uid: str | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """
        Get Investment Plans. GET /v5/earn/pwm/asset-manager/get-investment-plan.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/asset-manager/get-investment-plan

        Args:
            plan_id: Investment plan ID. Returns all plans if omitted. Only plans created by the
                institution via Open API can be queried
            status: Filter by status: `PendingSubscription` / `Active` / `Closed` / `Deleted`.
                Returns all if omitted
            subscription_uid: UID of the user who subscribed to the investment plan
            limit: Page size. Default: `20`, max: `50
            cursor: Pagination cursor
        """
        return await self._native_private(
            "get_earn_pwm_asset_manager_get_investment_plan",
            self._native_params(
                **{
                    "planId": plan_id,
                    "status": status,
                    "subscriptionUid": subscription_uid,
                    "limit": limit,
                    "cursor": cursor,
                }
            ),
        )

    async def request_earn_pwm_asset_manager_manage_investment_plan(
        self,
        *,
        plan_id: str,
        update_status: str | None = None,
        update_funds: list[Any] | None = None,
        req_link_id: str,
    ) -> dict[str, Any]:
        """
        Manage Investment Plan. POST /v5/earn/pwm/asset-manager/manage-investment-plan.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/asset-manager/manage-investment-plan

        Args:
            plan_id: Investment plan ID
            update_status: Update plan status. Options: `Closed` / `Deleted`. Status is unchanged if
                omitted
            update_funds: Fund list to update. If a matching `fundId` exists, the amount is updated;
                otherwise a new fund is added. Max 10 entries. Returns an error if duplicate
                `fundId` entries are present
            req_link_id: User-defined request ID, max 36 characters, used for idempotency
        """
        return await self._native_private(
            "request_earn_pwm_asset_manager_manage_investment_plan",
            self._native_params(
                **{
                    "planId": plan_id,
                    "updateStatus": update_status,
                    "updateFunds": update_funds,
                    "reqLinkId": req_link_id,
                }
            ),
        )

    async def request_earn_pwm_asset_manager_manage_order(
        self, *, order_id: str, action: str, req_link_id: str
    ) -> dict[str, Any]:
        """
        Manage Order. POST /v5/earn/pwm/asset-manager/manage-order.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/asset-manager/manage-order

        Args:
            order_id: Order ID. Must be in `Pending Review` status
            action: Action to perform: `approve` / `reject
            req_link_id: User-defined request ID, max 36 characters, used for idempotency
        """
        return await self._native_private(
            "request_earn_pwm_asset_manager_manage_order",
            self._native_params(
                **{"orderId": order_id, "action": action, "reqLinkId": req_link_id}
            ),
        )

    async def request_earn_pwm_asset_manager_settle_profit(
        self, *, fund_id: str, req_link_id: str
    ) -> dict[str, Any]:
        """
        Settle Fund Profit. POST /v5/earn/pwm/asset-manager/settle-profit.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/asset-manager/settle-profit

        Args:
            fund_id: Fund ID
            req_link_id: User-defined request ID, max 36 characters, used for idempotency
        """
        return await self._native_private(
            "request_earn_pwm_asset_manager_settle_profit",
            self._native_params(**{"fundId": fund_id, "reqLinkId": req_link_id}),
        )

    async def create_earn_pwm_customize_plan(
        self, *, account_type: str | None = None, products: list[Any]
    ) -> dict[str, Any]:
        """
        Create Customize Investment Plan. POST /v5/earn/pwm/customize-plan/create.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/customize-plan/create

        Args:
            account_type: Source account type. Default: `FUND
            products: Product configuration list. At least 1 item required
        """
        return await self._native_private(
            "create_earn_pwm_customize_plan",
            self._native_params(**{"accountType": account_type, "products": products}),
        )

    async def get_earn_pwm_customize_plan_product(self) -> dict[str, Any]:
        """
        Get Subscribable Product Info. GET /v5/earn/pwm/customize-plan/product.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/customize-plan/product
        """
        return await self._native_public("get_earn_pwm_customize_plan_product", [])

    async def get_earn_pwm_investment_plan_all(
        self,
        *,
        plan_id: str | None = None,
        status: str | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """
        Get All Investment Plans. GET /v5/earn/pwm/investment-plan/all.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/investment-plan/all

        Args:
            plan_id: Investment plan ID. Returns all plans if omitted
            status: Filter by status: `PendingSubscription` / `Active` / `Closed`. Returns all if
                omitted
            limit: Page size. Default: `20`, max: `50
            cursor: Pagination cursor
        """
        return await self._native_private(
            "get_earn_pwm_investment_plan_all",
            self._native_params(
                **{"planId": plan_id, "status": status, "limit": limit, "cursor": cursor}
            ),
        )

    async def get_earn_pwm_investment_plan_asset_trend(
        self, *, plan_id: str, start_time: int | None = None, end_time: int | None = None
    ) -> dict[str, Any]:
        """
        Get Asset Trend. GET /v5/earn/pwm/investment-plan/asset-trend.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/investment-plan/asset-trend

        Args:
            plan_id: Investment plan ID
            start_time: Start timestamp (ms). Default: current time minus 7 days
            end_time: End timestamp (ms). Default: current time
        """
        return await self._native_private(
            "get_earn_pwm_investment_plan_asset_trend",
            self._native_params(
                **{"planId": plan_id, "startTime": start_time, "endTime": end_time}
            ),
        )

    async def claim_earn_pwm_investment_plan(
        self, *, plan_id: str, to_account_type: str | None = None, order_link_id: str
    ) -> dict[str, Any]:
        """
        Claim Withdrawable Funds. POST /v5/earn/pwm/investment-plan/claim.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/investment-plan/claim

        Args:
            plan_id: Investment plan ID. Must be in `Active` status
            to_account_type: Target account type. Default: `FUND
            order_link_id: User-defined order ID, max 36 characters, used for idempotency
        """
        return await self._native_private(
            "claim_earn_pwm_investment_plan",
            self._native_params(
                **{
                    "planId": plan_id,
                    "toAccountType": to_account_type,
                    "orderLinkId": order_link_id,
                }
            ),
        )

    async def get_earn_pwm_investment_plan_detail(self, *, plan_id: str) -> dict[str, Any]:
        """
        Get Investment Plan Detail. GET /v5/earn/pwm/investment-plan/detail.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/investment-plan/detail

        Args:
            plan_id: Investment plan ID. Must be in `Active` or `Closed` status
        """
        return await self._native_private(
            "get_earn_pwm_investment_plan_detail", self._native_params(**{"planId": plan_id})
        )

    async def get_earn_pwm_investment_plan_fund_nav(
        self, *, fund_id: str, start_time: int | None = None, end_time: int | None = None
    ) -> dict[str, Any]:
        """
        Get Fund Historical NAV. GET /v5/earn/pwm/investment-plan/fund-nav.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/investment-plan/fund-nav

        Args:
            fund_id: Fund ID
            start_time: Start timestamp (ms). Default: current time minus 7 days
            end_time: End timestamp (ms). Default: current time
        """
        return await self._native_private(
            "get_earn_pwm_investment_plan_fund_nav",
            self._native_params(
                **{"fundId": fund_id, "startTime": start_time, "endTime": end_time}
            ),
        )

    async def request_earn_pwm_investment_plan_invest_more(
        self,
        *,
        plan_id: str,
        account_type: str | None = None,
        category: str,
        product_id: str,
        amount: str,
        order_link_id: str,
    ) -> dict[str, Any]:
        """
        Invest More. POST /v5/earn/pwm/investment-plan/invest-more.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/investment-plan/invest-more

        Args:
            plan_id: Investment plan ID. Must be in `Active` status
            account_type: Source account type. Default: `FUND
            category: Product type
            product_id: Product ID
            amount: Additional investment amount (base coin)
            order_link_id: User-defined order ID, max 36 characters, used for idempotency
        """
        return await self._native_private(
            "request_earn_pwm_investment_plan_invest_more",
            self._native_params(
                **{
                    "planId": plan_id,
                    "accountType": account_type,
                    "category": category,
                    "productId": product_id,
                    "amount": amount,
                    "orderLinkId": order_link_id,
                }
            ),
        )

    async def get_earn_pwm_investment_plan_new_plan(self, *, plan_id: str) -> dict[str, Any]:
        """
        Get Pending Investment Plan Detail. GET /v5/earn/pwm/investment-plan/new-plan.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/investment-plan/new-plan

        Args:
            plan_id: Investment plan ID. Must be in `PendingSubscription` status
        """
        return await self._native_private(
            "get_earn_pwm_investment_plan_new_plan", self._native_params(**{"planId": plan_id})
        )

    async def get_earn_pwm_investment_plan_order(
        self,
        *,
        plan_id: str | None = None,
        category: str | None = None,
        type_: str | None = None,
        status: str | None = None,
        start_time: str | None = None,
        end_time: str | None = None,
        limit: int | None = None,
        cursor: str | None = None,
        order_link_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Get Investment Plan Orders. GET /v5/earn/pwm/investment-plan/order.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/investment-plan/order

        Args:
            plan_id: Investment plan ID. Returns orders for all plans if omitted
            category: Product type filter: `flexibleSavings` / `fundPool` / `fundPoolPremium` /
                `equityFund` / `onchainEarn`. Returns all if omitted
            type_: Order type filter: `Subscribe` / `Redeem`. Returns all if omitted
            status: Order status filter: `Completed` / `Pending` / `Failed`. Returns all if omitted
            start_time: Start time in milliseconds. No lower limit if omitted
            end_time: End time in milliseconds. Defaults to current time if omitted
            limit: Page size. Default: `20`, max: `50
            cursor: Pagination cursor
            order_link_id: User-defined order ID, max 36 characters
        """
        return await self._native_private(
            "get_earn_pwm_investment_plan_order",
            self._native_params(
                **{
                    "planId": plan_id,
                    "category": category,
                    "type": type_,
                    "status": status,
                    "startTime": start_time,
                    "endTime": end_time,
                    "limit": limit,
                    "cursor": cursor,
                    "orderLinkId": order_link_id,
                }
            ),
        )

    async def redeem_earn_pwm_investment_plan(
        self,
        *,
        plan_id: str,
        category: str,
        product_id: str,
        shares: str | None = None,
        amount: str | None = None,
        order_link_id: str,
        position_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Redeem. POST /v5/earn/pwm/investment-plan/redeem.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/investment-plan/redeem

        Args:
            plan_id: Investment plan ID
            category: Product type
            product_id: Product ID. Pass `fundId` for fund products
            shares: Number of shares to redeem. Required for fund products
            amount: Redemption amount. Required for non-fund products
            order_link_id: User-defined order ID, max 36 characters, used for idempotency
            position_id: Position ID to redeem. Required for FundPool and On-chain Earn products
        """
        return await self._native_private(
            "redeem_earn_pwm_investment_plan",
            self._native_params(
                **{
                    "planId": plan_id,
                    "category": category,
                    "productId": product_id,
                    "shares": shares,
                    "amount": amount,
                    "orderLinkId": order_link_id,
                    "positionId": position_id,
                }
            ),
        )

    async def subscribe_earn_pwm_investment_plan(
        self, *, plan_id: str, account_type: str | None = None, order_link_id: str
    ) -> dict[str, Any]:
        """
        Subscribe Investment Plan. POST /v5/earn/pwm/investment-plan/subscribe.

        Source: https://bybit-exchange.github.io/docs/v5/finance/pwm/investment-plan/subscribe

        Args:
            plan_id: Investment plan ID. Must be in `PendingSubscription` status
            account_type: Source account type. Default: `FUND
            order_link_id: User-defined order ID, max 36 characters, used for idempotency
        """
        return await self._native_private(
            "subscribe_earn_pwm_investment_plan",
            self._native_params(
                **{"planId": plan_id, "accountType": account_type, "orderLinkId": order_link_id}
            ),
        )
