"""Generated bybit stocks HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedStocksHTTP(MarketHTTP):
    """Stocks API methods."""

    async def cancel_stock_order(self, *, order_no: str) -> dict[str, Any]:
        """
        Cancel Stock Order. POST /v5/rwa/stocks/order/cancel.

        Source: https://bybit-exchange.github.io/docs/v5/stocks/cancel-order

        Args:
            order_no: System order number
        """
        return await self._native_private(
            "cancel_stock_order", self._native_params(**{"orderNo": order_no})
        )

    async def get_rwa_stocks_convert_detail(
        self, *, order_no: str | None = None, request_id: str | None = None
    ) -> dict[str, Any]:
        """
        Get Convert Detail. GET /v5/rwa/stocks/convert/detail.

        Source: https://bybit-exchange.github.io/docs/v5/stocks/convert-detail

        Args:
            order_no: Convert order number. Either `orderNo` or `requestId` is **required
            request_id: Idempotency key used at submission. Either `orderNo` or `requestId` is
                **required
        """
        return await self._native_private(
            "get_rwa_stocks_convert_detail",
            self._native_params(**{"orderNo": order_no, "requestId": request_id}),
        )

    async def get_rwa_stocks_convert_list(self, *, symbol: str | None = None) -> dict[str, Any]:
        """
        Get Convert List. GET /v5/rwa/stocks/convert/list.

        Source: https://bybit-exchange.github.io/docs/v5/stocks/convert-list

        Args:
            symbol: Filter by symbol, e.g. `AAPL-US`. Returns all supported symbols if omitted
        """
        return await self._native_private(
            "get_rwa_stocks_convert_list", self._native_params(**{"symbol": symbol})
        )

    async def submit_rwa_stocks_convert(
        self,
        *,
        convert_type: str,
        symbol: str,
        input_amount: str,
        front_multiplier: str,
        account_type: str | None = None,
        request_id: str,
        contract_addr: str | None = None,
        flow: str,
        burn_scene: str | None = None,
    ) -> dict[str, Any]:
        """
        Submit Convert. POST /v5/rwa/stocks/convert/submit.

        Source: https://bybit-exchange.github.io/docs/v5/stocks/convert-submit

        Args:
            convert_type: Direction. `MINT`, `REDEEM
            symbol: Underlying stock symbol, e.g. `AAPL-US
            input_amount: Input amount. Number of underlying shares when `MINT`; number of Tokens
                when `REDEEM
            front_multiplier: Conversion ratio from the front-end snapshot
            account_type: Only effective when `REDEEM`. `all` (default), `uta`, `fund
            request_id: Idempotency key. Length ≤ 36. Alphanumeric plus `-` `_`. Must be unique
                within 24 hours for the same MM account
            contract_addr: Token receive address when `MINT`; Token provide address when `REDEEM`.
                **Do not send when `flow=DEX` and `burnScene=NDP
            flow: CEX`, `DEX`. `MINT` flows are identical across CEX/DEX (mint to the specified
                address). `REDEEM` (burn) flows differ between CEX and DEX
            burn_scene: Scene for **DEX `REDEEM` (burn)**: `DEP` (through Bybit main site), `NDP`
                (not through Bybit main site)
        """
        return await self._native_private(
            "submit_rwa_stocks_convert",
            self._native_params(
                **{
                    "convertType": convert_type,
                    "symbol": symbol,
                    "inputAmount": input_amount,
                    "frontMultiplier": front_multiplier,
                    "accountType": account_type,
                    "requestId": request_id,
                    "contractAddr": contract_addr,
                    "flow": flow,
                    "burnScene": burn_scene,
                }
            ),
        )

    async def get_rwa_stocks_market_session(self, *, symbol: str | None = None) -> dict[str, Any]:
        """
        Get Market Session. GET /v5/rwa/stocks/market/session.

        Source: https://bybit-exchange.github.io/docs/v5/stocks/market-session

        Args:
            symbol: Stock symbol, e.g. `AAPL-US
        """
        return await self._native_private(
            "get_rwa_stocks_market_session", self._native_params(**{"symbol": symbol})
        )

    async def get_rwa_stocks_market_get_multiplier_list(
        self, *, symbol: str | None = None, current: int, page_size: int
    ) -> dict[str, Any]:
        """
        Get Multiplier List. GET /v5/rwa/stocks/market/getMultiplierList.

        Source: https://bybit-exchange.github.io/docs/v5/stocks/multiplier-list

        Args:
            symbol: Stock symbol, e.g. `AAPL-US`. Filter by symbol; returns all symbols if omitted
            current: Current page number
            page_size: Page size. Default `10
        """
        return await self._native_private(
            "get_rwa_stocks_market_get_multiplier_list",
            self._native_params(**{"symbol": symbol, "current": current, "pageSize": page_size}),
        )

    async def get_rwa_stocks_order_detail(
        self, *, order_no: str | None = None, request_id: str | None = None
    ) -> dict[str, Any]:
        """
        Get Stock Order Detail. GET /v5/rwa/stocks/order/detail.

        Source: https://bybit-exchange.github.io/docs/v5/stocks/order-detail

        Args:
            order_no: System order number. Either `orderNo` or `requestId` is **required
            request_id: Client idempotency key. Either `orderNo` or `requestId` is **required
        """
        return await self._native_private(
            "get_rwa_stocks_order_detail",
            self._native_params(**{"orderNo": order_no, "requestId": request_id}),
        )

    async def place_stock_order(
        self,
        *,
        symbol: str,
        quote_token: str,
        side: str,
        order_type: str,
        qty: str | None = None,
        notional: str | None = None,
        limit_price: str | None = None,
        stop_price: str | None = None,
        time_in_force: str,
        trading_session: str | None = None,
        tokenize: bool | None = None,
        order_time: int,
        request_id: str,
    ) -> dict[str, Any]:
        """
        Place Stock Order. POST /v5/rwa/stocks/order.

        Source: https://bybit-exchange.github.io/docs/v5/stocks/place-order

        Args:
            symbol: Stock symbol, e.g. `TSLA-US`, `AAPL-US
            quote_token: Quote asset. Currently only `USDC` is supported
            side: BUY`, `SELL
            order_type: Order type. `MARKET`, `LIMIT`, `STOP`, `STOP_LIMIT
            qty: Order quantity. **Required** for `SELL`; **required** for `BUY` with
                `type=LIMIT`/`STOP`/`STOP_LIMIT`. Mutually exclusive with `notional
            notional: Notional amount (USDC). Only valid when `side=BUY` and `type=MARKET`. Mutually
                exclusive with `qty
            limit_price: Limit price. **Required** when `type=LIMIT` or `STOP_LIMIT
            stop_price: Trigger price. **Required** when `type=STOP` or `STOP_LIMIT
            time_in_force: Time in force: `DAY` / `GTC` / `IOC`. `SELL` only supports `DAY` / `GTC`;
                `IOC` requires `type=LIMIT` + whole-share `qty` + `tradingSession=RTH
            trading_session: Trading session. `RTH` (default), `24H`. Non-`RTH` sessions accept
                `LIMIT` orders only
            tokenize: Whether to auto tokenize after the order is filled. Default: `false`. Only
                valid for `BUY
            order_time: Client order timestamp in milliseconds
            request_id: Idempotency key. Length ≤ 36. Alphanumeric plus `-` `_`. Must be unique
                within 24 hours for the same MM account
        """
        return await self._native_private(
            "place_stock_order",
            self._native_params(
                **{
                    "symbol": symbol,
                    "quoteToken": quote_token,
                    "side": side,
                    "type": order_type,
                    "qty": qty,
                    "notional": notional,
                    "limitPrice": limit_price,
                    "stopPrice": stop_price,
                    "timeInForce": time_in_force,
                    "tradingSession": trading_session,
                    "tokenize": tokenize,
                    "orderTime": order_time,
                    "requestId": request_id,
                }
            ),
        )

    async def get_rwa_stocks_positions(
        self, *, symbol: str | None = None, show_zero: bool | None = None
    ) -> dict[str, Any]:
        """
        Get Stock Positions. GET /v5/rwa/stocks/positions.

        Source: https://bybit-exchange.github.io/docs/v5/stocks/positions

        Args:
            symbol: Stock symbol, e.g. `AAPL-US`. Filter by symbol; returns all positions if omitted
            show_zero: Whether to return zero-quantity positions. Default: `false
        """
        return await self._native_private(
            "get_rwa_stocks_positions",
            self._native_params(**{"symbol": symbol, "showZero": show_zero}),
        )
