"""Generated bybit subaccount HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedSubaccountHTTP(MarketHTTP):
    """Subaccount API methods."""

    async def get_user_escrow_sub_members(
        self, *, page_size: str | None = None, next_cursor: str | None = None
    ) -> dict[str, Any]:
        """
        Get Fund Custodial Sub Acct. GET /v5/user/escrow_sub_members.

        Source: https://bybit-exchange.github.io/docs/v5/user/fund-subuid-list

        Args:
            page_size: Data size per page. Return up to 100 records per request
            next_cursor: Cursor. Use the `nextCursor` token from the response to retrieve the next
                page of the result set
        """
        return await self._native_private(
            "get_user_escrow_sub_members",
            self._native_params(**{"pageSize": page_size, "nextCursor": next_cursor}),
        )
