//! Business-specific endpoint and field metadata.
use super::super::*;
pub(super) fn endpoint(name: &str) -> Option<RiskEndpoint> {
    Some(match name {
        "set_isolated_mode" => RiskEndpoint {
            path: "/api/v5/account/set-isolated-mode",
            post: true,
            public: false,
            keys: &["isoMode", "type"],
            required: &["isoMode", "type"],
            bools: &[],
            schema: None,
        },
        "get_account_risk_state" => RiskEndpoint {
            path: "/api/v5/account/risk-state",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            bools: &[],
            schema: None,
        },
        "get_greeks" => RiskEndpoint {
            path: "/api/v5/account/greeks",
            post: false,
            public: false,
            keys: &["ccy"],
            required: &[],
            bools: &[],
            schema: None,
        },
        "set_account_level" => RiskEndpoint {
            path: "/api/v5/account/set-account-level",
            post: true,
            public: false,
            keys: &["acctLv"],
            required: &["acctLv"],
            bools: &[],
            schema: None,
        },
        "get_collateral_assets" => RiskEndpoint {
            path: "/api/v5/account/collateral-assets",
            post: false,
            public: false,
            keys: &["ccy", "collateralEnabled"],
            required: &[],
            bools: &["collateralEnabled"],
            schema: None,
        },
        "get_asset_bill_history" => RiskEndpoint {
            path: "/api/v5/asset/bills-history",
            post: false,
            public: false,
            keys: &[
                "ccy",
                "type",
                "thirdPartyType",
                "clientId",
                "after",
                "before",
                "limit",
                "pagingType",
            ],
            required: &[],
            bools: &[],
            schema: None,
        },
        "set_fee_type" => RiskEndpoint {
            path: "/api/v5/account/set-fee-type",
            post: true,
            public: false,
            keys: &["feeType"],
            required: &["feeType"],
            bools: &[],
            schema: None,
        },
        "set_risk_offset_amount" => RiskEndpoint {
            path: "/api/v5/account/set-riskOffset-amt",
            post: true,
            public: false,
            keys: &["ccy", "clSpotInUseAmt"],
            required: &["ccy", "clSpotInUseAmt"],
            bools: &[],
            schema: None,
        },
        "preset_account_level_switch" => RiskEndpoint {
            path: "/api/v5/account/account-level-switch-preset",
            post: true,
            public: false,
            keys: &["acctLv", "lever"],
            required: &["acctLv"],
            bools: &[],
            schema: None,
        },
        "precheck_account_level_switch" => RiskEndpoint {
            path: "/api/v5/account/set-account-switch-precheck",
            post: false,
            public: false,
            keys: &["acctLv"],
            required: &["acctLv"],
            bools: &[],
            schema: None,
        },
        "set_collateral_assets" => RiskEndpoint {
            path: "/api/v5/account/set-collateral-assets",
            post: true,
            public: false,
            keys: &["type", "collateralEnabled", "ccyList"],
            required: &["type", "collateralEnabled"],
            bools: &["collateralEnabled"],
            schema: None,
        },
        "set_trading_config" => RiskEndpoint {
            path: "/api/v5/account/set-trading-config",
            post: true,
            public: false,
            keys: &["type", "stgyType"],
            required: &["type"],
            bools: &[],
            schema: None,
        },
        "precheck_delta_neutral" => RiskEndpoint {
            path: "/api/v5/account/precheck-set-delta-neutral",
            post: false,
            public: false,
            keys: &["stgyType"],
            required: &["stgyType"],
            bools: &[],
            schema: None,
        },
        "get_bill_types" => RiskEndpoint {
            path: "/api/v5/account/subtypes",
            post: false,
            public: false,
            keys: &["type"],
            required: &[],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"type\":{\"type\":\"string\"}},\"required\":[]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#trading-account-rest-api-position-builder-new
        "adjust_demo_balance" => RiskEndpoint {
            path: "/api/v5/account/demo-adjust-balance",
            post: true,
            public: false,
            keys: &["type", "adjustments"],
            required: &["type", "adjustments"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"type\":{\"type\":\"string\"},\"adjustments\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"ccy\":{\"type\":\"string\"},\"amt\":{\"type\":\"string\"}},\"required\":[\"ccy\",\"amt\"]}}},\"required\":[\"type\",\"adjustments\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#order-book-trading-market-data-get-rpi-order-book
        "get_non_tradable_assets" => RiskEndpoint {
            path: "/api/v5/asset/non-tradable-assets",
            post: false,
            public: false,
            keys: &["ccy"],
            required: &[],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"ccy\":{\"type\":\"string\"}},\"required\":[]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#sub-account-rest-api-create-sub-account
        "get_finance_stable_rewards_product_info" => RiskEndpoint {
            path: "/api/v5/finance/stable-rewards/product-info",
            post: false,
            public: false,
            keys: &["ccy"],
            required: &["ccy"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"ccy\":{\"type\":\"string\",\"description\":\"Stablecoin, e.g. USDG\"}},\"required\":[\"ccy\"]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#financial-product-stable-rewards-get-balance
        "get_finance_stable_rewards_balance" => RiskEndpoint {
            path: "/api/v5/finance/stable-rewards/balance",
            post: false,
            public: false,
            keys: &["ccy"],
            required: &[],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"ccy\":{\"type\":\"string\",\"description\":\"Stablecoin, e.g. USDG Returns all supported stablecoins if not specified\"}},\"required\":[]}",
            ),
        },
        // https://www.okx.com/docs-v5/en/#financial-product-stable-rewards-get-apy-history
        "get_finance_stable_rewards_apy_history" => RiskEndpoint {
            path: "/api/v5/finance/stable-rewards/apy-history",
            post: false,
            public: false,
            keys: &["ccy", "days"],
            required: &["ccy"],
            bools: &[],
            schema: Some(
                "{\"type\":\"object\",\"properties\":{\"ccy\":{\"type\":\"string\",\"description\":\"Stablecoin, e.g. USDG\"},\"days\":{\"type\":\"string\",\"description\":\"Number of historical days to return. The default is 100 . The maximum is 100\"}},\"required\":[\"ccy\"]}",
            ),
        },
        _ => return None,
    })
}
