//! Business-specific endpoint schema tables.
use super::*;
mod account;
mod affiliate;
mod announcements;
mod bots;
mod convert;
mod copy_trading;
mod event;
mod fiat;
mod glp;
mod loan;
mod margin;
mod market;
mod options;
mod rfq;
mod subaccount;
mod trading;
mod transfers;
mod withdrawals;
pub(super) fn endpoint(name: &str) -> Option<RiskEndpoint> {
    None.or_else(|| account::endpoint(name))
        .or_else(|| affiliate::endpoint(name))
        .or_else(|| announcements::endpoint(name))
        .or_else(|| bots::endpoint(name))
        .or_else(|| convert::endpoint(name))
        .or_else(|| copy_trading::endpoint(name))
        .or_else(|| event::endpoint(name))
        .or_else(|| fiat::endpoint(name))
        .or_else(|| glp::endpoint(name))
        .or_else(|| loan::endpoint(name))
        .or_else(|| margin::endpoint(name))
        .or_else(|| market::endpoint(name))
        .or_else(|| options::endpoint(name))
        .or_else(|| rfq::endpoint(name))
        .or_else(|| subaccount::endpoint(name))
        .or_else(|| trading::endpoint(name))
        .or_else(|| transfers::endpoint(name))
        .or_else(|| withdrawals::endpoint(name))
}
