use super::RiskEndpoint;
pub(super) fn endpoint(name: &str) -> Option<RiskEndpoint> {
    Some(match name {
        "get_server_time" => RiskEndpoint {
            path: "/v5/market/time",
            post: false,
            public: true,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "get_fixed_loan_supply_contract_info" => RiskEndpoint {
            path: "/v5/crypto-loan-fixed/supply-contract-info",
            post: false,
            public: false,
            keys: &[
                "orderId",
                "supplyId",
                "supplyCurrency",
                "term",
                "limit",
                "cursor",
            ],
            required: &[],
            integers: &["limit"],
        },
        "get_account_instruments" => RiskEndpoint {
            path: "/v5/account/instruments-info",
            post: false,
            public: false,
            keys: &["category", "symbol", "limit", "cursor", "product_symbol"],
            required: &["category"],
            integers: &["limit"],
        },
        "get_dcp_info" => RiskEndpoint {
            path: "/v5/account/query-dcp-info",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "get_coin_greeks" => RiskEndpoint {
            path: "/v5/asset/coin-greeks",
            post: false,
            public: false,
            keys: &["baseCoin"],
            required: &[],
            integers: &[],
        },
        "repay_liability" => RiskEndpoint {
            path: "/v5/account/quick-repayment",
            post: true,
            public: false,
            keys: &["coin"],
            required: &[],
            integers: &[],
        },
        "set_collateral_coin" => RiskEndpoint {
            path: "/v5/account/set-collateral-switch",
            post: true,
            public: false,
            keys: &["coin", "collateralSwitch"],
            required: &["coin", "collateralSwitch"],
            integers: &[],
        },
        "batch_set_collateral_coins" => RiskEndpoint {
            path: "/v5/account/set-collateral-switch-batch",
            post: true,
            public: false,
            keys: &["request"],
            required: &["request"],
            integers: &[],
        },
        "get_asset_overview" => RiskEndpoint {
            path: "/v5/asset/asset-overview",
            post: false,
            public: false,
            keys: &["memberId", "valuationCurrency", "accountType"],
            required: &[],
            integers: &[],
        },
        "get_delivery_records" => RiskEndpoint {
            path: "/v5/asset/delivery-record",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "startTime",
                "endTime",
                "expDate",
                "limit",
                "cursor",
                "product_symbol",
            ],
            required: &["category"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_settlement_records" => RiskEndpoint {
            path: "/v5/asset/settlement-record",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "startTime",
                "endTime",
                "limit",
                "cursor",
                "product_symbol",
            ],
            required: &["category"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_funding_account_history" => RiskEndpoint {
            path: "/v5/asset/fundinghistory",
            post: false,
            public: false,
            keys: &["createTimeFrom", "createTimeTo", "limit", "cursor"],
            required: &[],
            integers: &[],
        },
        "request_convert_quote" => RiskEndpoint {
            path: "/v5/asset/exchange/quote-apply",
            post: true,
            public: false,
            keys: &[
                "accountType",
                "fromCoin",
                "toCoin",
                "requestCoin",
                "requestAmount",
                "fromCoinType",
                "toCoinType",
                "requestId",
            ],
            required: &[
                "accountType",
                "fromCoin",
                "toCoin",
                "requestCoin",
                "requestAmount",
            ],
            integers: &[],
        },
        "execute_convert_quote" => RiskEndpoint {
            path: "/v5/asset/exchange/convert-execute",
            post: true,
            public: false,
            keys: &["quoteTxId"],
            required: &["quoteTxId"],
            integers: &[],
        },
        "get_convert_result" => RiskEndpoint {
            path: "/v5/asset/exchange/convert-result-query",
            post: false,
            public: false,
            keys: &["quoteTxId", "accountType"],
            required: &["quoteTxId", "accountType"],
            integers: &[],
        },
        "get_full_orderbook" => RiskEndpoint {
            path: "/v5/market/full_orderbook",
            post: false,
            public: true,
            keys: &["category", "symbol", "product_symbol"],
            required: &["category", "symbol"],
            integers: &[],
        },
        "get_rpi_orderbook" => RiskEndpoint {
            path: "/v5/market/rpi_orderbook",
            post: false,
            public: true,
            keys: &["category", "symbol", "limit", "product_symbol"],
            required: &["symbol", "limit"],
            integers: &["limit"],
        },
        "confirm_pending_mmr" => RiskEndpoint {
            path: "/v5/position/confirm-pending-mmr",
            post: true,
            public: false,
            keys: &["category", "symbol", "product_symbol"],
            required: &["category", "symbol"],
            integers: &[],
        },
        "get_position_symbol_info" => RiskEndpoint {
            path: "/v5/position/symbol-info",
            post: false,
            public: false,
            keys: &["category", "symbol", "product_symbol"],
            required: &["category"],
            integers: &[],
        },
        "get_system_status" => RiskEndpoint {
            path: "/v5/system/status",
            post: false,
            public: true,
            keys: &["id", "state"],
            required: &[],
            integers: &[],
        },
        "get_api_key_info" => RiskEndpoint {
            path: "/v5/user/query-api",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "get_option_asset_info" => RiskEndpoint {
            path: "/v5/account/option-asset-info",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "get_portfolio_margin_info" => RiskEndpoint {
            path: "/v5/asset/portfolio-margin",
            post: false,
            public: false,
            keys: &["baseCoin"],
            required: &[],
            integers: &[],
        },
        "get_repayment_info" => RiskEndpoint {
            path: "/v5/account/pay-info",
            post: false,
            public: false,
            keys: &["coin"],
            required: &[],
            integers: &[],
        },
        "get_trade_analysis" => RiskEndpoint {
            path: "/v5/account/trade-info-for-analysis",
            post: false,
            public: false,
            keys: &["symbol", "startTime", "endTime", "product_symbol"],
            required: &["symbol"],
            integers: &["startTime", "endTime"],
        },
        "get_total_members_assets" => RiskEndpoint {
            path: "/v5/asset/total-members-assets",
            post: false,
            public: false,
            keys: &["coin"],
            required: &[],
            integers: &[],
        },
        "get_smp_group" => RiskEndpoint {
            path: "/v5/account/smp-group",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "get_trade_behavior_config" => RiskEndpoint {
            path: "/v5/account/user-setting-config",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "set_delta_mode" => RiskEndpoint {
            path: "/v5/account/set-delta-mode",
            post: true,
            public: false,
            keys: &["deltaEnable"],
            required: &["deltaEnable"],
            integers: &[],
        },
        "set_spot_hedging" => RiskEndpoint {
            path: "/v5/account/set-hedging-mode",
            post: true,
            public: false,
            keys: &["setHedgingMode"],
            required: &["setHedgingMode"],
            integers: &[],
        },
        "set_price_limit_behavior" => RiskEndpoint {
            path: "/v5/account/set-limit-px-action",
            post: true,
            public: false,
            keys: &["category", "modifyEnable"],
            required: &["category", "modifyEnable"],
            integers: &[],
        },
        "get_closed_option_positions" => RiskEndpoint {
            path: "/v5/position/get-closed-positions",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "startTime",
                "endTime",
                "limit",
                "cursor",
            ],
            required: &["category"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_move_position_history" => RiskEndpoint {
            path: "/v5/position/move-history",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "startTime",
                "endTime",
                "status",
                "blockTradeId",
                "limit",
                "cursor",
            ],
            required: &[],
            integers: &["startTime", "endTime", "limit"],
        },
        "move_positions" => RiskEndpoint {
            path: "/v5/position/move-positions",
            post: true,
            public: false,
            keys: &["fromUid", "toUid", "list"],
            required: &["fromUid", "toUid", "list"],
            integers: &[],
        },
        "get_announcements" => RiskEndpoint {
            path: "/v5/announcements/index",
            post: false,
            public: true,
            keys: &["locale", "type", "tag", "page", "limit"],
            required: &["locale"],
            integers: &["page", "limit"],
        },
        "execute_small_balance_quote" => RiskEndpoint {
            path: "/v5/asset/covert/small-balance-execute",
            post: true,
            public: false,
            keys: &["quoteId"],
            required: &["quoteId"],
            integers: &[],
        },
        "get_small_balance_history" => RiskEndpoint {
            path: "/v5/asset/covert/small-balance-history",
            post: false,
            public: false,
            keys: &[
                "accountType",
                "quoteId",
                "startTime",
                "endTime",
                "cursor",
                "size",
            ],
            required: &[],
            integers: &[],
        },
        "request_small_balance_quote" => RiskEndpoint {
            path: "/v5/asset/covert/get-quote",
            post: true,
            public: false,
            keys: &["accountType", "fromCoinList", "toCoin"],
            required: &["accountType", "fromCoinList", "toCoin"],
            integers: &[],
        },
        "get_small_balance_coins" => RiskEndpoint {
            path: "/v5/asset/covert/small-balance-list",
            post: false,
            public: false,
            keys: &["accountType", "fromCoin"],
            required: &["accountType"],
            integers: &[],
        },
        "get_convert_coins" => RiskEndpoint {
            path: "/v5/asset/exchange/query-coin-list",
            post: false,
            public: false,
            keys: &["accountType", "coin", "side"],
            required: &["accountType"],
            integers: &["side"],
        },
        "get_convert_history" => RiskEndpoint {
            path: "/v5/asset/exchange/query-convert-history",
            post: false,
            public: false,
            keys: &["accountType", "index", "limit"],
            required: &[],
            integers: &["index", "limit"],
        },
        "get_sub_account_deposit_address" => RiskEndpoint {
            path: "/v5/asset/deposit/query-sub-member-address",
            post: false,
            public: false,
            keys: &["coin", "chainType", "subMemberId"],
            required: &["coin", "chainType", "subMemberId"],
            integers: &[],
        },
        "get_exchange_order_records" => RiskEndpoint {
            path: "/v5/asset/exchange/order-record",
            post: false,
            public: false,
            keys: &["fromCoin", "toCoin", "limit", "cursor"],
            required: &[],
            integers: &["limit"],
        },
        "get_fee_group_info" => RiskEndpoint {
            path: "/v5/market/fee-group-info",
            post: false,
            public: true,
            keys: &["productType", "groupId"],
            required: &["productType"],
            integers: &[],
        },
        "get_index_price_components" => RiskEndpoint {
            path: "/v5/market/index-price-components",
            post: false,
            public: true,
            keys: &["indexName"],
            required: &["indexName"],
            integers: &[],
        },
        "get_option_delivery_prices" => RiskEndpoint {
            path: "/v5/market/new-delivery-price",
            post: false,
            public: true,
            keys: &["category", "baseCoin", "settleCoin"],
            required: &["category", "baseCoin"],
            integers: &[],
        },
        "get_option_base_coins" => RiskEndpoint {
            path: "/v5/market/option-base-coins",
            post: false,
            public: true,
            keys: &["underlyingType"],
            required: &[],
            integers: &[],
        },
        "get_pre_upgrade_closed_pnl" => RiskEndpoint {
            path: "/v5/pre-upgrade/position/closed-pnl",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "startTime",
                "endTime",
                "limit",
                "cursor",
            ],
            required: &["category", "symbol"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_pre_upgrade_delivery_records" => RiskEndpoint {
            path: "/v5/pre-upgrade/asset/delivery-record",
            post: false,
            public: false,
            keys: &["category", "symbol", "expDate", "limit", "cursor"],
            required: &["category"],
            integers: &["limit"],
        },
        "get_pre_upgrade_executions" => RiskEndpoint {
            path: "/v5/pre-upgrade/execution/list",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "orderId",
                "orderLinkId",
                "baseCoin",
                "startTime",
                "endTime",
                "execType",
                "limit",
                "cursor",
            ],
            required: &["category"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_pre_upgrade_order_history" => RiskEndpoint {
            path: "/v5/pre-upgrade/order/history",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "baseCoin",
                "orderId",
                "orderLinkId",
                "orderFilter",
                "orderStatus",
                "startTime",
                "endTime",
                "limit",
                "cursor",
            ],
            required: &["category"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_pre_upgrade_settlement_records" => RiskEndpoint {
            path: "/v5/pre-upgrade/asset/settlement-record",
            post: false,
            public: false,
            keys: &["category", "symbol", "limit", "cursor"],
            required: &["category"],
            integers: &["limit"],
        },
        "get_pre_upgrade_transaction_log" => RiskEndpoint {
            path: "/v5/pre-upgrade/account/transaction-log",
            post: false,
            public: false,
            keys: &[
                "category",
                "baseCoin",
                "type",
                "startTime",
                "endTime",
                "limit",
                "cursor",
            ],
            required: &["category"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_margin_currency_data" => RiskEndpoint {
            path: "/v5/spot-margin-trade/currency-data",
            post: false,
            public: false,
            keys: &["currency"],
            required: &[],
            integers: &[],
        },
        "create_sub_account_api_key" => RiskEndpoint {
            path: "/v5/user/create-sub-api",
            post: true,
            public: false,
            keys: &["subuid", "note", "readOnly", "ips", "permissions"],
            required: &["subuid", "readOnly", "permissions"],
            integers: &["subuid", "readOnly"],
        },
        "create_sub_account" => RiskEndpoint {
            path: "/v5/user/create-sub-member",
            post: true,
            public: false,
            keys: &["username", "password", "memberType", "switch", "note"],
            required: &["username", "memberType"],
            integers: &["memberType", "switch"],
        },
        "set_sub_account_frozen" => RiskEndpoint {
            path: "/v5/user/frozen-sub-member",
            post: true,
            public: false,
            keys: &["subuid", "frozen"],
            required: &["subuid", "frozen"],
            integers: &["subuid", "frozen"],
        },
        "get_sub_account_api_keys" => RiskEndpoint {
            path: "/v5/user/sub-apikeys",
            post: false,
            public: false,
            keys: &["subMemberId", "limit", "cursor"],
            required: &["subMemberId"],
            integers: &["limit"],
        },
        "modify_api_key" => RiskEndpoint {
            path: "/v5/user/update-api",
            post: true,
            public: false,
            keys: &["readOnly", "permissions"],
            required: &[],
            integers: &["readOnly"],
        },
        "modify_sub_account_api_key" => RiskEndpoint {
            path: "/v5/user/update-sub-api",
            post: true,
            public: false,
            keys: &["apikey", "readOnly", "ips", "permissions"],
            required: &[],
            integers: &["readOnly"],
        },
        "get_sub_accounts_paginated" => RiskEndpoint {
            path: "/v5/user/submembers",
            post: false,
            public: false,
            keys: &["pageSize", "nextCursor"],
            required: &[],
            integers: &[],
        },
        "delete_api_key" => RiskEndpoint {
            path: "/v5/user/delete-api",
            post: true,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "delete_sub_account_api_key" => RiskEndpoint {
            path: "/v5/user/delete-sub-api",
            post: true,
            public: false,
            keys: &["apikey"],
            required: &[],
            integers: &[],
        },
        "delete_sub_account" => RiskEndpoint {
            path: "/v5/user/del-submember",
            post: true,
            public: false,
            keys: &["subMemberId"],
            required: &["subMemberId"],
            integers: &[],
        },
        "sign_trading_agreement" => RiskEndpoint {
            path: "/v5/user/agreement",
            post: true,
            public: false,
            keys: &["categoryV2", "agree"],
            required: &["categoryV2", "agree"],
            integers: &["categoryV2"],
        },
        "get_sub_accounts" => RiskEndpoint {
            path: "/v5/user/query-sub-members",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "get_member_wallet_types" => RiskEndpoint {
            path: "/v5/user/get-member-type",
            post: false,
            public: false,
            keys: &["memberIds"],
            required: &[],
            integers: &[],
        },
        "get_all_api_rate_limits" => RiskEndpoint {
            path: "/v5/apilimit/query-all",
            post: false,
            public: false,
            keys: &["limit", "cursor", "uids"],
            required: &[],
            integers: &[],
        },
        "get_api_rate_limit_cap" => RiskEndpoint {
            path: "/v5/apilimit/query-cap",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "get_api_rate_limits" => RiskEndpoint {
            path: "/v5/apilimit/query",
            post: false,
            public: false,
            keys: &["uids"],
            required: &["uids"],
            integers: &[],
        },
        "set_api_rate_limits" => RiskEndpoint {
            path: "/v5/apilimit/set",
            post: true,
            public: false,
            keys: &["list"],
            required: &["list"],
            integers: &[],
        },
        "submit_deposit_information" => RiskEndpoint {
            path: "/v5/asset/travel-rule/deposit/submit",
            post: true,
            public: false,
            keys: &["depositId", "subAccountId", "questionnaire"],
            required: &["depositId", "questionnaire"],
            integers: &["depositId", "subAccountId"],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/asset/withdraw/vasp-list.mdx
        "get_asset_withdraw_vasp_list" => RiskEndpoint {
            path: "/v5/asset/withdraw/vasp/list",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/asset/withdraw/withdraw-address.mdx
        "get_asset_withdraw_query_address" => RiskEndpoint {
            path: "/v5/asset/withdraw/query-address",
            post: false,
            public: false,
            keys: &["coin", "chain", "addressType", "limit", "cursor"],
            required: &[],
            integers: &["addressType", "limit"],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/asset/withdraw/withdraw-record.mdx
        "get_asset_withdraw_query_record" => RiskEndpoint {
            path: "/v5/asset/withdraw/query-record",
            post: false,
            public: false,
            keys: &[
                "withdrawID",
                "txID",
                "coin",
                "withdrawType",
                "startTime",
                "endTime",
                "limit",
                "cursor",
            ],
            required: &[],
            integers: &["withdrawType", "startTime", "endTime", "limit"],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/crypto-loan/acct-borrow-collateral.mdx
        "get_crypto_loan_borrowable_collateralisable_number" => RiskEndpoint {
            path: "/v5/crypto-loan/borrowable-collateralisable-number",
            post: false,
            public: false,
            keys: &["loanCurrency", "collateralCurrency"],
            required: &["loanCurrency", "collateralCurrency"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/crypto-loan/adjust-collateral.mdx
        "crypto_loan_adjust_ltv" => RiskEndpoint {
            path: "/v5/crypto-loan/adjust-ltv",
            post: true,
            public: false,
            keys: &["orderId", "amount", "direction"],
            required: &["orderId", "amount", "direction"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/crypto-loan/collateral-coin.mdx
        "get_crypto_loan_collateral_data" => RiskEndpoint {
            path: "/v5/crypto-loan/collateral-data",
            post: false,
            public: true,
            keys: &["vipLevel", "currency"],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/crypto-loan/completed-loan-order.mdx
        "get_crypto_loan_borrow_history" => RiskEndpoint {
            path: "/v5/crypto-loan/borrow-history",
            post: false,
            public: false,
            keys: &[
                "orderId",
                "loanCurrency",
                "collateralCurrency",
                "limit",
                "cursor",
            ],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/crypto-loan/loan-coin.mdx
        "get_crypto_loan_loanable_data" => RiskEndpoint {
            path: "/v5/crypto-loan/loanable-data",
            post: false,
            public: true,
            keys: &["vipLevel", "currency"],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/crypto-loan/ltv-adjust-history.mdx
        "get_crypto_loan_adjustment_history" => RiskEndpoint {
            path: "/v5/crypto-loan/adjustment-history",
            post: false,
            public: false,
            keys: &[
                "orderId",
                "adjustId",
                "collateralCurrency",
                "limit",
                "cursor",
            ],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/crypto-loan/reduce-max-collateral-amt.mdx
        "get_crypto_loan_max_collateral_amount" => RiskEndpoint {
            path: "/v5/crypto-loan/max-collateral-amount",
            post: false,
            public: false,
            keys: &["orderId"],
            required: &["orderId"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/crypto-loan/repay-transaction.mdx
        "get_crypto_loan_repayment_history" => RiskEndpoint {
            path: "/v5/crypto-loan/repayment-history",
            post: false,
            public: false,
            keys: &["orderId", "repayId", "loanCurrency", "limit", "cursor"],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/crypto-loan/repay.mdx
        "crypto_loan_repay" => RiskEndpoint {
            path: "/v5/crypto-loan/repay",
            post: true,
            public: false,
            keys: &["orderId", "amount"],
            required: &["orderId", "amount"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/crypto-loan/unpaid-loan-order.mdx
        "get_crypto_loan_ongoing_orders" => RiskEndpoint {
            path: "/v5/crypto-loan/ongoing-orders",
            post: false,
            public: false,
            keys: &[
                "orderId",
                "loanCurrency",
                "collateralCurrency",
                "loanTermType",
                "loanTerm",
                "limit",
                "cursor",
            ],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/finance/spot-x/puzzle/puzzle-project-list.mdx
        "get_spot_x_puzzle_project_list" => RiskEndpoint {
            path: "/v5/spot-x/puzzle/project/list",
            post: false,
            public: false,
            keys: &["status", "projectId", "activityCoin", "cursor", "limit"],
            required: &["status"],
            integers: &["status", "limit"],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/finance/spot-x/token-splash/token-splash-project-list.mdx
        "get_spot_x_token_splash_project_list" => RiskEndpoint {
            path: "/v5/spot-x/token-splash/project/list",
            post: false,
            public: false,
            keys: &["status", "projectId", "activityCoin", "cursor", "limit"],
            required: &["status"],
            integers: &["status", "limit"],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/finance/spot-x/token-splash/token-splash-user-activity-params.mdx
        "get_spot_x_token_splash_user_activity_params" => RiskEndpoint {
            path: "/v5/spot-x/token-splash/user/activity-params",
            post: false,
            public: false,
            keys: &["projectId", "activityCoin"],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/adjust-collateral.mdx
        "crypto_loan_common_adjust_ltv" => RiskEndpoint {
            path: "/v5/crypto-loan-common/adjust-ltv",
            post: true,
            public: false,
            keys: &["currency", "amount", "direction"],
            required: &["currency", "amount", "direction"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/collateral-coin.mdx
        "get_crypto_loan_common_collateral_data" => RiskEndpoint {
            path: "/v5/crypto-loan-common/collateral-data",
            post: false,
            public: true,
            keys: &["currency"],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/crypto-loan-position.mdx
        "get_crypto_loan_common_position" => RiskEndpoint {
            path: "/v5/crypto-loan-common/position",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/fixed/available-inventory.mdx
        "get_crypto_loan_fixed_available_inventory" => RiskEndpoint {
            path: "/v5/crypto-loan-fixed/available-inventory",
            post: false,
            public: false,
            keys: &["currency", "term", "annualRate"],
            required: &["currency", "term", "annualRate"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/fixed/borrow-contract.mdx
        "get_crypto_loan_fixed_borrow_contract_info" => RiskEndpoint {
            path: "/v5/crypto-loan-fixed/borrow-contract-info",
            post: false,
            public: false,
            keys: &[
                "orderId",
                "loanId",
                "orderCurrency",
                "term",
                "limit",
                "cursor",
            ],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/fixed/borrow-market.mdx
        "get_crypto_loan_fixed_borrow_order_quote" => RiskEndpoint {
            path: "/v5/crypto-loan-fixed/borrow-order-quote",
            post: false,
            public: true,
            keys: &["orderCurrency", "orderBy", "term", "sort", "limit"],
            required: &["orderCurrency", "orderBy"],
            integers: &["sort", "limit"],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/fixed/borrow-order.mdx
        "get_crypto_loan_fixed_borrow_order_info" => RiskEndpoint {
            path: "/v5/crypto-loan-fixed/borrow-order-info",
            post: false,
            public: false,
            keys: &[
                "orderId",
                "orderCurrency",
                "state",
                "term",
                "limit",
                "cursor",
            ],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/fixed/borrow.mdx
        "crypto_loan_fixed_borrow" => RiskEndpoint {
            path: "/v5/crypto-loan-fixed/borrow",
            post: true,
            public: false,
            keys: &[
                "orderCurrency",
                "orderAmount",
                "annualRate",
                "term",
                "repayType",
                "strategyType",
                "collateralList",
            ],
            required: &["orderCurrency", "orderAmount", "annualRate", "term"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/fixed/cancel-borrow.mdx
        "crypto_loan_fixed_borrow_order_cancel" => RiskEndpoint {
            path: "/v5/crypto-loan-fixed/borrow-order-cancel",
            post: true,
            public: false,
            keys: &["orderId"],
            required: &["orderId"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/fixed/cancel-supply.mdx
        "crypto_loan_fixed_supply_order_cancel" => RiskEndpoint {
            path: "/v5/crypto-loan-fixed/supply-order-cancel",
            post: true,
            public: false,
            keys: &["orderId", "refundedAccount"],
            required: &["orderId"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/fixed/renew-order.mdx
        "get_crypto_loan_fixed_renew_info" => RiskEndpoint {
            path: "/v5/crypto-loan-fixed/renew-info",
            post: false,
            public: false,
            keys: &["orderId", "orderCurrency", "limit", "cursor"],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/fixed/renew.mdx
        "crypto_loan_fixed_renew" => RiskEndpoint {
            path: "/v5/crypto-loan-fixed/renew",
            post: true,
            public: false,
            keys: &["loanId", "collateralList"],
            required: &["loanId"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/fixed/repay-collateral.mdx
        "crypto_loan_fixed_repay_collateral" => RiskEndpoint {
            path: "/v5/crypto-loan-fixed/repay-collateral",
            post: true,
            public: false,
            keys: &["loanId", "loanCurrency", "collateralCoin", "amount"],
            required: &["loanCurrency", "collateralCoin", "amount"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/fixed/repay-history.mdx
        "get_crypto_loan_fixed_repayment_history" => RiskEndpoint {
            path: "/v5/crypto-loan-fixed/repayment-history",
            post: false,
            public: false,
            keys: &["repayId", "loanCurrency", "limit", "cursor"],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/fixed/repay.mdx
        "crypto_loan_fixed_fully_repay" => RiskEndpoint {
            path: "/v5/crypto-loan-fixed/fully-repay",
            post: true,
            public: false,
            keys: &["loanId", "loanCurrency"],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/fixed/supply-market.mdx
        "get_crypto_loan_fixed_supply_order_quote" => RiskEndpoint {
            path: "/v5/crypto-loan-fixed/supply-order-quote",
            post: false,
            public: true,
            keys: &["orderCurrency", "term", "orderBy", "sort", "limit"],
            required: &["orderCurrency", "orderBy"],
            integers: &["sort", "limit"],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/fixed/supply-order.mdx
        "get_crypto_loan_fixed_supply_order_info" => RiskEndpoint {
            path: "/v5/crypto-loan-fixed/supply-order-info",
            post: false,
            public: false,
            keys: &[
                "orderId",
                "orderCurrency",
                "state",
                "term",
                "limit",
                "cursor",
            ],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/fixed/supply.mdx
        "crypto_loan_fixed_supply" => RiskEndpoint {
            path: "/v5/crypto-loan-fixed/supply",
            post: true,
            public: false,
            keys: &[
                "orderCurrency",
                "orderAmount",
                "annualRate",
                "term",
                "availableSource",
            ],
            required: &["orderCurrency", "orderAmount", "annualRate", "term"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/flexible/available-inventory.mdx
        "get_crypto_loan_flexible_available_inventory" => RiskEndpoint {
            path: "/v5/crypto-loan-flexible/available-inventory",
            post: false,
            public: false,
            keys: &["currency"],
            required: &["currency"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/flexible/borrow.mdx
        "crypto_loan_flexible_borrow" => RiskEndpoint {
            path: "/v5/crypto-loan-flexible/borrow",
            post: true,
            public: false,
            keys: &["loanCurrency", "loanAmount", "collateralList"],
            required: &["loanCurrency", "loanAmount"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/flexible/loan-orders.mdx
        "get_crypto_loan_flexible_borrow_history" => RiskEndpoint {
            path: "/v5/crypto-loan-flexible/borrow-history",
            post: false,
            public: false,
            keys: &["orderId", "loanCurrency", "limit", "cursor"],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/flexible/repay-collateral.mdx
        "crypto_loan_flexible_repay_collateral" => RiskEndpoint {
            path: "/v5/crypto-loan-flexible/repay-collateral",
            post: true,
            public: false,
            keys: &["loanCurrency", "collateralCoin", "amount"],
            required: &["loanCurrency", "collateralCoin", "amount"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/flexible/repay-orders.mdx
        "get_crypto_loan_flexible_repayment_history" => RiskEndpoint {
            path: "/v5/crypto-loan-flexible/repayment-history",
            post: false,
            public: false,
            keys: &["repayId", "loanCurrency", "limit", "cursor"],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/flexible/repay.mdx
        "crypto_loan_flexible_repay" => RiskEndpoint {
            path: "/v5/crypto-loan-flexible/repay",
            post: true,
            public: false,
            keys: &["loanCurrency", "amount"],
            required: &["loanCurrency", "amount"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/flexible/unpaid-loan-order.mdx
        "get_crypto_loan_flexible_ongoing_coin" => RiskEndpoint {
            path: "/v5/crypto-loan-flexible/ongoing-coin",
            post: false,
            public: false,
            keys: &["loanCurrency"],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/loan-coin.mdx
        "get_crypto_loan_common_loanable_data" => RiskEndpoint {
            path: "/v5/crypto-loan-common/loanable-data",
            post: false,
            public: true,
            keys: &["vipLevel", "currency"],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/ltv-adjust-history.mdx
        "get_crypto_loan_common_adjustment_history" => RiskEndpoint {
            path: "/v5/crypto-loan-common/adjustment-history",
            post: false,
            public: false,
            keys: &["adjustId", "collateralCurrency", "limit", "cursor"],
            required: &[],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/max-loan-amt.mdx
        "crypto_loan_common_max_loan" => RiskEndpoint {
            path: "/v5/crypto-loan-common/max-loan",
            post: true,
            public: false,
            keys: &["currency", "collateralList"],
            required: &["currency"],
            integers: &[],
        },
        // https://raw.githubusercontent.com/bybit-exchange/docs/master/docs/v5/new-crypto-loan/reduce-max-collateral-amt.mdx
        "get_crypto_loan_common_max_collateral_amount" => RiskEndpoint {
            path: "/v5/crypto-loan-common/max-collateral-amount",
            post: false,
            public: false,
            keys: &["currency"],
            required: &["currency"],
            integers: &[],
        },
        // https://github.com/bybit-exchange/docs/blob/master/docs/v5/lt/leverage-token-reference.mdx
        "get_spot_lever_token_reference" => RiskEndpoint {
            path: "/v5/spot-lever-token/reference",
            post: false,
            public: true,
            keys: &["ltCoin"],
            required: &["ltCoin"],
            integers: &[],
        },
        // https://github.com/bybit-exchange/docs/blob/master/docs/v5/lt/order-record.mdx
        "get_spot_lever_token_order_record" => RiskEndpoint {
            path: "/v5/spot-lever-token/order-record",
            post: false,
            public: false,
            keys: &[
                "ltCoin",
                "orderId",
                "startTime",
                "endTime",
                "limit",
                "ltOrderType",
                "serialNo",
            ],
            required: &[],
            integers: &["startTime", "endTime", "limit", "ltOrderType"],
        },
        // https://github.com/bybit-exchange/docs/blob/master/docs/v5/lt/purchase.mdx
        "spot_lever_token_purchase" => RiskEndpoint {
            path: "/v5/spot-lever-token/purchase",
            post: true,
            public: false,
            keys: &["ltCoin", "ltAmount", "serialNo"],
            required: &["ltCoin", "ltAmount"],
            integers: &[],
        },
        // https://github.com/bybit-exchange/docs/blob/master/docs/v5/lt/redeem.mdx
        "spot_lever_token_redeem" => RiskEndpoint {
            path: "/v5/spot-lever-token/redeem",
            post: true,
            public: false,
            keys: &["ltCoin", "quantity", "serialNo"],
            required: &["ltCoin", "quantity"],
            integers: &[],
        },
        _ => return None,
    })
}
