use super::RiskEndpoint;
pub(super) fn endpoint(name: &str) -> Option<RiskEndpoint> {
    Some(match name {
        "get_account_instruments" => RiskEndpoint {
            path: "/v5/account/instruments-info",
            post: false,
            public: false,
            keys: &["category", "symbol", "limit", "cursor", "product_symbol"],
            required: &["category"],
            integers: &["limit"],
        },
        "get_dcp_info" => RiskEndpoint {
            path: "/v5/account/query-dcp-info",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "get_coin_greeks" => RiskEndpoint {
            path: "/v5/asset/coin-greeks",
            post: false,
            public: false,
            keys: &["baseCoin"],
            required: &[],
            integers: &[],
        },
        "repay_liability" => RiskEndpoint {
            path: "/v5/account/quick-repayment",
            post: true,
            public: false,
            keys: &["coin"],
            required: &[],
            integers: &[],
        },
        "set_collateral_coin" => RiskEndpoint {
            path: "/v5/account/set-collateral-switch",
            post: true,
            public: false,
            keys: &["coin", "collateralSwitch"],
            required: &["coin", "collateralSwitch"],
            integers: &[],
        },
        "batch_set_collateral_coins" => RiskEndpoint {
            path: "/v5/account/set-collateral-switch-batch",
            post: true,
            public: false,
            keys: &["request"],
            required: &["request"],
            integers: &[],
        },
        "get_asset_overview" => RiskEndpoint {
            path: "/v5/asset/asset-overview",
            post: false,
            public: false,
            keys: &["memberId", "valuationCurrency", "accountType"],
            required: &[],
            integers: &[],
        },
        "get_delivery_records" => RiskEndpoint {
            path: "/v5/asset/delivery-record",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "startTime",
                "endTime",
                "expDate",
                "limit",
                "cursor",
                "product_symbol",
            ],
            required: &["category"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_settlement_records" => RiskEndpoint {
            path: "/v5/asset/settlement-record",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "startTime",
                "endTime",
                "limit",
                "cursor",
                "product_symbol",
            ],
            required: &["category"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_funding_account_history" => RiskEndpoint {
            path: "/v5/asset/fundinghistory",
            post: false,
            public: false,
            keys: &["createTimeFrom", "createTimeTo", "limit", "cursor"],
            required: &[],
            integers: &[],
        },
        "request_convert_quote" => RiskEndpoint {
            path: "/v5/asset/exchange/quote-apply",
            post: true,
            public: false,
            keys: &[
                "accountType",
                "fromCoin",
                "toCoin",
                "requestCoin",
                "requestAmount",
                "fromCoinType",
                "toCoinType",
                "requestId",
            ],
            required: &[
                "accountType",
                "fromCoin",
                "toCoin",
                "requestCoin",
                "requestAmount",
            ],
            integers: &[],
        },
        "execute_convert_quote" => RiskEndpoint {
            path: "/v5/asset/exchange/convert-execute",
            post: true,
            public: false,
            keys: &["quoteTxId"],
            required: &["quoteTxId"],
            integers: &[],
        },
        "get_convert_result" => RiskEndpoint {
            path: "/v5/asset/exchange/convert-result-query",
            post: false,
            public: false,
            keys: &["quoteTxId", "accountType"],
            required: &["quoteTxId", "accountType"],
            integers: &[],
        },
        "get_full_orderbook" => RiskEndpoint {
            path: "/v5/market/full_orderbook",
            post: false,
            public: true,
            keys: &["category", "symbol", "product_symbol"],
            required: &["category", "symbol"],
            integers: &[],
        },
        "get_rpi_orderbook" => RiskEndpoint {
            path: "/v5/market/rpi_orderbook",
            post: false,
            public: true,
            keys: &["category", "symbol", "limit", "product_symbol"],
            required: &["symbol", "limit"],
            integers: &["limit"],
        },
        "confirm_pending_mmr" => RiskEndpoint {
            path: "/v5/position/confirm-pending-mmr",
            post: true,
            public: false,
            keys: &["category", "symbol", "product_symbol"],
            required: &["category", "symbol"],
            integers: &[],
        },
        "get_position_symbol_info" => RiskEndpoint {
            path: "/v5/position/symbol-info",
            post: false,
            public: false,
            keys: &["category", "symbol", "product_symbol"],
            required: &["category"],
            integers: &[],
        },
        "get_system_status" => RiskEndpoint {
            path: "/v5/system/status",
            post: false,
            public: true,
            keys: &["id", "state"],
            required: &[],
            integers: &[],
        },
        "get_api_key_info" => RiskEndpoint {
            path: "/v5/user/query-api",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "get_option_asset_info" => RiskEndpoint {
            path: "/v5/account/option-asset-info",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "get_portfolio_margin_info" => RiskEndpoint {
            path: "/v5/asset/portfolio-margin",
            post: false,
            public: false,
            keys: &["baseCoin"],
            required: &[],
            integers: &[],
        },
        "get_repayment_info" => RiskEndpoint {
            path: "/v5/account/pay-info",
            post: false,
            public: false,
            keys: &["coin"],
            required: &[],
            integers: &[],
        },
        "get_trade_analysis" => RiskEndpoint {
            path: "/v5/account/trade-info-for-analysis",
            post: false,
            public: false,
            keys: &["symbol", "startTime", "endTime", "product_symbol"],
            required: &["symbol"],
            integers: &["startTime", "endTime"],
        },
        "get_total_members_assets" => RiskEndpoint {
            path: "/v5/asset/total-members-assets",
            post: false,
            public: false,
            keys: &["coin"],
            required: &[],
            integers: &[],
        },
        "get_smp_group" => RiskEndpoint {
            path: "/v5/account/smp-group",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "get_trade_behavior_config" => RiskEndpoint {
            path: "/v5/account/user-setting-config",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "set_delta_mode" => RiskEndpoint {
            path: "/v5/account/set-delta-mode",
            post: true,
            public: false,
            keys: &["deltaEnable"],
            required: &["deltaEnable"],
            integers: &[],
        },
        "set_spot_hedging" => RiskEndpoint {
            path: "/v5/account/set-hedging-mode",
            post: true,
            public: false,
            keys: &["setHedgingMode"],
            required: &["setHedgingMode"],
            integers: &[],
        },
        "set_price_limit_behavior" => RiskEndpoint {
            path: "/v5/account/set-limit-px-action",
            post: true,
            public: false,
            keys: &["category", "modifyEnable"],
            required: &["category", "modifyEnable"],
            integers: &[],
        },
        "get_closed_option_positions" => RiskEndpoint {
            path: "/v5/position/get-closed-positions",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "startTime",
                "endTime",
                "limit",
                "cursor",
            ],
            required: &["category"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_move_position_history" => RiskEndpoint {
            path: "/v5/position/move-history",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "startTime",
                "endTime",
                "status",
                "blockTradeId",
                "limit",
                "cursor",
            ],
            required: &[],
            integers: &["startTime", "endTime", "limit"],
        },
        "move_positions" => RiskEndpoint {
            path: "/v5/position/move-positions",
            post: true,
            public: false,
            keys: &["fromUid", "toUid", "list"],
            required: &["fromUid", "toUid", "list"],
            integers: &[],
        },
        "get_announcements" => RiskEndpoint {
            path: "/v5/announcements/index",
            post: false,
            public: true,
            keys: &["locale", "type", "tag", "page", "limit"],
            required: &["locale"],
            integers: &["page", "limit"],
        },
        "execute_small_balance_quote" => RiskEndpoint {
            path: "/v5/asset/covert/small-balance-execute",
            post: true,
            public: false,
            keys: &["quoteId"],
            required: &["quoteId"],
            integers: &[],
        },
        "get_small_balance_history" => RiskEndpoint {
            path: "/v5/asset/covert/small-balance-history",
            post: false,
            public: false,
            keys: &[
                "accountType",
                "quoteId",
                "startTime",
                "endTime",
                "cursor",
                "size",
            ],
            required: &[],
            integers: &[],
        },
        "request_small_balance_quote" => RiskEndpoint {
            path: "/v5/asset/covert/get-quote",
            post: true,
            public: false,
            keys: &["accountType", "fromCoinList", "toCoin"],
            required: &["accountType", "fromCoinList", "toCoin"],
            integers: &[],
        },
        "get_small_balance_coins" => RiskEndpoint {
            path: "/v5/asset/covert/small-balance-list",
            post: false,
            public: false,
            keys: &["accountType", "fromCoin"],
            required: &["accountType"],
            integers: &[],
        },
        "get_convert_coins" => RiskEndpoint {
            path: "/v5/asset/exchange/query-coin-list",
            post: false,
            public: false,
            keys: &["accountType", "coin", "side"],
            required: &["accountType"],
            integers: &["side"],
        },
        "get_convert_history" => RiskEndpoint {
            path: "/v5/asset/exchange/query-convert-history",
            post: false,
            public: false,
            keys: &["accountType", "index", "limit"],
            required: &[],
            integers: &["index", "limit"],
        },
        "get_sub_account_deposit_address" => RiskEndpoint {
            path: "/v5/asset/deposit/query-sub-member-address",
            post: false,
            public: false,
            keys: &["coin", "chainType", "subMemberId"],
            required: &["coin", "chainType", "subMemberId"],
            integers: &[],
        },
        "get_exchange_order_records" => RiskEndpoint {
            path: "/v5/asset/exchange/order-record",
            post: false,
            public: false,
            keys: &["fromCoin", "toCoin", "limit", "cursor"],
            required: &[],
            integers: &["limit"],
        },
        "get_fee_group_info" => RiskEndpoint {
            path: "/v5/market/fee-group-info",
            post: false,
            public: true,
            keys: &["productType", "groupId"],
            required: &["productType"],
            integers: &[],
        },
        "get_index_price_components" => RiskEndpoint {
            path: "/v5/market/index-price-components",
            post: false,
            public: true,
            keys: &["indexName"],
            required: &["indexName"],
            integers: &[],
        },
        "get_option_delivery_prices" => RiskEndpoint {
            path: "/v5/market/new-delivery-price",
            post: false,
            public: true,
            keys: &["category", "baseCoin", "settleCoin"],
            required: &["category", "baseCoin"],
            integers: &[],
        },
        "get_option_base_coins" => RiskEndpoint {
            path: "/v5/market/option-base-coins",
            post: false,
            public: true,
            keys: &["underlyingType"],
            required: &[],
            integers: &[],
        },
        "get_pre_upgrade_closed_pnl" => RiskEndpoint {
            path: "/v5/pre-upgrade/position/closed-pnl",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "startTime",
                "endTime",
                "limit",
                "cursor",
            ],
            required: &["category", "symbol"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_pre_upgrade_delivery_records" => RiskEndpoint {
            path: "/v5/pre-upgrade/asset/delivery-record",
            post: false,
            public: false,
            keys: &["category", "symbol", "expDate", "limit", "cursor"],
            required: &["category"],
            integers: &["limit"],
        },
        "get_pre_upgrade_executions" => RiskEndpoint {
            path: "/v5/pre-upgrade/execution/list",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "orderId",
                "orderLinkId",
                "baseCoin",
                "startTime",
                "endTime",
                "execType",
                "limit",
                "cursor",
            ],
            required: &["category"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_pre_upgrade_order_history" => RiskEndpoint {
            path: "/v5/pre-upgrade/order/history",
            post: false,
            public: false,
            keys: &[
                "category",
                "symbol",
                "baseCoin",
                "orderId",
                "orderLinkId",
                "orderFilter",
                "orderStatus",
                "startTime",
                "endTime",
                "limit",
                "cursor",
            ],
            required: &["category"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_pre_upgrade_settlement_records" => RiskEndpoint {
            path: "/v5/pre-upgrade/asset/settlement-record",
            post: false,
            public: false,
            keys: &["category", "symbol", "limit", "cursor"],
            required: &["category"],
            integers: &["limit"],
        },
        "get_pre_upgrade_transaction_log" => RiskEndpoint {
            path: "/v5/pre-upgrade/account/transaction-log",
            post: false,
            public: false,
            keys: &[
                "category",
                "baseCoin",
                "type",
                "startTime",
                "endTime",
                "limit",
                "cursor",
            ],
            required: &["category"],
            integers: &["startTime", "endTime", "limit"],
        },
        "get_margin_currency_data" => RiskEndpoint {
            path: "/v5/spot-margin-trade/currency-data",
            post: false,
            public: false,
            keys: &["currency"],
            required: &[],
            integers: &[],
        },
        "create_sub_account_api_key" => RiskEndpoint {
            path: "/v5/user/create-sub-api",
            post: true,
            public: false,
            keys: &["subuid", "note", "readOnly", "ips", "permissions"],
            required: &["subuid", "readOnly", "permissions"],
            integers: &["subuid", "readOnly"],
        },
        "create_sub_account" => RiskEndpoint {
            path: "/v5/user/create-sub-member",
            post: true,
            public: false,
            keys: &["username", "password", "memberType", "switch", "note"],
            required: &["username", "memberType"],
            integers: &["memberType", "switch"],
        },
        "set_sub_account_frozen" => RiskEndpoint {
            path: "/v5/user/frozen-sub-member",
            post: true,
            public: false,
            keys: &["subuid", "frozen"],
            required: &["subuid", "frozen"],
            integers: &["subuid", "frozen"],
        },
        "get_sub_account_api_keys" => RiskEndpoint {
            path: "/v5/user/sub-apikeys",
            post: false,
            public: false,
            keys: &["subMemberId", "limit", "cursor"],
            required: &["subMemberId"],
            integers: &["limit"],
        },
        "modify_api_key" => RiskEndpoint {
            path: "/v5/user/update-api",
            post: true,
            public: false,
            keys: &["readOnly", "permissions"],
            required: &[],
            integers: &["readOnly"],
        },
        "modify_sub_account_api_key" => RiskEndpoint {
            path: "/v5/user/update-sub-api",
            post: true,
            public: false,
            keys: &["apikey", "readOnly", "ips", "permissions"],
            required: &[],
            integers: &["readOnly"],
        },
        "get_sub_accounts_paginated" => RiskEndpoint {
            path: "/v5/user/submembers",
            post: false,
            public: false,
            keys: &["pageSize", "nextCursor"],
            required: &[],
            integers: &[],
        },
        "delete_api_key" => RiskEndpoint {
            path: "/v5/user/delete-api",
            post: true,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "delete_sub_account_api_key" => RiskEndpoint {
            path: "/v5/user/delete-sub-api",
            post: true,
            public: false,
            keys: &["apikey"],
            required: &[],
            integers: &[],
        },
        "delete_sub_account" => RiskEndpoint {
            path: "/v5/user/del-submember",
            post: true,
            public: false,
            keys: &["subMemberId"],
            required: &["subMemberId"],
            integers: &[],
        },
        "sign_trading_agreement" => RiskEndpoint {
            path: "/v5/user/agreement",
            post: true,
            public: false,
            keys: &["categoryV2", "agree"],
            required: &["categoryV2", "agree"],
            integers: &["categoryV2"],
        },
        "get_sub_accounts" => RiskEndpoint {
            path: "/v5/user/query-sub-members",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "get_member_wallet_types" => RiskEndpoint {
            path: "/v5/user/get-member-type",
            post: false,
            public: false,
            keys: &["memberIds"],
            required: &[],
            integers: &[],
        },
        "get_all_api_rate_limits" => RiskEndpoint {
            path: "/v5/apilimit/query-all",
            post: false,
            public: false,
            keys: &["limit", "cursor", "uids"],
            required: &[],
            integers: &[],
        },
        "get_api_rate_limit_cap" => RiskEndpoint {
            path: "/v5/apilimit/query-cap",
            post: false,
            public: false,
            keys: &[],
            required: &[],
            integers: &[],
        },
        "get_api_rate_limits" => RiskEndpoint {
            path: "/v5/apilimit/query",
            post: false,
            public: false,
            keys: &["uids"],
            required: &["uids"],
            integers: &[],
        },
        "set_api_rate_limits" => RiskEndpoint {
            path: "/v5/apilimit/set",
            post: true,
            public: false,
            keys: &["list"],
            required: &["list"],
            integers: &[],
        },
        "submit_deposit_information" => RiskEndpoint {
            path: "/v5/asset/travel-rule/deposit/submit",
            post: true,
            public: false,
            keys: &["depositId", "subAccountId", "questionnaire"],
            required: &["depositId", "questionnaire"],
            integers: &["depositId", "subAccountId"],
        },
        _ => return None,
    })
}
