use super::client::BybitClient;

crate::exchanges::impl_exchange_method_wrappers! {
    BybitClient;
    public [
        get_adl_alert(),
        get_advanced_earn_products(category => "category"),
        get_advanced_earn_product_quote(category => "category", product_id => "productId"),
        get_liquidity_mining_products(),
        get_fixed_earn_products(),
        get_hold_to_earn_products(),
        get_byusdt_product(),
        get_byusdt_apr_history(range => "range"),
        get_rwa_earn_products(),
        get_rwa_earn_nav_chart(product_id => "productId"),
        get_launchpool_projects(status => "status"),
        get_delivery_price(),
        get_earn_products(category => "category"),
        get_earn_apr_history(category => "category", product_id => "productId"),
        get_funding_rate_history(product_symbol => "product_symbol"),
        get_historical_volatility(),
        get_instruments_info(),
        get_insurance_pool(),
        get_kline(product_symbol => "product_symbol", interval => "interval"),
        get_long_short_ratio(product_symbol => "product_symbol"),
        get_open_interest(product_symbol => "product_symbol"),
        get_order_price_limit(product_symbol => "product_symbol"),
        get_orderbook(product_symbol => "product_symbol"),
        get_public_trade_history(product_symbol => "product_symbol"),
        get_risk_limit(),
        get_tickers(),
    ];
    private [
        amend_batch_order(request => "request"),
        amend_order(product_symbol => "product_symbol"),
        cancel_all_orders(),
        cancel_batch_orders(request => "request"),
        cancel_order(product_symbol => "product_symbol"),
        create_internal_transfer(coin => "coin", amount => "amount", from_account_type => "fromAccountType", to_account_type => "toAccountType"),
        create_universal_transfer(coin => "coin", amount => "amount", from_member_id => "fromMemberId", to_member_id => "toMemberId", from_account_type => "fromAccountType", to_account_type => "toAccountType"),
        get_account_info(),
        get_advanced_earn_orders(category => "category"),
        get_advanced_earn_positions(category => "category"),
        get_advanced_earn_redeem_estimates(category => "category", position_ids => "positionIds"),
        get_double_win_leverage(product_id => "productId", initial_price => "initialPrice", lower_price => "lowerPrice", upper_price => "upperPrice"),
        get_liquidity_mining_positions(),
        get_liquidity_mining_orders(),
        get_liquidity_mining_yield_records(),
        get_liquidity_mining_liquidation_records(),
        add_liquidity_mining(product_id => "productId", order_link_id => "orderLinkId"),
        remove_liquidity_mining(product_id => "productId", order_link_id => "orderLinkId", position_id => "positionId"),
        reinvest_liquidity_mining(product_id => "productId", order_link_id => "orderLinkId", position_id => "positionId"),
        add_liquidity_mining_margin(product_id => "productId", order_link_id => "orderLinkId", position_id => "positionId", amount => "amount", quote_account_type => "quoteAccountType"),
        claim_liquidity_mining_interest(product_id => "productId"),
        get_fixed_earn_positions(),
        get_fixed_earn_orders(),
        place_fixed_earn_order(product_id => "productId", category => "category", coin => "coin", amount => "amount", account_type => "accountType", order_link_id => "orderLinkId"),
        redeem_fixed_earn(product_id => "productId", category => "category", position_id => "positionId"),
        set_fixed_earn_auto_invest(product_id => "productId", category => "category", position_id => "positionId", status => "status"),
        get_hold_to_earn_yield_history(limit => "limit"),
        get_byusdt_orders(),
        get_byusdt_position(),
        get_byusdt_daily_yield(),
        get_byusdt_hourly_yield(),
        place_byusdt_order(order_type => "orderType", amount => "amount", account_type => "accountType", order_link_id => "orderLinkId"),
        get_rwa_earn_positions(),
        get_rwa_earn_orders(),
        place_rwa_earn_order(product_id => "productId", order_type => "orderType", coin => "coin", order_link_id => "orderLinkId"),
        get_launchpool_activity_log(),
        get_launchpool_current_staking(),
        get_launchpool_history(),
        get_borrow_history(),
        get_earn_order_history(category => "category"),
        get_earn_coupons(category => "category"),
        set_earn_auto_reinvest(category => "category", product_id => "productId", position_id => "positionId", auto_reinvest => "autoReinvest"),
        get_earn_positions(category => "category"),
        get_earn_yield_history(category => "category"),
        get_earn_hourly_yield_history(category => "category"),
        place_earn_order(category => "category", order_type => "orderType", account_type => "accountType", amount => "amount", coin => "coin", product_id => "productId", order_link_id => "orderLinkId"),
        place_advanced_earn_order(category => "category", product_id => "productId", order_type => "orderType", account_type => "accountType", order_link_id => "orderLinkId"),
        get_borrow_quota(product_symbol => "product_symbol", side => "side"),
        manual_borrow(coin => "coin", amount => "amount"),
        manual_repay(),
        manual_repay_without_conversion(coin => "coin"),
        get_closed_pnl(),
        get_coin_balance(account_type => "accountType", coin => "coin"),
        get_coin_info(),
        get_coins_balance(account_type => "accountType"),
        get_collateral(),
        get_collateral_info(),
        get_deposit_records(),
        get_execution_list(),
        get_inverse_fee_rates(),
        get_linear_fee_rates(),
        get_option_fee_rates(),
        get_spot_fee_rates(),
        get_historical_interest_rate(currency => "currency"),
        get_margin_max_borrowable(currency => "currency"),
        get_margin_position_tiers(),
        get_margin_coin_state(),
        get_margin_repayment_available_amount(currency => "currency"),
        set_margin_auto_repay_mode(auto_repay_mode => "autoRepayMode"),
        get_margin_auto_repay_mode(),
        get_fixed_borrow_quote(order_currency => "orderCurrency"),
        borrow_fixed_rate(order_currency => "orderCurrency", order_amount => "orderAmount", annual_rate => "annualRate", term => "term"),
        renew_fixed_rate_borrow(loan_id => "loanId"),
        get_fixed_borrow_orders(),
        get_fixed_borrow_contracts(),
        get_margin_liability(currency => "currency"),
        get_flexible_borrow_inventory(currency => "currency"),
        get_fixed_borrow_inventory(currency => "currency", term => "term", annual_rate => "annualRate"),
        get_internal_deposit_records(),
        get_internal_transfer_records(),
        get_master_deposit_address(coin => "coin"),
        get_open_orders(),
        get_order_history(),
        get_positions(),
        get_rfq_public_trades(),
        get_rfq_config(),
        create_rfq(counterparties => "counterparties", legs => "list"),
        cancel_rfq(),
        cancel_all_rfqs(),
        accept_other_rfq_quote(rfq_id => "rfqId"),
        create_rfq_quote(rfq_id => "rfqId"),
        execute_rfq_quote(rfq_id => "rfqId", quote_id => "quoteId", quote_side => "quoteSide"),
        cancel_rfq_quote(),
        cancel_all_rfq_quotes(),
        get_realtime_rfqs(),
        get_rfqs(),
        get_rfq_details(),
        get_realtime_rfq_quotes(),
        get_rfq_quotes(),
        get_rfq_trade_history(),
        get_spot_asset_info(),
        get_status_and_leverage(),
        get_sub_deposit_records(sub_member_id => "subMemberId"),
        get_sub_uid(),
        get_transaction_log(),
        get_transferable_amount(coins => "coins"),
        get_transferable_coin(from_account_type => "fromAccountType", to_account_type => "toAccountType"),
        get_universal_transfer_records(),
        get_vip_margin_data(),
        get_wallet_balance(),
        get_withdrawable_amount(coin => "coin"),
        place_batch_order(request => "request"),
        place_limit_buy_order(product_symbol => "product_symbol", qty => "qty", price => "price"),
        place_limit_order(product_symbol => "product_symbol", side => "side", qty => "qty", price => "price"),
        place_limit_sell_order(product_symbol => "product_symbol", qty => "qty", price => "price"),
        place_market_buy_order(product_symbol => "product_symbol", qty => "qty"),
        place_market_order(product_symbol => "product_symbol", side => "side", qty => "qty"),
        place_market_sell_order(product_symbol => "product_symbol", qty => "qty"),
        place_order(product_symbol => "product_symbol", side => "side", order_type => "orderType", qty => "qty"),
        pre_check_order(product_symbol => "product_symbol", side => "side", order_type => "orderType", qty => "qty"),
        place_post_only_limit_buy_order(product_symbol => "product_symbol", qty => "qty", price => "price"),
        place_post_only_limit_order(product_symbol => "product_symbol", side => "side", qty => "qty", price => "price"),
        place_post_only_limit_sell_order(product_symbol => "product_symbol", qty => "qty", price => "price"),
        set_deposit_account(account_type => "accountType"),
        set_disconnected_cancel_all(time_window => "timeWindow"),
        set_leverage(product_symbol => "product_symbol", leverage => "leverage"),
        set_margin_mode(margin_mode => "margin_mode"),
        switch_position_mode(mode => "mode"),
        upgrade_to_unified_trading_account(),
    ];
}
