use super::client::BybitClient;

crate::exchanges::impl_exchange_method_wrappers! {
    BybitClient;
    public [
        get_adl_alert() => get_adl_alert_with,
        get_delivery_price() => get_delivery_price_with,
        get_funding_rate_history(product_symbol => "product_symbol") => get_funding_rate_history_with,
        get_historical_volatility() => get_historical_volatility_with,
        get_instruments_info() => get_instruments_info_with,
        get_insurance_pool() => get_insurance_pool_with,
        get_kline(product_symbol => "product_symbol", interval => "interval") => get_kline_with,
        get_long_short_ratio(product_symbol => "product_symbol") => get_long_short_ratio_with,
        get_open_interest(product_symbol => "product_symbol") => get_open_interest_with,
        get_order_price_limit(product_symbol => "product_symbol") => get_order_price_limit_with,
        get_orderbook(product_symbol => "product_symbol") => get_orderbook_with,
        get_public_trade_history(product_symbol => "product_symbol") => get_public_trade_history_with,
        get_risk_limit() => get_risk_limit_with,
        get_tickers() => get_tickers_with,
    ];
    private [
        amend_batch_order(request => "request") => amend_batch_order_with,
        amend_order(product_symbol => "product_symbol") => amend_order_with,
        cancel_all_orders() => cancel_all_orders_with,
        cancel_batch_orders(request => "request") => cancel_batch_orders_with,
        cancel_order(product_symbol => "product_symbol") => cancel_order_with,
        create_internal_transfer(coin => "coin", amount => "amount", from_account_type => "fromAccountType", to_account_type => "toAccountType") => create_internal_transfer_with,
        get_account_info() => get_account_info_with,
        get_borrow_history() => get_borrow_history_with,
        get_borrow_quota(product_symbol => "product_symbol", side => "side") => get_borrow_quota_with,
        get_closed_pnl() => get_closed_pnl_with,
        get_coin_balance(account_type => "accountType", coin => "coin") => get_coin_balance_with,
        get_coin_info() => get_coin_info_with,
        get_coins_balance(account_type => "accountType") => get_coins_balance_with,
        get_collateral() => get_collateral_with,
        get_collateral_info() => get_collateral_info_with,
        get_deposit_records() => get_deposit_records_with,
        get_execution_list() => get_execution_list_with,
        get_fee_rates() => get_fee_rates_with,
        get_historical_interest_rate(currency => "currency") => get_historical_interest_rate_with,
        get_internal_deposit_records() => get_internal_deposit_records_with,
        get_internal_transfer_records() => get_internal_transfer_records_with,
        get_master_deposit_address(coin => "coin") => get_master_deposit_address_with,
        get_open_orders() => get_open_orders_with,
        get_order_history() => get_order_history_with,
        get_positions() => get_positions_with,
        get_spot_asset_info() => get_spot_asset_info_with,
        get_status_and_leverage() => get_status_and_leverage_with,
        get_sub_deposit_records(sub_member_id => "subMemberId") => get_sub_deposit_records_with,
        get_sub_uid() => get_sub_uid_with,
        get_transaction_log() => get_transaction_log_with,
        get_transferable_amount(coins => "coins") => get_transferable_amount_with,
        get_transferable_coin(from_account_type => "fromAccountType", to_account_type => "toAccountType") => get_transferable_coin_with,
        get_universal_transfer_records() => get_universal_transfer_records_with,
        get_vip_margin_data() => get_vip_margin_data_with,
        get_wallet_balance() => get_wallet_balance_with,
        get_withdrawable_amount(coin => "coin") => get_withdrawable_amount_with,
        place_batch_order(request => "request") => place_batch_order_with,
        place_limit_buy_order(product_symbol => "product_symbol", qty => "qty", price => "price") => place_limit_buy_order_with,
        place_limit_order(product_symbol => "product_symbol", side => "side", qty => "qty", price => "price") => place_limit_order_with,
        place_limit_sell_order(product_symbol => "product_symbol", qty => "qty", price => "price") => place_limit_sell_order_with,
        place_market_buy_order(product_symbol => "product_symbol", qty => "qty") => place_market_buy_order_with,
        place_market_order(product_symbol => "product_symbol", side => "side", qty => "qty") => place_market_order_with,
        place_market_sell_order(product_symbol => "product_symbol", qty => "qty") => place_market_sell_order_with,
        place_order(product_symbol => "product_symbol", side => "side", order_type => "orderType", qty => "qty") => place_order_with,
        place_post_only_limit_buy_order(product_symbol => "product_symbol", qty => "qty", price => "price") => place_post_only_limit_buy_order_with,
        place_post_only_limit_order(product_symbol => "product_symbol", side => "side", qty => "qty", price => "price") => place_post_only_limit_order_with,
        place_post_only_limit_sell_order(product_symbol => "product_symbol", qty => "qty", price => "price") => place_post_only_limit_sell_order_with,
        set_deposit_account(account_type => "accountType") => set_deposit_account_with,
        set_leverage(product_symbol => "product_symbol", leverage => "leverage") => set_leverage_with,
        set_margin_mode(margin_mode => "margin_mode") => set_margin_mode_with,
        switch_position_mode(mode => "mode") => switch_position_mode_with,
        upgrade_to_unified_trading_account() => upgrade_to_unified_trading_account_with,
    ];
}
