"""Generate exchange adapters for immutable JSON endpoint tables."""

import json
import re
from pathlib import Path

from scripts.generation import emit, run

ROOT = Path(__file__).resolve().parents[1] / "crates/dcex/src/exchanges"
EXCHANGES = ("binance", "bitget", "bybit", "bingx", "kucoin", "kraken", "okx")


def members(source: str, name: str) -> list[tuple[str, str]]:
    """Read adapter types; schema values always come from the JSON catalog."""
    match = re.search(rf"struct {name} \{{(.*?)\n\}}", source, re.S)
    if match is None:
        raise ValueError(f"Missing {name} adapter")
    return re.findall(r"(?:pub\s+)?(\w+): ([^\n]+),", match[1])


def expression(name: str, kind: str, samples: list[dict], variable: str = "row") -> str:
    """Render the fixed Rust transport metadata for one schema member."""
    access = f'{variable}["{name}"]'
    if kind == "&'static str":
        return f'{access}.as_str().expect("schema {name}")'
    if kind == "bool":
        return f'{access}.as_bool().expect("schema {name}")'
    if kind == "char":
        return f'{access}.as_str().expect("schema kind").chars().next().expect("kind")'
    if kind == "&'static [&'static str]":
        return f"schema::static_strings(&{access})"
    if kind in ("u64", "i64"):
        return f'{access}.as_{kind}().expect("schema {name}")'
    if kind in ("Option<u64>", "Option<i64>"):
        return f"{access}.as_{kind[7:-1]}()"
    if kind == "Option<&'static str>":
        return f"{access}.as_str()"
    variants = sorted({item[name] for item in samples})
    if all(isinstance(item, str) and item.startswith(kind + "::") for item in variants):
        arms = ", ".join(f"{json.dumps(item)} => {item}" for item in variants)
        return (
            f'match {access}.as_str().expect("schema {name}") {{ {arms}, '
            '_ => unreachable!("checked schema enum") }'
        )
    raise ValueError((name, kind))


def main() -> None:
    """Regenerate adapters; table JSON is the source of truth."""
    jobs = [(exchange, "schema_requests", "table_*", "schema_tables") for exchange in EXCHANGES]
    jobs += [
        ("backpack", topic, f"table_{topic}", f"{topic}_schema")
        for topic in ("prediction", "borrow_lend")
    ]
    for exchange, module, pattern, output in jobs:
        folder = ROOT / exchange
        files = sorted((folder / "schemas").glob(f"{pattern}.json"))
        records = [item for file in files for item in json.loads(file.read_text(encoding="utf-8"))]
        source = (folder / f"{module}.rs").read_text(encoding="utf-8")
        name = "RiskEndpoint" if "struct RiskEndpoint" in source else "Endpoint"
        fields = members(source, name)
        lines = [
            "// Generated by scripts/build_schema_tables.py; edit schemas/table_*.json.",
            "use super::*;",
            "use crate::exchanges::schema;",
            f"pub(super) static ENDPOINTS: std::sync::LazyLock<Vec<{name}>> = "
            "std::sync::LazyLock::new(|| {",
            "schema::load_tables(&[",
            *[f'include_str!("../schemas/{file.name}"),' for file in files],
            f"]).iter().map(|row| {name} {{",
        ]
        for member, kind in fields:
            if kind == "&'static [Field]":
                samples = [field for record in records for field in record[member]]
                nested = ", ".join(
                    f"{key}: {expression(key, value, samples, 'field')}"
                    for key, value in members(source, "Field")
                )
                code = f'schema::static_fields(&row["{member}"], |field| Field {{ {nested} }})'
            else:
                code = expression(member, kind, records)
            lines.append(f"{member}: {code},")
        lines += ["}).collect()", "});"]
        if exchange not in {"binance", "kraken"}:
            # These adapters previously matched the external method name.
            names = ",".join(json.dumps(record["name"]) for record in records)
            lines += [
                f"pub(super) fn endpoint(name: &str) -> Option<&'static {name}> {{",
                f"const NAMES: &[&str] = &[{names}];",
                "NAMES.iter().position(|candidate| *candidate == name)"
                ".map(|index| &ENDPOINTS[index])",
                "}",
            ]
        destination = folder / f"generated/{output}.rs"
        emit(destination, "\n".join(lines) + "\n")


if __name__ == "__main__":
    raise SystemExit(run(main))
