"""Generate explicit Rust and Python wrappers from reviewed Bybit schemas."""

import textwrap
from pathlib import Path

from scripts.generation import run
from scripts.wrapper_codegen import load_schemas, write_python_wrappers, write_rust_wrappers

ROOT = Path(__file__).resolve().parents[1]


def python_type(kind: str) -> str:
    """Map wire types without converting decimal strings to floats."""
    if kind in {"integer", "int", "int64", "long"}:
        return "int"
    if kind == "boolean":
        return "bool"
    if kind.startswith("array"):
        return "list[Any]"
    if kind == "object":
        return "dict[str, Any]"
    if kind == "string":
        return "str"
    raise ValueError(f"Unsupported type: {kind}")


def main() -> None:
    """Regenerate transport wrappers; never modify ledger completion status."""
    endpoints = load_schemas("bybit")
    for asynchronous in (False, True):
        text = [
            '"""Additional Bybit V5 endpoints from reviewed official request schemas."""',
            "",
            "from typing import Any",
            "",
            "from ._market_http import MarketHTTP",
            "",
            "",
            "class GeneratedMethods(MarketHTTP):",
            '    """Explicit additional V5 endpoint wrappers."""',
        ]
        for endpoint in endpoints:
            prefix = "async " if asynchronous else ""
            fields = endpoint["fields"]
            text += ["", f"    {prefix}def {endpoint['name']}(", "        self,"]
            if fields:
                text += ["        *,"]
            for field in fields:
                kind = python_type(field["type"])
                optional = "" if field["required"] else " | None = None"
                text += [f"        {field['python_name']}: {kind}{optional},"]
            text += ["    ) -> dict[str, Any]:", '        """']
            text += [
                f"        {endpoint['title'].rstrip('.')}. "
                f"{endpoint['method']} {endpoint['path']}.",
                "",
            ]
            if endpoint["path"] == "/v5/asset/withdraw/create":
                text += [
                    "        API withdrawals have no second confirmation; they execute on submit.",
                    "        With force_chain=2 the recipient may be another Bybit user.",
                ]
            if endpoint.get("verification_note"):
                text += textwrap.wrap(
                    endpoint["verification_note"],
                    width=100,
                    initial_indent="        ",
                    subsequent_indent="        ",
                )
            text += ["        Source: " + endpoint["official_source"]]
            if fields:
                text += ["", "        Args:"]
                for field in fields:
                    text += textwrap.wrap(
                        f"{field['python_name']}: {field['description']}",
                        width=100,
                        initial_indent="            ",
                        subsequent_indent="                ",
                        break_long_words=False,
                        break_on_hyphens=False,
                    )
            text += ['        """']
            await_word = "await " if asynchronous else ""
            auth = "public" if endpoint["public"] else "private"
            text += [
                f"        return {await_word}self._native_{auth}(",
                f'''            "{endpoint["name"]}",''',
            ]
            if fields:
                text += ["            self._native_params(**{"]
                for field in fields:
                    text += [f'''                "{field["name"]}": {field["python_name"]},''']
                text += ["            }),"]
            else:
                text += ["            [],"]
            text += ["        )"]
        write_python_wrappers("bybit", asynchronous, "\n".join(text) + "\n")
    rust = [
        "// Generated by scripts/build_bybit_wrappers.py.",
        "use super::client::BybitClient;",
        "",
        "crate::exchanges::impl_exchange_method_wrappers! {",
        "    @extend;",
        "    BybitClient;",
    ]
    for public in (True, False):
        rust += ["    " + ("public" if public else "private") + " ["]
        for endpoint in endpoints:
            if endpoint["public"] != public:
                continue
            args = [
                f'''{field["python_name"]} => "{field["name"]}"'''
                for field in endpoint["fields"]
                if field["required"]
            ]
            if endpoint["path"] == "/v5/asset/withdraw/create":
                rust += [
                    "        /// API withdrawals have no second confirmation; "
                    "they execute on submit.",
                    "        /// With forceChain=2 the recipient may be another Bybit user.",
                ]
            rust += [f"        {endpoint['name']}({', '.join(args)}),"]
        rust += ["    ];"]
    rust += ["}"]
    write_rust_wrappers("bybit", "\n".join(rust) + "\n")
    print(f"Generated {len(endpoints)} Rust, sync and async wrappers.")


if __name__ == "__main__":
    raise SystemExit(run(main))
