"""Generate typed Bitget wrappers from the committed official operation schemas."""

import json
import keyword
import re
from pathlib import Path

from scripts.wrapper_codegen import (
    generated_endpoints,
    write_python_wrappers,
    write_rust_wrappers,
    write_schemas,
)

ROOT = Path(__file__).resolve().parents[1]


def snake(value: str) -> str:
    """Convert a documented field name to a Python keyword."""
    value = re.sub("([A-Z]+)([A-Z][a-z])", "\\1_\\2", value)
    value = re.sub("([a-z0-9])([A-Z])", "\\1_\\2", value).lower().replace("-", "_")
    return value + "_" if keyword.iskeyword(value) or value in {"self", "type"} else value


def main() -> None:
    """Regenerate the committed artifacts from the documented source data."""
    selected = generated_endpoints("bitget")
    operations = json.loads(
        (ROOT / "docs/official-endpoint-inventory/sources/bitget-operations.json").read_text(
            encoding="utf-8"
        )
    )["operations"]
    specs = []
    for op in operations:
        if snake(op["operationId"]) not in selected or "demo-placeholder" in op["path"]:
            continue
        fields = []
        for param in op["parameters"]:
            if param["in"] not in {"query", "header"}:
                raise ValueError((op["path"], param))
            if param["in"] == "header":
                continue
            fields.append(
                {
                    "wire": param["name"],
                    "required": param["required"],
                    "schema": param["schema"],
                    "location": "query",
                }
            )
        content = (op.get("requestBody") or {}).get("content", [])
        if content:
            schema = content[0]["schema"]
            if schema["type"] != "object":
                raise ValueError(f"Expected object body for {op['path']}")
            for key, value in schema.get("properties", {}).items():
                fields.append(
                    {
                        "wire": key,
                        "required": key in schema.get("required", []),
                        "schema": value,
                        "location": "body",
                    }
                )
        description = op.get("description") or ""
        public = (
            op["method"] == "get"
            and ("/market/" in op["path"] or "/public/" in op["path"])
            and ("(IP)" in description)
        )
        confirm = (
            op["path"].endswith(
                (
                    "/cancel-all",
                    "/close-all",
                    "/close-all-positions",
                    "/order-pay",
                    "/order-release",
                )
            )
            or "delete-sub" in op["path"]
        )
        specs.append(
            {
                "name": snake(op["operationId"]),
                "method": op["method"].upper(),
                "path": op["path"],
                "public": public,
                "confirm": confirm,
                "scoped": op["path"]
                in {
                    "/api/v2/copy/mix-follower/close-positions",
                    "/api/v2/copy/mix-trader/order-close-positions",
                },
                "fields": fields,
                "source": op["official_source"],
                "summary": op["summary"],
            }
        )
    write_schemas("bitget", specs)
    groups = {True: [], False: []}
    for spec in specs:
        fields = [f for f in spec["fields"] if f["required"]]
        params = ", ".join(snake(f["wire"]) + " => " + json.dumps(f["wire"]) for f in fields)
        line = f"        {spec['name']}({params}),"
        if "withdrawal" in spec["path"] and spec["method"] == "POST":
            line = (
                "        /// API withdrawals have no second confirmation; they execute on submit.\n"
                + line
            )
        groups[spec["public"]].append(line)
    write_rust_wrappers(
        "bitget",
        "// Generated by scripts/build_bitget_wrappers.py.\n"
        "use super::BitgetClient;\n"
        "crate::exchanges::impl_exchange_method_wrappers! {\n"
        "    @extend; BitgetClient;\n"
        "    public [\n"
        + "\n".join(groups[True])
        + "\n    ];\n    private [\n"
        + "\n".join(groups[False])
        + "\n    ];\n}\n",
    )
    for asynchronous in (False, True):
        lines = [
            '"""Typed wrappers generated from the official Bitget operation schemas."""',
            "from typing import Any",
            "from dcex._operation_guards import require_confirmation, require_scope",
            "from ._market_http import MarketHTTP",
            "",
            "class GeneratedMethods(MarketHTTP):",
            '    """Additional broker, copy-trading, P2P, CFD and Stock+ endpoints."""',
        ]
        for spec in specs:
            fields = sorted(spec["fields"], key=lambda f: not f["required"])
            args = []
            for field in fields:
                kind = field["schema"].get("type", "string")
                annotation = {
                    "string": "str",
                    "integer": "int",
                    "number": "int | float",
                    "boolean": "bool",
                    "array": "list[Any]",
                    "object": "dict[str, Any]",
                }[kind]
                args.append(
                    snake(field["wire"])
                    + ": "
                    + annotation
                    + ("" if field["required"] else " | None = None")
                )
            if spec["confirm"]:
                args.append("confirm: bool = False")
            if spec["scoped"]:
                args.append("all_symbols: bool = False")
            signature = "self" + (", *, " + ", ".join(args) if args else "")
            lines += [
                "",
                "    "
                + ("async " if asynchronous else "")
                + f"def {spec['name']}({signature}) -> dict[str, Any]:",
                '        """',
                "        " + spec["summary"] + ".",
                "",
                "        Use native exchange symbols. Optional fields retain "
                "their documented types.",
                "        Source: " + spec["source"],
            ]
            if "withdrawal" in spec["path"] and spec["method"] == "POST":
                lines += [
                    "",
                    "        API withdrawals have no second confirmation; they execute on submit.",
                ]
            if spec["scoped"]:
                lines += [
                    "        Supply symbol or tracking_no, or explicitly set all_symbols=True.",
                    "        The official documentation does not define "
                    "unfiltered scope precisely.",
                ]
            lines += ['        """']
            if spec["scoped"]:
                lines.append("        require_scope(symbol or tracking_no, all_symbols)")
            if spec["confirm"]:
                lines.append("        require_confirmation(confirm)")
            values = ", ".join(json.dumps(f["wire"]) + ": " + snake(f["wire"]) for f in fields)
            if spec["confirm"]:
                values += (", " if values else "") + '"confirm": confirm'
            if spec["scoped"]:
                values += ', "all_symbols": all_symbols'
            lines += [
                "        return "
                + ("await " if asynchronous else "")
                + f"self._native_{('public' if spec['public'] else 'private')}"
                + f"({spec['name']!r}, self._native_params(**{{{values}}}))"
            ]
        write_python_wrappers("bitget", asynchronous, "\n".join(lines) + "\n")
    print(f"Generated {len(specs)} operations.")


if __name__ == "__main__":
    main()
