"""
Generate Binance's official REST field table from the committed SDK inventory.

Every dispatched Binance request is checked against it before it is sent, so a field the
endpoint does not document is rejected locally instead of reaching the exchange.
"""

import json
from collections import defaultdict
from pathlib import Path

from scripts.generation import emit, run

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "crates/dcex/src/exchanges/binance/official_fields.rs"


# Fields the official docs list but the SDK inventory omits.
DOCUMENTED_EXTRAS = {
    # https://developers.binance.com/docs/margin_trading/trade/Query-Special-Key
    ("GET", "/sapi/v1/margin/apiKey"): ["apiKey"],
}


def comparable(name: str) -> str:
    """
    Case- and underscore-insensitive form, so `spot_bnb_burn` matches `spotBNBBurn`.

    The SDK prefixes Python keywords with `var_` (`var_from` is the wire field `from`).
    """
    return name.removeprefix("var_").rstrip("_").replace("_", "").lower()


def main() -> None:
    """Emit `official_fields(method, path)` for every REST endpoint the SDK documents."""
    inventory = json.loads(
        (ROOT / "docs/official-endpoint-inventory/binance.json").read_text(encoding="utf-8")
    )["endpoints"]
    fields: dict[tuple[str, str], set[str]] = defaultdict(set)
    for op in inventory:
        if op["method"] == "WS" or "parameters" not in op or not op["path"].startswith("/"):
            continue
        fields[(op["method"], op["path"])].update(comparable(p["name"]) for p in op["parameters"])
    for endpoint, extras in DOCUMENTED_EXTRAS.items():
        fields[endpoint].update(comparable(name) for name in extras)
    arms = []
    for (method, path), names in sorted(fields.items()):
        listed = ", ".join(json.dumps(name) for name in sorted(names))
        arms.append(f"        ({json.dumps(method)}, {json.dumps(path)}) => Some(&[{listed}]),")
    emit(
        OUTPUT,
        "// @generated by scripts/build_binance_official_fields.py; do not edit.\n"
        "//! Request fields of every REST endpoint in the official Binance SDK inventory.\n\n"
        "/// Documented request fields for `method path`, lowercase without underscores, or\n"
        "/// `None` when the inventory does not describe the endpoint.\n"
        "pub(in crate::exchanges::binance) fn official_fields(\n"
        "    method: &str,\n"
        "    path: &str,\n"
        ") -> Option<&'static [&'static str]> {\n"
        "    match (method, path) {\n" + "\n".join(arms) + "\n        _ => None,\n    }\n}\n",
    )
    print(f"Generated {len(arms)} endpoints.")


if __name__ == "__main__":
    raise SystemExit(run(main))
