"""Shared declarations of schema adapter outputs in generated directories."""

from pathlib import Path

from scripts.generation import own_directory

SCHEMA_JOBS = [
    (exchange, "schema_requests", "table_*", "schema_tables")
    for exchange in ("binance", "bitget", "bybit", "bingx", "kucoin", "kraken", "okx")
] + [
    ("backpack", topic, f"table_{topic}", f"{topic}_schema")
    for topic in ("prediction", "borrow_lend")
]


def schema_output_names(exchange: str) -> tuple[str, ...]:
    """List exact schema filenames from the same jobs used for emission."""
    return tuple(f"{output}.rs" for owner, _, _, output in SCHEMA_JOBS if owner == exchange)


def register_schema_directories(root: Path) -> None:
    """Claim all Rust files for sole owners and marked adapters in shared folders."""
    scripts = Path(__file__).resolve().parent
    for folder in root.glob("*/generated"):
        shared = (scripts / f"build_{folder.parent.name}_wrappers.py").exists()
        own_directory(
            folder,
            "*.rs",
            marker="Generated by scripts/build_schema_tables.py" if shared else None,
        )
