"""Write domain-specific endpoint schemas and generated client methods."""

from __future__ import annotations

import ast
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]


def endpoint_domains(exchange: str) -> dict[str, str]:
    """Load explicit business ownership; new endpoints require classification."""
    return json.loads((ROOT / "scripts/endpoint_domains.json").read_text(encoding="utf-8"))[
        exchange
    ]["domains"]


def generated_endpoints(exchange: str) -> set[str]:
    """Select the explicit generated API surface independently of review status."""
    return set(
        json.loads((ROOT / "scripts/endpoint_domains.json").read_text(encoding="utf-8"))[exchange][
            "generated_methods"
        ]
    )


def load_schemas(exchange: str) -> list[dict[str, Any]]:
    """Read the generated surface from its committed business schema files."""
    names = generated_endpoints(exchange)
    folder = ROOT / "crates/dcex/src/exchanges" / exchange / "schemas"
    return [
        item
        for path in sorted(folder.glob("*.json"))
        for item in json.loads(path.read_text(encoding="utf-8"))
        if item["name"] in names
    ]


def write_schemas(exchange: str, endpoints: list[dict[str, Any]]) -> None:
    """Preserve each exchange's schema format while grouping by responsibility."""
    domains = endpoint_domains(exchange)
    groups: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for endpoint in endpoints:
        groups[domains[endpoint["name"]]].append(endpoint)
    folder = ROOT / "crates/dcex/src/exchanges" / exchange / "schemas"
    folder.mkdir(parents=True, exist_ok=True)
    for domain, records in groups.items():
        (folder / f"{domain}.json").write_text(
            json.dumps(records, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )


def write_rust_wrappers(exchange: str, source: str) -> None:
    """Partition explicit method declarations without changing their parameters."""
    domains = endpoint_domains(exchange)
    groups: dict[str, dict[str, list[str]]] = defaultdict(lambda: {"public": [], "private": []})
    client = re.search(r"@extend;\s*(\w+);", source)
    if client is None:
        raise ValueError("Expected an extension wrapper declaration")
    for visibility in ("public", "private"):
        match = re.search(rf"{visibility}\s*\[(.*?)\]", source, re.S)
        if match is None:
            raise ValueError(f"Missing {visibility} wrapper section")
        previous_end = 0
        for method in re.finditer(r"(\w+)\s*\([^)]*\)", match[1], re.S):
            comments = re.findall(r"^\s*(///[^\n]*)", match[1][previous_end : method.start()], re.M)
            declaration = "\n        ".join([*comments, method[0]])
            groups[domains[method[1]]][visibility].append(declaration)
            previous_end = method.end()
    folder = ROOT / "crates/dcex/src/exchanges" / exchange / "generated"
    folder.mkdir(parents=True, exist_ok=True)
    for domain, sections in sorted(groups.items()):
        lines = [
            f"// Generated by scripts/build_{exchange}_wrappers.py.",
            f"use super::super::{client[1]};",
            "crate::exchanges::impl_exchange_method_wrappers! {",
            f"    @extend; {client[1]};",
        ]
        for visibility, methods in sections.items():
            lines += [
                f"    {visibility} [",
                *[f"        {method}," for method in methods],
                "    ];",
            ]
        lines += ["}", ""]
        (folder / f"{domain}.rs").write_text("\n".join(lines), encoding="utf-8")
    (folder / "mod.rs").write_text(
        "//! Generated business-specific Client methods.\n"
        + "".join(f"mod {domain};\n" for domain in sorted(groups)),
        encoding="utf-8",
    )


def write_python_wrappers(exchange: str, asynchronous: bool, source: str) -> None:
    """Generate domain mixins and preserve the original handwritten base order."""
    domains = endpoint_domains(exchange)
    tree = ast.parse(source)
    cls = next(node for node in tree.body if isinstance(node, ast.ClassDef))
    bases = [ast.unparse(base) for base in cls.bases]
    imports = [node for node in tree.body if isinstance(node, (ast.Import, ast.ImportFrom))]
    base_imports = []
    shared_imports = []
    for node in imports:
        if isinstance(node, ast.ImportFrom) and any(alias.name in bases for alias in node.names):
            node.level += 1
            base_imports.append(ast.unparse(node))
        else:
            if isinstance(node, ast.ImportFrom) and node.level:
                node.level += 1
            shared_imports.append(ast.unparse(node))
    groups: dict[str, list[ast.FunctionDef | ast.AsyncFunctionDef]] = defaultdict(list)
    for node in cls.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            groups[domains[node.name]].append(node)
    package = ROOT / ("dcex/async_support" if asynchronous else "dcex") / exchange
    folder = package / "_generated"
    folder.mkdir(parents=True, exist_ok=True)
    classes = []
    for domain, methods in sorted(groups.items()):
        class_name = "Generated" + "".join(word.capitalize() for word in domain.split("_")) + "HTTP"
        classes.append((domain, class_name))
        generated = ast.ClassDef(
            name=class_name,
            bases=cls.bases,
            keywords=[],
            body=[
                ast.Expr(
                    value=ast.Constant(
                        value=f"{domain.replace('_', ' ').capitalize()} API methods."
                    )
                ),
                *methods,
            ],
            decorator_list=[],
            type_params=[],
        )
        ast.fix_missing_locations(generated)
        text = [
            f'"""Generated {exchange} {domain.replace("_", " ")} HTTP methods."""',
            *shared_imports,
            *base_imports,
            "",
            ast.unparse(generated).replace(") -> Any:", ") -> Any:  # noqa: ANN401"),
            "",
        ]
        (folder / f"{domain}_http.py").write_text("\n".join(text), encoding="utf-8")
    init = [
        '"""Compose generated domain methods with the handwritten client bases."""',
        *base_imports,
    ]
    init += [f"from .{domain}_http import {name}" for domain, name in classes]
    init += [
        "",
        "class GeneratedHTTP(" + ", ".join([name for _, name in classes] + bases) + "):",
        '    """Business-specific generated methods with compatible base precedence."""',
        "",
    ]
    (folder / "__init__.py").write_text("\n".join(init), encoding="utf-8")
