"""Generated bybit alpha HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedAlphaHTTP(MarketHTTP):
    """Alpha API methods."""

    def get_alpha_lp_order_list(
        self,
        *,
        order_type: int | None = None,
        token_code: str | None = None,
        order_status: list[Any] | None = None,
        days: int | None = None,
        limit: int | None = None,
        page_index: int | None = None,
        pool_address: str | None = None,
    ) -> dict[str, Any]:
        """
        Get LP Order List. POST /v5/alpha/lp/order-list.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/lp/order-list

        Args:
            order_type: Filter by order type. `0`: All (default), `1`: Stake, `2`: Redeem
            token_code: Filter by token code
            order_status: Filter by order status (multiple values allowed). `1`: Processing, `2`:
                Success, `3`: Failed
            days: Query last N days. Default: `90`, Max: `365
            limit: Results per page. Default: `20`, Max: `100
            page_index: Page number (1-based). Default: `1
            pool_address: Filter by pool contract address
        """
        return self._native_private(
            "get_alpha_lp_order_list",
            self._native_params(
                **{
                    "orderType": order_type,
                    "tokenCode": token_code,
                    "orderStatus": order_status,
                    "days": days,
                    "limit": limit,
                    "pageIndex": page_index,
                    "poolAddress": pool_address,
                }
            ),
        )

    def get_alpha_lp_pay_token_list(
        self, *, chain_code: str | None = None, token_address: str | None = None
    ) -> dict[str, Any]:
        """
        Get LP Pay Token List. POST /v5/alpha/lp/pay-token-list.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/lp/pay-token-list

        Args:
            chain_code: Filter by blockchain identifier
            token_address: Filter by token contract address
        """
        return self._native_private(
            "get_alpha_lp_pay_token_list",
            self._native_params(**{"chainCode": chain_code, "tokenAddress": token_address}),
        )

    def get_alpha_lp_pay_token_price(
        self, *, token_code: list[Any], chain_code: str | None = None
    ) -> dict[str, Any]:
        """
        Get LP Pay Token Price. POST /v5/alpha/lp/pay-token-price.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/lp/pay-token-price

        Args:
            token_code: Array of token codes to query, e.g. `["CEX_1", "CEX_2"]`. Max 50 items
            chain_code: Filter by blockchain identifier
        """
        return self._native_private(
            "get_alpha_lp_pay_token_price",
            self._native_params(**{"tokenCode": token_code, "chainCode": chain_code}),
        )

    def get_alpha_lp_pool_info(self, *, pool_address: str) -> dict[str, Any]:
        """
        Get LP Pool Info. POST /v5/alpha/lp/pool-info.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/lp/pool-info

        Args:
            pool_address: Pool contract address
        """
        return self._native_private(
            "get_alpha_lp_pool_info", self._native_params(**{"poolAddress": pool_address})
        )

    def get_alpha_lp_pool_list(self, *, token_symbol: str | None = None) -> dict[str, Any]:
        """
        Get LP Pool List. POST /v5/alpha/lp/pool-list.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/lp/pool-list

        Args:
            token_symbol: Search pools containing this token symbol, e.g. `ETH`, `USDC
        """
        return self._native_private(
            "get_alpha_lp_pool_list", self._native_params(**{"tokenSymbol": token_symbol})
        )

    def get_alpha_lp_position_list(self) -> dict[str, Any]:
        """
        Get LP Position List. POST /v5/alpha/lp/position-list.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/lp/position-list
        """
        return self._native_private("get_alpha_lp_position_list", [])

    def redeem_alpha_lp(
        self,
        *,
        position_id: int,
        pool_address: str,
        derc_ratio: str,
        receive_token_code: str | None = None,
    ) -> dict[str, Any]:
        """
        Execute LP Redeem. POST /v5/alpha/lp/redeem.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/lp/redeem

        Args:
            position_id: Position ID (from Get LP Position List)
            pool_address: Pool contract address
            derc_ratio: Reduction ratio (0–1). `"0.25"` = redeem 25%, `"0.5"` = redeem 50%, `"1"` =
                close entire position
            receive_token_code: Token code for receiving the redeemed amount
        """
        return self._native_private(
            "redeem_alpha_lp",
            self._native_params(
                **{
                    "positionId": position_id,
                    "poolAddress": pool_address,
                    "dercRatio": derc_ratio,
                    "receiveTokenCode": receive_token_code,
                }
            ),
        )

    def stake_alpha_lp(
        self,
        *,
        position_id: int,
        pool_address: str,
        pay_token_amount: str,
        pay_token_code: str,
        range_upper: str | None = None,
        range_lower: str | None = None,
        price_upper: str | None = None,
        price_lower: str | None = None,
    ) -> dict[str, Any]:
        """
        Execute LP Stake. POST /v5/alpha/lp/stake.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/lp/stake

        Args:
            position_id: Position ID. Use `0` to create a new position, or provide an existing
                position ID to add liquidity
            pool_address: Pool contract address
            pay_token_amount: Payment token amount (positive decimal as string)
            pay_token_code: Payment token code, e.g. `CEX_1` for USDT
            range_upper: Range order upper limit. Use this OR `priceUpper`, not both
            range_lower: Range order lower limit. Use this OR `priceLower`, not both
            price_upper: Price order upper limit (price priority). Use this OR `rangeUpper`, not
                both
            price_lower: Price order lower limit (price priority). Use this OR `rangeLower`, not
                both
        """
        return self._native_private(
            "stake_alpha_lp",
            self._native_params(
                **{
                    "positionId": position_id,
                    "poolAddress": pool_address,
                    "payTokenAmount": pay_token_amount,
                    "payTokenCode": pay_token_code,
                    "rangeUpper": range_upper,
                    "rangeLower": range_lower,
                    "priceUpper": price_upper,
                    "priceLower": price_lower,
                }
            ),
        )

    def buy_alpha_prediction(
        self,
        *,
        token_id: str,
        amount: str,
        pay_token_code: str,
        order_type: int,
        slippage: str,
        event_id: str,
    ) -> dict[str, Any]:
        """
        Execute Buy. POST /v5/alpha/prediction/buy.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/buy

        Args:
            token_id: Outcome token ID to buy (from Get Event Detail)
            amount: USDC amount to invest (positive decimal as string)
            pay_token_code: Payment token code. Phase 1 fixed to `USDC
            order_type: Order type. Refer to predictionOrderType. Phase 1: `1` (FOK) only
            slippage: Maximum acceptable price slippage as decimal. `0.05` = 5% tolerance
            event_id: Event ID associated with the token
        """
        return self._native_private(
            "buy_alpha_prediction",
            self._native_params(
                **{
                    "tokenId": token_id,
                    "amount": amount,
                    "payTokenCode": pay_token_code,
                    "orderType": order_type,
                    "slippage": slippage,
                    "eventId": event_id,
                }
            ),
        )

    def get_alpha_prediction_engine_status(self) -> dict[str, Any]:
        """
        Get Engine Status. GET /v5/alpha/prediction/engine-status.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/engine-status
        """
        return self._native_private("get_alpha_prediction_engine_status", [])

    def get_alpha_prediction_event_detail(
        self,
        *,
        event_id: str | None = None,
        slug: str | None = None,
        has_more_markets: bool | None = None,
    ) -> dict[str, Any]:
        """
        Get Event Detail. POST /v5/alpha/prediction/event-detail.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/event-detail

        Args:
            event_id: Event ID. Use `slug` when available
            slug: URL-friendly event slug. Takes priority over `eventId
            has_more_markets: Whether to include markets from related sub-events. Default: `false
        """
        return self._native_private(
            "get_alpha_prediction_event_detail",
            self._native_params(
                **{"eventId": event_id, "slug": slug, "hasMoreMarkets": has_more_markets}
            ),
        )

    def request_alpha_prediction_order_book(self, *, token_ids: list[Any]) -> dict[str, Any]:
        """
        Get Order Book. POST /v5/alpha/prediction/order-book.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/order-book

        Args:
            token_ids: List of outcome token IDs. Maximum 20
        """
        return self._native_private(
            "request_alpha_prediction_order_book", self._native_params(**{"tokenIds": token_ids})
        )

    def request_alpha_prediction_order_estimate(
        self,
        *,
        token_id: str,
        side: int,
        event_id: str,
        amount: str,
        order_type: int,
        pay_token_code: str | None = None,
    ) -> dict[str, Any]:
        """
        Get Order Estimate. POST /v5/alpha/prediction/order-estimate.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/order-estimate

        Args:
            token_id: Outcome token ID (from Get Event Detail)
            side: Trade direction. Refer to predictionSide
            event_id: Event ID associated with the token
            amount: BUY: USDC to invest. SELL: number of shares to sell (positive decimal as string)
            order_type: Order type. Refer to predictionOrderType. Phase 1: `1` (FOK) only
            pay_token_code: Payment token code. Required for BUY. Phase 1 fixed to `USDC
        """
        return self._native_private(
            "request_alpha_prediction_order_estimate",
            self._native_params(
                **{
                    "tokenId": token_id,
                    "side": side,
                    "eventId": event_id,
                    "amount": amount,
                    "orderType": order_type,
                    "payTokenCode": pay_token_code,
                }
            ),
        )

    def get_alpha_prediction_order_list(
        self,
        *,
        status: int | None = None,
        token_id: str | None = None,
        event_id: str | None = None,
        side: int | None = None,
        days: int | None = None,
        limit: int | None = None,
        page_index: int | None = None,
    ) -> dict[str, Any]:
        """
        Get Order List. POST /v5/alpha/prediction/order-list.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/order-list

        Args:
            status: Filter by order status. Refer to predictionOrderStatus
            token_id: Filter by outcome token ID
            event_id: Filter by event ID
            side: Filter by trade direction. Refer to predictionSide
            days: Look back N days. Max: `90
            limit: Number of records per page
            page_index: Page number starting from `1
        """
        return self._native_private(
            "get_alpha_prediction_order_list",
            self._native_params(
                **{
                    "status": status,
                    "tokenId": token_id,
                    "eventId": event_id,
                    "side": side,
                    "days": days,
                    "limit": limit,
                    "pageIndex": page_index,
                }
            ),
        )

    def get_alpha_prediction_pay_token_list(self) -> dict[str, Any]:
        """
        Get Payment Token List. GET /v5/alpha/prediction/pay-token-list.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/pay-token-list
        """
        return self._native_private("get_alpha_prediction_pay_token_list", [])

    def get_alpha_prediction_portfolio_summary(
        self, *, event_type: int | None = None
    ) -> dict[str, Any]:
        """
        Get Portfolio Summary. POST /v5/alpha/prediction/portfolio-summary.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/portfolio-summary

        Args:
            event_type: Filter by event type. Refer to predictionEventType
        """
        return self._native_private(
            "get_alpha_prediction_portfolio_summary",
            self._native_params(**{"eventType": event_type}),
        )

    def get_alpha_prediction_position_history(
        self,
        *,
        token_id: str | None = None,
        event_id: str | None = None,
        result: int | None = None,
        days: int | None = None,
        limit: int | None = None,
        page_index: int | None = None,
    ) -> dict[str, Any]:
        """
        Get Position History. POST /v5/alpha/prediction/position-history.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/position-history

        Args:
            token_id: Filter by outcome token ID
            event_id: Filter by event ID
            result: Filter by position outcome. Refer to predictionPositionResult
            days: Look back N days. Max: `90
            limit: Number of records per page
            page_index: Page number starting from `1
        """
        return self._native_private(
            "get_alpha_prediction_position_history",
            self._native_params(
                **{
                    "tokenId": token_id,
                    "eventId": event_id,
                    "result": result,
                    "days": days,
                    "limit": limit,
                    "pageIndex": page_index,
                }
            ),
        )

    def get_alpha_prediction_position_list(
        self,
        *,
        token_id: str | None = None,
        event_id: str | None = None,
        limit: int | None = None,
        page_index: int | None = None,
    ) -> dict[str, Any]:
        """
        Get Position List. POST /v5/alpha/prediction/position-list.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/position-list

        Args:
            token_id: Filter by outcome token ID
            event_id: Filter by event ID
            limit: Number of records per page
            page_index: Page number starting from `1
        """
        return self._native_private(
            "get_alpha_prediction_position_list",
            self._native_params(
                **{
                    "tokenId": token_id,
                    "eventId": event_id,
                    "limit": limit,
                    "pageIndex": page_index,
                }
            ),
        )

    def get_alpha_prediction_price_history(self, *, token_id: str, interval: str) -> dict[str, Any]:
        """
        Get Price History. POST /v5/alpha/prediction/price-history.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/price-history

        Args:
            token_id: Outcome token ID
            interval: Time interval. Refer to predictionPriceInterval
        """
        return self._native_private(
            "get_alpha_prediction_price_history",
            self._native_params(**{"tokenId": token_id, "interval": interval}),
        )

    def sell_alpha_prediction(
        self,
        *,
        token_id: str,
        size: str,
        order_type: int,
        slippage: str,
        event_id: str,
        to_token_code: str | None = None,
    ) -> dict[str, Any]:
        """
        Execute Sell. POST /v5/alpha/prediction/sell.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/sell

        Args:
            token_id: Outcome token ID to sell (from Get Position List)
            size: Number of shares to sell (positive decimal as string)
            order_type: Order type. Refer to predictionOrderType. Phase 1: `1` (FOK) only
            slippage: Maximum acceptable price slippage as decimal. `0.05` = 5% tolerance
            event_id: Event ID associated with the token
            to_token_code: Destination token code. Phase 1 fixed to `USDC
        """
        return self._native_private(
            "sell_alpha_prediction",
            self._native_params(
                **{
                    "tokenId": token_id,
                    "size": size,
                    "orderType": order_type,
                    "slippage": slippage,
                    "eventId": event_id,
                    "toTokenCode": to_token_code,
                }
            ),
        )

    def get_alpha_prediction_side_market_list(
        self,
        *,
        event_id: str,
        sort_by: str | None = None,
        market_type: int | None = None,
        limit: int | None = None,
        page_index: int | None = None,
    ) -> dict[str, Any]:
        """
        Get Side Market List. POST /v5/alpha/prediction/side-market-list.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/side-market-list

        Args:
            event_id: Event ID to query markets for
            sort_by: Sort field. Refer to predictionSortBy
            market_type: Filter by market type. Refer to predictionMarketType
            limit: Number of records per page
            page_index: Page number starting from `1
        """
        return self._native_private(
            "get_alpha_prediction_side_market_list",
            self._native_params(
                **{
                    "eventId": event_id,
                    "sortBy": sort_by,
                    "marketType": market_type,
                    "limit": limit,
                    "pageIndex": page_index,
                }
            ),
        )

    def get_alpha_prediction_sports_group_stage_detail(
        self, *, event_type: int, group_name: str | None = None
    ) -> dict[str, Any]:
        """
        Get Sports Group Stage Detail. POST /v5/alpha/prediction/sports/group-stage-detail.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/sports-group-stage-detail

        Args:
            event_type: Sports event type. Refer to predictionEventType. Phase 1: `1` (FIFA_2026)
            group_name: Filter by group name (e.g., `A`, `B`, … `L` for FIFA 2026)
        """
        return self._native_private(
            "get_alpha_prediction_sports_group_stage_detail",
            self._native_params(**{"eventType": event_type, "groupName": group_name}),
        )

    def get_alpha_prediction_sports_match_list(
        self,
        *,
        event_type: int,
        status: int | None = None,
        start_time: int | None = None,
        end_time: int | None = None,
        stage_code: str | None = None,
        limit: int | None = None,
        page_index: int | None = None,
    ) -> dict[str, Any]:
        """
        Get Sports Match List. POST /v5/alpha/prediction/sports/match-list.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/sports-match-list

        Args:
            event_type: Sports event type. Refer to predictionEventType. Phase 1: `1` (FIFA_2026)
            status: Match status filter. Refer to predictionMatchStatus
            start_time: Filter matches starting after this timestamp (UTC milliseconds)
            end_time: Filter matches starting before this timestamp (UTC milliseconds)
            stage_code: Filter by tournament stage. Refer to predictionStageCode
            limit: Number of records per page
            page_index: Page number starting from `1
        """
        return self._native_private(
            "get_alpha_prediction_sports_match_list",
            self._native_params(
                **{
                    "eventType": event_type,
                    "status": status,
                    "startTime": start_time,
                    "endTime": end_time,
                    "stageCode": stage_code,
                    "limit": limit,
                    "pageIndex": page_index,
                }
            ),
        )

    def get_alpha_prediction_sports_timeline_stages(self, *, event_type: int) -> dict[str, Any]:
        """
        Get Sports Timeline Stages. GET /v5/alpha/prediction/sports/timeline-stages.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/sports-timeline-stages

        Args:
            event_type: Sports event type. Refer to predictionEventType. Phase 1: `1` (FIFA_2026)
        """
        return self._native_private(
            "get_alpha_prediction_sports_timeline_stages",
            self._native_params(**{"eventType": event_type}),
        )

    def get_alpha_prediction_token_price(self, *, token_ids: list[Any]) -> dict[str, Any]:
        """
        Get Token Price. POST /v5/alpha/prediction/token-price.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/prediction/token-price

        Args:
            token_ids: List of outcome token IDs to query. Maximum 20
        """
        return self._native_private(
            "get_alpha_prediction_token_price", self._native_params(**{"tokenIds": token_ids})
        )

    def get_alpha_trade_asset_detail(
        self, *, chain_code: str, token_address: str
    ) -> dict[str, Any]:
        """
        Get Asset Detail. POST /v5/alpha/trade/asset-detail.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/trade/asset-detail

        Args:
            chain_code: Blockchain code, e.g. `ETH`, `SOL`, `BSC
            token_address: Token contract address on the specified chain
        """
        return self._native_private(
            "get_alpha_trade_asset_detail",
            self._native_params(**{"chainCode": chain_code, "tokenAddress": token_address}),
        )

    def get_alpha_trade_asset_list(self) -> dict[str, Any]:
        """
        Get Asset List. POST /v5/alpha/trade/asset-list.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/trade/asset-list
        """
        return self._native_private("get_alpha_trade_asset_list", [])

    def request_alpha_trade_biz_token_details(
        self, *, chain_code: str, token_address: str
    ) -> dict[str, Any]:
        """
        Get Token Details. POST /v5/alpha/trade/biz-token-details.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/trade/biz-token-details

        Args:
            chain_code: Blockchain code, e.g. `ETH`, `SOL`, `BSC
            token_address: Token contract address on the specified chain
        """
        return self._native_private(
            "request_alpha_trade_biz_token_details",
            self._native_params(**{"chainCode": chain_code, "tokenAddress": token_address}),
        )

    def get_alpha_trade_biz_token_list(self, *, token_tag: int | None = None) -> dict[str, Any]:
        """
        Get Biz Token List. POST /v5/alpha/trade/biz-token-list.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/trade/biz-token-list

        Args:
            token_tag: Token tag filter. `0`: All (default), `1`: New token sniping, `2`: On-chain
                hot token
        """
        return self._native_private(
            "get_alpha_trade_biz_token_list", self._native_params(**{"tokenTag": token_tag})
        )

    def get_alpha_trade_biz_token_price_list(
        self, *, token_address_info: list[Any]
    ) -> dict[str, Any]:
        """
        Get Token Price List. POST /v5/alpha/trade/biz-token-price-list.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/trade/biz-token-price-list

        Args:
            token_address_info: List of token identifiers to query. Maximum 20 items per request
        """
        return self._native_private(
            "get_alpha_trade_biz_token_price_list",
            self._native_params(**{"tokenAddressInfo": token_address_info}),
        )

    def get_alpha_trade_order_list(
        self,
        *,
        trade_type: int | None = None,
        token_code: str | None = None,
        order_status: list[Any] | None = None,
        days: int | None = None,
        limit: int,
        page_index: int,
        direction: str | None = None,
    ) -> dict[str, Any]:
        """
        Get Order List. POST /v5/alpha/trade/order-list.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/trade/order-list

        Args:
            trade_type: Filter by trade type. `0`: All (default), `1`: Purchase, `2`: Redeem
            token_code: Filter by token code
            order_status: Filter by order status (multiple values allowed). `1`: Processing, `2`:
                Success, `3`: Failed
            days: Query last N days. Range: [0, 90]. `0` uses system default (90 days). Default: `0
            limit: Results per page. Range: [1, 100]
            page_index: Page number (1-based)
            direction: Pagination direction. `prev`, `next
        """
        return self._native_private(
            "get_alpha_trade_order_list",
            self._native_params(
                **{
                    "tradeType": trade_type,
                    "tokenCode": token_code,
                    "orderStatus": order_status,
                    "days": days,
                    "limit": limit,
                    "pageIndex": page_index,
                    "direction": direction,
                }
            ),
        )

    def get_alpha_trade_pay_token_list(
        self, *, chain_code: str, token_address: str
    ) -> dict[str, Any]:
        """
        Get Payment Token List. POST /v5/alpha/trade/pay-token-list.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/trade/pay-token-list

        Args:
            chain_code: Blockchain code, e.g. `SOL`, `MANTLE
            token_address: Token contract address on the specified chain
        """
        return self._native_private(
            "get_alpha_trade_pay_token_list",
            self._native_params(**{"chainCode": chain_code, "tokenAddress": token_address}),
        )

    def purchase_alpha_trade(
        self,
        *,
        from_token_code: str,
        from_token_amount: str,
        to_token_code: str,
        slippage: str,
        quote_data: str,
        gas: str,
        quote_mode: int,
        correcting_code: str,
        tenant: str | None = None,
    ) -> dict[str, Any]:
        """
        Execute Purchase. POST /v5/alpha/trade/purchase.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/trade/trade-purchase

        Args:
            from_token_code: Payment token code (`CEX_`), e.g. `CEX_1` for USDT. Must match the
                quote request
            from_token_amount: Payment amount (positive decimal as string). Must match the quote
                request
            to_token_code: Target on-chain token code (`DEX_`), e.g. `DEX_123`. Must match the quote
                request
            slippage: Slippage tolerance as decimal. `0.005` = 0.5%, `0.01` = 1%, `0.05` = 5%
            quote_data: Base64-encoded quote data. Must pass as-is from the `/quote` response
            gas: Estimated gas fee. Must pass as-is from the `/quote` response
            quote_mode: Quote mode. Must be consistent with the `/quote` request. `0`: Auto, `1`:
                Price Priority, `2`: Success Rate Priority
            correcting_code: MD5 checksum for data integrity. Must pass as-is from the `/quote`
                response
            tenant: Optional tenant identifier
        """
        return self._native_private(
            "purchase_alpha_trade",
            self._native_params(
                **{
                    "fromTokenCode": from_token_code,
                    "fromTokenAmount": from_token_amount,
                    "toTokenCode": to_token_code,
                    "slippage": slippage,
                    "quoteData": quote_data,
                    "gas": gas,
                    "quoteMode": quote_mode,
                    "correctingCode": correcting_code,
                    "tenant": tenant,
                }
            ),
        )

    def request_alpha_trade_quote(
        self,
        *,
        trade_type: int,
        from_token_code: str,
        from_token_amount: str,
        to_token_code: str,
        quote_mode: int | None = None,
    ) -> dict[str, Any]:
        """
        Get Trade Quote. POST /v5/alpha/trade/quote.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/trade/trade-quote

        Args:
            trade_type: Trade type. `1`: Purchase (buy on-chain token with payment token), `2`:
                Redeem (sell on-chain token for payment token)
            from_token_code: Source token code (`CEX_` or `DEX_`). Purchase: CEX token (e.g. `CEX_1`
                for USDT); Redeem: DEX token (e.g. `DEX_123`)
            from_token_amount: Amount to pay, string-formatted positive decimal. Must be greater
                than 0
            to_token_code: Target token code (`CEX_` or `DEX_`). Purchase: DEX token; Redeem: CEX
                token (e.g. `CEX_1` for USDT)
            quote_mode: Quote mode. `0`: Auto (default), `1`: Price Priority, `2`: Success Rate
                Priority
        """
        return self._native_private(
            "request_alpha_trade_quote",
            self._native_params(
                **{
                    "tradeType": trade_type,
                    "fromTokenCode": from_token_code,
                    "fromTokenAmount": from_token_amount,
                    "toTokenCode": to_token_code,
                    "quoteMode": quote_mode,
                }
            ),
        )

    def redeem_alpha_trade(
        self,
        *,
        from_token_code: str,
        from_token_amount: str,
        to_token_code: str,
        slippage: str,
        quote_data: str,
        gas: str,
        quote_mode: int,
        correcting_code: str,
        tenant: str | None = None,
    ) -> dict[str, Any]:
        """
        Execute Redeem. POST /v5/alpha/trade/redeem.

        Source: https://bybit-exchange.github.io/docs/v5/alpha/trade/trade-redeem

        Args:
            from_token_code: On-chain token to sell (`DEX_`). Must match the quote request, e.g.
                `DEX_123
            from_token_amount: Amount to sell (positive decimal as string). Must match the quote
                request
            to_token_code: Payment token to receive (`CEX_`), e.g. `CEX_1` for USDT. Must match the
                quote request
            slippage: Slippage tolerance as decimal. `0.005` = 0.5%, `0.01` = 1%, `0.05` = 5%
            quote_data: Base64-encoded quote data. Must pass as-is from the `/quote` response
            gas: Estimated gas fee. Must pass as-is from the `/quote` response
            quote_mode: Quote mode. Must be consistent with the `/quote` request. `0`: Auto, `1`:
                Price Priority, `2`: Success Rate Priority
            correcting_code: MD5 checksum for data integrity. Must pass as-is from the `/quote`
                response
            tenant: Optional tenant identifier
        """
        return self._native_private(
            "redeem_alpha_trade",
            self._native_params(
                **{
                    "fromTokenCode": from_token_code,
                    "fromTokenAmount": from_token_amount,
                    "toTokenCode": to_token_code,
                    "slippage": slippage,
                    "quoteData": quote_data,
                    "gas": gas,
                    "quoteMode": quote_mode,
                    "correctingCode": correcting_code,
                    "tenant": tenant,
                }
            ),
        )
