"""Generated bybit broker HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedBrokerHTTP(MarketHTTP):
    """Broker API methods."""

    def get_broker_ip_changelog(
        self,
        *,
        start_time: str | None = None,
        end_time: str | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """
        Get Broker IP Change Log. GET /v5/broker/ip/changelog.

        Source: https://bybit-exchange.github.io/docs/v5/broker/api-broker/ip-changelog

        Args:
            start_time: Filter start time, Unix timestamp in milliseconds
            end_time: Filter end time, Unix timestamp in milliseconds
            limit: Records per page. Range: [1, 50]. Default: 20
            cursor: Pagination cursor. Use the `nextPageCursor` value from the previous response
        """
        return self._native_private(
            "get_broker_ip_changelog",
            self._native_params(
                **{"startTime": start_time, "endTime": end_time, "limit": limit, "cursor": cursor}
            ),
        )

    def get_broker_whitelist_ip(self) -> dict[str, Any]:
        """
        Get Broker Whitelist IP. GET /v5/broker/whitelist/ip.

        Source: https://bybit-exchange.github.io/docs/v5/broker/api-broker/whitelist-ip
        """
        return self._native_private("get_broker_whitelist_ip", [])

    def get_broker_account_info(self) -> dict[str, Any]:
        """
        Get Account Info. GET /v5/broker/account-info.

        Source: https://bybit-exchange.github.io/docs/v5/broker/exchange-broker/account-info
        """
        return self._native_private("get_broker_account_info", [])

    def get_broker_earnings_info(
        self,
        *,
        biz_type: str | None = None,
        begin: str | None = None,
        end: str | None = None,
        uid: str | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """
        Get Earning. GET /v5/broker/earnings-info.

        Source: https://bybit-exchange.github.io/docs/v5/broker/exchange-broker/exchange-earning

        Args:
            biz_type: Business type. `SPOT`, `DERIVATIVES`, `OPTIONS`, `CONVERT`, `FIAT_CONVERT
            begin: Begin date, in the format of YYYYMMDD, e.g, 20231201, search the data from 1st
                Dec 2023 00:00:00 UTC (include)
            end: End date, in the format of YYYYMMDD, e.g, 20231201, search the data before 2nd Dec
                2023 00:00:00 UTC (exclude)
            uid: To get results for a specific subaccount: Enter the subaccount UIDTo get results
                for all subaccounts: Leave the field empty
            limit: Limit for data size per page. [`1`, `1000`]. Default: `1000
            cursor: Cursor. Use the `nextPageCursor` token from the response to retrieve the next
                page of the result set
        """
        return self._native_private(
            "get_broker_earnings_info",
            self._native_params(
                **{
                    "bizType": biz_type,
                    "begin": begin,
                    "end": end,
                    "uid": uid,
                    "limit": limit,
                    "cursor": cursor,
                }
            ),
        )

    def get_broker_apilimit_query_all(
        self, *, limit: str | None = None, cursor: str | None = None, uids: str | None = None
    ) -> dict[str, Any]:
        """
        Get All Rate Limits. GET /v5/broker/apilimit/query-all.

        Source: https://bybit-exchange.github.io/docs/v5/broker/exchange-broker/rate-limit/query-all

        Args:
            limit: Limit for data size per page. [`1`, `1000`]. Default: `1000
            cursor: Cursor. Use the `nextPageCursor` token from the response to retrieve the next
                page of the result set
            uids: Multiple UIDs across different master accounts, separated by commas. Returns all
                subaccounts by default
        """
        return self._native_private(
            "get_broker_apilimit_query_all",
            self._native_params(**{"limit": limit, "cursor": cursor, "uids": uids}),
        )

    def get_broker_apilimit_query_cap(self) -> dict[str, Any]:
        """
        Get Rate Limit Cap. GET /v5/broker/apilimit/query-cap.

        Source: https://bybit-exchange.github.io/docs/v5/broker/exchange-broker/rate-limit/query-cap
        """
        return self._native_private("get_broker_apilimit_query_cap", [])

    def set_broker_apilimit(self, *, list_: list[Any]) -> dict[str, Any]:
        """
        Set Rate Limit. POST /v5/broker/apilimit/set.

        Source: https://bybit-exchange.github.io/docs/v5/broker/exchange-broker/rate-limit/set

        Args:
            list_: Object
        """
        return self._native_private("set_broker_apilimit", self._native_params(**{"list": list_}))

    def get_broker_asset_query_sub_member_deposit_record(
        self,
        *,
        id: str | None = None,
        tx_id: str | None = None,
        sub_member_id: str | None = None,
        coin: str | None = None,
        start_time: int | None = None,
        end_time: int | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """
        Get Sub Account Deposit Records. GET /v5/broker/asset/query-sub-member-deposit-record.

        Source: https://bybit-exchange.github.io/docs/v5/broker/exchange-broker/sub-deposit-record

        Args:
            id: Internal ID: Can be used to uniquely identify and filter the deposit. When combined
                with other parameters, this field takes the highest priority
            tx_id: Transaction ID: Please note that data generated before Jan 1, 2024 cannot be
                queried using txID
            sub_member_id: Sub UID
            coin: Coin, uppercase only
            start_time: The start timestamp (ms) _Note: the query logic is actually effective based
                on **second** level_
            end_time: The end timestamp (ms) _Note: the query logic is actually effective based on
                **second** level_
            limit: Limit for data size per page. [`1`, `50`]. Default: `50
            cursor: Cursor. Use the `nextPageCursor` token from the response to retrieve the next
                page of the result set
        """
        return self._native_private(
            "get_broker_asset_query_sub_member_deposit_record",
            self._native_params(
                **{
                    "id": id,
                    "txID": tx_id,
                    "subMemberId": sub_member_id,
                    "coin": coin,
                    "startTime": start_time,
                    "endTime": end_time,
                    "limit": limit,
                    "cursor": cursor,
                }
            ),
        )

    def request_broker_award_distribution_record(
        self,
        *,
        account_id: str,
        award_id: str,
        spec_code: str,
        with_used_amount: bool | None = None,
    ) -> dict[str, Any]:
        """
        Get Issued Voucher. POST /v5/broker/award/distribution-record.

        Source: https://bybit-exchange.github.io/docs/v5/broker/reward/get-issue-voucher

        Args:
            account_id: User ID
            award_id: Voucher ID
            spec_code: Customised unique spec code, up to 8 characters
            with_used_amount: Whether or not to return the amount used by the user `true``false`
                (default)
        """
        return self._native_private(
            "request_broker_award_distribution_record",
            self._native_params(
                **{
                    "accountId": account_id,
                    "awardId": award_id,
                    "specCode": spec_code,
                    "withUsedAmount": with_used_amount,
                }
            ),
        )

    def request_broker_award_distribute_award(
        self, *, account_id: str, award_id: str, spec_code: str, amount: str, broker_id: str
    ) -> dict[str, Any]:
        """
        Issue Voucher. POST /v5/broker/award/distribute-award.

        Source: https://bybit-exchange.github.io/docs/v5/broker/reward/issue-voucher

        Args:
            account_id: User ID
            award_id: Voucher ID
            spec_code: Customised unique spec code, up to 8 characters
            amount: Issue amount Spot airdrop supports up to 16 decimalsOther types supports up to 4
                decimals
            broker_id: Broker ID
        """
        return self._native_private(
            "request_broker_award_distribute_award",
            self._native_params(
                **{
                    "accountId": account_id,
                    "awardId": award_id,
                    "specCode": spec_code,
                    "amount": amount,
                    "brokerId": broker_id,
                }
            ),
        )

    def get_broker_award_info(self, *, id: str) -> dict[str, Any]:
        """
        Get Voucher Spec. POST /v5/broker/award/info.

        Source: https://bybit-exchange.github.io/docs/v5/broker/reward/voucher

        Args:
            id: Voucher ID
        """
        return self._native_private("get_broker_award_info", self._native_params(**{"id": id}))
