"""Generated bybit compliance HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedComplianceHTTP(MarketHTTP):
    """Compliance API methods."""

    def commit_compliance_appeal(
        self, *, appeal_id: str, decision_type: int | None = None, items_data: list[Any]
    ) -> dict[str, Any]:
        """
        Commit Appeal. POST /v5/compliance/appeal/commit.

        Source: https://bybit-exchange.github.io/docs/v5/tm-onchain/appeal-commit

        Args:
            appeal_id: Appeal ID
            decision_type: 0` = normal submit (default); `1` = refuse submit, appeal will be disused
            items_data: Submission content per material, one element per material
        """
        return self._native_private(
            "commit_compliance_appeal",
            self._native_params(
                **{"appealId": appeal_id, "decisionType": decision_type, "itemsData": items_data}
            ),
        )

    def get_compliance_appeal_detail(self, *, appeal_id: str) -> dict[str, Any]:
        """
        Get Appeal Detail. GET /v5/compliance/appeal/detail.

        Source: https://bybit-exchange.github.io/docs/v5/tm-onchain/appeal-detail

        Args:
            appeal_id: Appeal ID, obtained from the list endpoint or the WebSocket push
        """
        return self._native_private(
            "get_compliance_appeal_detail", self._native_params(**{"appealId": appeal_id})
        )

    def get_compliance_appeal_list(
        self,
        *,
        appeal_types: str | None = None,
        page: int | None = None,
        page_size: int | None = None,
    ) -> dict[str, Any]:
        """
        Get Appeal List. GET /v5/compliance/appeal/list.

        Official spec incomplete; not verified live. appeal_types is passed through because array
        query encoding is unspecified.
        Source: https://bybit-exchange.github.io/docs/v5/tm-onchain/appeal-list

        Args:
            appeal_types: Raw query value. Official example uses TM_Onchain; multi-value encoding is
                not specified.
            page: Page number, starts from `1`, default `1
            page_size: Page size, default `20`, max `100
        """
        return self._native_private(
            "get_compliance_appeal_list",
            self._native_params(
                **{"appealTypes": appeal_types, "page": page, "pageSize": page_size}
            ),
        )
