"""Generated bybit convert HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedConvertHTTP(MarketHTTP):
    """Convert API methods."""

    def get_ins_loan_ltv_convert(self) -> dict[str, Any]:
        """
        Get LTV. GET /v5/ins-loan/ltv-convert.

        Source: https://bybit-exchange.github.io/docs/v5/otc/ltv-convert
        """
        return self._native_private("get_ins_loan_ltv_convert", [])

    def get_ins_loan_ensure_tokens_convert(
        self, *, product_id: str | None = None
    ) -> dict[str, Any]:
        """
        Get Margin Coin Info. GET /v5/ins-loan/ensure-tokens-convert.

        Source: https://bybit-exchange.github.io/docs/v5/otc/margin-coin-convert-info

        Args:
            product_id: Product ID. If not passed, returns all margin products. For spot, it returns
                coins with a `convertRatio` greater than 0.
        """
        return self._native_public(
            "get_ins_loan_ensure_tokens_convert", self._native_params(**{"productId": product_id})
        )
