"""Generated bybit fiat HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedFiatHTTP(MarketHTTP):
    """Fiat API methods."""

    def get_fiat_balance_query(self, *, currency: str | None = None) -> dict[str, Any]:
        """
        Get Balance. GET /v5/fiat/balance-query.

        Source: https://bybit-exchange.github.io/docs/v5/asset/fiat-convert/balance-query

        Args:
            currency: Fiat`: fiat currency code (ISO 4217) etc: KZT. not set will query all fiat
                balance list
        """
        return self._native_private(
            "get_fiat_balance_query", self._native_params(**{"currency": currency})
        )

    def request_fiat_trade_execute(
        self,
        *,
        quote_tx_id: str,
        sub_user_id: str,
        webhook_url: str | None = None,
        merchant_request_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Confirm a Quote . POST /v5/fiat/trade-execute.

        Source: https://bybit-exchange.github.io/docs/v5/asset/fiat-convert/confirm-quote

        Args:
            quote_tx_id: The quote tx ID from Request a Quote
            sub_user_id: The user's sub userId in bybit
            webhook_url: API URL to call when order is successful or failed (max 256 characters)
            merchant_request_id: Customised request ID(maximum length of 36)Generally it is useless,
                but it is convenient to track the quote request internally if you fill this field
        """
        return self._native_private(
            "request_fiat_trade_execute",
            self._native_params(
                **{
                    "quoteTxId": quote_tx_id,
                    "subUserId": sub_user_id,
                    "webhookUrl": webhook_url,
                    "MerchantRequestId": merchant_request_id,
                }
            ),
        )

    def get_fiat_query_coin_list(self, *, side: str | None = None) -> dict[str, Any]:
        """
        Get Trading Pair List. GET /v5/fiat/query-coin-list.

        Source: https://bybit-exchange.github.io/docs/v5/asset/fiat-convert/query-coin-list

        Args:
            side: 0`: buy, buy crypto sell fiat; `1`: sell, sell crypto buy fiat
        """
        return self._native_private(
            "get_fiat_query_coin_list", self._native_params(**{"side": side})
        )

    def get_fiat_query_trade_history(
        self,
        *,
        index: int | None = None,
        limit: int | None = None,
        start_time: str | None = None,
        end_time: str | None = None,
    ) -> dict[str, Any]:
        """
        Get Convert History. GET /v5/fiat/query-trade-history.

        Source: https://bybit-exchange.github.io/docs/v5/asset/fiat-convert/query-trade-history

        Args:
            index: Page number,started from 1, default 1
            limit: Page Size [20-100] 20 records by default,up to 100 records, return 100 when
                exceeds 100
            start_time: Query start time(Millisecond timestamp)
            end_time: Query end time(Millisecond timestamp)
        """
        return self._native_private(
            "get_fiat_query_trade_history",
            self._native_params(
                **{"index": index, "limit": limit, "startTime": start_time, "endTime": end_time}
            ),
        )

    def get_fiat_trade_query(
        self, *, trade_no: str | None = None, merchant_request_id: str | None = None
    ) -> dict[str, Any]:
        """
        Get Convert Status. GET /v5/fiat/trade-query.

        Source: https://bybit-exchange.github.io/docs/v5/asset/fiat-convert/query-trade

        Args:
            trade_no: Trade order No,tradeNo or merchantRequestId must be provided
            merchant_request_id: Customised request ID,tradeNo or merchantRequestId must be provided
        """
        return self._native_private(
            "get_fiat_trade_query",
            self._native_params(**{"tradeNo": trade_no, "merchantRequestId": merchant_request_id}),
        )

    def request_fiat_quote_apply(
        self,
        *,
        from_coin: str,
        from_coin_type: str,
        to_coin: str,
        to_coin_type: str,
        request_amount: str,
        request_coin_type: str | None = None,
    ) -> dict[str, Any]:
        """
        Request a Quote . POST /v5/fiat/quote-apply.

        Source: https://bybit-exchange.github.io/docs/v5/asset/fiat-convert/quote-apply

        Args:
            from_coin: Convert from coin (coin to sell)
            from_coin_type: fiat` or `crypto
            to_coin: Convert to coin (coin to buy)
            to_coin_type: fiat` or `crypto
            request_amount: request coin amount (the amount you want to sell)
            request_coin_type: coinType you want to sell, `fiat` or `crypto`, default to `fiat
        """
        return self._native_private(
            "request_fiat_quote_apply",
            self._native_params(
                **{
                    "fromCoin": from_coin,
                    "fromCoinType": from_coin_type,
                    "toCoin": to_coin,
                    "toCoinType": to_coin_type,
                    "requestAmount": request_amount,
                    "requestCoinType": request_coin_type,
                }
            ),
        )

    def get_fiat_reference_price(self, *, symbol: str) -> dict[str, Any]:
        """
        Get Reference Price. GET /v5/fiat/reference-price.

        Source: https://bybit-exchange.github.io/docs/v5/asset/fiat-convert/reference-price

        Args:
            symbol: Coin Pair, such as EUR-USDT
        """
        return self._native_private(
            "get_fiat_reference_price", self._native_params(**{"symbol": symbol})
        )
