"""Generated bybit file upload HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedFileUploadHTTP(MarketHTTP):
    """File upload API methods."""

    def request_file_get_file_upload_sign(
        self, *, file_type: str, file_md5: str, file_len: int, file_name: str, file_mime_type: str
    ) -> dict[str, Any]:
        """
        Get File Upload Sign. POST /v5/file/get-file-upload-sign.

        Source: https://bybit-exchange.github.io/docs/v5/file/file-upload-sign

        Args:
            file_type: File business type: `fiat-pdf`, `fiat-image`, `fiat-video
            file_md5: Base64-encoded MD5 of the file content. Formula: `base64(md5(file_content))`,
                MD5 is **raw binary (16 bytes), not hex**.Golden cases for self-verification:Empty
                string `""` → `1B2M2Y8AsgTpgAmY7PhCfg==``"abc"` (3 bytes) →
                `kAFQmDzST7DWlj99KOF/cg==
            file_len: Current file size in bytes. Upper limit: `fiat-pdf` / `fiat-image` /
                `fiat-video` all `104857600` (100 MB)
            file_name: Full file name, e.g. `evidence.pdf`, `screenshot.png`, `video.mp4
            file_mime_type: File `Content-Type`.`fiat-pdf`: `application/pdf``fiat-image`:
                `image/jpeg`, `image/png`, `image/jpg``fiat-video`: `video/mp4`, `video/quicktime`,
                `video/3gpp`, `video/x-msvideo`, `video/avi`, `video/rm`, `video/rmvb`, `video/wmv
        """
        return self._native_private(
            "request_file_get_file_upload_sign",
            self._native_params(
                **{
                    "fileType": file_type,
                    "fileMd5": file_md5,
                    "fileLen": file_len,
                    "fileName": file_name,
                    "fileMimeType": file_mime_type,
                }
            ),
        )

    def request_file_report_file_upload(self, *, resource_id: str) -> dict[str, Any]:
        """
        Report File Upload. POST /v5/file/report-file-upload.

        Source: https://bybit-exchange.github.io/docs/v5/file/report-file-upload

        Args:
            resource_id: Resource ID returned by Get File Upload Sign
        """
        return self._native_private(
            "request_file_report_file_upload", self._native_params(**{"resourceId": resource_id})
        )
