"""Generated bybit referral HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedReferralHTTP(MarketHTTP):
    """Referral API methods."""

    def get_user_invitation_referrals(
        self, *, status: str | None = None, size: str | None = None, cursor: str | None = None
    ) -> dict[str, Any]:
        """
        Get Friend Referrals. GET /v5/user/invitation/referrals.

        Source: https://bybit-exchange.github.io/docs/v5/user/friend-referral

        Args:
            status: Invitation relationship status, `0`: alive; `1`: invalid. By default, returns
                all status
            size: Data size per page [1, 100]. Return 20 records by default
            cursor: Cursor. Use the `nextCursor` token from the response to retrieve the next page
                of the result set
        """
        return self._native_private(
            "get_user_invitation_referrals",
            self._native_params(**{"status": status, "size": size, "cursor": cursor}),
        )
