"""Generated bybit trading HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedTradingHTTP(MarketHTTP):
    """Trading API methods."""

    def get_mmp_state(self, *, base_coin: str) -> dict[str, Any]:
        """
        Get MMP State. GET /v5/account/mmp-state.

        Source: https://bybit-exchange.github.io/docs/v5/account/get-mmp-state

        Args:
            base_coin: Base coin, uppercase only
        """
        return self._native_private("get_mmp_state", self._native_params(**{"baseCoin": base_coin}))

    def reset_mmp(self, *, base_coin: str) -> dict[str, Any]:
        """
        Reset MMP. POST /v5/account/mmp-reset.

        Source: https://bybit-exchange.github.io/docs/v5/account/reset-mmp

        Args:
            base_coin: Base coin, uppercase only
        """
        return self._native_private("reset_mmp", self._native_params(**{"baseCoin": base_coin}))

    def set_mmp_config(
        self,
        *,
        base_coin: str,
        window: str,
        frozen_period: str,
        qty_limit: str,
        delta_limit: str,
        vega_limit: str | None = None,
    ) -> dict[str, Any]:
        """
        Set MMP. POST /v5/account/mmp-modify.

        Source: https://bybit-exchange.github.io/docs/v5/account/set-mmp

        Args:
            base_coin: Base coin, uppercase only
            window: Time window (ms)
            frozen_period: Frozen period (ms). "0" means the trade will remain frozen until manually
                reset
            qty_limit: Trade qty limit (positive and up to 2 decimal places)
            delta_limit: Delta limit (positive and up to 2 decimal places)
            vega_limit: Vega limit (positive and up to 2 decimal places). Default: `500000
        """
        return self._native_private(
            "set_mmp_config",
            self._native_params(
                **{
                    "baseCoin": base_coin,
                    "window": window,
                    "frozenPeriod": frozen_period,
                    "qtyLimit": qty_limit,
                    "deltaLimit": delta_limit,
                    "vegaLimit": vega_limit,
                }
            ),
        )
