"""Generated bybit withdrawals HTTP methods."""

from typing import Any

from .._market_http import MarketHTTP


class GeneratedWithdrawalsHTTP(MarketHTTP):
    """Withdrawals API methods."""

    def cancel_withdrawal(self, *, id: str) -> dict[str, Any]:
        """
        Cancel Withdrawal. POST /v5/asset/withdraw/cancel.

        Source: https://bybit-exchange.github.io/docs/v5/asset/withdraw/cancel-withdraw

        Args:
            id: Withdrawal ID
        """
        return self._native_private("cancel_withdrawal", self._native_params(**{"id": id}))

    def create_withdrawal(
        self,
        *,
        coin: str,
        chain: str | None = None,
        address: str,
        tag: str | None = None,
        amount: str,
        timestamp: int,
        force_chain: int | None = None,
        account_type: str,
        fee_type: int | None = None,
        request_id: str | None = None,
        transaction_purpose: str | None = None,
        questionnaire: str | None = None,
        beneficiary: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """
        Withdraw. POST /v5/asset/withdraw/create.

        API withdrawals have no second confirmation; they execute on submit.
        With force_chain=2 the recipient may be another Bybit user.
        Source: https://bybit-exchange.github.io/docs/v5/asset/withdraw/withdraw

        Args:
            coin: Coin, uppercase only
            chain: Chain `forceChain`=0 or 1: this field is **required**`forceChain`=2: this field
                can be null
            address: forceChain`=0 or 1: fill wallet address, and make sure you add address in the
                address book first. Please note that the address is case sensitive, so use the exact
                same address added in address book`forceChain`=2: fill Bybit UID, and it can only be
                another Bybit **main** account UID. Make sure you add UID in the address book first
            tag: Tag **Required** if tag exists in the wallet address list.**Note**: please do not
                set a tag/memo in the address book if the chain does not support tag
            amount: Withdraw amount
            timestamp: Current timestamp (ms). Used for preventing from withdraw replay
            force_chain: Whether or not to force an on-chain withdrawal`0`(default): If the address
                is parsed out to be an internal address, then internal transfer (**Bybit main
                account only**)`1`: Force the withdrawal to occur on-chain`2`: Use UID to withdraw
            account_type: Select the wallet to be withdrawn from `FUND`: Funding wallet`UTA`: System
                transfers the funds to Funding wallet to withdraw`EARN`: some coins may not support
                to be withdrawn via Earn account, please transfer it to Funding wallet then
                withdraw`FUND,UTA,EARN`: For combo withdrawals, funds will be deducted from the
                Funding wallet first. If the balance is insufficient, the remaining amount will be
                deducted from the UTA wallet and Earn account.
            fee_type: Handling fee option `0`(default): input amount is the actual amount received,
                so you have to calculate handling fee manually`1`: input amount is not the actual
                amount you received, the system will help to deduct the handling fee automatically
            request_id: Customised ID, globally unique, it is used for idempotent verification A
                combination of letters (case sensitive) and numbers, which can be pure letters or
                pure numbers and the length must be between 1 and 32 digits
            transaction_purpose: Purpose of the withdrawal transaction, need at least 20 characters,
                Required for Bybit Turkey site users
            questionnaire: Travel Rule questionnaire info, JSON string, ≤16384 bytes. Supersedes
                `beneficiary` and `transactionPurpose` when both are present. **New integrations are
                always recommended to use this field to submit travel rule**. See Questionnaire for
                field structure by compliance zone
            beneficiary: Travel rule info. It is required for kyc/kyb=KOR (Korean), kyc=IND (India)
                users, and users who registered in Bybit Turkey(TR), Bybit Kazakhstan(KZ), Bybit
                Indonesia (ID)
        """
        return self._native_private(
            "create_withdrawal",
            self._native_params(
                **{
                    "coin": coin,
                    "chain": chain,
                    "address": address,
                    "tag": tag,
                    "amount": amount,
                    "timestamp": timestamp,
                    "forceChain": force_chain,
                    "accountType": account_type,
                    "feeType": fee_type,
                    "requestId": request_id,
                    "transactionPurpose": transaction_purpose,
                    "questionnaire": questionnaire,
                    "beneficiary": beneficiary,
                }
            ),
        )
