use super::BackpackClient;

crate::exchanges::impl_exchange_method_wrappers! {
    BackpackClient;
    public [
        get_assets() => get_assets_with,
        get_collateral() => get_collateral_with,
        get_borrow_lend_markets() => get_borrow_lend_markets_with,
        get_borrow_lend_market_history(interval => "interval") => get_borrow_lend_market_history_with,
        get_borrow_lend_apy() => get_borrow_lend_apy_with,
        get_markets() => get_markets_with,
        get_market(product_symbol => "product_symbol") => get_market_with,
        get_order_book_depth(product_symbol => "product_symbol") => get_order_book_depth_with,
        get_market_sessions() => get_market_sessions_with,
        get_securities() => get_securities_with,
        get_mark_prices() => get_mark_prices_with,
        get_open_interest() => get_open_interest_with,
        get_funding_rates(product_symbol => "product_symbol") => get_funding_rates_with,
        get_klines(product_symbol => "product_symbol", interval => "interval", start_time => "startTime") => get_klines_with,
        get_ticker(product_symbol => "product_symbol") => get_ticker_with,
        get_tickers() => get_tickers_with,
        get_status() => get_status_with,
        ping() => ping_with,
        get_time() => get_time_with,
        get_wallets() => get_wallets_with,
        get_recent_trades(product_symbol => "product_symbol") => get_recent_trades_with,
        get_historical_trades(product_symbol => "product_symbol") => get_historical_trades_with
    ];
    private [
        get_account() => get_account_with,
        get_max_borrow_quantity(symbol => "symbol") => get_max_borrow_quantity_with,
        get_max_order_quantity(symbol => "symbol", side => "side") => get_max_order_quantity_with,
        get_max_withdrawal_quantity(symbol => "symbol") => get_max_withdrawal_quantity_with,
        get_borrow_lend_positions() => get_borrow_lend_positions_with,
        get_borrow_history() => get_borrow_history_with,
        get_interest_history() => get_interest_history_with,
        get_borrow_position_history() => get_borrow_position_history_with,
        get_balances() => get_balances_with,
        convert_dust(symbol => "symbol") => convert_dust_with,
        get_private_collateral() => get_private_collateral_with,
        get_deposits() => get_deposits_with,
        get_deposit_address(blockchain => "blockchain") => get_deposit_address_with,
        get_withdrawals() => get_withdrawals_with,
        get_dust_conversion_history() => get_dust_conversion_history_with,
        get_settlement_history() => get_settlement_history_with,
        get_open_order(product_symbol => "product_symbol") => get_open_order_with,
        place_order(product_symbol => "product_symbol", side => "side", order_type => "orderType") => place_order_with,
        place_market_order(product_symbol => "product_symbol", side => "side") => place_market_order_with,
        place_limit_order(product_symbol => "product_symbol", side => "side", quantity => "quantity", price => "price") => place_limit_order_with,
        cancel_order(product_symbol => "product_symbol") => cancel_order_with,
        place_batch_orders(orders => "orders") => place_batch_orders_with,
        get_open_orders() => get_open_orders_with,
        cancel_open_orders() => cancel_open_orders_with,
        get_fill_history() => get_fill_history_with,
        get_order_history() => get_order_history_with,
        get_open_positions() => get_open_positions_with,
        get_funding_payments() => get_funding_payments_with,
        get_position_history() => get_position_history_with
    ];
}
