"""Native route, encoding and signature coverage for Binance risk endpoints."""

# ruff: noqa: ANN401, D103
from __future__ import annotations

import hashlib
import hmac
import inspect
import json
from pathlib import Path
from typing import Any
from urllib.parse import parse_qsl, urlsplit

import pytest

from dcex.async_support.binance.client import Client as AsyncClient
from dcex.binance.client import Client
from tests.unit.native_http_helpers import _http_server

CASES = [
    ("create_futures_listen_key", {}, "POST", "/fapi/v1/listenKey", {}, False, True),
    ("keep_alive_futures_listen_key", {}, "PUT", "/fapi/v1/listenKey", {}, False, True),
    ("close_futures_listen_key", {}, "DELETE", "/fapi/v1/listenKey", {}, False, True),
    (
        "disable_isolated_margin_account",
        {"symbol": "BTCUSDT"},
        "DELETE",
        "/sapi/v1/margin/isolated/account",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    (
        "enable_isolated_margin_account",
        {"symbol": "BTCUSDT"},
        "POST",
        "/sapi/v1/margin/isolated/account",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    (
        "get_transferable_earn_asset_balance_for_portfolio_margin",
        {"asset": "LDUSDT", "transfer_type": "EARN_TO_FUTURE"},
        "GET",
        "/sapi/v1/portfolio/earn-asset-balance",
        {"asset": "LDUSDT", "transferType": "EARN_TO_FUTURE"},
        True,
        False,
    ),
    (
        "transfer_ldusdt_rwusd_for_portfolio_margin",
        {"asset": "LDUSDT", "transfer_type": "EARN_TO_FUTURE", "amount": "1.25"},
        "POST",
        "/sapi/v1/portfolio/earn-asset-transfer",
        {"asset": "LDUSDT", "transferType": "EARN_TO_FUTURE", "amount": "1.25"},
        True,
        False,
    ),
    ("tradfi_options_contract", {}, "POST", "/eapi/v1/stock/contract", {}, True, False),
    (
        "get_cloud_mining_payment_and_refund_history",
        {"start_time": 1700000000000, "end_time": 1700000010000},
        "GET",
        "/sapi/v1/asset/ledger-transfer/cloud-mining/queryByPage",
        {"startTime": "1700000000000", "endTime": "1700000010000"},
        True,
        False,
    ),
    (
        "query_user_delegation_history",
        {"email": "sub@example.com", "start_time": 1700000000000, "end_time": 1700000010000},
        "GET",
        "/sapi/v1/asset/custody/transfer-history",
        {"email": "sub@example.com", "startTime": "1700000000000", "endTime": "1700000010000"},
        True,
        False,
    ),
    (
        "fetch_withdraw_address_list",
        {},
        "GET",
        "/sapi/v1/capital/withdraw/address/list",
        {},
        True,
        False,
    ),
    ("fetch_withdraw_quota", {}, "GET", "/sapi/v1/capital/withdraw/quota", {}, True, False),
    ("get_withdrawal_history", {}, "GET", "/sapi/v1/capital/withdraw/history", {}, True, False),
    (
        "check_questionnaire_requirements",
        {},
        "GET",
        "/sapi/v1/localentity/questionnaire-requirements",
        {},
        True,
        False,
    ),
    (
        "get_travel_rule_deposit_history",
        {},
        "GET",
        "/sapi/v1/localentity/deposit/history",
        {},
        True,
        False,
    ),
    (
        "get_travel_rule_deposit_history_v2",
        {},
        "GET",
        "/sapi/v2/localentity/deposit/history",
        {},
        True,
        False,
    ),
    ("fetch_address_verification_list", {}, "GET", "/sapi/v1/addressVerify/list", {}, True, False),
    ("get_country_list", {}, "GET", "/sapi/v1/localentity/country/list", {}, True, False),
    (
        "get_region_list",
        {"country_code": "example"},
        "GET",
        "/sapi/v1/localentity/region/list",
        {"countryCode": "example"},
        True,
        False,
    ),
    (
        "submit_deposit_questionnaire_travel_rule",
        {"tran_id": 1, "questionnaire": "{}"},
        "PUT",
        "/sapi/v1/localentity/deposit/provide-info",
        {"tranId": "1", "questionnaire": "{}"},
        True,
        False,
    ),
    (
        "submit_deposit_questionnaire_v2",
        {"deposit_id": 1, "questionnaire": "{}"},
        "PUT",
        "/sapi/v2/localentity/deposit/provide-info",
        {"depositId": "1", "questionnaire": "{}"},
        True,
        False,
    ),
    ("vasp_list", {}, "GET", "/sapi/v1/localentity/vasp", {}, True, False),
    (
        "get_travel_rule_withdrawal_history",
        {},
        "GET",
        "/sapi/v1/localentity/withdraw/history",
        {},
        True,
        False,
    ),
    (
        "get_travel_rule_withdrawal_history_v2",
        {},
        "GET",
        "/sapi/v2/localentity/withdraw/history",
        {},
        True,
        False,
    ),
    (
        "get_futures_lead_trader_status",
        {},
        "GET",
        "/sapi/v1/copyTrading/futures/userStatus",
        {},
        True,
        False,
    ),
    (
        "get_futures_lead_trading_symbol_whitelist",
        {},
        "GET",
        "/sapi/v1/copyTrading/futures/leadSymbol",
        {},
        True,
        False,
    ),
    (
        "get_dual_investment_product_list",
        {"option_type": "CALL", "exercised_coin": "example", "invest_coin": "example"},
        "GET",
        "/sapi/v1/dci/product/list",
        {"optionType": "CALL", "exercisedCoin": "example", "investCoin": "example"},
        False,
        False,
    ),
    (
        "change_auto_compound_status",
        {"position_id": "example", "auto_compound_plan": "NONE"},
        "POST",
        "/sapi/v1/dci/product/auto_compound/edit-status",
        {"positionId": "example", "autoCompoundPlan": "NONE"},
        True,
        False,
    ),
    ("check_dual_investment_accounts", {}, "GET", "/sapi/v1/dci/product/accounts", {}, True, False),
    ("get_dual_investment_positions", {}, "GET", "/sapi/v1/dci/product/positions", {}, True, False),
    (
        "subscribe_dual_investment_products",
        {
            "id": "example",
            "order_id": "example",
            "deposit_amount": "1.25",
            "auto_compound_plan": "NONE",
        },
        "POST",
        "/sapi/v1/dci/product/subscribe",
        {
            "id": "example",
            "orderId": "example",
            "depositAmount": "1.25",
            "autoCompoundPlan": "NONE",
        },
        True,
        False,
    ),
    ("get_bfusd_account", {}, "GET", "/sapi/v1/bfusd/account", {}, True, False),
    ("get_bfusd_quota_details", {}, "GET", "/sapi/v1/bfusd/quota", {}, True, False),
    ("get_bfusd_rate_history", {}, "GET", "/sapi/v1/bfusd/history/rateHistory", {}, True, False),
    (
        "get_bfusd_redemption_history",
        {},
        "GET",
        "/sapi/v1/bfusd/history/redemptionHistory",
        {},
        True,
        False,
    ),
    (
        "get_bfusd_rewards_history",
        {},
        "GET",
        "/sapi/v1/bfusd/history/rewardsHistory",
        {},
        True,
        False,
    ),
    (
        "get_bfusd_subscription_history",
        {},
        "GET",
        "/sapi/v1/bfusd/history/subscriptionHistory",
        {},
        True,
        False,
    ),
    (
        "redeem_bfusd",
        {"amount": "1.25", "type_": "FAST"},
        "POST",
        "/sapi/v1/bfusd/redeem",
        {"amount": "1.25", "type": "FAST"},
        True,
        False,
    ),
    (
        "subscribe_bfusd",
        {"asset": "USDT", "amount": "1.25"},
        "POST",
        "/sapi/v1/bfusd/subscribe",
        {"asset": "USDT", "amount": "1.25"},
        True,
        False,
    ),
    (
        "get_collateral_record",
        {},
        "GET",
        "/sapi/v1/simple-earn/flexible/history/collateralRecord",
        {},
        True,
        False,
    ),
    (
        "get_flexible_personal_left_quota",
        {"product_id": "example"},
        "GET",
        "/sapi/v1/simple-earn/flexible/personalLeftQuota",
        {"productId": "example"},
        True,
        False,
    ),
    (
        "get_flexible_subscription_preview",
        {"product_id": "example", "amount": "1.25"},
        "GET",
        "/sapi/v1/simple-earn/flexible/subscriptionPreview",
        {"productId": "example", "amount": "1.25"},
        True,
        False,
    ),
    (
        "get_locked_personal_left_quota",
        {"project_id": "example"},
        "GET",
        "/sapi/v1/simple-earn/locked/personalLeftQuota",
        {"projectId": "example"},
        True,
        False,
    ),
    (
        "get_locked_subscription_preview",
        {"project_id": "example", "amount": "1.25"},
        "GET",
        "/sapi/v1/simple-earn/locked/subscriptionPreview",
        {"projectId": "example", "amount": "1.25"},
        True,
        False,
    ),
    (
        "get_flexible_rate_history",
        {"product_id": "example"},
        "GET",
        "/sapi/v1/simple-earn/flexible/history/rateHistory",
        {"productId": "example"},
        True,
        False,
    ),
    (
        "set_flexible_auto_subscribe",
        {"product_id": "example", "auto_subscribe": True},
        "POST",
        "/sapi/v1/simple-earn/flexible/setAutoSubscribe",
        {"productId": "example", "autoSubscribe": "true"},
        True,
        False,
    ),
    (
        "set_locked_auto_subscribe",
        {"position_id": "example", "auto_subscribe": True},
        "POST",
        "/sapi/v1/simple-earn/locked/setAutoSubscribe",
        {"positionId": "example", "autoSubscribe": "true"},
        True,
        False,
    ),
    (
        "set_locked_product_redeem_option",
        {"position_id": "example", "redeem_to": "SPOT"},
        "POST",
        "/sapi/v1/simple-earn/locked/setRedeemOption",
        {"positionId": "example", "redeemTo": "SPOT"},
        True,
        False,
    ),
    ("get_rwusd_account", {}, "GET", "/sapi/v1/rwusd/account", {}, True, False),
    ("get_rwusd_quota_details", {}, "GET", "/sapi/v1/rwusd/quota", {}, True, False),
    ("get_rwusd_rate_history", {}, "GET", "/sapi/v1/rwusd/history/rateHistory", {}, True, False),
    (
        "get_rwusd_redemption_history",
        {},
        "GET",
        "/sapi/v1/rwusd/history/redemptionHistory",
        {},
        True,
        False,
    ),
    (
        "get_rwusd_rewards_history",
        {},
        "GET",
        "/sapi/v1/rwusd/history/rewardsHistory",
        {},
        True,
        False,
    ),
    (
        "get_rwusd_subscription_history",
        {},
        "GET",
        "/sapi/v1/rwusd/history/subscriptionHistory",
        {},
        True,
        False,
    ),
    (
        "redeem_rwusd",
        {"amount": "1.25", "type_": "FAST"},
        "POST",
        "/sapi/v1/rwusd/redeem",
        {"amount": "1.25", "type": "FAST"},
        True,
        False,
    ),
    (
        "subscribe_rwusd",
        {"asset": "USDT", "amount": "1.25"},
        "POST",
        "/sapi/v1/rwusd/subscribe",
        {"asset": "USDT", "amount": "1.25"},
        True,
        False,
    ),
    ("get_yield_arena_activities", {}, "GET", "/sapi/v1/earn/arena/activities", {}, True, False),
    (
        "create_a_virtual_sub_account",
        {"sub_account_string": "example"},
        "POST",
        "/sapi/v1/sub-account/virtualSubAccount",
        {"subAccountString": "example"},
        True,
        False,
    ),
    (
        "enable_futures_for_sub_account",
        {"email": "sub@example.com"},
        "POST",
        "/sapi/v1/sub-account/futures/enable",
        {"email": "sub@example.com"},
        True,
        False,
    ),
    (
        "enable_options_for_sub_account",
        {"email": "sub@example.com"},
        "POST",
        "/sapi/v1/sub-account/eoptions/enable",
        {"email": "sub@example.com"},
        True,
        False,
    ),
    (
        "add_ip_restriction_for_sub_account_api_key",
        {"email": "sub@example.com", "sub_account_api_key": "example", "status": 1},
        "POST",
        "/sapi/v2/sub-account/subAccountApi/ipRestriction",
        {"email": "sub@example.com", "subAccountApiKey": "example", "status": "1"},
        True,
        False,
    ),
    (
        "create_sub_account_api_key",
        {"email": "sub@example.com", "api_name": "example", "status": 1},
        "POST",
        "/sapi/v1/sub-account/subAccountApi",
        {"email": "sub@example.com", "apiName": "example", "status": "1"},
        True,
        False,
    ),
    (
        "delete_ip_list_for_a_sub_account_api_key",
        {"email": "sub@example.com", "sub_account_api_key": "example", "ip_address": "example"},
        "DELETE",
        "/sapi/v1/sub-account/subAccountApi/ipRestriction/ipList",
        {"email": "sub@example.com", "subAccountApiKey": "example", "ipAddress": "example"},
        True,
        False,
    ),
    (
        "delete_sub_account_api_key",
        {"email": "sub@example.com", "sub_account_api_key": "example"},
        "DELETE",
        "/sapi/v1/sub-account/subAccountApi",
        {"email": "sub@example.com", "subAccountApiKey": "example"},
        True,
        False,
    ),
    (
        "get_ip_restriction_for_a_sub_account_api_key",
        {"email": "sub@example.com", "sub_account_api_key": "example"},
        "GET",
        "/sapi/v1/sub-account/subAccountApi/ipRestriction",
        {"email": "sub@example.com", "subAccountApiKey": "example"},
        True,
        False,
    ),
    (
        "modify_sub_account_api_key_permission",
        {"email": "sub@example.com", "sub_account_api_key": "example"},
        "POST",
        "/sapi/v1/sub-account/subAccountApiPermission",
        {"email": "sub@example.com", "subAccountApiKey": "example"},
        True,
        False,
    ),
    (
        "query_sub_account_api_key",
        {"email": "sub@example.com"},
        "GET",
        "/sapi/v1/sub-account/subAccountApi",
        {"email": "sub@example.com"},
        True,
        False,
    ),
    (
        "get_move_position_history_for_sub_account",
        {"symbol": "BTCUSDT", "page": 1, "rows": 1},
        "GET",
        "/sapi/v1/sub-account/futures/move-position",
        {"symbol": "BTCUSDT", "page": "1", "rows": "1"},
        True,
        False,
    ),
    (
        "get_sub_account_deposit_address",
        {"email": "sub@example.com", "coin": "BTC"},
        "GET",
        "/sapi/v1/capital/deposit/subAddress",
        {"email": "sub@example.com", "coin": "BTC"},
        True,
        False,
    ),
    (
        "get_sub_account_deposit_history",
        {"email": "sub@example.com"},
        "GET",
        "/sapi/v1/capital/deposit/subHisrec",
        {"email": "sub@example.com"},
        True,
        False,
    ),
    (
        "move_position_for_sub_account",
        {
            "from_user_email": "parent@example.com",
            "to_user_email": "sub@example.com",
            "product_type": "UM",
            "order_args": [{"symbol": "BTCUSDT", "quantity": "0.001", "positionSide": "BOTH"}],
        },
        "POST",
        "/sapi/v1/sub-account/futures/move-position",
        {
            "fromUserEmail": "parent@example.com",
            "toUserEmail": "sub@example.com",
            "productType": "UM",
            "orderArgs[0].symbol": "BTCUSDT",
            "orderArgs[0].quantity": "0.001",
            "orderArgs[0].positionSide": "BOTH",
        },
        True,
        False,
    ),
    (
        "deposit_assets_into_the_managed_sub_account",
        {"to_email": "example", "asset": "USDT", "amount": "1.25"},
        "POST",
        "/sapi/v1/managed-subaccount/deposit",
        {"toEmail": "example", "asset": "USDT", "amount": "1.25"},
        True,
        False,
    ),
    (
        "get_managed_sub_account_deposit_address",
        {"email": "sub@example.com", "coin": "BTC"},
        "GET",
        "/sapi/v1/managed-subaccount/deposit/address",
        {"email": "sub@example.com", "coin": "BTC"},
        True,
        False,
    ),
    (
        "query_managed_sub_account_asset_details",
        {"email": "sub@example.com"},
        "GET",
        "/sapi/v1/managed-subaccount/asset",
        {"email": "sub@example.com"},
        True,
        False,
    ),
    (
        "query_managed_sub_account_futures_asset_details",
        {"email": "sub@example.com"},
        "GET",
        "/sapi/v1/managed-subaccount/fetch-future-asset",
        {"email": "sub@example.com"},
        True,
        False,
    ),
    (
        "query_managed_sub_account_list",
        {},
        "GET",
        "/sapi/v1/managed-subaccount/info",
        {},
        True,
        False,
    ),
    (
        "query_managed_sub_account_margin_asset_details",
        {"email": "sub@example.com"},
        "GET",
        "/sapi/v1/managed-subaccount/marginAsset",
        {"email": "sub@example.com"},
        True,
        False,
    ),
    (
        "query_managed_sub_account_snapshot",
        {"email": "sub@example.com", "type_": "SPOT"},
        "GET",
        "/sapi/v1/managed-subaccount/accountSnapshot",
        {"email": "sub@example.com", "type": "SPOT"},
        True,
        False,
    ),
    (
        "query_managed_sub_account_transfer_log_master_account_investor",
        {
            "email": "sub@example.com",
            "start_time": 1700000000000,
            "end_time": 1700000010000,
            "page": 1,
            "limit": 1,
        },
        "GET",
        "/sapi/v1/managed-subaccount/queryTransLogForInvestor",
        {
            "email": "sub@example.com",
            "startTime": "1700000000000",
            "endTime": "1700000010000",
            "page": "1",
            "limit": "1",
        },
        True,
        False,
    ),
    (
        "query_managed_sub_account_transfer_log_master_account_trading",
        {
            "email": "sub@example.com",
            "start_time": 1700000000000,
            "end_time": 1700000010000,
            "page": 1,
            "limit": 1,
        },
        "GET",
        "/sapi/v1/managed-subaccount/queryTransLogForTradeParent",
        {
            "email": "sub@example.com",
            "startTime": "1700000000000",
            "endTime": "1700000010000",
            "page": "1",
            "limit": "1",
        },
        True,
        False,
    ),
    (
        "query_managed_sub_account_transfer_log_sub_account_trading",
        {"start_time": 1700000000000, "end_time": 1700000010000, "page": 1, "limit": 1},
        "GET",
        "/sapi/v1/managed-subaccount/query-trans-log",
        {"startTime": "1700000000000", "endTime": "1700000010000", "page": "1", "limit": "1"},
        True,
        False,
    ),
    (
        "algo_cancel_algo_order_future_algo",
        {"algo_id": 123},
        "DELETE",
        "/sapi/v1/algo/futures/order",
        {"algoId": "123"},
        True,
        False,
    ),
    (
        "query_algo_current_algo_open_orders_future_algo",
        {},
        "GET",
        "/sapi/v1/algo/futures/openOrders",
        {},
        True,
        False,
    ),
    (
        "query_algo_historical_algo_orders_future_algo",
        {},
        "GET",
        "/sapi/v1/algo/futures/historicalOrders",
        {},
        True,
        False,
    ),
    (
        "query_algo_sub_orders_future_algo",
        {"algo_id": 1},
        "GET",
        "/sapi/v1/algo/futures/subOrders",
        {"algoId": "1"},
        True,
        False,
    ),
    (
        "algo_time_weighted_average_price_future_algo",
        {"symbol": "BTCUSDT", "side": "BUY", "quantity": "1.25", "duration": 300},
        "POST",
        "/sapi/v1/algo/futures/newOrderTwap",
        {"symbol": "BTCUSDT", "side": "BUY", "quantity": "1.25", "duration": "300"},
        True,
        False,
    ),
    (
        "algo_volume_participation_future_algo",
        {"symbol": "BTCUSDT", "side": "BUY", "quantity": "1.25", "urgency": "LOW"},
        "POST",
        "/sapi/v1/algo/futures/newOrderVp",
        {"symbol": "BTCUSDT", "side": "BUY", "quantity": "1.25", "urgency": "LOW"},
        True,
        False,
    ),
    (
        "algo_cancel_algo_order_spot_algo",
        {"algo_id": 123},
        "DELETE",
        "/sapi/v1/algo/spot/order",
        {"algoId": "123"},
        True,
        False,
    ),
    (
        "query_algo_current_algo_open_orders_spot_algo",
        {},
        "GET",
        "/sapi/v1/algo/spot/openOrders",
        {},
        True,
        False,
    ),
    (
        "query_algo_historical_algo_orders_spot_algo",
        {},
        "GET",
        "/sapi/v1/algo/spot/historicalOrders",
        {},
        True,
        False,
    ),
    (
        "query_algo_sub_orders_spot_algo",
        {"algo_id": 1},
        "GET",
        "/sapi/v1/algo/spot/subOrders",
        {"algoId": "1"},
        True,
        False,
    ),
    (
        "algo_time_weighted_average_price_spot_algo",
        {"symbol": "BTCUSDT", "side": "BUY", "quantity": "1.25", "duration": 300},
        "POST",
        "/sapi/v1/algo/spot/newOrderTwap",
        {"symbol": "BTCUSDT", "side": "BUY", "quantity": "1.25", "duration": "300"},
        True,
        False,
    ),
    (
        "pm_pro_bnb_transfer",
        {"amount": "1.25", "transfer_side": "TO_UM"},
        "POST",
        "/sapi/v1/portfolio/bnb-transfer",
        {"amount": "1.25", "transferSide": "TO_UM"},
        True,
        False,
    ),
    (
        "change_pm_pro_auto_repay_futures_status",
        {"auto_repay": "true"},
        "POST",
        "/sapi/v1/portfolio/repay-futures-switch",
        {"autoRepay": "true"},
        True,
        False,
    ),
    (
        "delete_pm_pro_margin_call_level",
        {},
        "DELETE",
        "/sapi/v1/portfolio/margin-call-level",
        {},
        True,
        False,
    ),
    (
        "pm_pro_fund_auto_collection",
        {},
        "POST",
        "/sapi/v1/portfolio/auto-collection",
        {},
        True,
        False,
    ),
    (
        "pm_pro_fund_collection_by_asset",
        {"asset": "USDT"},
        "POST",
        "/sapi/v1/portfolio/asset-collection",
        {"asset": "USDT"},
        True,
        False,
    ),
    (
        "get_pm_pro_auto_repay_futures_status",
        {},
        "GET",
        "/sapi/v1/portfolio/repay-futures-switch",
        {},
        True,
        False,
    ),
    ("get_pm_pro_delta_mode_status", {}, "GET", "/sapi/v1/portfolio/delta-mode", {}, True, False),
    (
        "get_pm_pro_margin_call_level",
        {},
        "GET",
        "/sapi/v1/portfolio/margin-call-level",
        {},
        True,
        False,
    ),
    (
        "get_pm_pro_portfolio_margin_pro_account_balance",
        {},
        "GET",
        "/sapi/v1/portfolio/balance",
        {},
        True,
        False,
    ),
    (
        "get_pm_pro_portfolio_margin_pro_account_info",
        {},
        "GET",
        "/sapi/v1/portfolio/account",
        {},
        True,
        False,
    ),
    (
        "get_pm_pro_portfolio_margin_pro_span_account_info",
        {},
        "GET",
        "/sapi/v2/portfolio/account",
        {},
        True,
        False,
    ),
    (
        "pm_pro_portfolio_margin_pro_bankruptcy_loan_repay",
        {},
        "POST",
        "/sapi/v1/portfolio/repay",
        {},
        True,
        False,
    ),
    (
        "query_pm_pro_portfolio_margin_pro_bankruptcy_loan_amount",
        {},
        "GET",
        "/sapi/v1/portfolio/pmLoan",
        {},
        True,
        False,
    ),
    (
        "query_pm_pro_portfolio_margin_pro_bankruptcy_loan_repay_history",
        {},
        "GET",
        "/sapi/v1/portfolio/pmloan-history",
        {},
        True,
        False,
    ),
    (
        "query_pm_pro_portfolio_margin_pro_negative_balance_interest_history",
        {},
        "GET",
        "/sapi/v1/portfolio/interest-history",
        {},
        True,
        False,
    ),
    (
        "repay_pm_pro_futures_negative_balance",
        {},
        "POST",
        "/sapi/v1/portfolio/repay-futures-negative-balance",
        {},
        True,
        False,
    ),
    (
        "set_pm_pro_margin_call_level",
        {"margin_call_level": "1.25"},
        "POST",
        "/sapi/v1/portfolio/margin-call-level",
        {"marginCallLevel": "1.25"},
        True,
        False,
    ),
    (
        "pm_pro_switch_delta_mode",
        {"delta_enabled": "true"},
        "POST",
        "/sapi/v1/portfolio/delta-mode",
        {"deltaEnabled": "true"},
        True,
        False,
    ),
    (
        "get_pm_pro_portfolio_margin_asset_leverage",
        {},
        "GET",
        "/sapi/v1/portfolio/margin-asset-leverage",
        {},
        True,
        False,
    ),
    (
        "pm_pro_portfolio_margin_collateral_rate",
        {},
        "GET",
        "/sapi/v1/portfolio/collateralRate",
        {},
        False,
        True,
    ),
    (
        "pm_pro_portfolio_margin_pro_tiered_collateral_rate",
        {},
        "GET",
        "/sapi/v2/portfolio/collateralRate",
        {},
        True,
        False,
    ),
    (
        "query_pm_pro_portfolio_margin_asset_index_price",
        {},
        "GET",
        "/sapi/v1/portfolio/asset-index-price",
        {},
        False,
        True,
    ),
    (
        "get_coin_futures_download_id_for_futures_order_history",
        {"start_time": 1700000000000, "end_time": 1700000010000},
        "GET",
        "/dapi/v1/order/asyn",
        {"startTime": "1700000000000", "endTime": "1700000010000"},
        True,
        False,
    ),
    (
        "get_coin_futures_download_id_for_futures_trade_history",
        {"start_time": 1700000000000, "end_time": 1700000010000},
        "GET",
        "/dapi/v1/trade/asyn",
        {"startTime": "1700000000000", "endTime": "1700000010000"},
        True,
        False,
    ),
    (
        "get_coin_futures_download_id_for_futures_transaction_history",
        {"start_time": 1700000000000, "end_time": 1700000010000},
        "GET",
        "/dapi/v1/income/asyn",
        {"startTime": "1700000000000", "endTime": "1700000010000"},
        True,
        False,
    ),
    (
        "get_coin_futures_futures_order_history_download_link_by_id",
        {"download_id": "example"},
        "GET",
        "/dapi/v1/order/asyn/id",
        {"downloadId": "example"},
        True,
        False,
    ),
    (
        "get_coin_futures_futures_trade_download_link_by_id",
        {"download_id": "example"},
        "GET",
        "/dapi/v1/trade/asyn/id",
        {"downloadId": "example"},
        True,
        False,
    ),
    (
        "get_coin_futures_futures_transaction_history_download_link_by_id",
        {"download_id": "example"},
        "GET",
        "/dapi/v1/income/asyn/id",
        {"downloadId": "example"},
        True,
        False,
    ),
    (
        "coin_futures_old_trades_lookup",
        {"symbol": "BTCUSD_PERP"},
        "GET",
        "/dapi/v1/historicalTrades",
        {"symbol": "BTCUSD_PERP"},
        False,
        True,
    ),
    (
        "query_coin_futures_index_price_constituents",
        {"symbol": "BTCUSD_PERP"},
        "GET",
        "/dapi/v1/constituents",
        {"symbol": "BTCUSD_PERP"},
        False,
        False,
    ),
    (
        "coin_futures_taker_buy_sell_volume",
        {"pair": "BTCUSD", "contract_type": "ALL", "period": "5m"},
        "GET",
        "/futures/data/takerBuySellVol",
        {"pair": "BTCUSD", "contractType": "ALL", "period": "5m"},
        False,
        False,
    ),
    ("coin_futures_test_connectivity", {}, "GET", "/dapi/v1/ping", {}, False, False),
    (
        "get_coin_futures_order_modify_history",
        {"symbol": "BTCUSD_PERP"},
        "GET",
        "/dapi/v1/orderAmendment",
        {"symbol": "BTCUSD_PERP"},
        True,
        False,
    ),
    (
        "get_coin_futures_position_margin_change_history",
        {"symbol": "BTCUSD_PERP"},
        "GET",
        "/dapi/v1/positionMargin/history",
        {"symbol": "BTCUSD_PERP"},
        True,
        False,
    ),
    (
        "query_coin_futures_current_open_order",
        {"symbol": "BTCUSD_PERP", "order_id": 123},
        "GET",
        "/dapi/v1/openOrder",
        {"symbol": "BTCUSD_PERP", "orderId": "123"},
        True,
        False,
    ),
    (
        "pm_bnb_transfer",
        {"amount": "1.25", "transfer_side": "TO_UM"},
        "POST",
        "/papi/v1/bnb-transfer",
        {"amount": "1.25", "transferSide": "TO_UM"},
        True,
        False,
    ),
    (
        "change_pm_auto_repay_futures_status",
        {"auto_repay": "true"},
        "POST",
        "/papi/v1/repay-futures-switch",
        {"autoRepay": "true"},
        True,
        False,
    ),
    ("pm_fund_auto_collection", {}, "POST", "/papi/v1/auto-collection", {}, True, False),
    (
        "pm_fund_collection_by_asset",
        {"asset": "USDT"},
        "POST",
        "/papi/v1/asset-collection",
        {"asset": "USDT"},
        True,
        False,
    ),
    (
        "get_pm_auto_repay_futures_status",
        {},
        "GET",
        "/papi/v1/repay-futures-switch",
        {},
        True,
        False,
    ),
    (
        "get_pm_download_id_for_um_futures_order_history",
        {"start_time": 1700000000000, "end_time": 1700000010000},
        "GET",
        "/papi/v1/um/order/asyn",
        {"startTime": "1700000000000", "endTime": "1700000010000"},
        True,
        False,
    ),
    (
        "get_pm_download_id_for_um_futures_trade_history",
        {"start_time": 1700000000000, "end_time": 1700000010000},
        "GET",
        "/papi/v1/um/trade/asyn",
        {"startTime": "1700000000000", "endTime": "1700000010000"},
        True,
        False,
    ),
    (
        "get_pm_download_id_for_um_futures_transaction_history",
        {"start_time": 1700000000000, "end_time": 1700000010000},
        "GET",
        "/papi/v1/um/income/asyn",
        {"startTime": "1700000000000", "endTime": "1700000010000"},
        True,
        False,
    ),
    ("get_pm_um_account_detail_v2", {}, "GET", "/papi/v2/um/account", {}, True, False),
    (
        "get_pm_um_futures_order_download_link_by_id",
        {"download_id": "example"},
        "GET",
        "/papi/v1/um/order/asyn/id",
        {"downloadId": "example"},
        True,
        False,
    ),
    (
        "get_pm_um_futures_trade_download_link_by_id",
        {"download_id": "example"},
        "GET",
        "/papi/v1/um/trade/asyn/id",
        {"downloadId": "example"},
        True,
        False,
    ),
    (
        "get_pm_um_futures_transaction_download_link_by_id",
        {"download_id": "example"},
        "GET",
        "/papi/v1/um/income/asyn/id",
        {"downloadId": "example"},
        True,
        False,
    ),
    (
        "query_pm_portfolio_margin_negative_balance_interest_history",
        {},
        "GET",
        "/papi/v1/portfolio/interest-history",
        {},
        True,
        False,
    ),
    (
        "query_pm_user_negative_balance_auto_exchange_record",
        {"start_time": 1700000000000, "end_time": 1700000010000},
        "GET",
        "/papi/v1/portfolio/negative-balance-exchange-record",
        {"startTime": "1700000000000", "endTime": "1700000010000"},
        True,
        False,
    ),
    (
        "repay_pm_futures_negative_balance",
        {},
        "POST",
        "/papi/v1/repay-futures-negative-balance",
        {},
        True,
        False,
    ),
    ("pm_test_connectivity", {}, "GET", "/papi/v1/ping", {}, False, False),
    ("pm_futures_tradfi_perps_contract", {}, "POST", "/papi/v1/um/stock/contract", {}, True, False),
    ("get_pm_um_futures_bnb_burn_status", {}, "GET", "/papi/v1/um/feeBurn", {}, True, False),
    (
        "query_pm_current_cm_open_order",
        {"symbol": "BTCUSD_PERP", "order_id": 123},
        "GET",
        "/papi/v1/cm/openOrder",
        {"symbol": "BTCUSD_PERP", "orderId": "123"},
        True,
        False,
    ),
    (
        "query_pm_current_um_open_order",
        {"symbol": "BTCUSDT", "order_id": 123},
        "GET",
        "/papi/v1/um/openOrder",
        {"symbol": "BTCUSDT", "orderId": "123"},
        True,
        False,
    ),
    (
        "toggle_pm_bnb_burn_on_um_futures_trade",
        {"fee_burn": "true"},
        "POST",
        "/papi/v1/um/feeBurn",
        {"feeBurn": "true"},
        True,
        False,
    ),
    ("get_futures_bnb_burn_status", {}, "GET", "/fapi/v1/feeBurn", {}, True, False),
    (
        "get_futures_download_id_for_futures_order_history",
        {"start_time": 1700000000000, "end_time": 1700000010000},
        "GET",
        "/fapi/v1/order/asyn",
        {"startTime": "1700000000000", "endTime": "1700000010000"},
        True,
        False,
    ),
    (
        "get_futures_download_id_for_futures_trade_history",
        {"start_time": 1700000000000, "end_time": 1700000010000},
        "GET",
        "/fapi/v1/trade/asyn",
        {"startTime": "1700000000000", "endTime": "1700000010000"},
        True,
        False,
    ),
    (
        "get_futures_download_id_for_futures_transaction_history",
        {"start_time": 1700000000000, "end_time": 1700000010000},
        "GET",
        "/fapi/v1/income/asyn",
        {"startTime": "1700000000000", "endTime": "1700000010000"},
        True,
        False,
    ),
    (
        "get_futures_futures_order_history_download_link_by_id",
        {"download_id": "example"},
        "GET",
        "/fapi/v1/order/asyn/id",
        {"downloadId": "example"},
        True,
        False,
    ),
    (
        "get_futures_futures_trade_download_link_by_id",
        {"download_id": "example"},
        "GET",
        "/fapi/v1/trade/asyn/id",
        {"downloadId": "example"},
        True,
        False,
    ),
    (
        "get_futures_futures_transaction_history_download_link_by_id",
        {"download_id": "example"},
        "GET",
        "/fapi/v1/income/asyn/id",
        {"downloadId": "example"},
        True,
        False,
    ),
    (
        "toggle_futures_bnb_burn_on_futures_trade",
        {"fee_burn": "true"},
        "POST",
        "/fapi/v1/feeBurn",
        {"feeBurn": "true"},
        True,
        False,
    ),
    (
        "futures_accept_the_offered_quote",
        {"quote_id": "example"},
        "POST",
        "/fapi/v1/convert/acceptQuote",
        {"quoteId": "example"},
        True,
        False,
    ),
    (
        "futures_list_all_convert_pairs",
        {},
        "GET",
        "/fapi/v1/convert/exchangeInfo",
        {},
        False,
        False,
    ),
    (
        "futures_order_status",
        {"order_id": "123"},
        "GET",
        "/fapi/v1/convert/orderStatus",
        {"orderId": "123"},
        True,
        False,
    ),
    (
        "futures_send_quote_request",
        {"from_asset": "USDT", "to_asset": "USDC", "from_amount": "1.25"},
        "POST",
        "/fapi/v1/convert/getQuote",
        {"fromAsset": "USDT", "toAsset": "USDC", "fromAmount": "1.25"},
        True,
        False,
    ),
    ("futures_adl_risk", {}, "GET", "/fapi/v1/symbolAdlRisk", {}, False, False),
    ("futures_asset_index", {}, "GET", "/fapi/v1/assetIndex", {}, False, False),
    (
        "futures_composite_index_symbol_information",
        {},
        "GET",
        "/fapi/v1/indexInfo",
        {},
        False,
        False,
    ),
    (
        "futures_old_trades_lookup",
        {"symbol": "BTCUSDT"},
        "GET",
        "/fapi/v1/historicalTrades",
        {"symbol": "BTCUSDT"},
        False,
        True,
    ),
    (
        "futures_quarterly_contract_settlement_price",
        {"pair": "BTCUSDT"},
        "GET",
        "/futures/data/delivery-price",
        {"pair": "BTCUSDT"},
        False,
        False,
    ),
    (
        "query_futures_index_price_constituents",
        {"symbol": "BTCUSDT"},
        "GET",
        "/fapi/v1/constituents",
        {"symbol": "BTCUSDT"},
        False,
        False,
    ),
    (
        "query_futures_insurance_fund_balance_snapshot",
        {},
        "GET",
        "/fapi/v1/insuranceBalance",
        {},
        False,
        False,
    ),
    (
        "futures_rpi_order_book",
        {"symbol": "BTCUSDT"},
        "GET",
        "/fapi/v1/rpiDepth",
        {"symbol": "BTCUSDT"},
        False,
        False,
    ),
    ("futures_test_connectivity", {}, "GET", "/fapi/v1/ping", {}, False, False),
    ("futures_trading_schedule", {}, "GET", "/fapi/v1/tradingSchedule", {}, False, False),
    (
        "futures_classic_portfolio_margin_account_information",
        {"asset": "USDT"},
        "GET",
        "/fapi/v1/pmAccountInfo",
        {"asset": "USDT"},
        True,
        False,
    ),
    (
        "futures_futures_tradfi_perps_contract",
        {},
        "POST",
        "/fapi/v1/stock/contract",
        {},
        True,
        False,
    ),
    (
        "get_futures_order_modify_history",
        {"symbol": "BTCUSDT"},
        "GET",
        "/fapi/v1/orderAmendment",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    (
        "get_futures_position_margin_change_history",
        {"symbol": "BTCUSDT"},
        "GET",
        "/fapi/v1/positionMargin/history",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    (
        "adjust_margin_cross_margin_max_leverage",
        {"max_leverage": 5},
        "POST",
        "/sapi/v1/margin/max-leverage",
        {"maxLeverage": "5"},
        True,
        False,
    ),
    ("get_margin_bnb_burn_status", {}, "GET", "/sapi/v1/bnbBurn", {}, True, False),
    (
        "query_margin_cross_margin_fee_data",
        {},
        "GET",
        "/sapi/v1/margin/crossMarginData",
        {},
        True,
        False,
    ),
    (
        "query_margin_enabled_isolated_margin_account_limit",
        {},
        "GET",
        "/sapi/v1/margin/isolated/accountLimit",
        {},
        True,
        False,
    ),
    (
        "query_margin_isolated_margin_fee_data",
        {},
        "GET",
        "/sapi/v1/margin/isolatedMarginData",
        {},
        True,
        False,
    ),
    (
        "get_margin_future_hourly_interest_rate",
        {"assets": "USDT,BTC", "is_isolated": "TRUE"},
        "GET",
        "/sapi/v1/margin/next-hourly-interest-rate",
        {"assets": "USDT,BTC", "isIsolated": "TRUE"},
        True,
        False,
    ),
    (
        "query_margin_margin_interest_rate_history",
        {"asset": "USDT"},
        "GET",
        "/sapi/v1/margin/interestRateHistory",
        {"asset": "USDT"},
        True,
        False,
    ),
    (
        "margin_cross_margin_collateral_ratio",
        {},
        "GET",
        "/sapi/v1/margin/crossMarginCollateralRatio",
        {},
        False,
        True,
    ),
    (
        "get_margin_limit_price_pairs",
        {},
        "GET",
        "/sapi/v1/margin/limit-price-pairs",
        {},
        False,
        True,
    ),
    ("get_margin_list_schedule", {}, "GET", "/sapi/v1/margin/list-schedule", {}, False, True),
    (
        "get_margin_margin_asset_risk_based_liquidation_ratio",
        {},
        "GET",
        "/sapi/v1/margin/risk-based-liquidation-ratio",
        {},
        False,
        True,
    ),
    (
        "get_margin_margin_restricted_assets",
        {},
        "GET",
        "/sapi/v1/margin/restricted-asset",
        {},
        False,
        True,
    ),
    (
        "query_margin_isolated_margin_tier_data",
        {"symbol": "BTCUSDT"},
        "GET",
        "/sapi/v1/margin/isolatedMarginTier",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    (
        "query_margin_liability_coin_leverage_bracket_in_cross_margin_pro_mode",
        {},
        "GET",
        "/sapi/v1/margin/leverageBracket",
        {},
        False,
        True,
    ),
    (
        "query_margin_margin_available_inventory",
        {"kind_type": "MARGIN"},
        "GET",
        "/sapi/v1/margin/available-inventory",
        {"type": "MARGIN"},
        True,
        False,
    ),
    (
        "create_margin_special_key",
        {"api_name": "example"},
        "POST",
        "/sapi/v1/margin/apiKey",
        {"apiName": "example"},
        True,
        False,
    ),
    ("delete_margin_special_key", {}, "DELETE", "/sapi/v1/margin/apiKey", {}, True, False),
    (
        "edit_margin_ip_for_special_key",
        {"ip": "127.0.0.1"},
        "PUT",
        "/sapi/v1/margin/apiKey/ip",
        {"ip": "127.0.0.1"},
        True,
        False,
    ),
    (
        "margin_exit_special_key_mode",
        {},
        "POST",
        "/sapi/v1/margin/exit-special-key-mode",
        {},
        True,
        False,
    ),
    (
        "get_margin_small_liability_exchange_coin_list",
        {},
        "GET",
        "/sapi/v1/margin/exchange-small-liability",
        {},
        True,
        False,
    ),
    (
        "get_margin_small_liability_exchange_history",
        {"current": 1, "size": 1},
        "GET",
        "/sapi/v1/margin/exchange-small-liability-history",
        {"current": "1", "size": "1"},
        True,
        False,
    ),
    (
        "margin_liquidation_loan_repay",
        {"asset": "USDT", "amount": "1.25"},
        "POST",
        "/sapi/v1/margin/liquidation-loan/repay",
        {"asset": "USDT", "amount": "1.25"},
        True,
        False,
    ),
    (
        "margin_margin_manual_liquidation",
        {"kind_type": "MARGIN"},
        "POST",
        "/sapi/v1/margin/manual-liquidation",
        {"type": "MARGIN"},
        True,
        False,
    ),
    (
        "query_margin_liquidation_loan",
        {},
        "GET",
        "/sapi/v1/margin/liquidation-loan",
        {},
        True,
        False,
    ),
    (
        "query_margin_liquidation_loan_repay_history",
        {},
        "GET",
        "/sapi/v1/margin/liquidation-loan/repay-history",
        {},
        True,
        False,
    ),
    (
        "query_margin_prevented_matches",
        {"symbol": "BTCUSDT", "order_id": 123},
        "GET",
        "/sapi/v1/margin/myPreventedMatches",
        {"symbol": "BTCUSDT", "orderId": "123"},
        True,
        False,
    ),
    ("query_margin_special_key", {}, "GET", "/sapi/v1/margin/apiKey", {}, True, False),
    ("query_margin_special_key_list", {}, "GET", "/sapi/v1/margin/api-key-list", {}, True, False),
    (
        "margin_small_liability_exchange",
        {"asset_names": "USDT"},
        "POST",
        "/sapi/v1/margin/exchange-small-liability",
        {"assetNames": "USDT"},
        True,
        False,
    ),
    (
        "get_margin_cross_margin_transfer_history",
        {},
        "GET",
        "/sapi/v1/margin/transfer",
        {},
        True,
        False,
    ),
    (
        "spot_my_filters",
        {"symbol": "BTCUSDT"},
        "GET",
        "/api/v3/myFilters",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    (
        "spot_order_amendments",
        {"symbol": "BTCUSDT", "order_id": 1},
        "GET",
        "/api/v3/order/amendments",
        {"symbol": "BTCUSDT", "orderId": "1"},
        True,
        False,
    ),
    ("spot_execution_rules", {}, "GET", "/api/v3/executionRules", {}, False, False),
    ("spot_ping", {}, "GET", "/api/v3/ping", {}, False, False),
    (
        "spot_historical_block_trades",
        {"symbol": "BTCUSDT", "from_id": 1},
        "GET",
        "/api/v3/historicalBlockTrades",
        {"symbol": "BTCUSDT", "fromId": "1"},
        False,
        True,
    ),
    (
        "spot_historical_trades",
        {"symbol": "BTCUSDT"},
        "GET",
        "/api/v3/historicalTrades",
        {"symbol": "BTCUSDT"},
        False,
        False,
    ),
    (
        "spot_reference_price",
        {"symbol": "BTCUSDT"},
        "GET",
        "/api/v3/referencePrice",
        {"symbol": "BTCUSDT"},
        False,
        False,
    ),
    (
        "spot_reference_price_calculation",
        {"symbol": "BTCUSDT"},
        "GET",
        "/api/v3/referencePrice/calculation",
        {"symbol": "BTCUSDT"},
        False,
        False,
    ),
    ("spot_ticker", {}, "GET", "/api/v3/ticker", {}, False, False),
    ("spot_ticker_trading_day", {}, "GET", "/api/v3/ticker/tradingDay", {}, False, False),
    (
        "spot_ui_klines",
        {"symbol": "BTCUSDT", "interval": "1s"},
        "GET",
        "/api/v3/uiKlines",
        {"symbol": "BTCUSDT", "interval": "1s"},
        False,
        False,
    ),
    (
        "spot_sor_order",
        {
            "symbol": "BTCUSDT",
            "side": "BUY",
            "kind_type": "LIMIT",
            "quantity": "1.25",
            "price": "50000",
            "time_in_force": "GTC",
        },
        "POST",
        "/api/v3/sor/order",
        {
            "symbol": "BTCUSDT",
            "side": "BUY",
            "type": "LIMIT",
            "quantity": "1.25",
            "timeInForce": "GTC",
            "price": "50000",
        },
        True,
        False,
    ),
    (
        "spot_sor_order_test",
        {
            "symbol": "BTCUSDT",
            "side": "BUY",
            "kind_type": "LIMIT",
            "quantity": "1.25",
            "price": "50000",
            "time_in_force": "GTC",
        },
        "POST",
        "/api/v3/sor/order/test",
        {
            "symbol": "BTCUSDT",
            "side": "BUY",
            "type": "LIMIT",
            "quantity": "1.25",
            "timeInForce": "GTC",
            "price": "50000",
        },
        True,
        False,
    ),
    ("wallet_account_info", {}, "GET", "/sapi/v1/account/info", {}, True, False),
    (
        "wallet_daily_account_snapshot",
        {"kind_type": "SPOT"},
        "GET",
        "/sapi/v1/accountSnapshot",
        {"type": "SPOT"},
        True,
        False,
    ),
    ("wallet_asset_detail", {}, "GET", "/sapi/v1/asset/assetDetail", {}, True, False),
    ("wallet_asset_dividend_record", {}, "GET", "/sapi/v1/asset/assetDividend", {}, True, False),
    (
        "wallet_dust_convert",
        {"asset": "USDT"},
        "POST",
        "/sapi/v1/asset/dust-convert/convert",
        {"asset": "USDT"},
        True,
        False,
    ),
    (
        "wallet_dust_convertible_assets",
        {"target_asset": "BNB"},
        "POST",
        "/sapi/v1/asset/dust-convert/query-convertible-assets",
        {"targetAsset": "BNB"},
        True,
        False,
    ),
    (
        "wallet_dust_transfer",
        {"asset": "USDT"},
        "POST",
        "/sapi/v1/asset/dust",
        {"asset": "USDT"},
        True,
        False,
    ),
    ("wallet_dustlog", {}, "GET", "/sapi/v1/asset/dribblet", {}, True, False),
    (
        "get_wallet_assets_that_can_be_converted_into_bnb",
        {},
        "POST",
        "/sapi/v1/asset/dust-btc",
        {},
        True,
        False,
    ),
    ("get_wallet_open_symbol_list", {}, "GET", "/sapi/v1/spot/open-symbol-list", {}, False, True),
    ("get_wallet_spot_asset_tags", {}, "GET", "/sapi/v1/spot/asset/tags", {}, False, True),
    (
        "toggle_wallet_bnb_burn_on_spot_trade_and_margin_interest",
        {"spot_bnb_burn": "true"},
        "POST",
        "/sapi/v1/bnbBurn",
        {"spotBNBBurn": "true"},
        True,
        False,
    ),
    (
        "wallet_fetch_deposit_address_list_with_network",
        {"coin": "BTC"},
        "GET",
        "/sapi/v1/capital/deposit/address/list",
        {"coin": "BTC"},
        True,
        False,
    ),
    (
        "wallet_one_click_arrival_deposit_apply",
        {"deposit_id": 123},
        "POST",
        "/sapi/v1/capital/deposit/credit-apply",
        {"depositId": "123"},
        True,
        False,
    ),
    (
        "place_margin_oco",
        {
            "product_symbol": "BTC-USDT-SPOT",
            "side": "SELL",
            "quantity": "1",
            "price": "110",
            "stop_price": "90",
        },
        "POST",
        "/sapi/v1/margin/order/oco",
        {"symbol": "BTCUSDT", "side": "SELL", "quantity": "1", "price": "110", "stopPrice": "90"},
        True,
        False,
    ),
    (
        "place_margin_oto",
        {
            "product_symbol": "BTC-USDT-SPOT",
            "working_type": "LIMIT",
            "working_side": "BUY",
            "working_price": "100",
            "working_quantity": "1",
            "working_iceberg_qty": "0.5",
            "pending_type": "MARKET",
            "pending_side": "SELL",
            "pending_quantity": "1",
            "working_time_in_force": "GTC",
        },
        "POST",
        "/sapi/v1/margin/order/oto",
        {
            "symbol": "BTCUSDT",
            "workingType": "LIMIT",
            "workingSide": "BUY",
            "workingPrice": "100",
            "workingQuantity": "1",
            "workingIcebergQty": "0.5",
            "pendingType": "MARKET",
            "pendingSide": "SELL",
            "pendingQuantity": "1",
            "workingTimeInForce": "GTC",
        },
        True,
        False,
    ),
    (
        "place_margin_otoco",
        {
            "product_symbol": "BTC-USDT-SPOT",
            "working_type": "LIMIT",
            "working_side": "BUY",
            "working_price": "100",
            "working_quantity": "1",
            "pending_side": "SELL",
            "pending_quantity": "1",
            "pending_above_type": "LIMIT_MAKER",
            "working_time_in_force": "GTC",
            "pending_above_price": "110",
            "pending_below_type": "STOP_LOSS",
            "pending_below_stop_price": "90",
        },
        "POST",
        "/sapi/v1/margin/order/otoco",
        {
            "symbol": "BTCUSDT",
            "workingType": "LIMIT",
            "workingSide": "BUY",
            "workingPrice": "100",
            "workingQuantity": "1",
            "pendingSide": "SELL",
            "pendingQuantity": "1",
            "pendingAboveType": "LIMIT_MAKER",
            "workingTimeInForce": "GTC",
            "pendingAbovePrice": "110",
            "pendingBelowType": "STOP_LOSS",
            "pendingBelowStopPrice": "90",
        },
        True,
        False,
    ),
    (
        "place_spot_opo",
        {
            "product_symbol": "BTC-USDT-SPOT",
            "working_type": "LIMIT",
            "working_side": "BUY",
            "working_price": "100",
            "working_quantity": "1",
            "pending_type": "MARKET",
            "pending_side": "SELL",
            "working_time_in_force": "GTC",
        },
        "POST",
        "/api/v3/orderList/opo",
        {
            "symbol": "BTCUSDT",
            "workingType": "LIMIT",
            "workingSide": "BUY",
            "workingPrice": "100",
            "workingQuantity": "1",
            "pendingType": "MARKET",
            "pendingSide": "SELL",
            "workingTimeInForce": "GTC",
        },
        True,
        False,
    ),
    (
        "place_spot_opoco",
        {
            "product_symbol": "BTC-USDT-SPOT",
            "working_type": "LIMIT",
            "working_side": "BUY",
            "working_price": "100",
            "working_quantity": "1",
            "pending_side": "SELL",
            "pending_above_type": "LIMIT_MAKER",
            "working_time_in_force": "GTC",
            "pending_above_price": "110",
            "pending_below_type": "STOP_LOSS",
            "pending_below_stop_price": "90",
        },
        "POST",
        "/api/v3/orderList/opoco",
        {
            "symbol": "BTCUSDT",
            "workingType": "LIMIT",
            "workingSide": "BUY",
            "workingPrice": "100",
            "workingQuantity": "1",
            "pendingSide": "SELL",
            "pendingAboveType": "LIMIT_MAKER",
            "workingTimeInForce": "GTC",
            "pendingAbovePrice": "110",
            "pendingBelowType": "STOP_LOSS",
            "pendingBelowStopPrice": "90",
        },
        True,
        False,
    ),
    (
        "get_coin_futures_income_history",
        {"symbol": "BTCUSD_PERP"},
        "GET",
        "/dapi/v1/income",
        {"symbol": "BTCUSD_PERP"},
        True,
        False,
    ),
    (
        "get_coin_futures_commission_rate",
        {"symbol": "BTCUSD_PERP"},
        "GET",
        "/dapi/v1/commissionRate",
        {"symbol": "BTCUSD_PERP"},
        True,
        False,
    ),
    (
        "get_coin_futures_aggregate_trades",
        {"symbol": "BTCUSD_PERP"},
        "GET",
        "/dapi/v1/aggTrades",
        {"symbol": "BTCUSD_PERP"},
        False,
        False,
    ),
    (
        "get_coin_futures_continuous_klines",
        {"pair": "BTCUSD", "contract_type": "PERPETUAL", "interval": "1m"},
        "GET",
        "/dapi/v1/continuousKlines",
        {"pair": "BTCUSD", "contractType": "PERPETUAL", "interval": "1m"},
        False,
        False,
    ),
    ("get_coin_futures_funding_info", {}, "GET", "/dapi/v1/fundingInfo", {}, False, False),
    (
        "get_coin_futures_index_price_klines",
        {"pair": "BTCUSD", "interval": "1m"},
        "GET",
        "/dapi/v1/indexPriceKlines",
        {"pair": "BTCUSD", "interval": "1m"},
        False,
        False,
    ),
    (
        "get_coin_futures_mark_price_klines",
        {"symbol": "BTCUSD_PERP", "interval": "1m"},
        "GET",
        "/dapi/v1/markPriceKlines",
        {"symbol": "BTCUSD_PERP", "interval": "1m"},
        False,
        False,
    ),
    (
        "get_coin_futures_open_interest",
        {"symbol": "BTCUSD_PERP"},
        "GET",
        "/dapi/v1/openInterest",
        {"symbol": "BTCUSD_PERP"},
        False,
        False,
    ),
    (
        "get_coin_futures_premium_index_klines",
        {"symbol": "BTCUSD_PERP", "interval": "1m"},
        "GET",
        "/dapi/v1/premiumIndexKlines",
        {"symbol": "BTCUSD_PERP", "interval": "1m"},
        False,
        False,
    ),
    (
        "get_coin_futures_book_ticker",
        {"symbol": "BTCUSD_PERP"},
        "GET",
        "/dapi/v1/ticker/bookTicker",
        {"symbol": "BTCUSD_PERP"},
        False,
        False,
    ),
    (
        "get_coin_futures_24h_ticker",
        {"symbol": "BTCUSD_PERP"},
        "GET",
        "/dapi/v1/ticker/24hr",
        {"symbol": "BTCUSD_PERP"},
        False,
        False,
    ),
    (
        "adjust_coin_futures_position_margin",
        {"symbol": "BTCUSD_PERP", "amount": "1.25", "kind_type": 1},
        "POST",
        "/dapi/v1/positionMargin",
        {"symbol": "BTCUSD_PERP", "amount": "1.25", "type": "1"},
        True,
        False,
    ),
    (
        "get_coin_futures_adl_quantiles",
        {"symbol": "BTCUSD_PERP"},
        "GET",
        "/dapi/v1/adlQuantile",
        {"symbol": "BTCUSD_PERP"},
        True,
        False,
    ),
    (
        "get_coin_futures_force_orders",
        {"symbol": "BTCUSD_PERP"},
        "GET",
        "/dapi/v1/forceOrders",
        {"symbol": "BTCUSD_PERP"},
        True,
        False,
    ),
    (
        "get_pm_coin_income_history",
        {"symbol": "BTCUSD_PERP"},
        "GET",
        "/papi/v1/cm/income",
        {"symbol": "BTCUSD_PERP"},
        True,
        False,
    ),
    (
        "get_pm_margin_interest_history",
        {"recv_window": 5000},
        "GET",
        "/papi/v1/margin/marginInterestHistory",
        {"recvWindow": "5000"},
        True,
        False,
    ),
    (
        "get_pm_futures_income_history",
        {"product_symbol": "BTC-USDT-SWAP"},
        "GET",
        "/papi/v1/um/income",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    (
        "get_pm_coin_commission_rate",
        {"symbol": "BTCUSD_PERP"},
        "GET",
        "/papi/v1/cm/commissionRate",
        {"symbol": "BTCUSD_PERP"},
        True,
        False,
    ),
    (
        "get_pm_futures_commission_rate",
        {"product_symbol": "BTC-USDT-SWAP"},
        "GET",
        "/papi/v1/um/commissionRate",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    (
        "get_pm_margin_loan_records",
        {"asset": "USDT", "tx_id": 1},
        "GET",
        "/papi/v1/margin/marginLoan",
        {"asset": "USDT", "txId": "1"},
        True,
        False,
    ),
    (
        "get_pm_margin_transferable_amount",
        {"asset": "USDT"},
        "GET",
        "/papi/v1/margin/maxWithdraw",
        {"asset": "USDT"},
        True,
        False,
    ),
    (
        "get_pm_margin_repayment_records",
        {"asset": "USDT", "tx_id": 1},
        "GET",
        "/papi/v1/margin/repayLoan",
        {"asset": "USDT", "txId": "1"},
        True,
        False,
    ),
    (
        "get_pm_order_rate_limits",
        {"recv_window": 5000},
        "GET",
        "/papi/v1/rateLimit/order",
        {"recvWindow": "5000"},
        True,
        False,
    ),
    (
        "get_futures_account_config",
        {"recv_window": 5000},
        "GET",
        "/fapi/v1/accountConfig",
        {"recvWindow": "5000"},
        True,
        False,
    ),
    (
        "get_futures_trading_status",
        {"product_symbol": "BTC-USDT-SWAP"},
        "GET",
        "/fapi/v1/apiTradingStatus",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    (
        "get_futures_multi_assets_mode",
        {"recv_window": 5000},
        "GET",
        "/fapi/v1/multiAssetsMargin",
        {"recvWindow": "5000"},
        True,
        False,
    ),
    (
        "get_futures_order_rate_limits",
        {"recv_window": 5000},
        "GET",
        "/fapi/v1/rateLimit/order",
        {"recvWindow": "5000"},
        True,
        False,
    ),
    (
        "get_futures_symbol_config",
        {"product_symbol": "BTC-USDT-SWAP"},
        "GET",
        "/fapi/v1/symbolConfig",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    (
        "get_futures_aggregate_trades",
        {"product_symbol": "BTC-USDT-SWAP"},
        "GET",
        "/fapi/v1/aggTrades",
        {"symbol": "BTCUSDT"},
        False,
        False,
    ),
    (
        "get_futures_continuous_klines",
        {"pair": "BTCUSDT", "contract_type": "PERPETUAL", "interval": "1m"},
        "GET",
        "/fapi/v1/continuousKlines",
        {"pair": "BTCUSDT", "contractType": "PERPETUAL", "interval": "1m"},
        False,
        False,
    ),
    ("get_futures_funding_info", {}, "GET", "/fapi/v1/fundingInfo", {}, False, False),
    (
        "get_futures_index_price_klines",
        {"pair": "BTCUSDT", "interval": "1m"},
        "GET",
        "/fapi/v1/indexPriceKlines",
        {"pair": "BTCUSDT", "interval": "1m"},
        False,
        False,
    ),
    (
        "get_futures_mark_price_klines",
        {"product_symbol": "BTC-USDT-SWAP", "interval": "1m"},
        "GET",
        "/fapi/v1/markPriceKlines",
        {"symbol": "BTCUSDT", "interval": "1m"},
        False,
        False,
    ),
    (
        "get_futures_premium_index_klines",
        {"product_symbol": "BTC-USDT-SWAP", "interval": "1m"},
        "GET",
        "/fapi/v1/premiumIndexKlines",
        {"symbol": "BTCUSDT", "interval": "1m"},
        False,
        False,
    ),
    (
        "get_futures_recent_trades",
        {"product_symbol": "BTC-USDT-SWAP"},
        "GET",
        "/fapi/v1/trades",
        {"symbol": "BTCUSDT"},
        False,
        False,
    ),
    (
        "get_futures_price_ticker_v1",
        {"product_symbol": "BTC-USDT-SWAP"},
        "GET",
        "/fapi/v1/ticker/price",
        {"symbol": "BTCUSDT"},
        False,
        False,
    ),
    (
        "get_futures_price_ticker",
        {"product_symbol": "BTC-USDT-SWAP"},
        "GET",
        "/fapi/v2/ticker/price",
        {"symbol": "BTCUSDT"},
        False,
        False,
    ),
    (
        "get_futures_24h_ticker",
        {"product_symbol": "BTC-USDT-SWAP"},
        "GET",
        "/fapi/v1/ticker/24hr",
        {"symbol": "BTCUSDT"},
        False,
        False,
    ),
    (
        "set_futures_multi_assets_mode",
        {"multi_assets_margin": "true"},
        "POST",
        "/fapi/v1/multiAssetsMargin",
        {"multiAssetsMargin": "true"},
        True,
        False,
    ),
    (
        "adjust_futures_position_margin",
        {"product_symbol": "BTC-USDT-SWAP", "amount": "1.25", "kind_type": 1},
        "POST",
        "/fapi/v1/positionMargin",
        {"symbol": "BTCUSDT", "amount": "1.25", "type": "1"},
        True,
        False,
    ),
    (
        "get_futures_adl_quantiles",
        {"product_symbol": "BTC-USDT-SWAP"},
        "GET",
        "/fapi/v1/adlQuantile",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    (
        "get_futures_force_orders",
        {"product_symbol": "BTC-USDT-SWAP"},
        "GET",
        "/fapi/v1/forceOrders",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    (
        "get_margin_risk_coefficients",
        {"recv_window": 5000},
        "GET",
        "/sapi/v1/margin/tradeCoeff",
        {"recvWindow": "5000"},
        True,
        False,
    ),
    (
        "get_margin_capital_flow",
        {"product_symbol": "BTC-USDT-SPOT"},
        "GET",
        "/sapi/v1/margin/capital-flow",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    (
        "get_margin_delist_schedule",
        {"recv_window": 5000},
        "GET",
        "/sapi/v1/margin/delist-schedule",
        {"recvWindow": "5000"},
        False,
        True,
    ),
    (
        "get_margin_liquidation_records",
        {"recv_window": 5000},
        "GET",
        "/sapi/v1/margin/forceLiquidationRec",
        {"recvWindow": "5000"},
        True,
        False,
    ),
    (
        "cancel_margin_order_list",
        {"product_symbol": "BTC-USDT-SPOT", "order_list_id": 1},
        "DELETE",
        "/sapi/v1/margin/orderList",
        {"symbol": "BTCUSDT", "orderListId": "1"},
        True,
        False,
    ),
    (
        "get_margin_order_rate_limits",
        {"product_symbol": "BTC-USDT-SPOT"},
        "GET",
        "/sapi/v1/margin/rateLimit/order",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    (
        "get_margin_all_order_lists",
        {"product_symbol": "BTC-USDT-SPOT"},
        "GET",
        "/sapi/v1/margin/allOrderList",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    (
        "get_margin_order_list",
        {"order_list_id": 1},
        "GET",
        "/sapi/v1/margin/orderList",
        {"orderListId": "1"},
        True,
        False,
    ),
    (
        "get_margin_open_order_lists",
        {"product_symbol": "BTC-USDT-SPOT"},
        "GET",
        "/sapi/v1/margin/openOrderList",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    ("close_margin_listen_key", {}, "DELETE", "/sapi/v1/margin/listen-key", {}, False, True),
    (
        "keep_alive_margin_listen_key",
        {"listen_key": "listen-token"},
        "PUT",
        "/sapi/v1/margin/listen-key",
        {"listenKey": "listen-token"},
        False,
        True,
    ),
    ("create_margin_listen_key", {}, "POST", "/sapi/v1/margin/listen-key", {}, False, True),
    (
        "get_spot_aggregate_trades",
        {"product_symbol": "BTC-USDT-SPOT"},
        "GET",
        "/api/v3/aggTrades",
        {"symbol": "BTCUSDT"},
        False,
        False,
    ),
    (
        "get_spot_average_price",
        {"product_symbol": "BTC-USDT-SPOT"},
        "GET",
        "/api/v3/avgPrice",
        {"symbol": "BTCUSDT"},
        False,
        False,
    ),
    (
        "get_spot_24h_ticker",
        {"product_symbol": "BTC-USDT-SPOT"},
        "GET",
        "/api/v3/ticker/24hr",
        {"symbol": "BTCUSDT"},
        False,
        False,
    ),
    (
        "get_spot_book_ticker",
        {"product_symbol": "BTC-USDT-SPOT"},
        "GET",
        "/api/v3/ticker/bookTicker",
        {"symbol": "BTCUSDT"},
        False,
        False,
    ),
    (
        "get_account_trading_status",
        {"recv_window": 5000},
        "GET",
        "/sapi/v1/account/apiTradingStatus",
        {"recvWindow": "5000"},
        True,
        False,
    ),
    (
        "get_account_status",
        {"recv_window": 5000},
        "GET",
        "/sapi/v1/account/status",
        {"recvWindow": "5000"},
        True,
        False,
    ),
    (
        "get_api_key_permissions",
        {"recv_window": 5000},
        "GET",
        "/sapi/v1/account/apiRestrictions",
        {"recvWindow": "5000"},
        True,
        False,
    ),
    (
        "get_spot_trade_fees",
        {"product_symbol": "BTC-USDT-SPOT"},
        "GET",
        "/sapi/v1/asset/tradeFee",
        {"symbol": "BTCUSDT"},
        True,
        False,
    ),
    (
        "get_user_assets",
        {"recv_window": 5000},
        "POST",
        "/sapi/v3/asset/getUserAsset",
        {"recvWindow": "5000"},
        True,
        False,
    ),
    (
        "get_coin_network_config",
        {"recv_window": 5000},
        "GET",
        "/sapi/v1/capital/config/getall",
        {"recvWindow": "5000"},
        True,
        False,
    ),
    (
        "get_deposit_address",
        {"coin": "BTC"},
        "GET",
        "/sapi/v1/capital/deposit/address",
        {"coin": "BTC"},
        True,
        False,
    ),
    (
        "get_deposit_history",
        {"recv_window": 5000},
        "GET",
        "/sapi/v1/capital/deposit/hisrec",
        {"recvWindow": "5000"},
        True,
        False,
    ),
    (
        "get_spot_delist_schedule",
        {"recv_window": 5000},
        "GET",
        "/sapi/v1/spot/delist-schedule",
        {"recvWindow": "5000"},
        False,
        True,
    ),
    ("get_system_status", {}, "GET", "/sapi/v1/system/status", {}, False, False),
]


COMPLETION_CASES = json.loads(
    (Path(__file__).parents[1] / "fixtures/binance_request_cases.json").read_text(encoding="utf-8")
)
CASES.extend(
    (x["name"], x["kwargs"], x["method"], x["path"], x["expected"], True, False)
    for x in COMPLETION_CASES
)


@pytest.mark.asyncio
@pytest.mark.parametrize("asynchronous", [False, True])
@pytest.mark.parametrize(
    ("method", "kwargs", "verb", "path", "expected", "signed", "api_key"),
    CASES,
    ids=[c[0] for c in CASES],
)
async def test_risk_wire(
    asynchronous: bool,
    method: str,
    kwargs: dict[str, Any],
    verb: str,
    path: str,
    expected: dict[str, str],
    signed: bool,
    api_key: bool,
) -> None:
    import dcex._native as native

    with _http_server() as (base, received):
        cls = AsyncClient if asynchronous else Client
        client = cls(api_key="api-key", api_secret="api-secret", preload_product_table=False)
        if asynchronous:
            await client.async_init()
        client._native_client = native.BinanceHttpClient(
            api_key="api-key",
            api_secret="api-secret",
            timeout=10,
            spot_base_url=base,
            futures_base_url=base,
            coin_futures_base_url=base,
            portfolio_margin_base_url=base,
            options_base_url=base,
        )
        try:
            result = getattr(client, method)(**kwargs)
            if inspect.isawaitable(result):
                result = await result
            assert result == {"ok": True}
        finally:
            result = client.close()
            if inspect.isawaitable(result):
                await result
        requests = []
        while not received.empty():
            item = received.get_nowait()
            if not urlsplit(item["path"]).path.endswith("/time"):
                requests.append(item)
        assert len(requests) == 1
        request = requests[0]
    target = urlsplit(request["path"])
    assert (request["method"], target.path) == (verb, path)
    payload = target.query or request["body"]
    fields = dict(parse_qsl(payload))
    signature = fields.pop("signature", None)
    if signed:
        assert (
            signature
            == hmac.new(
                b"api-secret", payload.rsplit("&signature=", 1)[0].encode(), hashlib.sha256
            ).hexdigest()
        )
        assert fields.pop("timestamp").isdigit()
        if "recvWindow" not in expected:
            fields.pop("recvWindow", None)
    else:
        assert signature is None
        assert "timestamp" not in fields
    assert fields == expected
    if signed or api_key:
        assert request["api_key"] == "api-key"
    else:
        assert request["api_key"] is None


INVALID_CASES = [
    (
        "get_futures_aggregate_trades",
        {"product_symbol": "BTC-USDT-SWAP", "from_id": 1, "start_time": 1},
    ),
    (
        "get_futures_aggregate_trades",
        {"product_symbol": "BTC-USDT-SWAP", "start_time": 1, "end_time": 3600001},
    ),
    (
        "get_coin_futures_index_price_klines",
        {"pair": "BTCUSD", "interval": "1m", "start_time": 1, "end_time": 201 * 86400000},
    ),
    ("get_pm_margin_loan_records", {"asset": "USDT"}),
    ("get_pm_margin_interest_history", {"start_time": 1, "end_time": 31 * 86400000}),
    ("get_deposit_history", {"start_time": 1, "end_time": 90 * 86400000 + 1}),
    ("get_deposit_address", {"coin": "BTC", "network": "LIGHTNING"}),
    ("get_margin_order_list", {"order_list_id": 1, "is_isolated": "TRUE"}),
    ("get_margin_all_order_lists", {"from_id": 1, "start_time": 1}),
    (
        "adjust_futures_position_margin",
        {"product_symbol": "BTC-USDT-SWAP", "amount": "NaN", "kind_type": 1},
    ),
    (
        "adjust_futures_position_margin",
        {"product_symbol": "BTC-USDT-SWAP", "amount": "1", "kind_type": 3},
    ),
    ("set_futures_multi_assets_mode", {"multi_assets_margin": "yes"}),
]

INVALID_CASES.extend(
    [
        ("create_withdrawal", {"coin": "USDT", "address": "test", "amount": "1e-8"}),
        ("create_withdrawal", {"coin": "USDT", "address": "test", "amount": "1", "wallet_type": 2}),
        ("create_options_block_order", {"liquidity": "MAKER", "legs": []}),
        (
            "create_options_block_order",
            {
                "liquidity": "MAKER",
                "legs": [
                    {
                        "symbol": "BTC-261225-90000-C",
                        "side": "BUY",
                        "type": "LIMIT",
                        "quantity": 0.1,
                    }
                ],
            },
        ),
        (
            "create_broker_withdrawal",
            {
                "coin": "USDT",
                "address": "test",
                "amount": "1",
                "withdraw_order_id": "test",
                "questionnaire": {},
                "originator_pii": {"piiType": 0},
            },
        ),
    ]
)

for case in CASES:
    name, kwargs = case[:2]
    if name.startswith("place_"):
        if "working_time_in_force" in kwargs:
            invalid = dict(kwargs)
            invalid.pop("working_time_in_force")
            INVALID_CASES.append((name, invalid))
        if name in {"place_spot_opo", "place_spot_opoco"}:
            INVALID_CASES.append((name, {**kwargs, "working_side": "SELL"}))
            INVALID_CASES.append((name, {**kwargs, "pending_side": "BUY"}))
        if name == "place_margin_oco":
            INVALID_CASES.append((name, {**kwargs, "stop_limit_price": "89"}))
            INVALID_CASES.append((name, {**kwargs, "price": "80"}))


@pytest.mark.asyncio
@pytest.mark.parametrize("asynchronous", [False, True])
@pytest.mark.parametrize(("method", "kwargs"), INVALID_CASES)
async def test_invalid_risk_parameters(
    asynchronous: bool, method: str, kwargs: dict[str, Any]
) -> None:
    cls = AsyncClient if asynchronous else Client
    client = cls(api_key="api-key", api_secret="api-secret", preload_product_table=False)
    if asynchronous:
        await client.async_init()
    import dcex._native as native

    client._native_client = native.BinanceHttpClient(
        api_key="api-key",
        api_secret="api-secret",
        timeout=10,
        spot_base_url="http://127.0.0.1:1",
        futures_base_url="http://127.0.0.1:1",
        coin_futures_base_url="http://127.0.0.1:1",
        portfolio_margin_base_url="http://127.0.0.1:1",
        options_base_url="http://127.0.0.1:1",
    )
    try:
        with pytest.raises(ValueError):
            result = getattr(client, method)(**kwargs)
            if inspect.isawaitable(result):
                await result
    finally:
        result = client.close()
        if inspect.isawaitable(result):
            await result
